--liquibase formatted sql
--changeset Swetha.H:GS_AUDITLOG_REPORT_DDL_03_1 
--preconditions onFail:HALT onError:HALT

CREATE INDEX GS_AUDITLOG_REPORTSTATS ON GS_AUDITLOG_REPORTSTATS (STATID, TYPE, C5, C1, C2, C3, C4, VERSION) 
  ;

CREATE UNIQUE INDEX DATA_LOG_ARCHIVAL_PK ON DATA_LOG_ARCHIVAL (LOG_ID) 
  ;

CREATE UNIQUE INDEX DATA_LOG_LOG_ID_IDX ON DATA_LOG (LOG_ID) 
  ;

CREATE UNIQUE INDEX EVENT_LOG_ARCH_PK ON EVENT_LOG_ARCHIVAL (LOG_ID) 
  ;

CREATE UNIQUE INDEX EVENT_LOG_LOG_ID_IDX ON EVENT_LOG (LOG_ID) 
  ;

 CREATE UNIQUE INDEX DATA_LOG_REPORTS_LOG_ID_IDX ON DATA_LOG_REPORTS (LOG_ID) ;
 
 CREATE UNIQUE INDEX EVENT_LOG_REPORTS_LOG_ID_IDX ON EVENT_LOG_REPORTS (LOG_ID) ;