--liquibase formatted sql
--changeset Swetha.H:CRPT_DDL_03
--preconditions onFail:HALT onError:HALT


ALTER TABLE REF_STATUS ADD CONSTRAINT REF_STATUS_PK PRIMARY KEY (REF_STAT_ID)
USING INDEX   ENABLE;

ALTER TABLE PROJECT_DETAILS ADD CONSTRAINT PROJECT_ID_PK PRIMARY KEY (PROJECT_ID);

ALTER TABLE SALES_ORDER_DETAILS ADD CONSTRAINT SALES_ORDER_ID_PK PRIMARY KEY (SALES_ORDER_ID);

ALTER TABLE MARKET_OFFERING_DETAILS ADD CONSTRAINT MARKET_OFFERING_ID_PK PRIMARY KEY (MARKET_OFFERING_ID);

ALTER TABLE SERVICE_DETAILS ADD CONSTRAINT ID_PK PRIMARY KEY (ID);

ALTER TABLE LOCATION_DETAILS ADD CONSTRAINT LOCATION_ID_PK PRIMARY KEY (LOCATION_ID);

ALTER TABLE TASK_DETAILS ADD CONSTRAINT TASK_ID_PK PRIMARY KEY (TASK_ID);

ALTER TABLE PRODUCT_ORDER_DETAILS ADD CONSTRAINT SERVICE_REQUEST_ID_PK PRIMARY KEY (SERVICE_REQUEST_ID);

ALTER TABLE SOW_DETAILS ADD CONSTRAINT CONTRACT_ID_PK PRIMARY KEY (CONTRACT_ID);

ALTER TABLE ADDRESS_DETAILS ADD CONSTRAINT ADDRESS_ID_PK PRIMARY KEY (ADDRESS_ID);

ALTER TABLE CUSTOMER_DETAILS ADD CONSTRAINT CUSTOMER_ID_PK PRIMARY KEY (CUSTOMER_ID);

ALTER TABLE ACCOUNT_DETAILS ADD CONSTRAINT ACCOUNT_ID_PK PRIMARY KEY (ACCOUNT_ID);