--liquibase formatted sql
--changeset Swetha.H:CRPT_DDL_03 splitStatements:false
--preconditions onFail:HALT onError:HALT


  CREATE OR REPLACE EDITIONABLE TYPE LIST_NUMBER AS TABLE OF NUMBER;
  / 


--changeset Swetha.H:CRPT_DDL_03_02 splitStatements:false
--preconditions onFail:HALT onError:HALT


  CREATE OR REPLACE EDITIONABLE TYPE SDO_GEOMETRY AS OBJECT (
           SDO_GTYPE       NUMBER,
           SDO_SRID        NUMBER,
           SDO_POINT       SDO_POINT_TYPE,
           SDO_ELEM_INFO   SDO_ELEM_INFO_ARRAY,
           SDO_ORDINATES   SDO_ORDINATE_ARRAY,
           MEMBER FUNCTION  GET_GTYPE
           RETURN NUMBER DETERMINISTIC,
           MEMBER FUNCTION  GET_DIMS
           RETURN NUMBER DETERMINISTIC,
           MEMBER FUNCTION  GET_LRS_DIM
           RETURN NUMBER DETERMINISTIC)
 
  ALTER TYPE SDO_GEOMETRY 
  ADD MEMBER FUNCTION GET_WKB RETURN BLOB DETERMINISTIC,
  ADD MEMBER FUNCTION GET_WKT RETURN CLOB DETERMINISTIC,
  ADD MEMBER FUNCTION ST_CoordDim RETURN SMALLINT DETERMINISTIC,
  ADD MEMBER FUNCTION ST_IsValid RETURN INTEGER DETERMINISTIC,
  ADD CONSTRUCTOR FUNCTION SDO_GEOMETRY(wkt IN CLOB,
            srid IN INTEGER DEFAULT NULL) RETURN SELF AS RESULT,
  ADD CONSTRUCTOR FUNCTION SDO_GEOMETRY(wkt IN VARCHAR2,
            srid IN INTEGER DEFAULT NULL) RETURN SELF AS RESULT,
  ADD CONSTRUCTOR FUNCTION SDO_GEOMETRY(wkb IN BLOB,
            SRID IN INTEGER DEFAULT NULL) RETURN SELF AS RESULT
  CASCADE