--liquibase formatted sql
--changeset Swetha.H:HISTORYS_DDL_01_1 
--preconditions onFail:HALT onError:HALT

CREATE SEQUENCE  INSTANCE_ARCHIVAL_GEN_ID_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 114693 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

--changeset Swetha.H:HISTORYS_DDL_01_2 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_SEQUENCES
    WHERE  
	    SEQUENCE_NAME = 'ERROR_LOG_ID_SEQ';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE  ERROR_LOG_ID_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 20000 CACHE 20 NOORDER  NOCYCLE';
        DBMS_OUTPUT.PUT_LINE('Created');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;

