--liquibase formatted sql
--changeset Swetha.H:HISTORYS_DDL_02_1 
--preconditions onFail:HALT onError:HALT

CREATE TABLE ARCHIVAL_GEN_ERROR 
   (	INSTANCE_ARCHIVAL_EXECUTION_ID NUMBER, 
	INSTANCE_ARCHIVAL_PROC_NAME VARCHAR2(500), 
	INSTANCE_ARCHIVAL_LOGS VARCHAR2(4000), 
	INSTANCE_ARCHIVAL_ERROR_CODE VARCHAR2(4000), 
	INSTANCE_ARCHIVAL_ERROR_MSG VARCHAR2(4000), 
	INSTANCE_ARCHIVAL_EXECUTION_TIME TIMESTAMP (6), 
	INSTANCE_ID NUMBER
   ) ;

CREATE TABLE ARCHIVAL_GEN_TRACE 
   (	INSTANCE_ARCHIVAL_EXECUTION_ID NUMBER, 
	INSTANCE_ARCHIVAL_PROC_NAME VARCHAR2(500), 
	INSTANCE_ARCHIVAL_LOGS VARCHAR2(4000), 
	INSTANCE_ARCHIVAL_DYNAMIC_SCRIPT CLOB, 
	INSTANCE_ARCHIVAL_EXECUTION_TIME TIMESTAMP (6), 
	INSTANCE_ID NUMBER
   ) ;

CREATE TABLE ARCHIVAL_PKG_CONFIG 
   (	INSTANCE_CONFIG_NAME VARCHAR2(200), 
	INSTANCE_CONFIG_VALUE VARCHAR2(4000), 
	INSTANCE_CONFIG_VARIABLE VARCHAR2(250), 
	INSTANCE_CONFIG_TYPE VARCHAR2(250), 
	INSTANCE_ARGUMENT_TYPE VARCHAR2(100), 
	PKG_PROC_NAME VARCHAR2(100), 
	CONFIGURATION_TYPE VARCHAR2(100), 
	SCHEMA_NAME VARCHAR2(100)
   ) ;

CREATE TABLE ARCHIVAL_PKG_VERSION_CONFIG 
   (	INSTANCE_CONFIG_NAME VARCHAR2(200), 
	INSTANCE_CONFIG_VALUE VARCHAR2(4000), 
	INSTANCE_CONFIG_VARIABLE VARCHAR2(250), 
	INSTANCE_CONFIG_TYPE VARCHAR2(250), 
	INSTANCE_ARGUMENT_TYPE VARCHAR2(100), 
	PKG_PROC_NAME VARCHAR2(100), 
	CONFIGURATION_TYPE VARCHAR2(100), 
	SCHEMA_NAME VARCHAR2(100)
   ) ;

CREATE TABLE ARCHIVAL_TABLE_CONFIG 
   (	INSTANCE_TABLE_ID NUMBER, 
	INSTANCE_TABLE_NAME VARCHAR2(200), 
	INSTANCE_TABLE_ALIAS_NAME VARCHAR2(100), 
	INSTANCE_TABLE_SEQ NUMBER, 
	INSTANCE_TABLE_DELETE_SEQ NUMBER, 
	INSTANCE_FETCH_QUERY CLOB, 
	IS_ACTIVE VARCHAR2(1), 
	INSTANCE_QUERY_TYPE VARCHAR2(4000), 
	CONDITION_COLUMN VARCHAR2(4000), 
	SCHEMA_NAME VARCHAR2(20), 
	ARCHIVE_TABLE_NAME VARCHAR2(50), 
	IS_PURGE VARCHAR2(1)
   ) ;

CREATE TABLE ARCHIVAL_TABLE_VERSION_CONFIG 
   (	INSTANCE_TABLE_ID NUMBER, 
	INSTANCE_TABLE_NAME VARCHAR2(200), 
	INSTANCE_TABLE_ALIAS_NAME VARCHAR2(100), 
	INSTANCE_TABLE_SEQ NUMBER, 
	INSTANCE_TABLE_DELETE_SEQ NUMBER, 
	INSTANCE_FETCH_QUERY CLOB, 
	IS_ACTIVE VARCHAR2(1), 
	INSTANCE_QUERY_TYPE VARCHAR2(4000), 
	CONDITION_COLUMN VARCHAR2(4000), 
	SCHEMA_NAME VARCHAR2(20), 
	ARCHIVE_TABLE_NAME VARCHAR2(50), 
	IS_PURGE VARCHAR2(1)
   ) ;

CREATE TABLE ARCH_BUSINESS_PROCESS_INSTANCE 
   (	INSTANCE_ID NUMBER, 
	ENTITY_TYPE VARCHAR2(100), 
	VERSION_NO NUMBER, 
	ENTITYID NUMBER, 
	PARENT_ID NUMBER, 
	META_DATA_ID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	META_DATA_LIFECYCLEID NUMBER, 
	METADATA_VERSION NUMBER
   ) ;

CREATE TABLE ARCH_ENTITY_GROUP_FUNCTION 
   (	PID NUMBER, 
	ENTITY_TYPE VARCHAR2(100), 
	VERSION NUMBER, 
	BID NUMBER, 
	GROUP_ID VARCHAR2(50), 
	JOIN_PID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	HIERARCHY VARCHAR2(50), 
	PARENT_PID NUMBER, 
	PROCESS_ENTITY_TYPE VARCHAR2(100), 
	PROCESS_BID NUMBER, 
	ENTITY_FUNCTION_ID NUMBER, 
	GROUP_NAME VARCHAR2(250), 
	RELATED_FUNCTION_ID NUMBER, 
	START_DATE TIMESTAMP (6), 
	END_DATE TIMESTAMP (6), 
	STATUS VARCHAR2(50), 
	DESCRIPTION VARCHAR2(250), 
	NAME VARCHAR2(250), 
	GRANDFATHERED VARCHAR2(50), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	MAPPING_TYPE_SOURCE VARCHAR2(100), 
	MAPPING_TYPE_TARGET VARCHAR2(100), 
	EFFECTIVE_END_DATE TIMESTAMP (6), 
	CATEGORY_TYPE VARCHAR2(100), 
	MAPPING_TYPE VARCHAR2(250), 
	ENTITY_GROUP_FUNC_ID NUMBER
   ) ;

CREATE TABLE ARCH_ENTITY_GROUP_PARAMETER_VALUES 
   (	METADATA_ID NUMBER, 
	VALUE VARCHAR2(4000), 
	VERSION NUMBER, 
	PARENT_ID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	PARAM_SPEC_ID NUMBER, 
	ENTITY_ID NUMBER, 
	META_DATA_LIFECYCLEID NUMBER, 
	METADATA_VERSION NUMBER, 
	PARAM_INSTANCE_ID NUMBER(38,0)
   ) ;

CREATE TABLE ARCH_ENTITY_JOIN_PARAMETER 
   (	PARAMKEY1 NUMBER, 
	PARAMKEY2 NUMBER, 
	BUSINESS_ENTITY VARCHAR2(50), 
	VERSION_NO NUMBER, 
	GROUP_ID VARCHAR2(50), 
	LIFECYCLE_ID NUMBER, 
	ENTITY_FUNCTION_ID NUMBER, 
	GRANDFATHERED VARCHAR2(50), 
	JOIN_METHOD VARCHAR2(100), 
	MAPPING_ENTITY_ID NUMBER, 
	MAPPING_ENTITY_TYPE VARCHAR2(100), 
	TRANSFORMATION_TYPE VARCHAR2(100), 
	SOURCE_VALUE VARCHAR2(100), 
	TARGET_VALUE VARCHAR2(100), 
	JOIN_SEQ NUMBER, 
	ENTITY_JOIN_PARAM_ID NUMBER, 
	TRANSFORMATION_REQ VARCHAR2(20)
   ) ;

CREATE TABLE ARCH_LIFE_CYCLE_ACTIVITY 
   (	LCA_ID NUMBER, 
	LCA_TYPE VARCHAR2(50), 
	LCA_DESCRIPTION VARCHAR2(100), 
	LCA_VERSION NUMBER, 
	LCA_STATUS VARCHAR2(50), 
	LCA_STATUS_DTM TIMESTAMP (6), 
	LCA_LEVEL VARCHAR2(20), 
	LCA_PRIORITY VARCHAR2(20), 
	LCA_DEPENDENCY_DATE DATE, 
	LCA_CREATION_DTM TIMESTAMP (6), 
	LCA_CREATED_BY VARCHAR2(50), 
	LCA_SCHEDULE VARCHAR2(50), 
	LCA_DISPLAY_ON_TIMELINE VARCHAR2(50), 
	LCA_PLAN_START_DTM TIMESTAMP (6), 
	LCA_PLAN_END_DTM TIMESTAMP (6), 
	LCA_ACTUAL_START_DTM TIMESTAMP (6), 
	LCA_ACTUAL_END_DTM TIMESTAMP (6), 
	LCA_POTENTIAL_START_DTM TIMESTAMP (6), 
	LCA_POTENTIAL_END_DTM TIMESTAMP (6), 
	LCA_DURATION_PLAN NUMBER, 
	LCA_DURATION_ACTUAL NUMBER, 
	LCA_THRESHOLD NUMBER, 
	LCA_THRESHOLD_REASON_CODE VARCHAR2(10), 
	LCA_THRESHOLD_DATE DATE, 
	LCA_MILESTONE VARCHAR2(20), 
	LCA_REASON_CODE VARCHAR2(10), 
	LCA_COLOR_CODE VARCHAR2(10), 
	LCA_LABEL_COUNT NUMBER, 
	LCA_BEHAVIOUR_CODE VARCHAR2(10), 
	CPC_LCA_ID NUMBER, 
	CPC_LCA_VERSION NUMBER, 
	LCA_PARENT_ID NUMBER, 
	LCA_CHILD_ID NUMBER, 
	LCA_ROOT_ID NUMBER, 
	LCA_EXTERNAL_SOURCE_ID VARCHAR2(100), 
	LCA_NAME VARCHAR2(100), 
	LCA_COMPLETION_PERCENTAGE NUMBER, 
	LCA_MILESTONE_DTM TIMESTAMP (6), 
	LCA_MODIFIED_BY VARCHAR2(50), 
	LCA_MODIFIED_ON TIMESTAMP (6), 
	LCA_OWNER VARCHAR2(150), 
	ENTITY_SEQ NUMBER, 
	ENTITY_ID NUMBER, 
	ENTITY_NAME VARCHAR2(100), 
	LCA_ACTIVITY_REASON VARCHAR2(20), 
	LCA_ACTIVITY VARCHAR2(50), 
	VERSION NUMBER, 
	LIFE_CYCLE_ID NUMBER, 
	LCA_USERID NUMBER, 
	STANDARD_AGE NUMBER, 
	GRACE_AGE NUMBER, 
	CRITICAL_AGE NUMBER, 
	TYPE VARCHAR2(50), 
	CATEGORY VARCHAR2(100), 
	COMMENTS VARCHAR2(255), 
	REJECT_REASON VARCHAR2(255), 
	REJECT_DESCRIPTION VARCHAR2(255), 
	JEOPARDY_DESCRIPTION VARCHAR2(255), 
	JEOPARDY_CODE VARCHAR2(255), 
	RECALL_REASON VARCHAR2(255), 
	USER_GROUP VARCHAR2(100), 
	LCA_RULE_ID NUMBER, 
	LCA_RULE_STATUS VARCHAR2(150), 
	META_DATA_LIFECYCLEID NUMBER, 
	BUSINESS_ENTITY_TYPE VARCHAR2(200), 
	METADATA_VERSION NUMBER
   ) ;

CREATE TABLE ARCH_PLAN_INSTANCE_SPECIFICATION 
   (	PP_INSTANCE_ID NUMBER, 
	PP_ITEM_NAME VARCHAR2(100), 
	VERSION NUMBER, 
	PARENT_ID NUMBER, 
	PRIORITY NUMBER, 
	SEQUENCE NUMBER, 
	CHARGE_ITEM_TYPE VARCHAR2(100), 
	UNIT_OF_MEASURE_BASELINED VARCHAR2(100), 
	CHARGE_UNIT_BASELINED NUMBER, 
	CHARGE_UNIT_CUSTOM NUMBER, 
	STARTDATE TIMESTAMP (6), 
	ENDDATE TIMESTAMP (6), 
	PRICE_PLAN_ID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	DEFAULT_VALUE VARCHAR2(255), 
	BUSINESS_ENTITYID NUMBER, 
	SERVICE_CHARGE_PRICE NUMBER, 
	META_DATA_LIFECYCLEID NUMBER, 
	METADATA_VERSION NUMBER
   ) ;

CREATE TABLE ARCH_PROCESS_ENTITY_INSTANCE 
   (	INSTANCE_ID NUMBER, 
	VERSION NUMBER, 
	PARENT_INSTANCE_ID NUMBER, 
	META_DATA_ID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	META_DATA_LIFECYCLEID NUMBER, 
	METADATA_VERSION NUMBER, 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	STATUS VARCHAR2(500), 
	ROOT_ID NUMBER, 
	TYPE VARCHAR2(500), 
	PARENT_ROOT_ID NUMBER
   ) ;

CREATE TABLE ARCH_PROCESS_ENTITY_RELATION 
   (	PARENT_INSTANCE_ID NUMBER, 
	CHILD_INSTANCE_ID NUMBER, 
	ENTITY_TYPE VARCHAR2(30), 
	VERSION NUMBER, 
	STATUS VARCHAR2(30), 
	META_DATA_LIFECYCLEID NUMBER, 
	METADATA_VERSION NUMBER, 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200)
   ) ;

CREATE TABLE ARCH_PRODUCT_ENTITY_INSTANCE 
   (	BUSINESS_META_DATA_ID NUMBER, 
	INSTANCE_ID NUMBER, 
	ENTITY_TYPE VARCHAR2(100), 
	VERSION NUMBER, 
	STATUS VARCHAR2(50), 
	LIFECYCLE_ID NUMBER, 
	PRICE_PLAN_ID NUMBER, 
	EXTERNAL_USER_ID NUMBER, 
	ROOT_ID NUMBER, 
	META_DATA_LIFECYCLEID NUMBER, 
	METADATA_VERSION NUMBER
   ) ;

CREATE TABLE ARCH_PRODUCT_ENTITY_RELATION 
   (	PARENT_ID NUMBER, 
	CHILD_ID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	VERSION NUMBER, 
	TYPE VARCHAR2(100), 
	META_DATA_LIFECYCLEID NUMBER, 
	METADATA_VERSION NUMBER
   ) ;

CREATE TABLE ARCH_SERVICE_GROUP_PARAMETER 
   (	INSTANCE_ID NUMBER, 
	VERSION NUMBER, 
	PARENT_ID NUMBER, 
	VC_KEY_NAME1 VARCHAR2(100), 
	INSTANT_KEY1 NUMBER, 
	VALUE1 VARCHAR2(100), 
	VC_KEY_NAME2 VARCHAR2(100), 
	INSTANT_KEY2 NUMBER, 
	VALUE2 VARCHAR2(100), 
	VC_KEY_NAME3 VARCHAR2(100), 
	INSTANT_KEY3 NUMBER, 
	VALUE3 VARCHAR2(100), 
	VC_KEY_NAME4 VARCHAR2(100), 
	INSTANT_KEY4 NUMBER, 
	VALUE4 VARCHAR2(100), 
	VC_KEY_NAME5 VARCHAR2(100), 
	INSTANT_KEY5 NUMBER, 
	VALUE5 VARCHAR2(100), 
	VC_KEY_NAME6 VARCHAR2(100), 
	INSTANT_KEY6 NUMBER, 
	VALUE6 VARCHAR2(100), 
	VC_KEY_NAME7 VARCHAR2(100), 
	INSTANT_KEY7 NUMBER, 
	VALUE7 VARCHAR2(100), 
	VC_KEY_NAME8 VARCHAR2(100), 
	INSTANT_KEY8 NUMBER, 
	VALUE8 VARCHAR2(100), 
	VC_KEY_NAME9 VARCHAR2(100), 
	INSTANT_KEY9 NUMBER, 
	VALUE9 VARCHAR2(100), 
	VC_KEY_NAME10 VARCHAR2(100), 
	INSTANT_KEY10 NUMBER, 
	VALUE10 VARCHAR2(100), 
	VC_KEY_NAME11 VARCHAR2(100), 
	INSTANT_KEY11 NUMBER, 
	VALUE11 VARCHAR2(100), 
	VC_KEY_NAME12 VARCHAR2(100), 
	INSTANT_KEY12 NUMBER, 
	VALUE12 VARCHAR2(100), 
	VC_KEY_NAME13 VARCHAR2(100), 
	INSTANT_KEY13 NUMBER, 
	VALUE13 VARCHAR2(100), 
	VC_KEY_NAME14 VARCHAR2(100), 
	INSTANT_KEY14 NUMBER, 
	VALUE14 VARCHAR2(100), 
	VC_KEY_NAME15 VARCHAR2(100), 
	INSTANT_KEY15 NUMBER, 
	VALUE15 VARCHAR2(100), 
	VC_KEY_NAME16 VARCHAR2(100), 
	INSTANT_KEY16 NUMBER, 
	VALUE16 VARCHAR2(100), 
	VC_KEY_NAME17 VARCHAR2(100), 
	INSTANT_KEY17 NUMBER, 
	VALUE17 VARCHAR2(100), 
	VC_KEY_NAME18 VARCHAR2(100), 
	INSTANT_KEY18 NUMBER, 
	VALUE18 VARCHAR2(100), 
	VC_KEY_NAME19 VARCHAR2(100), 
	INSTANT_KEY19 NUMBER, 
	VALUE19 VARCHAR2(100), 
	VC_KEY_NAME20 VARCHAR2(100), 
	INSTANT_KEY20 NUMBER, 
	VALUE20 VARCHAR2(100), 
	VC_KEY_NAME21 VARCHAR2(100), 
	INSTANT_KEY21 NUMBER, 
	VALUE21 VARCHAR2(100), 
	VC_KEY_NAME22 VARCHAR2(100), 
	INSTANT_KEY22 NUMBER, 
	VALUE22 VARCHAR2(100), 
	VC_KEY_NAME23 VARCHAR2(100), 
	INSTANT_KEY23 NUMBER, 
	VALUE23 VARCHAR2(100), 
	VC_KEY_NAME24 VARCHAR2(100), 
	INSTANT_KEY24 NUMBER, 
	VALUE24 VARCHAR2(100), 
	VC_KEY_NAME25 VARCHAR2(100), 
	INSTANT_KEY25 NUMBER, 
	VALUE25 VARCHAR2(100), 
	VC_KEY_NAME26 VARCHAR2(100), 
	INSTANT_KEY26 NUMBER, 
	VALUE26 VARCHAR2(100), 
	VC_KEY_NAME27 VARCHAR2(100), 
	INSTANT_KEY27 NUMBER, 
	VALUE27 VARCHAR2(100), 
	VC_KEY_NAME28 VARCHAR2(100), 
	INSTANT_KEY28 NUMBER, 
	VALUE28 VARCHAR2(100), 
	VC_KEY_NAME29 VARCHAR2(100), 
	INSTANT_KEY29 NUMBER, 
	VALUE29 VARCHAR2(100), 
	VC_KEY_NAME30 VARCHAR2(100), 
	INSTANT_KEY31 NUMBER, 
	VALUE32 VARCHAR2(100), 
	VC_KEY_NAME33 VARCHAR2(100), 
	INSTANT_KEY33 NUMBER, 
	VALUE33 VARCHAR2(100), 
	VC_KEY_NAME34 VARCHAR2(100), 
	INSTANT_KEY34 NUMBER, 
	VALUE34 VARCHAR2(100), 
	VC_KEY_NAME35 VARCHAR2(100), 
	INSTANT_KEY35 NUMBER, 
	VALUE35 VARCHAR2(100), 
	VC_KEY_NAME36 VARCHAR2(100), 
	INSTANT_KEY36 NUMBER, 
	VALUE36 VARCHAR2(100), 
	VC_KEY_NAME37 VARCHAR2(100), 
	INSTANT_KEY37 NUMBER, 
	VALUE37 VARCHAR2(100), 
	VC_KEY_NAME38 VARCHAR2(100), 
	INSTANT_KEY38 NUMBER, 
	VALUE38 VARCHAR2(100), 
	VC_KEY_NAME39 VARCHAR2(100), 
	INSTANT_KEY39 NUMBER, 
	VALUE39 VARCHAR2(100), 
	VC_KEY_NAME40 VARCHAR2(100), 
	INSTANT_KEY40 NUMBER, 
	VALUE40 VARCHAR2(100), 
	LIFECYCLE_ID NUMBER, 
	VC_KEY1 NUMBER, 
	VC_KEY2 NUMBER, 
	VC_KEY3 NUMBER, 
	VC_KEY4 NUMBER, 
	VC_KEY5 NUMBER, 
	VC_KEY6 NUMBER, 
	VC_KEY7 NUMBER, 
	VC_KEY8 NUMBER, 
	VC_KEY9 NUMBER, 
	VC_KEY10 NUMBER, 
	VC_KEY11 NUMBER, 
	VC_KEY12 NUMBER, 
	VC_KEY13 NUMBER, 
	VC_KEY14 NUMBER, 
	VC_KEY15 NUMBER, 
	VC_KEY16 NUMBER, 
	VC_KEY17 NUMBER, 
	VC_KEY18 NUMBER, 
	VC_KEY19 NUMBER, 
	VC_KEY20 NUMBER, 
	VC_KEY21 NUMBER, 
	VC_KEY22 NUMBER, 
	VC_KEY23 NUMBER, 
	VC_KEY24 NUMBER, 
	VC_KEY25 NUMBER, 
	VC_KEY26 NUMBER, 
	VC_KEY27 NUMBER, 
	VC_KEY28 NUMBER, 
	VC_KEY29 NUMBER, 
	VC_KEY30 NUMBER, 
	VC_KEY33 NUMBER, 
	VC_KEY34 NUMBER, 
	VC_KEY35 NUMBER, 
	VC_KEY36 NUMBER, 
	VC_KEY37 NUMBER, 
	VC_KEY38 NUMBER, 
	VC_KEY39 NUMBER, 
	VC_KEY40 NUMBER, 
	ENTITY_ID NUMBER, 
	INSTANT_KEY30 NUMBER, 
	INSTANT_KEY32 NUMBER, 
	VALUE30 VARCHAR2(100), 
	VALUE31 VARCHAR2(100), 
	VC_KEY_NAME31 VARCHAR2(100), 
	VC_KEY_NAME32 VARCHAR2(100), 
	INSTANT_KEY41 NUMBER, 
	VALUE41 VARCHAR2(100), 
	VC_KEY_NAME41 VARCHAR2(100), 
	INSTANT_KEY42 NUMBER, 
	VALUE42 VARCHAR2(100), 
	VC_KEY_NAME42 VARCHAR2(100), 
	INSTANT_KEY43 NUMBER, 
	VALUE43 VARCHAR2(100), 
	VC_KEY_NAME43 VARCHAR2(100), 
	INSTANT_KEY44 NUMBER, 
	VALUE44 VARCHAR2(100), 
	VC_KEY_NAME44 VARCHAR2(100), 
	INSTANT_KEY45 NUMBER, 
	VALUE45 VARCHAR2(100), 
	VC_KEY_NAME45 VARCHAR2(100), 
	VC_KEY31 NUMBER, 
	VC_KEY32 NUMBER, 
	VC_KEY41 NUMBER, 
	VC_KEY42 NUMBER, 
	VC_KEY43 NUMBER, 
	VC_KEY44 NUMBER, 
	VC_KEY45 NUMBER, 
	VC_KEY_NAME46 VARCHAR2(100), 
	INSTANT_KEY46 NUMBER, 
	VALUE46 VARCHAR2(100), 
	VC_KEY_NAME47 VARCHAR2(100), 
	INSTANT_KEY47 NUMBER, 
	VALUE47 VARCHAR2(100), 
	VC_KEY_NAME48 VARCHAR2(100), 
	INSTANT_KEY48 NUMBER, 
	VALUE48 VARCHAR2(100), 
	VC_KEY_NAME49 VARCHAR2(100), 
	INSTANT_KEY49 NUMBER, 
	VALUE49 VARCHAR2(100), 
	VC_KEY_NAME50 VARCHAR2(100), 
	INSTANT_KEY50 NUMBER, 
	VALUE50 VARCHAR2(100), 
	VC_KEY_NAME51 VARCHAR2(100), 
	INSTANT_KEY51 NUMBER, 
	VALUE51 VARCHAR2(100), 
	VC_KEY_NAME52 VARCHAR2(100), 
	INSTANT_KEY52 NUMBER, 
	VALUE52 VARCHAR2(100), 
	VC_KEY_NAME53 VARCHAR2(100), 
	INSTANT_KEY53 NUMBER, 
	VALUE53 VARCHAR2(100), 
	VC_KEY_NAME54 VARCHAR2(100), 
	INSTANT_KEY54 NUMBER, 
	VALUE54 VARCHAR2(100), 
	VC_KEY_NAME55 VARCHAR2(100), 
	INSTANT_KEY55 NUMBER, 
	VALUE55 VARCHAR2(100), 
	VC_KEY_NAME56 VARCHAR2(100), 
	INSTANT_KEY56 NUMBER, 
	VALUE56 VARCHAR2(100), 
	VC_KEY_NAME57 VARCHAR2(100), 
	INSTANT_KEY57 NUMBER, 
	VALUE57 VARCHAR2(100), 
	VC_KEY_NAME58 VARCHAR2(100), 
	INSTANT_KEY58 NUMBER, 
	VALUE58 VARCHAR2(100), 
	VC_KEY_NAME59 VARCHAR2(100), 
	INSTANT_KEY59 NUMBER, 
	VALUE59 VARCHAR2(100), 
	VC_KEY_NAME60 VARCHAR2(100), 
	INSTANT_KEY60 NUMBER, 
	VALUE60 VARCHAR2(100), 
	VC_KEY46 NUMBER, 
	VC_KEY47 NUMBER, 
	VC_KEY48 NUMBER, 
	VC_KEY49 NUMBER, 
	VC_KEY50 NUMBER, 
	VC_KEY51 NUMBER, 
	VC_KEY52 NUMBER, 
	VC_KEY53 NUMBER, 
	VC_KEY54 NUMBER, 
	VC_KEY55 NUMBER, 
	VC_KEY56 NUMBER, 
	VC_KEY57 NUMBER, 
	VC_KEY58 NUMBER, 
	VC_KEY59 NUMBER, 
	VC_KEY60 NUMBER, 
	META_DATA_LIFECYCLEID NUMBER, 
	METADATA_VERSION NUMBER
   ) ;

CREATE TABLE ARCH_VER_LIFE_CYCLE_ACTIVITY 
   (	LCA_ID NUMBER, 
	LCA_TYPE VARCHAR2(50), 
	LCA_DESCRIPTION VARCHAR2(100), 
	LCA_VERSION NUMBER, 
	LCA_STATUS VARCHAR2(50), 
	LCA_STATUS_DTM TIMESTAMP (6), 
	LCA_LEVEL VARCHAR2(20), 
	LCA_PRIORITY VARCHAR2(20), 
	LCA_DEPENDENCY_DATE DATE, 
	LCA_CREATION_DTM TIMESTAMP (6), 
	LCA_CREATED_BY VARCHAR2(50), 
	LCA_SCHEDULE VARCHAR2(50), 
	LCA_DISPLAY_ON_TIMELINE VARCHAR2(50), 
	LCA_PLAN_START_DTM TIMESTAMP (6), 
	LCA_PLAN_END_DTM TIMESTAMP (6), 
	LCA_ACTUAL_START_DTM TIMESTAMP (6), 
	LCA_ACTUAL_END_DTM TIMESTAMP (6), 
	LCA_POTENTIAL_START_DTM TIMESTAMP (6), 
	LCA_POTENTIAL_END_DTM TIMESTAMP (6), 
	LCA_DURATION_PLAN NUMBER, 
	LCA_DURATION_ACTUAL NUMBER, 
	LCA_THRESHOLD NUMBER, 
	LCA_THRESHOLD_REASON_CODE VARCHAR2(10), 
	LCA_THRESHOLD_DATE DATE, 
	LCA_MILESTONE VARCHAR2(20), 
	LCA_REASON_CODE VARCHAR2(10), 
	LCA_COLOR_CODE VARCHAR2(10), 
	LCA_LABEL_COUNT NUMBER, 
	LCA_BEHAVIOUR_CODE VARCHAR2(10), 
	CPC_LCA_ID NUMBER, 
	CPC_LCA_VERSION NUMBER, 
	LCA_PARENT_ID NUMBER, 
	LCA_CHILD_ID NUMBER, 
	LCA_ROOT_ID NUMBER, 
	LCA_EXTERNAL_SOURCE_ID VARCHAR2(100), 
	LCA_NAME VARCHAR2(100), 
	LCA_COMPLETION_PERCENTAGE NUMBER, 
	LCA_MILESTONE_DTM TIMESTAMP (6), 
	LCA_MODIFIED_BY VARCHAR2(50), 
	LCA_MODIFIED_ON TIMESTAMP (6), 
	LCA_OWNER VARCHAR2(150), 
	ENTITY_SEQ NUMBER, 
	ENTITY_ID NUMBER, 
	ENTITY_NAME VARCHAR2(100), 
	LCA_ACTIVITY_REASON VARCHAR2(20), 
	LCA_ACTIVITY VARCHAR2(50), 
	VERSION NUMBER, 
	LIFE_CYCLE_ID NUMBER, 
	LCA_USERID NUMBER, 
	STANDARD_AGE NUMBER, 
	GRACE_AGE NUMBER, 
	CRITICAL_AGE NUMBER, 
	TYPE VARCHAR2(50), 
	CATEGORY VARCHAR2(100), 
	COMMENTS VARCHAR2(255), 
	REJECT_REASON VARCHAR2(255), 
	REJECT_DESCRIPTION VARCHAR2(255), 
	JEOPARDY_DESCRIPTION VARCHAR2(255), 
	JEOPARDY_CODE VARCHAR2(255), 
	RECALL_REASON VARCHAR2(255), 
	USER_GROUP VARCHAR2(100), 
	LCA_RULE_ID NUMBER, 
	LCA_RULE_STATUS VARCHAR2(150), 
	META_DATA_LIFECYCLEID NUMBER, 
	BUSINESS_ENTITY_TYPE VARCHAR2(200), 
	METADATA_VERSION NUMBER
   ) ;

CREATE TABLE ARCH_VER_TIME_CHECK 
   (	ID NUMBER, 
	EXE_TIME VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6)
   ) ;


CREATE TABLE STG_TEMP_ARCHIVE_DATA 
   (	INSTANCE_ID NUMBER, 
	STATUS VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	SCHEMA_NAME VARCHAR2(100), 
	PURGE_STATUS VARCHAR2(100), 
	PURGE_DATE TIMESTAMP (6)
   ) ;

CREATE TABLE STG_TEMP_ARCHIVE_VERSION_DATA 
   (	INSTANCE_ID NUMBER, 
	STATUS VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	SCHEMA_NAME VARCHAR2(100), 
	LCA_ID NUMBER, 
	PURGE_STATUS VARCHAR2(100), 
	PURGE_DATE TIMESTAMP (6)
   ) ;

CREATE TABLE STG_TEMP_PURGE_DATA 
   (	INSTANCE_ID NUMBER, 
	STATUS VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	SCHEMA_NAME VARCHAR2(100)
   ) ;

CREATE TABLE TEMP_INSTANCE_DATA 
   (	INSTANCE_ID NUMBER, 
	LCA_ID NUMBER
   ) ;

--changeset Swetha.H:HISTORY_DDL_02_2 splitStatements:false
--preconditions onFail:HALT onError:HALT 


DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TABLES 
    WHERE  
        TABLE_NAME = 'ARCH_MASTER_OBJECT_DETAILS';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE ARCH_MASTER_OBJECT_DETAILS (
    TRANSACTION_ID NUMBER NOT NULL,
    MODIFIED_DATE  TIMESTAMP(6),
    MASTER_OBJECT  CLOB,
    MASTER_ID      NUMBER NOT NULL,
    ENTITY_ID      NUMBER,
    CREATED_DATE   TIMESTAMP(6),
    PARENT_ROOT_ID NUMBER
)';
        DBMS_OUTPUT.PUT_LINE('Created');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Swetha.H:HISTORY_DDL_02_3 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TABLES 
    WHERE  
        TABLE_NAME = 'REF_ARCHIVE_DAYS';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE REF_ARCHIVE_DAYS (
    SCHEMA_NAME              VARCHAR2(20), 
TABLE_NAME               VARCHAR2(50), 
ARCHIVE_DAYS             NUMBER,       
ENABLE_FLAG              VARCHAR2(1),  
ARCHIVAL_BY_DATE         VARCHAR2(2),  
FROM_DATE                TIMESTAMP(6), 
TO_DATE                  TIMESTAMP(6), 
PURGE_LIMIT              NUMBER,       
PURGE_PG_FROM_DATE       TIMESTAMP(6), 
PURGE_PG_TO_DATE         TIMESTAMP(6), 
PURGE_PG_BY_DATE         VARCHAR2(2) 
)';
        DBMS_OUTPUT.PUT_LINE('Created');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;



--changeset Swetha.H:HISTORY_DDL_02_4 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TABLES 
    WHERE  
        TABLE_NAME = 'STG_TEMP_INSTANCE_ARCHIVAL';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE STG_TEMP_INSTANCE_ARCHIVAL (
    INSTANCE_ID       NUMBER 
)';
        DBMS_OUTPUT.PUT_LINE('Created');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Swetha.H:HISTORY_DDL_02_5 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TABLES 
    WHERE  
        TABLE_NAME = 'APP_ERROR_LOG';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE APP_ERROR_LOG
            (
            ERROR_LOG_ID            NUMBER        NOT NULL, 
            ENTITY_ID               NUMBER         ,
            ERROR_CODE              VARCHAR2(1000) ,
            ERROR_MSG               CLOB           ,
            APP_NAME                VARCHAR2(30)   ,
            ERROR_LOG_TIME          TIMESTAMP(6)   ,
            CREATED_BY              VARCHAR2(100)  ,
            CREATED_DATE            TIMESTAMP(6)   ,
            MODIFIED_BY             VARCHAR2(100)  ,
            MODIFIED_DATE           TIMESTAMP(6)   
            )';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;
