--liquibase formatted sql
--changeset Swetha.H:HISTORYS_DDL_05 splitStatements:false
--preconditions onFail:HALT onError:HALT

CREATE OR REPLACE EDITIONABLE PROCEDURE ARCHIVE_INSTANCE_TABLES_BACATALOGS (
op_msg OUT VARCHAR2
)
AS
--l_errno    number;
--l_msg    varchar2(4000);
--l_idx    number;
pei_instance_id number;
pei_lca_id number;
g_n_execution_id_seq number;
v_limit NUMBER:='10000';
ln_errors NUMBER;
l_vc_enable_flag ARCHIVAL_TABLE_CONFIG.is_active%TYPE;
dml_errors EXCEPTION;
CURSOR pei_ver_del IS select instance_id,lca_id from(
 select pei.instance_id,lca.LCA_STATUS,lca.LCA_VERSION,lca.lca_id,dense_rank ()over(partition by  lca.entity_id order by lca.LCA_VERSION desc)rk from product_entity_instance pei,       
life_cycle_activity lca where lca.entity_id = pei.instance_id  --and lca.LCA_STATUS='Completed' 
and  pei.instance_id=1808936107) where rk<>1;
CURSOR sgp_ver_del IS select instance_id,lca_id,entity_id from(
 select sgp.instance_id,lca.LCA_STATUS,lca.LCA_VERSION,lca.lca_id,sgp.entity_id,dense_rank ()over(partition by  sgp.entity_id order by sgp.VERSION desc)rk 
from product_entity_instance pei,  service_group_parameter sgp,
life_cycle_activity lca where pei.instance_id=sgp.entity_id and lca.entity_id = sgp.instance_id  --and lca.LCA_STATUS='Completed' 
and sgp.entity_id in (Select instance_id from product_entity_instance pee, life_cycle_activity lcc where 
 lcc.entity_id = pee.instance_id 
and  pei.instance_id=1808936107)) where rk<>1;-- and LCA_STATUS='Completed';


PRAGMA exception_init ( dml_errors, -24381 );
--NUMBER v_limit IS v_limit;
--NUMBER ln_errors IS ln_errors;
--ARCHIVAL_TABLE_CONFIG.is_active%TYPE l_vc_enable_flag IS l_vc_enable_flag;
--EXCEPTION dml_errors IS dml_errors;
TYPE brecord1 IS TABLE OF sgp_ver_del%rowtype;

TYPE brecord IS TABLE OF pei_ver_del%rowtype;
brec1 brecord1;
brec brecord;


BEGIN
insert into stg_temp_archive_data  (instance_id,status,created_date,schema_name)
select instance_id,'Pending',systimestamp,'BACATALOG' from(
 select sgp.instance_id,lca.LCA_STATUS,lca.LCA_VERSION,lca.lca_id,dense_rank ()over(partition by  sgp.entity_id order by sgp.VERSION desc)rk 
from product_entity_instance pei,  service_group_parameter sgp,
life_cycle_activity lca where pei.instance_id=sgp.entity_id and lca.entity_id = sgp.instance_id  --and lca.LCA_STATUS='Completed' 
and sgp.entity_id in (Select instance_id from product_entity_instance pee, life_cycle_activity lcc where 
 lcc.entity_id = pee.instance_id 
 and pei.instance_id=1808936078)) where rk<>1;




insert into stg_temp_archive_data (instance_id,status,created_date,schema_name)select instance_id,'Pending',systimestamp,'BACATALOG' from (select instance_id from(
 select pei.instance_id,lca.LCA_STATUS,lca.LCA_VERSION,lca_id,dense_rank ()over(partition by  lca.entity_id order by lca.LCA_VERSION desc)rk from product_entity_instance pei,       
life_cycle_activity lca where lca.entity_id = pei.instance_id  --and lca.LCA_STATUS='Completed' 
and  pei.instance_id=1808936078) where rk<>1 );--and LCA_STATUS='Completed');  


g_n_execution_id_seq  := INSTANCE_ARCHIVAL_GEN_ID_SEQ.nextval;

SELECT is_active INTO l_vc_enable_flag FROM ARCHIVAL_TABLE_CONFIG WHERE INSTANCE_TABLE_NAME = 'ARCH_SERVICE_GROUP_PARAMETER';

--begin
OPEN sgp_ver_del; 
LOOP            
FETCH sgp_ver_del BULK COLLECT INTO brec1 LIMIT v_limit;  
 EXIT WHEN brec1.COUNT = 0;

--begin
     OPEN pei_ver_del;   
     LOOP
     FETCH pei_ver_del BULK COLLECT INTO brec LIMIT v_limit;  
 EXIT WHEN brec.COUNT = 0;
 FORALL vloop IN 1..brec1.count --SAVE EXCEPTIONS
INSERT INTO ARCH_LIFE_CYCLE_ACTIVITY(LCA_ID,LCA_TYPE,LCA_DESCRIPTION,LCA_VERSION,LCA_STATUS,LCA_STATUS_DTM,LCA_LEVEL,LCA_PRIORITY,LCA_DEPENDENCY_DATE,LCA_CREATION_DTM,LCA_CREATED_BY,LCA_SCHEDULE,LCA_DISPLAY_ON_TIMELINE,LCA_PLAN_START_DTM,LCA_PLAN_END_DTM,LCA_ACTUAL_START_DTM,LCA_ACTUAL_END_DTM,LCA_POTENTIAL_START_DTM,LCA_POTENTIAL_END_DTM,LCA_DURATION_PLAN,LCA_DURATION_ACTUAL,LCA_THRESHOLD,LCA_THRESHOLD_REASON_CODE,LCA_THRESHOLD_DATE,LCA_MILESTONE,LCA_REASON_CODE,LCA_COLOR_CODE,LCA_LABEL_COUNT,LCA_BEHAVIOUR_CODE,CPC_LCA_ID,CPC_LCA_VERSION,LCA_PARENT_ID,LCA_CHILD_ID,LCA_ROOT_ID,LCA_EXTERNAL_SOURCE_ID,LCA_NAME,LCA_COMPLETION_PERCENTAGE,LCA_MILESTONE_DTM,LCA_MODIFIED_BY,LCA_MODIFIED_ON,LCA_OWNER,ENTITY_SEQ,ENTITY_ID,ENTITY_NAME,LCA_ACTIVITY_REASON,LCA_ACTIVITY,VERSION,LIFE_CYCLE_ID,LCA_USERID,STANDARD_AGE,GRACE_AGE,CRITICAL_AGE,TYPE,CATEGORY,COMMENTS,REJECT_REASON,REJECT_DESCRIPTION,JEOPARDY_DESCRIPTION,JEOPARDY_CODE,RECALL_REASON,USER_GROUP,LCA_RULE_ID,LCA_RULE_STATUS,META_DATA_LIFECYCLEID,BUSINESS_ENTITY_TYPE,METADATA_VERSION)SELECT LCA.LCA_ID,LCA.LCA_TYPE,LCA.LCA_DESCRIPTION,LCA.LCA_VERSION,LCA.LCA_STATUS,LCA.LCA_STATUS_DTM,LCA.LCA_LEVEL,LCA.LCA_PRIORITY,LCA.LCA_DEPENDENCY_DATE,LCA.LCA_CREATION_DTM,LCA.LCA_CREATED_BY,LCA.LCA_SCHEDULE,LCA.LCA_DISPLAY_ON_TIMELINE,LCA.LCA_PLAN_START_DTM,LCA.LCA_PLAN_END_DTM,LCA.LCA_ACTUAL_START_DTM,LCA.LCA_ACTUAL_END_DTM,LCA.LCA_POTENTIAL_START_DTM,LCA.LCA_POTENTIAL_END_DTM,LCA.LCA_DURATION_PLAN,LCA.LCA_DURATION_ACTUAL,LCA.LCA_THRESHOLD,LCA.LCA_THRESHOLD_REASON_CODE,LCA.LCA_THRESHOLD_DATE,LCA.LCA_MILESTONE,LCA.LCA_REASON_CODE,LCA.LCA_COLOR_CODE,LCA.LCA_LABEL_COUNT,LCA.LCA_BEHAVIOUR_CODE,LCA.CPC_LCA_ID,LCA.CPC_LCA_VERSION,LCA.LCA_PARENT_ID,LCA.LCA_CHILD_ID,LCA.LCA_ROOT_ID,LCA.LCA_EXTERNAL_SOURCE_ID,LCA.LCA_NAME,LCA.LCA_COMPLETION_PERCENTAGE,LCA.LCA_MILESTONE_DTM,LCA.LCA_MODIFIED_BY,LCA.LCA_MODIFIED_ON,LCA.LCA_OWNER,LCA.ENTITY_SEQ,LCA.ENTITY_ID,LCA.ENTITY_NAME,LCA.LCA_ACTIVITY_REASON,LCA.LCA_ACTIVITY,LCA.VERSION,LCA.LIFE_CYCLE_ID,LCA.LCA_USERID,LCA.STANDARD_AGE,LCA.GRACE_AGE,LCA.CRITICAL_AGE,LCA.TYPE,LCA.CATEGORY,LCA.COMMENTS,LCA.REJECT_REASON,LCA.REJECT_DESCRIPTION,LCA.JEOPARDY_DESCRIPTION,LCA.JEOPARDY_CODE,LCA.RECALL_REASON,LCA.USER_GROUP,LCA.LCA_RULE_ID,LCA.LCA_RULE_STATUS,LCA.META_DATA_LIFECYCLEID,LCA.BUSINESS_ENTITY_TYPE,LCA.METADATA_VERSION  FROM LIFE_CYCLE_ACTIVITY  LCA where entity_id  =brec1(vloop).instance_id and lca_id=brec1(vloop).LCA_ID;
--DBMS_OUTPUT.PUT_LINE( ' lca inert '||brec1(vloop).LCA_ID);

FORALL vloop IN 1..brec1.count --SAVE EXCEPTIONS
INSERT INTO ARCH_SERVICE_GROUP_PARAMETER(INSTANCE_ID,VERSION,PARENT_ID,VC_KEY_NAME1,INSTANT_KEY1,VALUE1,VC_KEY_NAME2,INSTANT_KEY2,VALUE2,VC_KEY_NAME3,INSTANT_KEY3,VALUE3,VC_KEY_NAME4,INSTANT_KEY4,VALUE4,VC_KEY_NAME5,INSTANT_KEY5,VALUE5,VC_KEY_NAME6,INSTANT_KEY6,VALUE6,VC_KEY_NAME7,INSTANT_KEY7,VALUE7,VC_KEY_NAME8,INSTANT_KEY8,VALUE8,VC_KEY_NAME9,INSTANT_KEY9,VALUE9,VC_KEY_NAME10,INSTANT_KEY10,VALUE10,VC_KEY_NAME11,INSTANT_KEY11,VALUE11,VC_KEY_NAME12,INSTANT_KEY12,VALUE12,VC_KEY_NAME13,INSTANT_KEY13,VALUE13,VC_KEY_NAME14,INSTANT_KEY14,VALUE14,VC_KEY_NAME15,INSTANT_KEY15,VALUE15,VC_KEY_NAME16,INSTANT_KEY16,VALUE16,VC_KEY_NAME17,INSTANT_KEY17,VALUE17,VC_KEY_NAME18,INSTANT_KEY18,VALUE18,VC_KEY_NAME19,INSTANT_KEY19,VALUE19,VC_KEY_NAME20,INSTANT_KEY20,VALUE20,VC_KEY_NAME21,INSTANT_KEY21,VALUE21,VC_KEY_NAME22,INSTANT_KEY22,VALUE22,VC_KEY_NAME23,INSTANT_KEY23,VALUE23,VC_KEY_NAME24,INSTANT_KEY24,VALUE24,VC_KEY_NAME25,INSTANT_KEY25,VALUE25,VC_KEY_NAME26,INSTANT_KEY26,VALUE26,VC_KEY_NAME27,INSTANT_KEY27,VALUE27,VC_KEY_NAME28,INSTANT_KEY28,VALUE28,VC_KEY_NAME29,INSTANT_KEY29,VALUE29,VC_KEY_NAME30,INSTANT_KEY31,VALUE32,VC_KEY_NAME33,INSTANT_KEY33,VALUE33,VC_KEY_NAME34,INSTANT_KEY34,VALUE34,VC_KEY_NAME35,INSTANT_KEY35,VALUE35,VC_KEY_NAME36,INSTANT_KEY36,VALUE36,VC_KEY_NAME37,INSTANT_KEY37,VALUE37,VC_KEY_NAME38,INSTANT_KEY38,VALUE38,VC_KEY_NAME39,INSTANT_KEY39,VALUE39,VC_KEY_NAME40,INSTANT_KEY40,VALUE40,LIFECYCLE_ID,VC_KEY1,VC_KEY2,VC_KEY3,VC_KEY4,VC_KEY5,VC_KEY6,VC_KEY7,VC_KEY8,VC_KEY9,VC_KEY10,VC_KEY11,VC_KEY12,VC_KEY13,VC_KEY14,VC_KEY15,VC_KEY16,VC_KEY17,VC_KEY18,VC_KEY19,VC_KEY20,VC_KEY21,VC_KEY22,VC_KEY23,VC_KEY24,VC_KEY25,VC_KEY26,VC_KEY27,VC_KEY28,VC_KEY29,VC_KEY30,VC_KEY33,VC_KEY34,VC_KEY35,VC_KEY36,VC_KEY37,VC_KEY38,VC_KEY39,VC_KEY40,ENTITY_ID,INSTANT_KEY30,INSTANT_KEY32,VALUE30,VALUE31,VC_KEY_NAME31,VC_KEY_NAME32,INSTANT_KEY41,VALUE41,VC_KEY_NAME41,INSTANT_KEY42,VALUE42,VC_KEY_NAME42,INSTANT_KEY43,VALUE43,VC_KEY_NAME43,INSTANT_KEY44,VALUE44,VC_KEY_NAME44,INSTANT_KEY45,VALUE45,VC_KEY_NAME45,VC_KEY31,VC_KEY32,VC_KEY41,VC_KEY42,VC_KEY43,VC_KEY44,VC_KEY45,VC_KEY_NAME46,INSTANT_KEY46,VALUE46,VC_KEY_NAME47,INSTANT_KEY47,VALUE47,VC_KEY_NAME48,INSTANT_KEY48,VALUE48,VC_KEY_NAME49,INSTANT_KEY49,VALUE49,VC_KEY_NAME50,INSTANT_KEY50,VALUE50,VC_KEY_NAME51,INSTANT_KEY51,VALUE51,VC_KEY_NAME52,INSTANT_KEY52,VALUE52,VC_KEY_NAME53,INSTANT_KEY53,VALUE53,VC_KEY_NAME54,INSTANT_KEY54,VALUE54,VC_KEY_NAME55,INSTANT_KEY55,VALUE55,VC_KEY_NAME56,INSTANT_KEY56,VALUE56,VC_KEY_NAME57,INSTANT_KEY57,VALUE57,VC_KEY_NAME58,INSTANT_KEY58,VALUE58,VC_KEY_NAME59,INSTANT_KEY59,VALUE59,VC_KEY_NAME60,INSTANT_KEY60,VALUE60,VC_KEY46,VC_KEY47,VC_KEY48,VC_KEY49,VC_KEY50,VC_KEY51,VC_KEY52,VC_KEY53,VC_KEY54,VC_KEY55,VC_KEY56,VC_KEY57,VC_KEY58,VC_KEY59,VC_KEY60,META_DATA_LIFECYCLEID,METADATA_VERSION)SELECT SGP.INSTANCE_ID,SGP.VERSION,SGP.PARENT_ID,SGP.VC_KEY_NAME1,SGP.INSTANT_KEY1,SGP.VALUE1,SGP.VC_KEY_NAME2,SGP.INSTANT_KEY2,SGP.VALUE2,SGP.VC_KEY_NAME3,SGP.INSTANT_KEY3,SGP.VALUE3,SGP.VC_KEY_NAME4,SGP.INSTANT_KEY4,SGP.VALUE4,SGP.VC_KEY_NAME5,SGP.INSTANT_KEY5,SGP.VALUE5,SGP.VC_KEY_NAME6,SGP.INSTANT_KEY6,SGP.VALUE6,SGP.VC_KEY_NAME7,SGP.INSTANT_KEY7,SGP.VALUE7,SGP.VC_KEY_NAME8,SGP.INSTANT_KEY8,SGP.VALUE8,SGP.VC_KEY_NAME9,SGP.INSTANT_KEY9,SGP.VALUE9,SGP.VC_KEY_NAME10,SGP.INSTANT_KEY10,SGP.VALUE10,SGP.VC_KEY_NAME11,SGP.INSTANT_KEY11,SGP.VALUE11,SGP.VC_KEY_NAME12,SGP.INSTANT_KEY12,SGP.VALUE12,SGP.VC_KEY_NAME13,SGP.INSTANT_KEY13,SGP.VALUE13,SGP.VC_KEY_NAME14,SGP.INSTANT_KEY14,SGP.VALUE14,SGP.VC_KEY_NAME15,SGP.INSTANT_KEY15,SGP.VALUE15,SGP.VC_KEY_NAME16,SGP.INSTANT_KEY16,SGP.VALUE16,SGP.VC_KEY_NAME17,SGP.INSTANT_KEY17,SGP.VALUE17,SGP.VC_KEY_NAME18,SGP.INSTANT_KEY18,SGP.VALUE18,SGP.VC_KEY_NAME19,SGP.INSTANT_KEY19,SGP.VALUE19,SGP.VC_KEY_NAME20,SGP.INSTANT_KEY20,SGP.VALUE20,SGP.VC_KEY_NAME21,SGP.INSTANT_KEY21,SGP.VALUE21,SGP.VC_KEY_NAME22,SGP.INSTANT_KEY22,SGP.VALUE22,SGP.VC_KEY_NAME23,SGP.INSTANT_KEY23,SGP.VALUE23,SGP.VC_KEY_NAME24,SGP.INSTANT_KEY24,SGP.VALUE24,SGP.VC_KEY_NAME25,SGP.INSTANT_KEY25,SGP.VALUE25,SGP.VC_KEY_NAME26,SGP.INSTANT_KEY26,SGP.VALUE26,SGP.VC_KEY_NAME27,SGP.INSTANT_KEY27,SGP.VALUE27,SGP.VC_KEY_NAME28,SGP.INSTANT_KEY28,SGP.VALUE28,SGP.VC_KEY_NAME29,SGP.INSTANT_KEY29,SGP.VALUE29,SGP.VC_KEY_NAME30,SGP.INSTANT_KEY31,SGP.VALUE32,SGP.VC_KEY_NAME33,SGP.INSTANT_KEY33,SGP.VALUE33,SGP.VC_KEY_NAME34,SGP.INSTANT_KEY34,SGP.VALUE34,SGP.VC_KEY_NAME35,SGP.INSTANT_KEY35,SGP.VALUE35,SGP.VC_KEY_NAME36,SGP.INSTANT_KEY36,SGP.VALUE36,SGP.VC_KEY_NAME37,SGP.INSTANT_KEY37,SGP.VALUE37,SGP.VC_KEY_NAME38,SGP.INSTANT_KEY38,SGP.VALUE38,SGP.VC_KEY_NAME39,SGP.INSTANT_KEY39,SGP.VALUE39,SGP.VC_KEY_NAME40,SGP.INSTANT_KEY40,SGP.VALUE40,SGP.LIFECYCLE_ID,SGP.VC_KEY1,SGP.VC_KEY2,SGP.VC_KEY3,SGP.VC_KEY4,SGP.VC_KEY5,SGP.VC_KEY6,SGP.VC_KEY7,SGP.VC_KEY8,SGP.VC_KEY9,SGP.VC_KEY10,SGP.VC_KEY11,SGP.VC_KEY12,SGP.VC_KEY13,SGP.VC_KEY14,SGP.VC_KEY15,SGP.VC_KEY16,SGP.VC_KEY17,SGP.VC_KEY18,SGP.VC_KEY19,SGP.VC_KEY20,SGP.VC_KEY21,SGP.VC_KEY22,SGP.VC_KEY23,SGP.VC_KEY24,SGP.VC_KEY25,SGP.VC_KEY26,SGP.VC_KEY27,SGP.VC_KEY28,SGP.VC_KEY29,SGP.VC_KEY30,SGP.VC_KEY33,SGP.VC_KEY34,SGP.VC_KEY35,SGP.VC_KEY36,SGP.VC_KEY37,SGP.VC_KEY38,SGP.VC_KEY39,SGP.VC_KEY40,SGP.ENTITY_ID,SGP.INSTANT_KEY30,SGP.INSTANT_KEY32,SGP.VALUE30,SGP.VALUE31,SGP.VC_KEY_NAME31,SGP.VC_KEY_NAME32,SGP.INSTANT_KEY41,SGP.VALUE41,SGP.VC_KEY_NAME41,SGP.INSTANT_KEY42,SGP.VALUE42,SGP.VC_KEY_NAME42,SGP.INSTANT_KEY43,SGP.VALUE43,SGP.VC_KEY_NAME43,SGP.INSTANT_KEY44,SGP.VALUE44,SGP.VC_KEY_NAME44,SGP.INSTANT_KEY45,SGP.VALUE45,SGP.VC_KEY_NAME45,SGP.VC_KEY31,SGP.VC_KEY32,SGP.VC_KEY41,SGP.VC_KEY42,SGP.VC_KEY43,SGP.VC_KEY44,SGP.VC_KEY45,SGP.VC_KEY_NAME46,SGP.INSTANT_KEY46,SGP.VALUE46,SGP.VC_KEY_NAME47,SGP.INSTANT_KEY47,SGP.VALUE47,SGP.VC_KEY_NAME48,SGP.INSTANT_KEY48,SGP.VALUE48,SGP.VC_KEY_NAME49,SGP.INSTANT_KEY49,SGP.VALUE49,SGP.VC_KEY_NAME50,SGP.INSTANT_KEY50,SGP.VALUE50,SGP.VC_KEY_NAME51,SGP.INSTANT_KEY51,SGP.VALUE51,SGP.VC_KEY_NAME52,SGP.INSTANT_KEY52,SGP.VALUE52,SGP.VC_KEY_NAME53,SGP.INSTANT_KEY53,SGP.VALUE53,SGP.VC_KEY_NAME54,SGP.INSTANT_KEY54,SGP.VALUE54,SGP.VC_KEY_NAME55,SGP.INSTANT_KEY55,SGP.VALUE55,SGP.VC_KEY_NAME56,SGP.INSTANT_KEY56,SGP.VALUE56,SGP.VC_KEY_NAME57,SGP.INSTANT_KEY57,SGP.VALUE57,SGP.VC_KEY_NAME58,SGP.INSTANT_KEY58,SGP.VALUE58,SGP.VC_KEY_NAME59,SGP.INSTANT_KEY59,SGP.VALUE59,SGP.VC_KEY_NAME60,SGP.INSTANT_KEY60,SGP.VALUE60,SGP.VC_KEY46,SGP.VC_KEY47,SGP.VC_KEY48,SGP.VC_KEY49,SGP.VC_KEY50,SGP.VC_KEY51,SGP.VC_KEY52,SGP.VC_KEY53,SGP.VC_KEY54,SGP.VC_KEY55,SGP.VC_KEY56,SGP.VC_KEY57,SGP.VC_KEY58,SGP.VC_KEY59,SGP.VC_KEY60,SGP.META_DATA_LIFECYCLEID,SGP.METADATA_VERSION  FROM SERVICE_GROUP_PARAMETER  SGP where --entity_id =brec1(vloop).entity_id and 
instance_id=brec1(vloop).instance_id ;--and version=brec1(vloop).VERSION;
--DBMS_OUTPUT.PUT_LINE( ' lca inert '||brec1(vloop).instance_id);

FORALL vloop IN 1..brec.count --SAVE EXCEPTIONS

INSERT INTO ARCH_LIFE_CYCLE_ACTIVITY(LCA_ID,LCA_TYPE,LCA_DESCRIPTION,LCA_VERSION,LCA_STATUS,LCA_STATUS_DTM,LCA_LEVEL,LCA_PRIORITY,LCA_DEPENDENCY_DATE,LCA_CREATION_DTM,LCA_CREATED_BY,LCA_SCHEDULE,LCA_DISPLAY_ON_TIMELINE,LCA_PLAN_START_DTM,LCA_PLAN_END_DTM,LCA_ACTUAL_START_DTM,LCA_ACTUAL_END_DTM,LCA_POTENTIAL_START_DTM,LCA_POTENTIAL_END_DTM,LCA_DURATION_PLAN,LCA_DURATION_ACTUAL,LCA_THRESHOLD,LCA_THRESHOLD_REASON_CODE,LCA_THRESHOLD_DATE,LCA_MILESTONE,LCA_REASON_CODE,LCA_COLOR_CODE,LCA_LABEL_COUNT,LCA_BEHAVIOUR_CODE,CPC_LCA_ID,CPC_LCA_VERSION,LCA_PARENT_ID,LCA_CHILD_ID,LCA_ROOT_ID,LCA_EXTERNAL_SOURCE_ID,LCA_NAME,LCA_COMPLETION_PERCENTAGE,LCA_MILESTONE_DTM,LCA_MODIFIED_BY,LCA_MODIFIED_ON,LCA_OWNER,ENTITY_SEQ,ENTITY_ID,ENTITY_NAME,LCA_ACTIVITY_REASON,LCA_ACTIVITY,VERSION,LIFE_CYCLE_ID,LCA_USERID,STANDARD_AGE,GRACE_AGE,CRITICAL_AGE,TYPE,CATEGORY,COMMENTS,REJECT_REASON,REJECT_DESCRIPTION,JEOPARDY_DESCRIPTION,JEOPARDY_CODE,RECALL_REASON,USER_GROUP,LCA_RULE_ID,LCA_RULE_STATUS,META_DATA_LIFECYCLEID,BUSINESS_ENTITY_TYPE,METADATA_VERSION)SELECT LCA.LCA_ID,LCA.LCA_TYPE,LCA.LCA_DESCRIPTION,LCA.LCA_VERSION,LCA.LCA_STATUS,LCA.LCA_STATUS_DTM,LCA.LCA_LEVEL,LCA.LCA_PRIORITY,LCA.LCA_DEPENDENCY_DATE,LCA.LCA_CREATION_DTM,LCA.LCA_CREATED_BY,LCA.LCA_SCHEDULE,LCA.LCA_DISPLAY_ON_TIMELINE,LCA.LCA_PLAN_START_DTM,LCA.LCA_PLAN_END_DTM,LCA.LCA_ACTUAL_START_DTM,LCA.LCA_ACTUAL_END_DTM,LCA.LCA_POTENTIAL_START_DTM,LCA.LCA_POTENTIAL_END_DTM,LCA.LCA_DURATION_PLAN,LCA.LCA_DURATION_ACTUAL,LCA.LCA_THRESHOLD,LCA.LCA_THRESHOLD_REASON_CODE,LCA.LCA_THRESHOLD_DATE,LCA.LCA_MILESTONE,LCA.LCA_REASON_CODE,LCA.LCA_COLOR_CODE,LCA.LCA_LABEL_COUNT,LCA.LCA_BEHAVIOUR_CODE,LCA.CPC_LCA_ID,LCA.CPC_LCA_VERSION,LCA.LCA_PARENT_ID,LCA.LCA_CHILD_ID,LCA.LCA_ROOT_ID,LCA.LCA_EXTERNAL_SOURCE_ID,LCA.LCA_NAME,LCA.LCA_COMPLETION_PERCENTAGE,LCA.LCA_MILESTONE_DTM,LCA.LCA_MODIFIED_BY,LCA.LCA_MODIFIED_ON,LCA.LCA_OWNER,LCA.ENTITY_SEQ,LCA.ENTITY_ID,LCA.ENTITY_NAME,LCA.LCA_ACTIVITY_REASON,LCA.LCA_ACTIVITY,LCA.VERSION,LCA.LIFE_CYCLE_ID,LCA.LCA_USERID,LCA.STANDARD_AGE,LCA.GRACE_AGE,LCA.CRITICAL_AGE,LCA.TYPE,LCA.CATEGORY,LCA.COMMENTS,LCA.REJECT_REASON,LCA.REJECT_DESCRIPTION,LCA.JEOPARDY_DESCRIPTION,LCA.JEOPARDY_CODE,LCA.RECALL_REASON,LCA.USER_GROUP,LCA.LCA_RULE_ID,LCA.LCA_RULE_STATUS,LCA.META_DATA_LIFECYCLEID,LCA.BUSINESS_ENTITY_TYPE,LCA.METADATA_VERSION  FROM LIFE_CYCLE_ACTIVITY  LCA where entity_id =brec(vloop).instance_id and lca_id=brec(vloop).LCA_ID;
--DBMS_OUTPUT.PUT_LINE( ' lca inert '||brec(vloop).LCA_ID);


end loop;
CLOSE pei_ver_del;

--begin
--exit when brec1.count = 0;
--exit when brec.count = 0;

-- close sgp_ver_del;
-- close pei_ver_del;


/*
EXCEPTION   
        WHEN dml_errors THEN   
     -- BEGIN
        ln_errors := SQL%BULK_EXCEPTIONS.count;
           -- errors := SQL%bulk_exceptions.count;   
           dbms_output.put_line('Number of errors is ' || ln_errors);   
           op_msg := 'FAILURE';   
            FOR i IN  1..ln_errors
            LOOP   
             dbms_output.put_line('Error '|| i|| ' occurred during '|| 'iteration '|| SQL%bulk_exceptions(i).error_index);   
              dbms_output.put_line('Oracle error is '|| sqlerrm(-SQL%bulk_exceptions(i).error_code));

               l_msg  :=  'Error#: ' || i
                 || '; Array index: '
                 || sql%bulk_exceptions(i).error_index ||  ': '
                 || sqlerrm(-sql%bulk_exceptions(i).error_code);
           --   l_errno := sqlerrm(-sql%bulk_exceptions(i).error_code);
                  --  l_msg   := sqlerrm(-l_errno);
                  -- l_idx   := sql%bulk_exceptions(exceptions(i)).error_index; 
                   INSERT
  INTO archival_gen_error
    (
      INSTANCE_ARCHIVAL_EXECUTION_ID,
      INSTANCE_ARCHIVAL_PROC_NAME,
     instance_id,-- INSTANCE_ARCHIVAL_LOGS,
      INSTANCE_ARCHIVAL_ERROR_CODE,
      INSTANCE_ARCHIVAL_ERROR_MSG,
      INSTANCE_ARCHIVAL_EXECUTION_TIME
    )
    VALUES
                    (  g_n_execution_id_seq,
                     'Error in executing package spec -'||  substr(SUBSTR(DBMS_UTILITY.format_call_stack,157),1,81),
         brec1(i).instance_id,--      brec(i),--  brec.instance_id,
              null,-- l_errno,
              l_msg,
                     systimestamp);

END LOOP;
*/
/*FORALL vloop IN brec.first..brec.last SAVE EXCEPTIONS
update stg_temp_archive_data set status='SUCCESS' where instance_id in (select instance_id from ARCH_PRODUCT_ENTITY_INSTANCE where instance_id=brec(vloop));
FORALL vloop IN brec.first..brec.last SAVE EXCEPTIONS
INSERT
  INTO instance_archival_gen_trace
    (
      INSTANCE_ARCHIVAL_EXECUTION_ID,
      INSTANCE_ARCHIVAL_PROC_NAME,
      INSTANCE_ARCHIVAL_LOGS,
      INSTANCE_ARCHIVAL_DYNAMIC_SCRIPT,
    INSTANCE_ID,
      INSTANCE_ARCHIVAL_EXECUTION_TIME
    )
    VALUES
    (
    g_n_execution_id_seq,
    substr(SUBSTR(DBMS_UTILITY.format_call_stack,157),1,81),
     DBMS_UTILITY.format_call_stack,
      'ID Archived Successfully'
,
      brec(vloop),
      systimestamp
    );

FORALL vloop IN 1..brec.count SAVE EXCEPTIONS
DELETE FROM LIFE_CYCLE_ACTIVITY where entity_id =brec(vloop).instance_id and lca_id=brec(vloop).LCA_ID;
FORALL vloop IN 1..brec1.count SAVE EXCEPTIONS
DELETE FROM LIFE_CYCLE_ACTIVITY where entity_id  =brec1(vloop).instance_id and lca_id=brec1(vloop).LCA_ID;
FORALL vloop IN 1..brec1.count SAVE EXCEPTIONS
DELETE FROM SERVICE_GROUP_PARAMETER where entity_id =brec1(vloop).entity_id and  instance_id=brec1(vloop).instance_id ;--and version=brec1(vloop).VERSION;

*/


op_msg := 'SUCCESS';

--     exit when pei_ver_del%notfound;
--        exit when pei_ver_del%notfound;

END LOOP;

--update stg_temp_archive_data  st set st.status='SUCCESS' where  not exists (select 1 from archival_gen_error  ar where st.instance_id=ar.instance_id and trunc(INSTANCE_ARCHIVAL_EXECUTION_TIME)=trunc(created_date)) and status='Pending';
--exception when others then 
--dbms_output.put_line('Error ');
CLOSE sgp_ver_del;

END archive_instance_tables_BACATALOGs;


--changeset Swetha.H:HISTORYS_DDL_05_02 splitStatements:false
--preconditions onFail:HALT onError:HALT

create or replace PROCEDURE PROC_APPLICATION_ERROR_LOG(
ip_entity_id number,
ip_error_code varchar2,
ip_error_msg clob,
ip_app_name varchar2,
ip_created_by varchar2
)
AS PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
INSERT INTO app_error_log (
     ERROR_LOG_ID,                
     ENTITY_ID ,                    
     ERROR_CODE ,          
     ERROR_MSG  ,          
     APP_NAME   ,            
     ERROR_LOG_TIME,         
     CREATED_BY  ,           
     CREATED_DATE ,           
     MODIFIED_BY   ,        
     MODIFIED_DATE
     ) VALUES
     (
     ERROR_LOG_ID_SEQ.NEXTVAL,
     ip_entity_id,
     ip_error_code,
     ip_error_msg,
     ip_app_name,
     systimestamp,
     ip_created_by,
     systimestamp,
     null,
     null
     );
COMMIT;
END PROC_APPLICATION_ERROR_LOG;

