--liquibase formatted sql
--changeset Vijaysree.S:BACATALOG_DML_03 splitStatements:true
--preconditions onFail:HALT onError:HALT

CREATE UNIQUE INDEX PK_LCA_ID ON LIFE_CYCLE_ACTIVITY (LCA_ID) 
  ;

CREATE INDEX IDX_LCA_VERSION ON LIFE_CYCLE_ACTIVITY (LCA_VERSION) 
  ;

CREATE INDEX IDX_LCA_TYPE ON LIFE_CYCLE_ACTIVITY (LCA_TYPE) 
  ;

CREATE INDEX IDX_LCA_STATUS ON LIFE_CYCLE_ACTIVITY (LCA_STATUS) 
  ;

CREATE INDEX IDX_LCA_MODIFED_ON ON LIFE_CYCLE_ACTIVITY (LCA_MODIFIED_ON) 
  ;

CREATE INDEX IDX_LCA_MODI ON LIFE_CYCLE_ACTIVITY (NVL(TO_CHAR(LCA_MODIFIED_ON,'MM-DD-YYYY'),TO_CHAR(LCA_CREATION_DTM,'MM-DD-YYYY'))) 
  ;

CREATE INDEX IDX_LCA_LIFECYCLE_ID ON LIFE_CYCLE_ACTIVITY (LIFE_CYCLE_ID) 
  ;

CREATE INDEX IDX_LCA_CREATED_DTM ON LIFE_CYCLE_ACTIVITY (LCA_CREATION_DTM) 
  ;

CREATE INDEX IDX_LCA_CATEGORY ON LIFE_CYCLE_ACTIVITY (CATEGORY) 
  ;

CREATE INDEX IDX_ENTITYLCA ON LIFE_CYCLE_ACTIVITY (ENTITY_ID) 
  ;

CREATE INDEX IDX_ENTITYLCA_META ON LIFE_CYCLE_ACTIVITY_METADATA (ENTITY_ID) 
  ;

CREATE INDEX IDX_LCA_VERSION_META ON LIFE_CYCLE_ACTIVITY_METADATA (LCA_VERSION) 
  ;

CREATE INDEX IDX_LCA_TYPE_META ON LIFE_CYCLE_ACTIVITY_METADATA (LCA_TYPE) 
  ;

CREATE INDEX IDX_LCA_STATUS_META ON LIFE_CYCLE_ACTIVITY_METADATA (LCA_STATUS) 
  ;

CREATE INDEX IDX_LCA_LIFECYCLE_ID_META ON LIFE_CYCLE_ACTIVITY_METADATA (LIFE_CYCLE_ID) 
  ;

CREATE INDEX IDX_LCA_CYCLE_VERSION_METADATA ON LIFE_CYCLE_ACTIVITY_METADATA (LIFE_CYCLE_ID, LCA_VERSION) 
  ;

CREATE INDEX METADATA_DLT_TRC_IND ON METADATA_DELETE_TRACE (TRUNC(METADATA_DELETE_EXECUTION_TIME)) 
  ;

CREATE INDEX METADATA_CRT_DT_IND ON METADATA_SCRIPT_EXPORT (TRUNC(CREATED_DATE)) 
  ;

CREATE INDEX IDX_PAS_PARENTID ON PARAMETER_ADDON_SPECIFICATION (PARENT_ID) 
  ;

CREATE INDEX IDX_DISPLAY_NAME ON PARAMETER_ADDON_SPECIFICATION (DISPLAY_NAME) 
  ;

CREATE INDEX IDX_DEFAULT_VALUE ON PARAMETER_ADDON_SPECIFICATION (DEFAULT_VALUE) 
  ;

CREATE INDEX IDX_PARAM_DATA_SPEC_PARENTID ON PARAMETER_DATA_SPECIFICATION (PARENT_ID) 
  ;

CREATE INDEX IDX_PARAM_SPEC_ID ON PARAMETER_REFERENCE_VALUE (PARAM_SPEC_ID) 
  ;

CREATE INDEX IDX_CATEGORY_TYPE ON PARAMETER_REFERENCE_VALUE (CATEGORY_TYPE) 
  ;

CREATE INDEX IDX_RULE_ID ON PARAMETER_RULE_SPECIFICATION (RULE_ID) 
  ;

CREATE INDEX IDX_REFERENCE_STORE_ID ON PARAMETER_RULE_SPECIFICATION (REFERENCE_STORE_ID) 
  ;

CREATE INDEX IDX_PARENT_ID ON PARAMETER_RULE_SPECIFICATION (PARENT_ID) 
  ;

CREATE INDEX IND_DYNAMIC_REFERENCE_ID ON PARAMETER_RULE_SPECIFICATION (DYNAMIC_REFERENCE_ID) 
  ;

CREATE INDEX IDX_PARAM_PARENTID ON PARAMETER_SPECIFICATION (PARENT_ID) 
  ;

CREATE INDEX IND_PARAM_NAME ON PARAMETER_SPECIFICATION (PARAM_NAME) 
  ;

CREATE INDEX IDX_BUSINESS_ENTITYID ON PLAN_INSTANCE_SPECIFICATION (BUSINESS_ENTITYID) 
  ;

CREATE INDEX IDX_OFF_ID_VER ON PP_RELATION (PROD_OFF_ID, PROD_OFF_VER, PP_UID, PP_LEVEL, PARENT_ID) 
  ;

CREATE INDEX IDX_PP_PARENT_ID ON PP_RELATION (PARENT_ID) 
  ;

CREATE INDEX IND_PP_RELAT_PLANID ON PP_RELATION (PLAN_ID) 
  ;

CREATE INDEX IDX_PAS_PARENT_ID ON PROCESS_ACTION_SPECIFICATION (PARENT_ID) 
  ;

CREATE INDEX IDX_ROOT_ID ON PROCESS_ENTITY (ROOT_ID) 
  ;

CREATE INDEX IDX_PROCESS_ENT_PARENT_ID ON PROCESS_ENTITY (PARENT_ID) 
  ;

CREATE INDEX IDX_PROCESS_ACTION_TYPE ON PROCESS_ENTITY (ACTION_TYPE) 
  ;

CREATE INDEX IDX_PE_TYPE ON PROCESS_ENTITY (TYPE) 
  ;

CREATE INDEX IDX_PE_SEQ ON PROCESS_ENTITY (PROCESS_SEQUENCE) 
  ;

CREATE INDEX IDX_PE_LIFECYCLEID ON PROCESS_ENTITY (LIFECYCLE_ID) 
  ;

CREATE UNIQUE INDEX PK_PEI_INSTANCE_ID ON PROCESS_ENTITY_INSTANCE (INSTANCE_ID) 
  ;

CREATE INDEX IND_ROOT_ID_PEI ON PROCESS_ENTITY_INSTANCE (ROOT_ID) 
  ;

CREATE INDEX IDX_PROCESS_ENT_INS_TYP ON PROCESS_ENTITY_INSTANCE (TYPE) 
  ;

CREATE INDEX IDX_PROCESS_ENT_INS_STS ON PROCESS_ENTITY_INSTANCE (STATUS) 
  ;

CREATE INDEX IDX_PROCESS_ENT_INS_CTD_DT ON PROCESS_ENTITY_INSTANCE (TRUNC(CREATED_DATE)) 
  ;

CREATE INDEX IDX_PEI_PARENT_ROOT_ID ON PROCESS_ENTITY_INSTANCE (PARENT_ROOT_ID) 
  ;

CREATE INDEX IDX_PEI_PARENT_INSTANCE_ID ON PROCESS_ENTITY_INSTANCE (PARENT_INSTANCE_ID) 
  ;

CREATE INDEX IDX_PEI_LIFECYCLEID ON PROCESS_ENTITY_INSTANCE (LIFECYCLE_ID) 
  ;

CREATE INDEX IDX_METADATA ON PROCESS_ENTITY_INSTANCE (META_DATA_ID) 
  ;

CREATE UNIQUE INDEX PK_CHILD_PARENT_INST_ID ON PROCESS_ENTITY_RELATION (CHILD_INSTANCE_ID, PARENT_INSTANCE_ID) 
  ;

CREATE INDEX IDX_PARENT_INSTANCE_ID ON PROCESS_ENTITY_RELATION (PARENT_INSTANCE_ID) 
  ;

CREATE INDEX IDX_CHILD_INSTANCE_ID ON PROCESS_ENTITY_RELATION (CHILD_INSTANCE_ID) 
  ;

CREATE INDEX IDX_PROCESS_GROUP ON PROCESS_ENTITY_SPECIFICATION (PROCESS_GROUP) 
  ;

CREATE INDEX IDX_PROCESS_ENT_TYPE ON PROCESS_ENTITY_SPECIFICATION (TYPE) 
  ;

CREATE INDEX IDX_PROCESS_ENT_NAME ON PROCESS_ENTITY_SPECIFICATION (NAME) 
  ;

CREATE INDEX IDX_PES_LIFECYCLE ON PROCESS_ENTITY_SPECIFICATION (LIFECYCLE_ID) 
  ;

CREATE INDEX IDX_PES_DEPENDENT_ASYNC_TASK_ID ON PROCESS_ENTITY_SPECIFICATION (DEPENDENT_ASYNC_TASK_ID) 
  ;

CREATE INDEX IDX_PARAM_ENTITY_SPEC_PID ON PROCESS_ENTITY_SPECIFICATION (PID) 
  ;

CREATE INDEX IDX_LOWER_NAME ON PROCESS_ENTITY_SPECIFICATION (LOWER(NAME)) 
  ;

CREATE INDEX IDX_PARENTID_PLS ON PROCESS_LAYOUT_SPECIFICATION (PARENT_ID) 
  ;

CREATE UNIQUE INDEX PK_PRODEI_INSTANCE_ID ON PRODUCT_ENTITY_INSTANCE (INSTANCE_ID) 
  ;

CREATE INDEX IND_ENTITY_TYPE_PEI ON PRODUCT_ENTITY_INSTANCE (ENTITY_TYPE) 
  ;

CREATE INDEX IDX_REL_PARENT_ID ON PRODUCT_ENTITY_RELATION (PARENT_ID) 
  ;

CREATE INDEX IDX_REL_CHILD_ID ON PRODUCT_ENTITY_RELATION (CHILD_ID) 
  ;

CREATE INDEX IND_TYPE_PER ON PRODUCT_ENTITY_RELATION (TYPE) 
  ;

CREATE INDEX IND_CTD_DT_PER ON PRODUCT_ENTITY_RELATION (TRUNC(CREATED_DATE)) 
  ;

CREATE INDEX IDX_REF_VAL_ID ON REFERENCE_HIERARCHY (REF_VAL_ID) 
  ;

CREATE INDEX IDX_ENTITY_ID ON RULE (ENTITY_ID, ENTITY_TYPE_ID) 
  ;

CREATE INDEX IDX_RE_ENTITYID ON RULE_EXPRESSION (ENTITY_ID) 
  ;

CREATE INDEX IDX_RULE_EXP ON RULE_EXPRESSION (RULE_ID) 
  ;

CREATE INDEX IDX_SERVICE ON SERVICE (S_SF_ID, S_ST_ID) 
  ;

CREATE INDEX IDX_SERV_NAME ON SERVICE (S_NAME) 
  ;

CREATE INDEX IDX_SERVICE_FEATURE_ASSOC ON SERVICE_FEATURE_ASSOC (PARENT_SID, CHILD_SID) 
  ;

CREATE INDEX IDX_SP_LIFECYCLE_ID ON SERVICE_GROUP_PARAMETER (LIFECYCLE_ID) 
  ;

CREATE INDEX IDX_SP_ENTITY_ID ON SERVICE_GROUP_PARAMETER (ENTITY_ID) 
  ;

CREATE INDEX IDX_TABLE_ROW_PARAM_MAPPING ON TABLE_PARAMETER_MAPPING (ROW_SPEC_ID) 
  ;

CREATE INDEX IDX_TABLE_ROW_SPEC_PARENTID ON TABLE_ROW_SPECIFICATION (PARENT_ID) 
  ;

CREATE INDEX IDX_TABLE_SPEC_PARENTID ON TABLE_SPECIFICATION (PARENT_ID) 
  ;

CREATE INDEX IDX_DOMAIN_TYPE ON BUSINESS_ENTITY (DOMAIN_TYPE) 
  ;

CREATE INDEX IDX_BEP_PARENT_ID ON BUSINESS_ENTITY_PARAMETER (PARENT_ID) 
  ;

CREATE INDEX IDX_BEP_PARAMETER_SPEC_ID ON BUSINESS_ENTITY_PARAMETER (PARAMETER_SPEC_ID) 
  ;

CREATE INDEX IDX_NAME ON BUSINESS_ENTITY_PARAMETER (NAME) 
  ;

CREATE INDEX IDX_BP_BID ON BUSINESS_PARAMETERS (BID) 
  ;

CREATE UNIQUE INDEX PK_BPI_INSTANCE_ID ON BUSINESS_PROCESS_INSTANCE (INSTANCE_ID) 
  ;

CREATE INDEX IDX_BUSINESS_PROCESS_PARENT ON BUSINESS_PROCESS_INSTANCE (PARENT_ID) 
  ;

CREATE INDEX IDX_BPI_METADATA_ID ON BUSINESS_PROCESS_INSTANCE (META_DATA_ID) 
  ;

CREATE INDEX IDX_BPI_ENTITY_ID ON BUSINESS_PROCESS_INSTANCE (ENTITYID) 
  ;

CREATE INDEX IDX_PARENTID ON BUSINESS_PROCESS_MAPPING (PARENT_ID) 
  ;

CREATE INDEX IDX_BPM_ENTITYID ON BUSINESS_PROCESS_MAPPING (ENTITYID) 
  ;

CREATE INDEX IDX_CHARGE_ITEM_ID ON CHARGE_PARAMETER_SPECIFICATION (CHARGE_ITEM_ID) 
  ;

CREATE INDEX IDX_BILL_RUN_EXC_ID ON CYCLE_PREP_SUMMARY (BILL_RUN_EXC_ID) 
  ;

CREATE INDEX IDX_CYCLE_PREP_ID ON CYCLE_PREP_SUMMARY (CYCLE_PREP_ID) 
  ;

CREATE INDEX IDX_JOIN_PID ON ENTITY_GROUP_FUNCTION (JOIN_PID) 
  ;

CREATE INDEX IDX_ENT_FUNC_ID ON ENTITY_GROUP_FUNCTION (ENTITY_FUNCTION_ID) 
  ;

CREATE INDEX IDX_EGF_RELATED_FUNCTION_ID ON ENTITY_GROUP_FUNCTION (RELATED_FUNCTION_ID) 
  ;

CREATE INDEX IDX_EGF_PID ON ENTITY_GROUP_FUNCTION (PID) 
  ;

CREATE INDEX IDX_EGF_PARENT_PID ON ENTITY_GROUP_FUNCTION (PARENT_PID) 
  ;

CREATE INDEX IDX_EGF_BID ON ENTITY_GROUP_FUNCTION (BID) 
  ;

CREATE INDEX IDX_PARAM_LIFECYCLEID ON ENTITY_GROUP_PARAMETER_VALUES (LIFECYCLE_ID) 
  ;

CREATE INDEX IDX_ENGPV_PARAM_SPEC_ID ON ENTITY_GROUP_PARAMETER_VALUES (PARAM_SPEC_ID) 
  ;

CREATE INDEX IDX_EGPV_PARENT_ID ON ENTITY_GROUP_PARAMETER_VALUES (PARENT_ID) 
  ;

CREATE INDEX IDX_EGPV_ENTITY_ID ON ENTITY_GROUP_PARAMETER_VALUES (ENTITY_ID) 
  ;

CREATE INDEX INDEX_EJP_PARAMKEY ON ENTITY_JOIN_PARAMETER (PARAMKEY1, PARAMKEY2) 
  ;

CREATE INDEX INDEX_EJP_GROUP_ID ON ENTITY_JOIN_PARAMETER (GROUP_ID) 
  ;

CREATE INDEX INDEX_EJP_ENT_FUNC_ID ON ENTITY_JOIN_PARAMETER (ENTITY_FUNCTION_ID) 
  ;

CREATE INDEX IDX_PARENT_ENTITY_ID ON HIERARCHY_METADATA (PARENT_ENTITY_ID) 
  ;

CREATE INDEX IDX_HIERARCHY_ENTITY_ID ON HIERARCHY_METADATA (HIERARCHY_ENTITY_ID) 
  ;

CREATE INDEX IND_ETY_NAME_PLC ON PROJECT_LIFECYCLE_ACTIVITY (ENTITY_NAME) 
  ;

CREATE INDEX IND_ROOT_ID_PLC ON PROJECT_LIFECYCLE_ACTIVITY (ROOT_ID) 
  ;

CREATE INDEX IND_TYP_PROJ_LIFE_CYC ON PROJECT_LIFECYCLE_ACTIVITY (TYPE) 
  ;

CREATE INDEX IND_LOC_ID_PLS ON PROJECT_LIFECYCLE_ACTIVITY (LOCATION_ID) 
  ;

CREATE INDEX IDX_MOD_PAR_ROOT_ID ON MASTER_OBJECT_DETAILS (PARENT_ROOT_ID) 
  ;

CREATE INDEX IDX_MOD_ENTITY_ID ON MASTER_OBJECT_DETAILS (ENTITY_ID) 
  ;


--changeset Swetha.H:BACATALOG_DDL_03_02 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_IND_COLUMNS 
    WHERE  
        INDEX_NAME = 'IDX_WRK_SPC_ENT_ID'
		AND COLUMN_NAME = 'ENTITY_ID';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_WRK_SPC_ENT_ID ON WORKSPACE_ENTITY_DETAILS (ENTITY_ID)';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Swetha.H:BACATALOG_DDL_03_03 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_IND_COLUMNS 
    WHERE  
        INDEX_NAME = 'IDX_WRK_SPC_REL_ID'
		AND COLUMN_NAME = 'WORKSPACE_REL_ID';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_WRK_SPC_REL_ID ON WORKSPACE_ENTITY_DETAILS (WORKSPACE_REL_ID)';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Swetha.H:BACATALOG_DDL_03_04 splitStatements:false
--preconditions onFail:HALT onError:HALT


DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_IND_COLUMNS 
    WHERE  
        INDEX_NAME = 'IDX_WRK_SPC_ENT_VER'
		AND COLUMN_NAME = 'ENTITY_VERSION';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_WRK_SPC_ENT_VER ON WORKSPACE_ENTITY_DETAILS (ENTITY_VERSION)';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;
