--liquibase formatted sql
--changeset Vijaysree.S:BACATALOG_DML_04 splitStatements:true
--preconditions onFail:HALT onError:HALT

ALTER TABLE PROJECT_LIFECYCLE_ACTIVITY ADD CONSTRAINT PROJECT_LIFECYCLE_ID_PK PRIMARY KEY (PROJECT_LIFECYCLE_ID)
  USING INDEX  ENABLE;

ALTER TABLE ENTITY_JSON_MAPPING ADD CONSTRAINT ENTITY_JSON_MAP_ID_PK PRIMARY KEY (ENTITY_JSON_MAP_ID)
  USING INDEX  ENABLE;

ALTER TABLE STATUS_HIERARCHY ADD CONSTRAINT STS_HRCHY_ID_PK PRIMARY KEY (STS_HRCHY_ID)
  USING INDEX  ENABLE;

ALTER TABLE BUSINESS_SCHEDULER_JOBS ADD CONSTRAINT JOB_ID_PK PRIMARY KEY (JOB_ID)
  USING INDEX  ENABLE;

ALTER TABLE BUSINESS_ENTITY_PARAMETER ADD CONSTRAINT BUSINESS_ENTITY_PARAMETER_PK PRIMARY KEY (RECORD_KEY_PARAM)
  USING INDEX  ENABLE;

ALTER TABLE PRICE_PLAN_SPECIFICATION ADD CONSTRAINT PK_PP_PP_INSTANCE_ID PRIMARY KEY (PP_INSTANCE_ID)
  USING INDEX  ENABLE;

ALTER TABLE ENTITY_GROUP_FUNCTION ADD CONSTRAINT ENTITY_GROUP_FUNCT_ID_PK PRIMARY KEY (ENTITY_GROUP_FUNC_ID)
  USING INDEX  ENABLE;

ALTER TABLE CHARGING_ATTRIBUTE ADD CONSTRAINT CHARGING_ATTRBIUTE_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE;

ALTER TABLE CHARGING_ALGORITHM ADD CONSTRAINT CHARGING_ALGORITHM_PK PRIMARY KEY (CHARGING_ALGORITHM_ID)
  USING INDEX  ENABLE;

ALTER TABLE SERVICE_GROUP_PARAMETER ADD CONSTRAINT SERVICE_GROUP_PARAMETER_PK PRIMARY KEY (INSTANCE_ID)
  USING INDEX  ENABLE;

ALTER TABLE PARAMETER_FORMAT_ADDON_SPEC ADD CONSTRAINT PARAM_FORMAT_ADDON_SPEC_ID_PK PRIMARY KEY (PARAM_FORMAT_ADDON_SPEC_ID)
  USING INDEX  ENABLE;

ALTER TABLE PRODUCT_CODE_DETAILS ADD CONSTRAINT PRDT_CODE_ID_PK PRIMARY KEY (PRODUCT_CODE_ID)
  USING INDEX  ENABLE;

ALTER TABLE ERROR_INFO ADD CONSTRAINT ERROR_ID_PK PRIMARY KEY (ERROR_ID)
  USING INDEX  ENABLE;

ALTER TABLE CHARGE_PARAMETER_SPECIFICATION ADD CONSTRAINT PK_CHARGE_INSTANCE_ID PRIMARY KEY (CHARGE_INSTANCE_ID)
  USING INDEX  ENABLE;

ALTER TABLE PARAMETER_REFERENCE_VALUE ADD CONSTRAINT PARAM_REF_VAL_ID_PK PRIMARY KEY (PARAM_REF_VAL_ID)
  USING INDEX  ENABLE;

ALTER TABLE PROCESS_ENTITY ADD CONSTRAINT PK_PID_PARENT_ID_VER_RT PRIMARY KEY (PID, VERSION, PARENT_ID, ROOT_ID)
  USING INDEX  ENABLE;

ALTER TABLE TABLE_SPECIFICATION ADD CONSTRAINT PK_TS_ID PRIMARY KEY (ID)
  USING INDEX  ENABLE;

ALTER TABLE PARAMETER_FUNC_SPECIFICATION ADD CONSTRAINT PARAM_FUNC_SPEC_PK PRIMARY KEY (PARAM_FUNC_SPEC_ID)
  USING INDEX  ENABLE;

ALTER TABLE COUNTER_ENTITY_INSTANCE ADD CONSTRAINT PK_COUNTER_INS_ID PRIMARY KEY (ID)
  USING INDEX  ENABLE;

ALTER TABLE EMAIL_TEMPLATE ADD CONSTRAINT EMAIL_TEMP_ID_PK PRIMARY KEY (EMAIL_TEMP_ID)
  USING INDEX  ENABLE;

ALTER TABLE PARAMETER_DATA_SPECIFICATION ADD CONSTRAINT PK_PARAM_DATA_SPEC_ID PRIMARY KEY (PARAM_DATA_SPEC_ID)
  USING INDEX  ENABLE;

ALTER TABLE BUSINESS_PARAMETERS ADD CONSTRAINT BUSINESS_PARAM_ID_PK PRIMARY KEY (BUSINESS_PARAM_ID)
  USING INDEX  ENABLE;

ALTER TABLE PROCESS_ACTION_SPECIFICATION ADD CONSTRAINT PK_ACTION_ID PRIMARY KEY (ACTION_ID)
  USING INDEX  ENABLE;

ALTER TABLE DECISION_TREE ADD CONSTRAINT PK_DECTNODE_ID PRIMARY KEY (DECISION_TREE_NODE_ID)
  USING INDEX  ENABLE;

ALTER TABLE PRODUCT_OFFERING ADD CONSTRAINT PROD_OFFERING_PK PRIMARY KEY (PROD_OFF_ID, PROD_OFF_VER)
  USING INDEX  ENABLE;

ALTER TABLE PRICE_PLAN_COUNTER ADD CONSTRAINT PK_PRICE_PLNA PRIMARY KEY (PRICE_PLAN_PRICING_ID)
  USING INDEX  ENABLE;

ALTER TABLE ENTITY_JOIN_PARAMETER ADD CONSTRAINT ENTITY_JOIN_PARAM_ID_PK PRIMARY KEY (ENTITY_JOIN_PARAM_ID)
  USING INDEX  ENABLE;

ALTER TABLE OBJECT_CHANGE_DETAILS ADD CONSTRAINT OBJ_DET_SCRIPT_ID_PK PRIMARY KEY (SCRIPT_ID)
  USING INDEX  ENABLE;

ALTER TABLE COUNTRY ADD CONSTRAINT COUNTRY_PK PRIMARY KEY (NAME)
  USING INDEX  ENABLE;

ALTER TABLE PARAMETER_RULE_SPECIFICATION ADD CONSTRAINT PK_PARAM_RULE_SPEC_ID PRIMARY KEY (PARAM_RULE_SPEC_ID)
  USING INDEX  ENABLE;

ALTER TABLE PARAMETER_ADDON_SPECIFICATION ADD CONSTRAINT PK_PARAM_ADDON_SPEC_ID PRIMARY KEY (PARAM_ADDON_SPEC_ID)
  USING INDEX  ENABLE;

ALTER TABLE SERVICE_COLUMN_METADATA ADD CONSTRAINT SER_COL_META_ID_PK PRIMARY KEY (SERV_COL_META_ID)
  USING INDEX  ENABLE;

ALTER TABLE HIERARCHY_METADATA ADD CONSTRAINT HIERARCHY_META_ID_PK PRIMARY KEY (HIERARCHY_METADATA_ID)
  USING INDEX  ENABLE;

ALTER TABLE BUSINESS_PROCESS_MAPPING ADD CONSTRAINT BUSINESS_PROCESS_ENTITY_PK PRIMARY KEY (RECORD_KEY)
  USING INDEX  ENABLE;

ALTER TABLE PARAMETER ADD CONSTRAINT PK_PARAMETER_ID PRIMARY KEY (PARAMETER_ID)
  USING INDEX  ENABLE;

ALTER TABLE PRICE_PLAN_ENTITY ADD CONSTRAINT PRICE_PLAN_ENTITY_ID_PK PRIMARY KEY (PRICE_PLAN_ENTITY_ID)
  USING INDEX  ENABLE;

ALTER TABLE REFERENCE_TYPES ADD CONSTRAINT REF_TYPE_ID_PK PRIMARY KEY (REF_TYPE_ID)
  USING INDEX  ENABLE;

ALTER TABLE RULE ADD CONSTRAINT RULE_PK PRIMARY KEY (RULE_ID)
  USING INDEX  ENABLE;

ALTER TABLE INVOICE_BILLING ADD CONSTRAINT BILLING_ID_PK PRIMARY KEY (BILLING_ID)
  USING INDEX  ENABLE;

ALTER TABLE LIFE_CYCLE_ACTIVITY_METADATA ADD CONSTRAINT LCA_ID_META_PK PRIMARY KEY (LCA_ID)
  USING INDEX  ENABLE;

ALTER TABLE BUSINESS_ENTITY ADD CONSTRAINT BID_PK PRIMARY KEY (BID)
  USING INDEX  ENABLE;

ALTER TABLE ENTITY_BOUNDARY_CONDITION ADD CONSTRAINT EBC_ID_PK PRIMARY KEY (EBC_ID)
  USING INDEX  ENABLE;

ALTER TABLE PRICE_PLAN ADD CONSTRAINT PK_PRICE_PLAN_ID PRIMARY KEY (PRICE_PLAN_ID)
  USING INDEX  ENABLE;

ALTER TABLE ENTITY_GROUP_PARAMETER_VALUES ADD CONSTRAINT PK_PARAM_INST_ID PRIMARY KEY (PARAM_INSTANCE_ID)
  USING INDEX  ENABLE;

ALTER TABLE PROCESS_LAYOUT_SPECIFICATION ADD CONSTRAINT PK_LAYOUT_ID PRIMARY KEY (LAYOUT_ID)
  USING INDEX  ENABLE;

ALTER TABLE SERVICE ADD CONSTRAINT SERVICE_PK PRIMARY KEY (S_ID)
  USING INDEX  ENABLE;

ALTER TABLE SCRIPT_INFO ADD CONSTRAINT SCRIPT_ID_PK PRIMARY KEY (SCRIPT_ID)
  USING INDEX  ENABLE;

ALTER TABLE BUSINESS_ENTITY_RELATION ADD CONSTRAINT BUSINESS_ENTITY_REL_ID_PK PRIMARY KEY (BUSINESS_ENTITY_REL_ID)
  USING INDEX  ENABLE;

ALTER TABLE TABLE_ROW_SPECIFICATION ADD CONSTRAINT PK_TRS_ID PRIMARY KEY (ID)
  USING INDEX  ENABLE;

ALTER TABLE RULE_EXECUTION_LOG ADD CONSTRAINT PK_LOG_ID PRIMARY KEY (RULE_LOG_ID)
  USING INDEX  ENABLE;

ALTER TABLE INVOICE_INFO ADD CONSTRAINT PK_INVOICE_ID PRIMARY KEY (INVOICE_ID)
  USING INDEX  ENABLE;

ALTER TABLE ACTION_INPUT_PARAMETER ADD CONSTRAINT ACTION_INPUT_PARAM_ID_PK PRIMARY KEY (ACTION_INPUT_PARAM_ID)
  USING INDEX  ENABLE;

ALTER TABLE PP_RELATION ADD CONSTRAINT PP_RELATION_PK PRIMARY KEY (PP_UID)
  USING INDEX  ENABLE;

ALTER TABLE COUNTER ADD CONSTRAINT PK_COUNTER_ID PRIMARY KEY (ID)
  USING INDEX  ENABLE;

ALTER TABLE TABLE_PARAMETER_MAPPING ADD CONSTRAINT TAB_PARAM_MAPPING_ID_PK PRIMARY KEY (TABL_PARAM_MAPPING_ID)
  USING INDEX  ENABLE;

ALTER TABLE PROCESS_ENTITY_SPECIFICATION ADD CONSTRAINT PK_PROCESS_SPEC_ID PRIMARY KEY (PROCESS_SPEC_ID)
  USING INDEX  ENABLE;

ALTER TABLE CUSTOM_TEMPLATE_MAPPING ADD CONSTRAINT CUSTOM_TEMPL_MAP_ID_PK PRIMARY KEY (CUSTOM_TEMPL_MAP_ID)
  USING INDEX  ENABLE;

ALTER TABLE PARAMETER_SPECIFICATION ADD CONSTRAINT PK_PARAM_BASIC_SPEC_ID PRIMARY KEY (PARAM_BASIC_SPEC_ID)
  USING INDEX  ENABLE;

ALTER TABLE RULE_EXPRESSION ADD CONSTRAINT RULE_EXPRESSION_PK PRIMARY KEY (RULE_EXPRESSION_ID)
  USING INDEX  ENABLE;

ALTER TABLE USER_AUTH_PROCESS_MAPPING ADD CONSTRAINT USR_AUTH_PROC_MAPPING_ID_PK PRIMARY KEY (USR_AUTH_PROC_MAPPING_ID)
  USING INDEX  ENABLE;

ALTER TABLE ENTITY_PRODUCT_CODE_MAPPING ADD CONSTRAINT ENTITY_PRD_CD_PK PRIMARY KEY (ENTITY_PRD_CD_ID)
  USING INDEX  ENABLE;

ALTER TABLE BUSINESS_ENTITY_SPECIFICATION ADD CONSTRAINT PK_BUSINESS_ENTITY_SPEC_ID PRIMARY KEY (BUSINESS_ENTITY_SPEC_ID)
  USING INDEX  ENABLE;

ALTER TABLE PROCESS_ENTITY_INSTANCE ADD CONSTRAINT PK_PEI_INSTANCE_ID PRIMARY KEY (INSTANCE_ID)
  USING INDEX PK_PEI_INSTANCE_ID  ENABLE;

ALTER TABLE REFERENCE_TYPE_VALUES ADD CONSTRAINT REF_TYPE_VALUE_ID_PK PRIMARY KEY (REF_VAL_ID)
  USING INDEX  ENABLE;

ALTER TABLE LIFE_CYCLE_ACTIVITY ADD CONSTRAINT PK_LCA_ID PRIMARY KEY (LCA_ID)
  USING INDEX PK_LCA_ID  ENABLE;

ALTER TABLE PROCESS_ENTITY_RELATION ADD CONSTRAINT PK_CHILD_PARENT_INST_ID PRIMARY KEY (CHILD_INSTANCE_ID, PARENT_INSTANCE_ID)
  USING INDEX PK_CHILD_PARENT_INST_ID  ENABLE;

ALTER TABLE PRODUCT_ENTITY_INSTANCE ADD CONSTRAINT PK_PRODEI_INSTANCE_ID PRIMARY KEY (INSTANCE_ID)
  USING INDEX PK_PRODEI_INSTANCE_ID  ENABLE;

ALTER TABLE BUSINESS_PROCESS_INSTANCE ADD CONSTRAINT PK_BPI_INSTANCE_ID PRIMARY KEY (INSTANCE_ID)
  USING INDEX PK_BPI_INSTANCE_ID  ENABLE;

ALTER TABLE ACCOUNT_DETAILS ADD PRIMARY KEY (ACCOUNT_ID)
  USING INDEX  ENABLE;

ALTER TABLE CUSTOMER_DETAILS ADD PRIMARY KEY (CUSTOMER_ID)
  USING INDEX  ENABLE;

ALTER TABLE ADDRESS_DETAILS ADD PRIMARY KEY (ADDRESS_ID)
  USING INDEX  ENABLE;

ALTER TABLE MASTER_OBJECT_DETAILS ADD CONSTRAINT MASTER_ID_PK PRIMARY KEY (MASTER_ID)
  USING INDEX  ENABLE;

ALTER TABLE PARAMETER_RULE_SPECIFICATION ADD CONSTRAINT PARAMETER_RULE_SPECIFICAT_FK1 FOREIGN KEY (RULE_ID)
	  REFERENCES RULE (RULE_ID) ENABLE NOVALIDATE;

ALTER TABLE BUSINESS_PROCESS_MAPPING ADD CONSTRAINT FK_ENTITYID FOREIGN KEY (ENTITYID)
	  REFERENCES BUSINESS_ENTITY (BID) ENABLE NOVALIDATE;

ALTER TABLE BUSINESS_ENTITY_RELATION ADD CONSTRAINT FK_BER_BID FOREIGN KEY (PARENT_ID)
	  REFERENCES BUSINESS_ENTITY (BID) ENABLE NOVALIDATE;

ALTER TABLE BUSINESS_ENTITY_PARAMETER ADD CONSTRAINT ENTITY_GROUP_JOIN_FUNCTIO_FK1 FOREIGN KEY (PARENT_ID)
	  REFERENCES BUSINESS_PROCESS_MAPPING (RECORD_KEY) ENABLE;

ALTER TABLE PRICE_PLAN_SPECIFICATION ADD CONSTRAINT PRICE_PLAN_SPECIFICATION_FK1 FOREIGN KEY (PRICE_PLAN_ID)
	  REFERENCES PRICE_PLAN (PRICE_PLAN_ID) ENABLE NOVALIDATE;

ALTER TABLE PRICE_PLAN_SPECIFICATION ADD CONSTRAINT DECISION_TREE_NODE_ID_FK FOREIGN KEY (DECISION_TREE_NODE_ID)
	  REFERENCES DECISION_TREE (DECISION_TREE_NODE_ID) ENABLE NOVALIDATE;

ALTER TABLE CHARGING_ALGORITHM ADD CONSTRAINT CHARGING_ALG_CHARGI_FK FOREIGN KEY (CHARGING_ATTRIBUTE)
	  REFERENCES CHARGING_ATTRIBUTE (ID) ENABLE NOVALIDATE;

ALTER TABLE REFERENCE_TYPE_VALUES ADD CONSTRAINT REF_TYPE_ID_FK FOREIGN KEY (REF_TYPE_ID)
	  REFERENCES REFERENCE_TYPES (REF_TYPE_ID) ENABLE;

ALTER TABLE CHARGE_PARAMETER_SPECIFICATION ADD CONSTRAINT CHARGE_PARAMETER_SPECIFIC_FK1 FOREIGN KEY (RULE_ID)
	  REFERENCES RULE (RULE_ID) ENABLE NOVALIDATE;

ALTER TABLE REFERENCE_TYPE_VALUES ADD CONSTRAINT REF_HIERARCHY_TYPE_FK FOREIGN KEY (HIERARCHY_ID)
	  REFERENCES REFERENCE_TYPE_VALUES (REF_VAL_ID) ENABLE;

ALTER TABLE PRICE_PLAN_ENTITY ADD CONSTRAINT FK_BID FOREIGN KEY (ENTITY_ID)
	  REFERENCES BUSINESS_ENTITY (BID) ENABLE;

ALTER TABLE BUSINESS_PROCESS_INSTANCE ADD CONSTRAINT FK_BPI_PARENT_ID FOREIGN KEY (PARENT_ID)
	  REFERENCES PROCESS_ENTITY_INSTANCE (INSTANCE_ID) ENABLE;

ALTER TABLE BUSINESS_PROCESS_INSTANCE ADD CONSTRAINT FK_BPI_ENTITYID FOREIGN KEY (ENTITYID)
	  REFERENCES PRODUCT_ENTITY_INSTANCE (INSTANCE_ID) ENABLE;

ALTER TABLE SERVICE_GROUP_PARAMETER ADD CONSTRAINT SERVICE_GROUP_PARAMETER_FK1 FOREIGN KEY (PARENT_ID)
	  REFERENCES BUSINESS_PROCESS_INSTANCE (INSTANCE_ID) ENABLE;

ALTER TABLE ENTITY_PRODUCT_CODE_MAPPING ADD CONSTRAINT ENTITY_PRD_MAP_FK FOREIGN KEY (PRODUCT_CODE_ID)
	  REFERENCES PRODUCT_CODE_DETAILS (PRODUCT_CODE_ID) DISABLE;


--changeset Vijaysree.S:BACATALOG_DML_04_02 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONSTRAINTS 
    WHERE  
        CONSTRAINT_NAME = 'ADDRESS_ID_PK' ;

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE location_information ADD CONSTRAINT address_id_pk PRIMARY KEY (address_id)';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;



--changeset Vijaysree.S:BACATALOG_DML_04_03 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONSTRAINTS 
    WHERE  
        CONSTRAINT_NAME = 'PROJECT_UNIQUE' ;

    IF L_CNT = 1 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PROJECT_LIFECYCLE_ACTIVITY DROP CONSTRAINT PROJECT_UNIQUE';
		EXECUTE IMMEDIATE 'ALTER TABLE PROJECT_LIFECYCLE_ACTIVITY ADD CONSTRAINT ENT_PARENT_STS_LYF_VER_UK UNIQUE (LIFE_CYCLE_ID,ENTITY_ID,STATUS,PARENT_ID,VERSION)';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Swetha.H:BACATALOG_DDL_04_04 splitStatements:false
--preconditions onFail:HALT onError:HALT


DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONS_COLUMNS
    WHERE  
        TABLE_NAME = 'ENTITY_DEPENDENCY' AND COLUMN_NAME = 'DEPENDENT_ID' AND CONSTRAINT_NAME = 'PK_ENTITY_DEPEND_ID';

    IF L_CNT = 0 THEN
		EXECUTE IMMEDIATE 'ALTER TABLE ENTITY_DEPENDENCY ADD CONSTRAINT PK_ENTITY_DEPEND_ID PRIMARY KEY(DEPENDENT_ID)';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Swetha.H:BACATALOG_DDL_04_05 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONS_COLUMNS 
    WHERE  
	    TABLE_NAME = 'CUSTOM_QUERY_DETAILS' AND
		COLUMN_NAME = 'CUSTOM_QUERY_ID' AND
        CONSTRAINT_NAME = 'CUSTOM_QUERY_ID_PK' ;

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE CUSTOM_QUERY_DETAILS ADD CONSTRAINT CUSTOM_QUERY_ID_PK PRIMARY KEY (CUSTOM_QUERY_ID)';
        DBMS_OUTPUT.PUT_LINE('Created');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Swetha.H:BACATALOG_DDL_04_06 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONSTRAINTS 
    WHERE  
        CONSTRAINT_NAME = 'NOTIFICATION_ID_PK';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE notification_details ADD CONSTRAINT notification_id_pk PRIMARY KEY(notification_id)';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:BACATALOG_DDL_04_07 splitStatements:false
--preconditions onFail:HALT onError:HALT


DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONS_COLUMNS 
    WHERE  
        CONSTRAINT_NAME = 'RELEASE_ID_PK'
		AND COLUMN_NAME = 'RELEASE_ID';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE RELEASE_DETAILS ADD CONSTRAINT RELEASE_ID_PK PRIMARY KEY (RELEASE_ID)';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:BACATALOG_DDL_04_08 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONS_COLUMNS 
    WHERE  
        CONSTRAINT_NAME = 'REL_USR_STRY_ID_PK'
		AND COLUMN_NAME = 'REL_USR_STRY_ID';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE RELEASE_USER_STORY_MAPPING ADD CONSTRAINT REL_USR_STRY_ID_PK PRIMARY KEY (REL_USR_STRY_ID)';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:BACATALOG_DDL_04_09 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONS_COLUMNS 
    WHERE  
        CONSTRAINT_NAME = 'USR_STRY_RELID_FK'
		AND COLUMN_NAME = 'RELEASE_ID';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE RELEASE_USER_STORY_MAPPING ADD CONSTRAINT USR_STRY_RELID_FK FOREIGN KEY (RELEASE_ID)
	  REFERENCES RELEASE_DETAILS (RELEASE_ID) ENABLE';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:BACATALOG_DDL_04_10 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONS_COLUMNS 
    WHERE  
        CONSTRAINT_NAME = 'WORKSPACE_ID_PK'
		AND COLUMN_NAME = 'WORKSPACE_ID';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE WORKSPACE_DETAILS ADD CONSTRAINT WORKSPACE_ID_PK PRIMARY KEY (WORKSPACE_ID)';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:BACATALOG_DDL_04_11 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONS_COLUMNS 
    WHERE  
        CONSTRAINT_NAME = 'WS_DET_REL_STRY_ID_FK'
		AND COLUMN_NAME = 'REL_USR_STRY_ID';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE WORKSPACE_DETAILS ADD CONSTRAINT WS_DET_REL_STRY_ID_FK FOREIGN KEY (REL_USR_STRY_ID)
	  REFERENCES RELEASE_USER_STORY_MAPPING (REL_USR_STRY_ID) ENABLE';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:BACATALOG_DDL_04_12 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONS_COLUMNS 
    WHERE  
        CONSTRAINT_NAME = 'WORKSPACE_REL_ID_PK'
		AND COLUMN_NAME = 'WORKSPACE_REL_ID';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE WORKSPACE_RELEASE_DETAILS ADD CONSTRAINT WORKSPACE_REL_ID_PK PRIMARY KEY (WORKSPACE_REL_ID)';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:BACATALOG_DDL_04_13 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONS_COLUMNS 
    WHERE  
        CONSTRAINT_NAME = 'WORKSPACE_ID_FK'
		AND COLUMN_NAME = 'WORKSPACE_ID';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE WORKSPACE_RELEASE_DETAILS ADD CONSTRAINT WORKSPACE_ID_FK FOREIGN KEY (WORKSPACE_ID)
	  REFERENCES WORKSPACE_DETAILS (WORKSPACE_ID) ENABLE';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;



--changeset Vijaysree.S:BACATALOG_DDL_04_14 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONSTRAINTS
    WHERE  
        CONSTRAINT_NAME = 'PK_MAROFFRE_INSTANCE_ID';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE MARKET_OFFERING_RELATION ADD CONSTRAINT PK_MAROFFRE_INSTANCE_ID PRIMARY KEY (INSTANCE_ID)';
		DBMS_OUTPUT.PUT_LINE('Created');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:BACATALOG_DDL_04_15 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    l_cnt NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO l_cnt
    FROM
        user_constraints
    WHERE
        table_name = 'BILLING_PAYMENT_DETAILS' and constraint_name = 'BILL_PAYMENT_ID_PK';

    IF l_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BILLING_PAYMENT_DETAILS ADD CONSTRAINT BILL_PAYMENT_ID_PK PRIMARY KEY (BILL_PAYMENT_ID)';
        dbms_output.put_line('Altered');
    ELSE
        dbms_output.put_line('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line('Skipped');
END;



--changeset Vijaysree.S:BACATALOG_DDL_04_16 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONSTRAINTS
    WHERE  
        TABLE_NAME = 'REF_LINEOFBUSINESS' AND CONSTRAINT_NAME = 'LOB_ID_PK';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE REF_LINEOFBUSINESS ADD CONSTRAINT LOB_ID_PK PRIMARY KEY (LOB_ID)';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:BACATALOG_DDL_04_17 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONSTRAINTS 
    WHERE  
        CONSTRAINT_NAME = 'USER_LOB_FK' ;

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE USER_LOB_ASSOC ADD CONSTRAINT USER_LOB_FK FOREIGN KEY (USER_ID)
	  REFERENCES USERS (USR_ID) ENABLE';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;
