app.accessCheck=false_updated_new_repo_11
app.centurypostUrl=dev-g7-product,excelacom,in
app.docuSignFileServerPath=/app/NFS/DocuSignUpdated
app.exchangeURL = https://webmail.excelacom.in/ews/exchange.asmx
app.fileExportHost = g7.cvussishtcnk.us-east-1.rds.amazonaws.com
app.fileExportPath = /projects/cm_leo_rep_dir/
app.fileExportPwd = dev123
app.fileExportUser = dev123
app.fileServerPath = /app/VO
app.fileTargetPath = /app/NFS/import
app.imagesFileServerPath = /app/NFS/images
app.imageurl=/app/NFS/images/
app.imapEmailFlag = false
app.importFilePath = /app/import
app.integrationJobCron = 0 0/1 * 1/1 * ?
app.integrationJobFlag = false
app.jobFlag = false
app.jsonFilePath= /app/jsonFiles/
app.pipelineDurationType = Minutes
app.pipelineDurationValue = 1
app.pipelineRunLimit =15
app.postgressFlag=true
app.securityCheckReq=N
app.serverHost = 10.90.1.210
app.serverPath = /app/NFS/
app.serverPwd = root@1234
app.serverUsrName = root
app.taskAccessCheck = false
app.taskJobCron = 0 0/2 * 1/1 * ?
app.falloutTaskJobCron =0 */2 * * * *
app.templatePath = /app/template
app.campaignJobFlag = false
app.campaignJobCron = 0 0/5 * 1/1 * ?
app.endDateTaskJobCron = 0 30 18 * * ?
app.endDateJobFlag = false
UI_THEME=SimplifiedTabMenu

#salesForce
app.EDI=01t5j000000FfgwAAC##01u5j000000YbbbAAC
app.EPL=01t5j000000FeAIAA0##01u5j000000YbE0AAK
app.EVPL=01t5j000003xMwzAAE##01u5j000000gjOSAAY
app.FIA=01t5j000003zC8wAAE##01u5j00000BmyvyAAB
app.FCP=01t5j000009kGi4AAE##01u5j00000Bmz0GAAR

#InternalCalls
app.stubUrl=http://framework-stub:7070/centuryStubAPI/v1/
app.armUrl=http://dev-g7-product.excelacom.in:7070/ARM/v1/armservices/
app.busrefreshUrl=http://businessapp-api-gateway:7001/centuryInboundService/actuator/refresh
app.centuryShieldServiceUrl = https://perf-product.excelacom.in/galaxyshield/service/
app.docuSignUrl=http://framework-docusign-service:7071/centuryDocuSignService/v1/
app.eurekaUrl = http://eureka-service:8081/centuryreports/service/eurekaServices/
app.externalIntegrationUrl=http://businessapp-service:9091/centuryServiceAPI/v1/
app.integServiceUrl=http://framework-integration-service:7004/centuryIntegrationAPI/v1/
app.internalIntegrationUrl=http://businessapp-service:9091/centuryServiceAPI/v1
app.multiSourceUrl=http://businessapp-multisource-api:9095/multisourcedataAPI/multisource
app.nifiUrl = http://dev-g7-product.excelacom.in:32674/nifi-api/
app.notificationUrl=http://framework-notification:1111/centuryNotificationAPI/v1
app.outboundService=http://businessapp-queue-management:7003/centuryQueueService/v1/inBoundRequestService
app.queueCacheUrl=http://businessapp-queue-management:7003/centuryQueueService/v1/reloadAPICache
app.reloadCacheUrl=http://businessapp-api-gateway:7001/centuryInboundService/v1/reloadAPICache
app.ruleServiceUrl=http://businessapp-service:9091/centuryServiceAPI/v1/
app.userManagementUrl = http://businessapp-service:9091/centuryServiceAPI/v1/userManagement
app.pageBuilderServiceUrl = https://dev-g7-product.excelacom.in/pageBuilderService/v1
app.amlUrl=https://dev-g7-product.excelacom.in/galaxyml-service/services/


#Other Application Properties
CLICKATELL_URL=https://platform.clickatell.com/messages 
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.javax.persistence.validation.mode=none
spring.liquibase.change-log=classpath:/db/changelog/changelog-master.xml
spring.liquibase.enabled=false
spring.main.allow-circular-references=true
spring.servlet.multipart.max-file-size =-1
spring.servlet.multipart.max-request-size =-1
swagger.environment.name=dev
app.serverName=NSL_UPG

#ELK Properties
app.commonIp = http://elasticsearch:9200/
app.elkAuthFlag=false
app.elkLogfile=galaxy-dev-ps-logs-%/_search
app.elkPassword=
app.elkUsername=

#CIF Data Source Properties
spring.datasource.cif.auto-commit =true
spring.datasource.cif.connection-timeout=300000 
spring.datasource.cif.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.cif.idle-timeout=30000
spring.datasource.cif.jdbcUrl=jdbc:oracle:thin:@10.90.1.148:1521/REGG7PDT
spring.datasource.cif.leak-detection-threshold=10000
spring.datasource.cif.maximum-pool-size=100
spring.datasource.cif.max-lifetime=30000
spring.datasource.cif.minimum-idle=50
#spring.datasource.cif.username=CIF_PNTR_PERF
#spring.datasource.cif.password=CIF_PNTR_PERF

#BACatalog Data Source Properties
spring.datasource.cm.auto-commit =true
spring.datasource.cm.connection-timeout=300000
spring.datasource.cm.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.cm.idle-timeout=30000
spring.datasource.cm.jdbcUrl=jdbc:oracle:thin:@10.90.1.148:1521/REGG7PDT
spring.datasource.cm.url=jdbc:oracle:thin:@10.90.1.148:1521/REGG7PDT
spring.datasource.cm.leak-detection-threshold=10000
spring.datasource.cm.maximum-pool-size=200
spring.datasource.cm.max-lifetime=300000
spring.datasource.cm.minimum-idle=100
#spring.datasource.cm.username=BACATALOG_PNTR_PERF
#spring.datasource.cm.password=BACATALOG_PNTR_PERF


#Appcatalog Data Source Properties
# spring.datasource.catalog.auto-commit =true
# spring.datasource.catalog.connection-timeout=300000
# spring.datasource.catalog.driver-class-name=oracle.jdbc.OracleDriver
# spring.datasource.catalog.idle-timeout=30000
# spring.datasource.catalog.jdbcUrl=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=tcps)(HOST=10.90.1.99)(PORT=1522))(CONNECT_DATA=(SERVICE_NAME=PANTHERPERF)))
# spring.datasource.catalog.leak-detection-threshold=10000
# spring.datasource.catalog.maximum-pool-size=20
# spring.datasource.catalog.max-lifetime=300000
# spring.datasource.catalog.minimum-idle=10
# spring.datasource.catalog.password=APPCATALOG_G7DEMOPDT
# spring.datasource.catalog.username=APPCATALOG_G7DEMOPDT

# SSL-Properties

app.keyStore=/app/oracletls.jks
app.keyStorePassword=changeit
app.storeType=JKS
app.authentication=true


#CIF postgres
spring.datasource.postgres.jdbcUrl=jdbc:postgresql://10.90.1.49:5432/postgres
spring.datasource.postgres.username=cif_g7k8s
spring.datasource.postgres.password=cif_g7k8s
spring.datasource.postgres.driver-class-name=org.postgresql.Driver


#Async Task Executor Properties
spring.task.execution.pool.core-size=2
spring.task.execution.pool.max-size=200
spring.task.execution.pool.queue-capacity=0
spring.task.execution.thread-name-prefix=autohost-task-
spring.task.scheduling.pool.size=2
spring.task.scheduling.thread-name-prefix=mail-receiver-

#Mail Server Properties
#from.mail.id=century@excelacom.in
#mail.imap.host=mail.excelacom.in
mail.imap.password=June@2024#
mail.imap.port=25
mail.imap.ssl=true
mail.imap.username=century.n
spring.mail.default-encoding=UTF-8
spring.mail.host=webmail.excelacom.in
spring.mail.port=25
spring.mail.protocol=smtp
spring.mail.test-connection=false

#Actuator Properties
info.app.description=BusinessApp Services
info.app.name=BusinessApp Services
management.metrics.tags.application=businessapp-services


#PSY Properties
app.encryptionAlias=nslkey
app.retriggerFlow=true
app.retriggerSLA=1
app.NO_OF_RETRIGGERS=5
spring.rabbitmq.heartBeat=30
app.pythonPath = /app/Century_application/bin/python3
app.replyTimeOut=60000
to.mail.id=galaxy@excelacom.in
app.queuedretriggerurl=https://wireless-nsl-devr2.dev.wtg.spectrum.net/nsl/manage-lines/retrigger-transaction

app.archiveProcessEnabled=false
app.interruptFlag=false

app.delayTime = 100
app.retryLoopCount=3
app.retrySLACount=3
app.masterPersistFlag = false
app.threadNamePrefix=master-task-
app.poolCoreSize=1
app.poolMaxSize=200
app.poolQueueCapacity=0


#Tomcat Thread Properties
server.tomcat.threads.max=5000

app.notificationFlag=false
app.billingTaskJobCron = 0 0 0 1 1 *
app.billingJobFlag = false
app.profile=dev
logging.config=classpath:log4j2.xml
tablesPrimaryKey={'ACCOUNT':'ACCT_ID','LINE':'L_ID','LINE_PLAN':'LINE_PLAN_ID','FEATURE':'FEATURE_ID','CUSTOMER':'CUSTOMER_ID','CONTACT':'CONTACT_ID','ADDRESS':'ADDRESS_ID','SERVICE':'S_ID','TRANSACTION_DETAILS':'TRANSACTION_ID','TRANSACTION_HISTORY':'TRANSACTION_ID','LINE_HISTORY':'LINE_HISTORY_ID','DEVICE':'DEVICE_ID','SIM':'SIM_ID'}
app.applicationUrl=https://dev-g7-product.excelacom.in
app.encryptionPrivateKeyPath=classpath:keystore/nslkeystore.jks
app.encryptionPassword=nsldev
app.encryptionAlias=nslkey
app.retriggerFlow=true
app.retriggerSLA=1
app.NO_OF_RETRIGGERS=2
app.replyTimeOut=60000
to.mail.id=Balaji.J@excelacom.in,Anushikha.A@excelacom.in
CAS_Redirect_URL = https://dev-g7-product.excelacom.in
CS_URL= galaxyshield/service/userManagementRestService
logging.level.com.excelacom.century.framework=TRACE
app.apiFlowEnable=false

spring.kafka.bootstrap-servers=kafka:9092
kafka.topic.partitions=1


spring.main.allow-bean-definition-overriding=true
app.domainTables=Note,NOTE_FOLLOWUP,document_info

spring.lifecycle.timeout-per-shutdown-phase=1m
server.shutdown=graceful

app.sequenceCount=500
app.splitPartition=30
app.locListenerConcurrentConsumer=15
app.locListenerMaxConcurrentConsumer=20
app.listenerConcurrentConsumer=15
app.listenerMaxConcurrentConsumer=20

app.buttonAccessCheck=false

app.menuAccess = false
app.kafkaFlag=false
app.webClientFlag=false
app.retrieveAllFlag=false

app.schedulerFlag=false
app.endDateJobFlag=false
app.OAuthFlag=false

app.embeddedCacheFlag=true
app.hazelcastPort=5701
kafka.topic.replication-factor=1
app.kafkaListenerTopic = fetchAddressTopic

app.perfFlag=false
app.saveFlag=false


app.apigateway.newrepo1234=true
app.apigateway.newrepo4321=true
