--liquibase formatted sql
--changeset Swetha.H:GALAXY_SHIELD_DDL_02
--preconditions onFail:HALT onError:HALT


  CREATE TABLE ACCESSOR 
   (	ACCESSOR_ID NUMBER, 
	ROLE_ID NUMBER, 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6) 
	 --CONSTRAINT ACCESSOR_ROLE_ID_FK FOREIGN KEY (ROLE_ID)
	--  REFERENCES ROLE (ROLE_ID) ENABLE NOVALIDATE
   ) ;

  CREATE TABLE ACCESSTOKEN_INFO 
   (	TOKEN_ID NUMBER, 
	CLIENT_ID NUMBER, 
	TOKEN_TYPE VARCHAR2(100), 
	SERVICE_ID NUMBER, 
	ENCRYPTIONID NUMBER, 
	SUBJECT VARCHAR2(100), 
	EXPIRY_DATE TIMESTAMP (6), 
	ISSUED_DATE TIMESTAMP (6), 
	KEY_TYPE VARCHAR2(100), 
	KEYFILEPATH VARCHAR2(100), 
	SECRET_KEY VARCHAR2(100), 
	TOKEN VARCHAR2(500), 
	STATUS VARCHAR2(100), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6)
	-- CONSTRAINT FK_CLIENT_INFO FOREIGN KEY (CLIENT_ID)
	 -- REFERENCES USERS (USR_ID) ENABLE, 
	-- CONSTRAINT FK_SERV_ID FOREIGN KEY (SERVICE_ID)
	 -- REFERENCES SERVICE_INFO (SERVICE_ID) ENABLE, 
	-- CONSTRAINT FK_ENCRYP_ID FOREIGN KEY (ENCRYPTIONID)
	 -- REFERENCES REF_ENCRYPTION (ID) ENABLE
   ) ;

  CREATE TABLE ACCESS_AUTH 
   (	ACCESSOR_ID NUMBER, 
	RSRC_ID VARCHAR2(100), 
	CREATED_DT TIMESTAMP (6), 
	MODIFY_DT TIMESTAMP (6), 
	CREATED_BY NUMBER, 
	MODIFY_BY NUMBER, 
	READ NUMBER, 
	WRITE NUMBER
	-- CONSTRAINT ACCESS_AUTH_WRITE_FK FOREIGN KEY (WRITE)
	---  REFERENCES REFERENCE_VALUES (VALUE_ID) ENABLE, 
	-- CONSTRAINT ACCESS_AUTH_ACCESSORID_FK FOREIGN KEY (ACCESSOR_ID)
	--  REFERENCES ACCESSOR (ACCESSOR_ID) ENABLE NOVALIDATE, 
	-- CONSTRAINT ACCESS_AUTH_READ_FK FOREIGN KEY (READ)
	--  REFERENCES REFERENCE_VALUES (VALUE_ID) ENABLE
   ) ;

  CREATE TABLE AUTHENTICATION_CONFIG 
   (	AUTH_ID NUMBER, 
	AUTH_TYPE VARCHAR2(500), 
	CMPNY_CD NUMBER, 
	TENANAT_ID NUMBER, 
	PARTNER_ID NUMBER, 
	GROUP_ID NUMBER, 
	USER_ID NUMBER, 
	ISACTIVE NUMBER, 
	CREATED_DT TIMESTAMP (6), 
	MODIFY_DT TIMESTAMP (6), 
	CREATED_BY NUMBER, 
	MODIFY_BY NUMBER
   ) ;

  CREATE TABLE GALAXY_SHIELDSTATS 
   (	STATID VARCHAR2(30), 
	TYPE CHAR(1), 
	VERSION NUMBER, 
	FLAGS NUMBER, 
	C1 VARCHAR2(30), 
	C2 VARCHAR2(30), 
	C3 VARCHAR2(30), 
	C4 VARCHAR2(30), 
	C5 VARCHAR2(30), 
	N1 NUMBER, 
	N2 NUMBER, 
	N3 NUMBER, 
	N4 NUMBER, 
	N5 NUMBER, 
	N6 NUMBER, 
	N7 NUMBER, 
	N8 NUMBER, 
	N9 NUMBER, 
	N10 NUMBER, 
	N11 NUMBER, 
	N12 NUMBER, 
	D1 DATE, 
	R1 RAW(32), 
	R2 RAW(32), 
	CH1 VARCHAR2(1000), 
	CL1 CLOB
   ) ;

  CREATE TABLE CLIENT_SERVICE_ASSOC 
   (	CLIENT_ID NUMBER, 
	SERVICE_ID NUMBER, 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6)
	-- CONSTRAINT FK_SERVIC_ID FOREIGN KEY (SERVICE_ID)
	--  REFERENCES SERVICE_INFO (SERVICE_ID) ENABLE, 
	-- CONSTRAINT FK_CLIENT_ID FOREIGN KEY (CLIENT_ID)
	--  REFERENCES USERS (USR_ID) ENABLE
   ) ;

  CREATE TABLE CMPNY_CLIENT 
   (	CMPNY_CD NUMBER, 
	CLIENT_IP VARCHAR2(100), 
	CREATED_DT VARCHAR2(8), 
	MODIFY_DT VARCHAR2(8), 
	CREATED_BY NUMBER, 
	MODIFIED_BY NUMBER
   ) ;

  CREATE TABLE CMPNY_PARTNER 
   (	CMPNY_PARTNER_ID NUMBER, 
	CMPNY_PARTNER_NAME VARCHAR2(100), 
	SHORT_NAME VARCHAR2(100), 
	CMPNY_PARTNER_TYPE VARCHAR2(100), 
	IMPLEMENTATION_STATUS VARCHAR2(100), 
	PARTNER_DESC VARCHAR2(100), 
	CMPNY_CD VARCHAR2(100), 
	TENANT_ID NUMBER, 
	WEBSITE VARCHAR2(100), 
	INDUSTRY NUMBER, 
	PARTNER_PREF_LANG VARCHAR2(100), 
	VAT_ID VARCHAR2(100), 
	TAX_ID VARCHAR2(100), 
	PARTNER_START_DATE DATE, 
	PARTNER_END_DATE DATE, 
	COMMERCIAL_DATE DATE, 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	ADDRESS1 VARCHAR2(100), 
	ADDRESS2 VARCHAR2(100), 
	COUNTRY VARCHAR2(100), 
	STATE VARCHAR2(100), 
	CITY VARCHAR2(100), 
	ZIPCODE VARCHAR2(100), 
	TITLE NUMBER, 
	FIRST_NAME VARCHAR2(100), 
	LAST_NAME VARCHAR2(100), 
	PHONE_NUMBER NUMBER, 
	ALT_PHONE_NUMBER NUMBER, 
	EMAIL_ID VARCHAR2(100), 
	ISACTIVE NUMBER
   ) ;

  CREATE TABLE CMPNY_TO_CMPNY_REL 
   (	CMPNY_ID1 NUMBER, 
	CREATED_DT TIMESTAMP (6), 
	MODIFIED_DT TIMESTAMP (6), 
	CREATED_BY NUMBER, 
	MODIFIED_BY NUMBER, 
	CMPNY_ID2 NUMBER, 
	REL_TYP_CD NUMBER
	-- CONSTRAINT CMPNY_TO_CMPNY_REL_COMPAN_FK1 FOREIGN KEY (CMPNY_ID1)
	--  REFERENCES COMPANY (CMPNY_CD) ENABLE NOVALIDATE, 
	-- CONSTRAINT CMPNY_REL_TYPES_FK FOREIGN KEY (REL_TYP_CD)
	--  REFERENCES REFERENCE_VALUES (VALUE_ID) ENABLE
   ) ;

  CREATE TABLE COMPANY 
   (	CMPNY_CD NUMBER, 
	CMPNY_NAME VARCHAR2(100), 
	CMPNY_SHORTNAME VARCHAR2(100), 
	CMPNY_DESC VARCHAR2(100), 
	CREATED_BY NUMBER, 
	MODIFY_BY NUMBER, 
	CMPNY_TYPE NUMBER, 
	INDUSTRY NUMBER, 
	WEBSITE VARCHAR2(100), 
	TITLE NUMBER, 
	FIRST_NAME VARCHAR2(100), 
	LAST_NAME VARCHAR2(100), 
	CONTACT_TYPE NUMBER, 
	CMPNY_PREF_LANG NUMBER, 
	JOB_TITLE NUMBER, 
	CONTACT_EMAIL VARCHAR2(400), 
	PHN_NUMBER VARCHAR2(100), 
	EXT_SYSTEM VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_DATE TIMESTAMP (6), 
	ISACTIVE NUMBER
   ) ;

  
  CREATE TABLE DOMAIN_DETAILS 
   (	DOMAIN_ID NUMBER, 
	URL VARCHAR2(200), 
	PRINCIPLE VARCHAR2(100), 
	CREDENTIALS VARCHAR2(100), 
	NAME VARCHAR2(100)
   ) ;

  CREATE TABLE ENTITY_ROLE_ASSOC 
   (	E_R_ID NUMBER, 
	COMPANY_ID NUMBER, 
	GROUP_ID NUMBER, 
	PARTNER_ID NUMBER, 
	TENANT_ID NUMBER, 
	USR_ID NUMBER, 
	ROLE_ID NUMBER, 
	PORTAL_ID NUMBER, 
	CREATED_BY NUMBER, 
	CREATED_DT TIMESTAMP (6), 
	MODIFY_BY NUMBER, 
	MODIFY_DT TIMESTAMP (6)
   ) ;

  CREATE TABLE ENTITY_USER_ASSOC 
   (	ENTITY_TYPE_ID NUMBER, 
	USER_ID NUMBER, 
	VALUE_1 VARCHAR2(100), 
	VALUE_2 VARCHAR2(100), 
	RELATION VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(30), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY NUMBER
	-- CONSTRAINT ENTITY_USER_ASSOC_USERS_FK FOREIGN KEY (USER_ID)
	 -- REFERENCES USERS (USR_ID) ENABLE, 
	 --CONSTRAINT USER_ENTITY_FK FOREIGN KEY (ENTITY_TYPE_ID)
	--  REFERENCES REFERENCE_VALUES (VALUE_ID) ENABLE
   ) ;

  CREATE TABLE EXPORT_RESOURCE_SCRIPT 
   (	ID NUMBER, 
	IP_SCRIPT CLOB, 
	CREATED_DATE TIMESTAMP (6)
   ) ;

  CREATE TABLE GROUPS 
   (	GROUP_ID NUMBER, 
	CREATED_DT TIMESTAMP (5) WITH TIME ZONE, 
	CREATED_BY NUMBER, 
	MODIFIED_BY NUMBER, 
	MODIFIED_DT TIMESTAMP (5) WITH TIME ZONE, 
	GROUP_NAME VARCHAR2(100), 
	GROUP_DESC VARCHAR2(100), 
	PARENT_GROUP_ID NUMBER, 
	CMPNY_CD NUMBER, 
	GROUP_CATEGORY VARCHAR2(30), 
	ISACTIVE NUMBER, 
	CREATE_FOR VARCHAR2(100)
	-- CONSTRAINT PARENT_GROUP_FK FOREIGN KEY (PARENT_GROUP_ID)
	--  REFERENCES GROUPS (GROUP_ID) ENABLE
   ) ;

  CREATE TABLE GROUP_PARTNER_ASSOC 
   (	PARTNER_ID NUMBER, 
	GROUP_ID NUMBER, 
	ACTIVE_FLG VARCHAR2(1), 
	START_DATE TIMESTAMP (6), 
	END_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6) 
	-- CONSTRAINT GROUP_PARTNER_ASSOC_PARTNER_FK FOREIGN KEY (PARTNER_ID)
	--  REFERENCES PARTNER (PARTNER_ID) ENABLE, 
	-- CONSTRAINT GROUP_PARTNER_ASSOC_GROUP_FK FOREIGN KEY (GROUP_ID)
	--  REFERENCES GROUPS (GROUP_ID) ENABLE
   ) ;

  CREATE TABLE GROUP_TO_ROLE 
   (	GROUP_ID NUMBER, 
	ROLE_ID NUMBER, 
	CREATED_DT TIMESTAMP (6), 
	CREATED_BY NUMBER, 
	MODIFIED_DT TIMESTAMP (6), 
	MODIFIED_BY NUMBER, 
	ISACTIVE NUMBER
	-- CONSTRAINT FK_GROUP_TO_ROLE_GROUPID FOREIGN KEY (GROUP_ID)
	--  REFERENCES GROUPS (GROUP_ID) ENABLE NOVALIDATE, 
	-- CONSTRAINT FK_GROUP_TO_ROLEID FOREIGN KEY (ROLE_ID)
	--  REFERENCES ROLE (ROLE_ID) ENABLE NOVALIDATE
   ) ;

  CREATE TABLE GROUP_TO_USER 
   (	CREATED_DT TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DT TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	GROUP_ID NUMBER, 
	USER_ID NUMBER, 
	ISACTIVE NUMBER 
	-- CONSTRAINT GROUP_TO_USER_USERS_FK FOREIGN KEY (USER_ID)
	--  REFERENCES USERS (USR_ID) ENABLE NOVALIDATE, 
	-- CONSTRAINT GROUP_TO_USER_GROUPS_FK FOREIGN KEY (GROUP_ID)
	--  REFERENCES GROUPS (GROUP_ID) ENABLE NOVALIDATE
   ) ;

  CREATE TABLE HIERARCHY_DETAILS 
   (	HIERARCHY_ID NUMBER, 
	HIERARCHY_TYPE VARCHAR2(100), 
	HIERARCHY_NAME VARCHAR2(100), 
	HIERARCHY_VERSION NUMBER, 
	CREATED_BY VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	ISACTIVE NUMBER
   ) ;

  CREATE TABLE HIST_USER 
   (	USR_LOGIN_ID VARCHAR2(100), 
	USR_ID NUMBER, 
	CREATED_BY VARCHAR2(30), 
	CREATED_DATE DATE
	-- CONSTRAINT HIST_USER_FK FOREIGN KEY (USR_ID)
	 -- REFERENCES USERS (USR_ID) ENABLE
   ) ;

  CREATE TABLE ORGANIZATION_ENTITY_DETAILS 
   (	ID NUMBER, 
	NAME VARCHAR2(100), 
	IP_ADDRESS VARCHAR2(100), 
	SERVER_NAME VARCHAR2(100), 
	DESCRIPTION VARCHAR2(100), 
	DB_NAME VARCHAR2(100), 
	PRIMARY_MAIL VARCHAR2(100), 
	ALTERNATE_MAIL VARCHAR2(100), 
	PHONE_NUMEBR VARCHAR2(100), 
	ALT_PHONE_NUMEBR VARCHAR2(100), 
	ACTIVE_FLG VARCHAR2(1), 
	START_DATE TIMESTAMP (6), 
	END_DATE TIMESTAMP (6), 
	SSN NUMBER, 
	COUNTRY VARCHAR2(30), 
	STATE VARCHAR2(30), 
	CITY VARCHAR2(30), 
	ZIPCODE VARCHAR2(10), 
	SUPERVISOR VARCHAR2(100), 
	INDUSTRY VARCHAR2(100), 
	WEBSITE VARCHAR2(100), 
	TITLE NUMBER, 
	FIRST_NAME VARCHAR2(100), 
	LAST_NAME VARCHAR2(100), 
	CONTACT_TYPE NUMBER, 
	JOB_TITLE NUMBER, 
	ISACTIVE NUMBER, 
	ENTITY_ID NUMBER, 
	ORGANIZATION_TYPE VARCHAR2(100), 
	EXT_SYSTEM VARCHAR2(100), 
	PREFERED_LANG NUMBER, 
	CREATED_BY VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	SHORTNAME VARCHAR2(100), 
	ENTITY_SUB_CATOGORY VARCHAR2(100), 
	VAT_ID VARCHAR2(100), 
	TAX_ID VARCHAR2(100), 
	COMMERCIAL_DATE DATE, 
	ADDRESS1 VARCHAR2(100), 
	ADDRESS2 VARCHAR2(100), 
	IMPLEMENTATION_STATUS VARCHAR2(100), 
	TIM_ZN_CD NUMBER, 
	TENANT_ID NUMBER, 
	COMPANY_ID NUMBER, 
	PARTNER_ID NUMBER
   ) ;

  CREATE TABLE ORGANIZATION_ENTITY_RELATION 
   (	PARENT_ID NUMBER, 
	CHILD_ID NUMBER, 
	ENTITY_TYPE VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	ROOT_BRANCH_ID NUMBER, 
	HIERARCHY_ID NUMBER, 
	ORG_HIERARCHY_ID NUMBER, 
	PARENT_ENTITY_TYPE VARCHAR2(255), 
	CHILD_ENTITY_TYPE VARCHAR2(100)
   ) ;

  CREATE TABLE ORGANIZATION_USER_ASSOC 
   (	ORG_ID NUMBER, 
	USER_ID NUMBER, 
	UESR_TYPE VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100)
   ) ;

  CREATE TABLE OTP_CONFIG 
   (	OTP_ID NUMBER, 
	OTP_NAME VARCHAR2(400), 
	MIN_LENGTH NUMBER, 
	MAX_LENGTH NUMBER, 
	OTP_EXPIRY_LIMIT VARCHAR2(400), 
	REGENERATE_OTP VARCHAR2(400), 
	OTP_NOTIFICATION_TYPE VARCHAR2(400), 
	ACQUIRE_CHARATERS VARCHAR2(400), 
	CREATED_DT TIMESTAMP (6), 
	MODIFY_DT TIMESTAMP (6), 
	CREATED_BY NUMBER(38,0), 
	MODIFY_BY NUMBER, 
	ISACTIVE NUMBER
   ) ;

  CREATE TABLE OTP_GENERATION 
   (	USER_ID NUMBER, 
	OTP_CODE VARCHAR2(400), 
	OTP_STATUS NUMBER, 
	CREATED_DT TIMESTAMP (6), 
	MODIFY_DT TIMESTAMP (6), 
	OTP_ATTEMPTS NUMBER
   ) ;

  CREATE TABLE PARTNER 
   (	PARTNER_ID NUMBER, 
	PARTNER_TYPE_ID NUMBER, 
	PARTNER_NAME VARCHAR2(300), 
	CMPNY_CD NUMBER, 
	ACTIVE_FLG VARCHAR2(1), 
	START_DATE TIMESTAMP (6), 
	END_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6)
	-- CONSTRAINT PARTNER_REF_VALAUES_FK FOREIGN KEY (PARTNER_TYPE_ID)
	--  REFERENCES REFERENCE_VALUES (VALUE_ID) ENABLE
   ) ;

  CREATE TABLE PARTNER_ROLE_ASSOC 
   (	PARTNER_ID NUMBER, 
	ROLE_ID NUMBER, 
	ACTIVE_FLG VARCHAR2(1), 
	START_DATE TIMESTAMP (6), 
	END_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6)
	-- CONSTRAINT PARTNER_ROLE_ASSOC_ROLE_FK FOREIGN KEY (ROLE_ID)
	--  REFERENCES ROLE (ROLE_ID) ENABLE, 
	-- CONSTRAINT PARTNER_ROLE_ASSOC_PARTNER_FK FOREIGN KEY (PARTNER_ID)
	 -- REFERENCES PARTNER (PARTNER_ID) ENABLE
   ) ;

  CREATE TABLE PASSWORD_HISTORY_TABLE 
   (	ID NUMBER(19,0), 
	PASSWORD VARCHAR2(2048 CHAR), 
	RECORD_DATE TIMESTAMP (6), 
	USERNAME VARCHAR2(255 CHAR)
   ) ;

  CREATE TABLE PASSWORD_POLICY 
   (	PWD_ID NUMBER, 
	PWD_NAME VARCHAR2(400), 
	PWD_TO_LAST NUMBER, 
	PWD_MIN_AGE NUMBER, 
	PWD_MAX_AGE NUMBER, 
	NO_UPPER_CASE NUMBER, 
	NO_LOWER_CASE NUMBER, 
	ACCEPT_SPEC_CHAR VARCHAR2(400), 
	MIN_LF_PWD VARCHAR2(400), 
	MAX_PWD_ATTEMPTS NUMBER, 
	PWD_EXPIRY VARCHAR2(400), 
	NOTIFICATION_PWD_EXPIRY VARCHAR2(400), 
	ENABLE_PWD_POLICY VARCHAR2(400), 
	ENABLE_STRONG_PWD VARCHAR2(400), 
	CREATED_DT TIMESTAMP (6), 
	MODIFY_DT TIMESTAMP (6), 
	CREATED_BY NUMBER(38,0), 
	MODIFY_BY NUMBER, 
	ISACTIVE NUMBER
   ) ;

  CREATE TABLE POLICY_ASSOCIATION 
   (	POLICY_ID NUMBER, 
	POLICY_NAME VARCHAR2(500), 
	POLICY_TYPE VARCHAR2(500), 
	CMPNY_CD NUMBER, 
	TENANAT_ID NUMBER, 
	PARTNER_ID NUMBER, 
	GROUP_ID NUMBER, 
	USER_ID NUMBER, 
	ISACTIVE NUMBER, 
	CREATED_DT TIMESTAMP (6), 
	MODIFY_DT TIMESTAMP (6), 
	CREATED_BY NUMBER, 
	MODIFY_BY NUMBER
   ) ;

  CREATE TABLE PORTAL 
   (	PORTAL_ID NUMBER, 
	PORTAL_NAME VARCHAR2(50), 
	PORT_NUM VARCHAR2(50), 
	PORTAL_DESC VARCHAR2(50), 
	CMPNY_CD NUMBER, 
	GROUP_ID NUMBER, 
	ROLE_ID NUMBER, 
	CREATED_DT TIMESTAMP (6), 
	MODIFY_DT TIMESTAMP (6), 
	CREATED_BY NUMBER, 
	MODIFY_BY NUMBER, 
	PORTAL_URL VARCHAR2(50), 
	USR_ID NUMBER, 
	PORTAL_TYPE VARCHAR2(50), 
	END_POINT_URL VARCHAR2(200), 
	EXT_SYSTEM_1 VARCHAR2(50), 
	EXT_SYSTEM_2 VARCHAR2(50)
   ) ;

  CREATE TABLE PRESENTATION 
   (	PRSNTTN_ID NUMBER, 
	FRAME_ID VARCHAR2(100), 
	URL VARCHAR2(4000), 
	ONCLICK VARCHAR2(4000), 
	PRSNTTN_LABEL VARCHAR2(200), 
	PRSNTTN_LABEL2 VARCHAR2(100), 
	PRSNTTN_LABEL_TAG VARCHAR2(100), 
	PRSNTTN_LABEL_POS VARCHAR2(100), 
	PRSNTTN_RESTRICT VARCHAR2(100), 
	PRSNTTN_CHK_BX_GRP VARCHAR2(100), 
	PRSNTTN_POS VARCHAR2(100), 
	PRSNTTN_COL_HEADING VARCHAR2(100), 
	CREATED_DT TIMESTAMP (6), 
	MODIFY_DT TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFY_BY VARCHAR2(100), 
	PRSNTTN_COPERMISSIONID VARCHAR2(100), 
	PRSNTTN_DENYUSERCLASS VARCHAR2(100), 
	PRSNTTN_COMPANY_TYPE VARCHAR2(100), 
	PRSNTTTN_ALLOW_USERCLASS VARCHAR2(100), 
	PRSNTTN_GROUP_ID VARCHAR2(200), 
	INDICATOR CHAR(1), 
	FLAG CHAR(1), 
	DEFAULTLAYOUT VARCHAR2(100), 
	EXT_MENU_ID NUMBER, 
	EXT_SYSTEM VARCHAR2(100), 
	PRSNTTN_ORDER NUMBER
   ) ;

  CREATE TABLE REFERENCE_TYPES 
   (	TYPE_ID NUMBER, 
	TYPE_NAME VARCHAR2(100), 
	CREATED_DT TIMESTAMP (6), 
	MODIFY_DT TIMESTAMP (6), 
	CREATED_BY NUMBER, 
	MODIFY_BY NUMBER
   ) ;

  CREATE TABLE REFERENCE_VALUES 
   (	VALUE_ID NUMBER, 
	TYPE_ID NUMBER, 
	VALUE VARCHAR2(500), 
	VALUE_DESC VARCHAR2(500), 
	CREATED_DT TIMESTAMP (6), 
	MODIFY_DT TIMESTAMP (6), 
	CREATED_BY NUMBER, 
	MODIFY_BY NUMBER, 
	ORG_LEVEL NUMBER 
	-- CONSTRAINT REF_TYPE_REF_VALUES_FK FOREIGN KEY (TYPE_ID)
	--  REFERENCES REFERENCE_TYPES (TYPE_ID) ENABLE
   ) ;

  CREATE TABLE REF_ENCRYPTION 
   (	SIGNATUREALGORITHM VARCHAR2(100), 
	ID NUMBER, 
	TYPE VARCHAR2(100), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

  CREATE TABLE RESOURC 
   (	RSRC_ID VARCHAR2(100), 
	RSRC_NAME VARCHAR2(100), 
	RSRC_DESC VARCHAR2(100), 
	PRSNTTN_ID NUMBER, 
	CREATED_DT TIMESTAMP (6), 
	MODIFY_DT TIMESTAMP (6), 
	CREATED_BY CHAR(100), 
	MODIFY_BY CHAR(100), 
	PROD_MENU_CATEGORY VARCHAR2(10) DEFAULT 'None', 
	RSRC_GROUPTYPE VARCHAR2(100), 
	RSRC_TYP_CD NUMBER, 
	CMPNY_CD NUMBER, 
	RESOURC_ID NUMBER, 
	PARENT_MENU_ID NUMBER, 
	CHILD_MENU_ID NUMBER
	 --CONSTRAINT RESOURC_RES_TYPE_FK FOREIGN KEY (RSRC_TYP_CD)
	 -- REFERENCES REFERENCE_VALUES (VALUE_ID) ENABLE, 
	 --CONSTRAINT RESORC_PRESEN_ID_FK FOREIGN KEY (PRSNTTN_ID)
	 -- REFERENCES PRESENTATION (PRSNTTN_ID) ENABLE
   ) ;

 
  CREATE TABLE ROLE 
   (	ROLE_ID NUMBER, 
	ROLE_NAME VARCHAR2(100), 
	ROLE_DESC VARCHAR2(300), 
	CREATED_DT TIMESTAMP (6), 
	MODIFY_DT TIMESTAMP (6), 
	CREATED_BY NUMBER, 
	MODIFY_BY VARCHAR2(50), 
	PORTAL VARCHAR2(50), 
	ISACTIVE NUMBER, 
	CREATE_FOR VARCHAR2(100), 
	ISADMIN_FLAG VARCHAR2(3)
   ) ;

  CREATE TABLE ROLE_MENU_ASSOC 
   (	ROLEID NUMBER, 
	MENU_ID NUMBER, 
	PARENT_MENU_ID NUMBER, 
	READ_FLG NUMBER, 
	WRITE_FLG NUMBER, 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MENU_PRSNT_ORD NUMBER, 
	PARENT_FLAG NUMBER, 
	PROTECTED_FLG NUMBER, 
	OVERRIDABLE_FLG NUMBER, 
	CHILD_FLAG VARCHAR2(100)
   ) ;

  CREATE TABLE RSRC_TO_RSRC_REL 
   (	RSRC_ID1 VARCHAR2(100), 
	RSRC_ID2 VARCHAR2(100), 
	CREATED_DT TIMESTAMP (6), 
	MODIFIED_DT TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_BY VARCHAR2(100), 
	IS_PERM_ASSIGNABLE CHAR(3), 
	REL_TYP_CD NUMBER, 
	RSRC_TYP_CD NUMBER, 
	RESOURC_ID NUMBER 
	-- CONSTRAINT RESOURC_ID_FK FOREIGN KEY (RESOURC_ID)
	--  REFERENCES RESOURC (RESOURC_ID) ENABLE, 
	-- CONSTRAINT RSRC_REL_RES_TYPES_FK FOREIGN KEY (RSRC_TYP_CD)
	--  REFERENCES REFERENCE_VALUES (VALUE_ID) ENABLE, 
	-- CONSTRAINT RSRC_REL_REL_TYPE_FK FOREIGN KEY (REL_TYP_CD)
	 -- REFERENCES REFERENCE_VALUES (VALUE_ID) ENABLE
   ) ;

  CREATE TABLE SERVICE_INFO 
   (	SERVICE_ID NUMBER, 
	SERVICE_NAME VARCHAR2(100), 
	SERVICE_URL VARCHAR2(100), 
	STATUS VARCHAR2(100), 
	VERSION VARCHAR2(100), 
	ISSUER_NAME VARCHAR2(100), 
	SERVICE_TYPE VARCHAR2(100), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

  CREATE TABLE TENANT 
   (	TNT_ID NUMBER, 
	TNT_NAME VARCHAR2(100), 
	IP_ADDRESS VARCHAR2(100), 
	SERVER_NAME VARCHAR2(100), 
	DB_NAME VARCHAR2(100), 
	TIM_ZN_CD NUMBER, 
	INDUSTRY_TYPE VARCHAR2(100), 
	TNT_MAIL VARCHAR2(400), 
	TNT_TELEPHONE VARCHAR2(100), 
	SSN NUMBER, 
	FIRST_NAME VARCHAR2(100), 
	LAST_NAME VARCHAR2(100), 
	TNT_ALT_MAIL VARCHAR2(400), 
	ALT_PHONE_NUMEBR VARCHAR2(100), 
	COUNTRY VARCHAR2(30), 
	STATE VARCHAR2(30), 
	CITY VARCHAR2(30), 
	ZIPCODE VARCHAR2(10), 
	SUPERVISOR VARCHAR2(100), 
	CREATED_DT TIMESTAMP (6), 
	MODIFY_DT TIMESTAMP (6), 
	CREATED_BY NUMBER, 
	MODIFY_BY NUMBER, 
	TNT_DELETED_DT VARCHAR2(100), 
	TENANT_DESC VARCHAR2(100), 
	ISACTIVE NUMBER, 
	TENANT_TYPE VARCHAR2(100), 
	PARENT_TENANT_ID NUMBER
   ) ;

  CREATE TABLE TENANT_CMPNY_REL 
   (	TNT_ID NUMBER, 
	CMPNY_CD NUMBER, 
	CREATED_DT TIMESTAMP (6), 
	CREATED_BY NUMBER, 
	MODIFIED_DT TIMESTAMP (6), 
	MODIFIED_BY NUMBER, 
	ISACTIVE NUMBER
	-- CONSTRAINT FK_TNT_ID FOREIGN KEY (TNT_ID)
	--  REFERENCES TENANT (TNT_ID) ENABLE
   ) ;

  CREATE TABLE TENANT_TO_USER 
   (	CREATED_DT TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	TNT_ID NUMBER, 
	USER_ID NUMBER, 
	TENANT_TYPE VARCHAR2(100)
   ) ;

 

  CREATE TABLE URL_NO_ACCESS 
   (	URL VARCHAR2(200 CHAR), 
	ROLE NUMBER
   ) ;

  CREATE TABLE USERS 
   (	USR_ID NUMBER(*,0), 
	USR_LOGIN_ID VARCHAR2(100), 
	TIM_ZN_CD NUMBER, 
	USR_PSSWORD VARCHAR2(100), 
	USR_NAME VARCHAR2(100), 
	USR_LAST_NAME VARCHAR2(100), 
	USR_MIDDLE_NAME VARCHAR2(100), 
	USR_LAST_ACCESS TIMESTAMP (6), 
	USR_ACCESS_STAT VARCHAR2(100), 
	USR_END_TO DATE, 
	USR_START_DT DATE, 
	USR_PREF_LANG VARCHAR2(100), 
	USR_TIMEOUT VARCHAR2(100), 
	USR_LEGAL_ACCEPT_DT VARCHAR2(100), 
	USR_DEFLT_PORTAL VARCHAR2(100), 
	USR_MAIL VARCHAR2(400), 
	USR_TELEPHONE VARCHAR2(100), 
	USR_CHALLENGE_RESPONSE VARCHAR2(100), 
	USR_DELETED_DT VARCHAR2(100), 
	CREATED_DT TIMESTAMP (6), 
	MODIFY_DT TIMESTAMP (6), 
	CREATED_BY NUMBER(*,0), 
	MODIFY_BY NUMBER, 
	FAX NUMBER, 
	PAGER VARCHAR2(100), 
	EXT VARCHAR2(100), 
	LOGIN_ATTEMPTS NUMBER(5,0), 
	MAIL_FLAG VARCHAR2(1), 
	FIRSTLOGIN_FLAG NUMBER(1,0), 
	DOMAIN_ID NUMBER, 
	SSN NUMBER, 
	EMP_ID VARCHAR2(30), 
	PERNR VARCHAR2(30), 
	CONTACT_NUMBER NUMBER, 
	ALT_PHONE_NUMEBR NUMBER, 
	MOBILE_NUMBER NUMBER, 
	CITY VARCHAR2(30), 
	SUPERVISOR NUMBER, 
	LDAP_ID NUMBER, 
	COUNTRY VARCHAR2(30), 
	STATE VARCHAR2(30), 
	INTERNAL_NOTIFICATION CHAR(3), 
	EMAIL_NOTIFICATION CHAR(3), 
	TITLE_ID NUMBER(5,0), 
	CMPNY_CD NUMBER, 
	USR_CHALLENGE NUMBER, 
	MIN_AGE NUMBER, 
	MAX_AGE NUMBER, 
	DESIGINATION_ID NUMBER, 
	BUSINESS_UNIT_ID NUMBER, 
	GEOGRAPHY_ID NUMBER, 
	ORG_LEVEL NUMBER, 
	USER_TYPE VARCHAR2(50), 
	OTP_ID NUMBER, 
	USR_LOGIN_ALLOW NUMBER DEFAULT 1, 
	TNT_ID NUMBER, 
	PARTNER_ID NUMBER, 
	ISCAPTCHA VARCHAR2(10) DEFAULT 'Y', 
	SUB_TNT_ID NUMBER, 
	REQUESTED_SYSTEM VARCHAR2(100), 
	EMPLOYEE_TYPE VARCHAR2(100), 
	AUTO_RENEWAL VARCHAR2(10)
	-- CONSTRAINT USERS_LDAP_DETAILS_FK FOREIGN KEY (DOMAIN_ID)
	 -- REFERENCES DOMAIN_DETAILS (DOMAIN_ID) ENABLE
   ) ;

  CREATE TABLE USER_ACTIVATION 
   (	USER_ID NUMBER, 
	ACTIVATION_ID VARCHAR2(200), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(255), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(255)
   ) ;

  CREATE TABLE USER_DETAILS 
   (	USR_LOGIN_ID VARCHAR2(26), 
	USR_NAME VARCHAR2(26), 
	USR_LAST_NAME VARCHAR2(128), 
	USR_MAIL VARCHAR2(128), 
	USR_TELEPHONE NUMBER(38,0), 
	TITLE_ID VARCHAR2(26), 
	TIM_ZN_CD VARCHAR2(26)
   ) ;

  CREATE TABLE USER_DEVICE_ASSOC 
   (	USR_ID NUMBER, 
	DEVICE_ID VARCHAR2(200), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(200)
   ) ;

  CREATE TABLE USER_PARTNER_ASSOC 
   (	PARTNER_ID NUMBER, 
	USER_ID NUMBER, 
	ACTIVE_FLG VARCHAR2(1), 
	START_DATE TIMESTAMP (6), 
	END_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6)
	-- CONSTRAINT USER_PARTNER_ASSOC_USER_FK FOREIGN KEY (USER_ID)
	--  REFERENCES USERS (USR_ID) ENABLE, 
	-- CONSTRAINT USER_PARTNER_ASSOC_PARTNER_FK FOREIGN KEY (PARTNER_ID)
	--  REFERENCES PARTNER (PARTNER_ID) ENABLE
   ) ;

  CREATE TABLE USER_PROFILE 
   (	USER_PROFILE_ID NUMBER, 
	USR_ID NUMBER, 
	USER_IMAGE BLOB, 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6) 
	-- CONSTRAINT USER_PROFILE_USERS_FK FOREIGN KEY (USR_ID)
	--  REFERENCES USERS (USR_ID) ENABLE
   ) ;

  CREATE TABLE USER_ROLE_ASSOC 
   (	USER_ID NUMBER, 
	ROLE_ID NUMBER, 
	CREATED_DT TIMESTAMP (6), 
	MODIFY_DT TIMESTAMP (6), 
	CREATED_BY NUMBER, 
	MODIFY_BY NUMBER, 
	ISACTIVE NUMBER
	-- CONSTRAINT USER_ROLE_USR_FK FOREIGN KEY (USER_ID)
	--  REFERENCES USERS (USR_ID) ENABLE NOVALIDATE, 
	-- CONSTRAINT USER_ROLE_ROLE_FK1 FOREIGN KEY (ROLE_ID)
	--  REFERENCES ROLE (ROLE_ID) ENABLE NOVALIDATE
   ) ;

  CREATE TABLE USER_SKILL_ASSOC 
   (	USER_SKILL_SEQ NUMBER, 
	USR_ID NUMBER, 
	SKILL_ID NUMBER, 
	SKILL_LEVEL_ID NUMBER, 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE DATE, 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE DATE
   ) ;

  CREATE TABLE USER_TO_USER_REL 
   (	USR_ID1 NUMBER, 
	CREATED_DT TIMESTAMP (6), 
	MODIFY_DT TIMESTAMP (6), 
	CREATED_BY NUMBER, 
	MODIFY_BY NUMBER, 
	USR_ID2 NUMBER, 
	REL_TYP_CD NUMBER
	-- CONSTRAINT USER_TO_USER_REL_USER_FK2 FOREIGN KEY (USR_ID1)
	--  REFERENCES USERS (USR_ID) ENABLE NOVALIDATE, 
	-- CONSTRAINT USER_REL_TYPES_FK FOREIGN KEY (REL_TYP_CD)
	--  REFERENCES REFERENCE_VALUES (VALUE_ID) ENABLE
   ) ;

  CREATE TABLE USER_TRACKER 
   (	TRACKER_ID NUMBER, 
	APPLICATION_NAME VARCHAR2(100), 
	URL VARCHAR2(100), 
	SYSTEM_IP VARCHAR2(100), 
	USER_ID NUMBER, 
	SESSION_ID NUMBER, 
	SESSION_STATUS VARCHAR2(100), 
	CREATED_BY VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	SESSION_START_TIME TIMESTAMP (6), 
	SESSION_END_TIME TIMESTAMP (6)
   ) ;

  CREATE TABLE USR_ORG_MAP 
   (	USR_ID NUMBER, 
	JURISDICTION_ID NUMBER, 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

  CREATE TABLE USR_PASSW_TRACK 
   (	USERID NUMBER, 
	PASSWORD VARCHAR2(100), 
	INSERT_DATE TIMESTAMP (6), 
	USR_PWD_HIST_ID NUMBER(7,0), 
	CREATED_BY VARCHAR2(50), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

--changeset Swetha.H:GALAXY_SHIELD_DDL_02_02 splitStatements:false
--preconditions onFail:HALT onError:HALT  
   
DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TABLES 
    WHERE  
        TABLE_NAME = 'USER_LOB_ASSOC' ;

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE USER_LOB_ASSOC 
   (	USER_ID NUMBER, 
	LINEOFBUSINESS VARCHAR2(100)
   )';
		DBMS_OUTPUT.PUT_LINE('Created');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;