--liquibase formatted sql
--changeset Swetha.H:GALAXY_SHIELD_DDL_03
--preconditions onFail:HALT onError:HALT

  ALTER TABLE PRESENTATION ADD CONSTRAINT PRESENTATION_PK PRIMARY KEY (PRSNTTN_ID)
  USING INDEX   ENABLE;

  ALTER TABLE PARTNER ADD CONSTRAINT PARTNER_PK PRIMARY KEY (PARTNER_ID)
  USING INDEX   ENABLE;

  ALTER TABLE USER_ROLE_ASSOC ADD CONSTRAINT USER_ROLE_ASSOC_COMPO_PK PRIMARY KEY (USER_ID, ROLE_ID)
  USING INDEX   ENABLE;

  ALTER TABLE REF_ENCRYPTION ADD CONSTRAINT ENCRYP_ID_PK PRIMARY KEY (ID)
  USING INDEX   ENABLE;

  ALTER TABLE USER_SKILL_ASSOC ADD CONSTRAINT USER_SKILL_SEQ_PK PRIMARY KEY (USER_SKILL_SEQ)
  USING INDEX   ENABLE;

  ALTER TABLE SERVICE_INFO ADD CONSTRAINT SERV_ID_PK PRIMARY KEY (SERVICE_ID)
  USING INDEX   ENABLE;

  ALTER TABLE ORGANIZATION_ENTITY_DETAILS ADD CONSTRAINT ORG_ENTITYDTLS_ID_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE;


  ALTER TABLE ACCESSOR ADD CONSTRAINT ACCESSOR_PK PRIMARY KEY (ACCESSOR_ID)
  USING INDEX   ENABLE;

  ALTER TABLE GROUP_TO_USER ADD CONSTRAINT GROUP_TO_USER_COMPO_PK PRIMARY KEY (GROUP_ID, USER_ID)
  USING INDEX   ENABLE;

  ALTER TABLE CMPNY_TO_CMPNY_REL ADD CONSTRAINT CMPNY_TO_CMPNY_REL_PK PRIMARY KEY (CMPNY_ID1, REL_TYP_CD, CMPNY_ID2)
  USING INDEX   ENABLE;

  ALTER TABLE GROUP_TO_ROLE ADD CONSTRAINT GROUP_TO_ROLE_COMPO_PK PRIMARY KEY (GROUP_ID, ROLE_ID)
  USING INDEX   ENABLE;

  ALTER TABLE GROUPS ADD CONSTRAINT GROUPS_PK PRIMARY KEY (GROUP_ID)
  USING INDEX   ENABLE;

  ALTER TABLE PASSWORD_HISTORY_TABLE ADD PRIMARY KEY (ID)
  USING INDEX  ENABLE;

  ALTER TABLE COMPANY ADD CONSTRAINT COMPANY_PK PRIMARY KEY (CMPNY_CD)
  USING INDEX   ENABLE;

  ALTER TABLE USER_TO_USER_REL ADD CONSTRAINT USER_TO_USER_REL_PK PRIMARY KEY (USR_ID1, USR_ID2, REL_TYP_CD)
  USING INDEX   ENABLE;

  ALTER TABLE DOMAIN_DETAILS ADD CONSTRAINT LDAP_DETAILS_PK PRIMARY KEY (DOMAIN_ID)
  USING INDEX   ENABLE;

  ALTER TABLE USERS ADD CONSTRAINT USER_PK PRIMARY KEY (USR_ID)
  USING INDEX   ENABLE;

  ALTER TABLE REFERENCE_TYPES ADD CONSTRAINT REFERENCE_TYPES_PK PRIMARY KEY (TYPE_ID)
  USING INDEX   ENABLE;

  ALTER TABLE REFERENCE_VALUES ADD CONSTRAINT REFERENCE_VALUES_PK PRIMARY KEY (VALUE_ID)
  USING INDEX   ENABLE;

  ALTER TABLE RESOURC ADD CONSTRAINT RESOURC_PK PRIMARY KEY (RESOURC_ID)
  USING INDEX   ENABLE;

  ALTER TABLE ROLE ADD CONSTRAINT ROLE_PK PRIMARY KEY (ROLE_ID)
  USING INDEX   ENABLE;

  ALTER TABLE ENTITY_ROLE_ASSOC ADD CONSTRAINT ENTITY_ROLE_ASSOC_PK PRIMARY KEY (E_R_ID)
  USING INDEX   ENABLE;

  ALTER TABLE TENANT ADD CONSTRAINT PK_COUNTER_INSTANCE_ID PRIMARY KEY (TNT_ID)
  USING INDEX   ENABLE;

  ALTER TABLE USER_PROFILE ADD CONSTRAINT USER_PROFILE_PK PRIMARY KEY (USER_PROFILE_ID)
  USING INDEX   ENABLE;

  ALTER TABLE RSRC_TO_RSRC_REL ADD CONSTRAINT RSRC_TO_RSRC_REL_PK1 PRIMARY KEY (REL_TYP_CD, RSRC_ID1, RSRC_ID2, RSRC_TYP_CD) DISABLE;
  
  
  ALTER TABLE PARTNER ADD CONSTRAINT PARTNER_REF_VALAUES_FK FOREIGN KEY (PARTNER_TYPE_ID)
	  REFERENCES REFERENCE_VALUES (VALUE_ID) ENABLE;

  ALTER TABLE USER_ROLE_ASSOC ADD CONSTRAINT USER_ROLE_USR_FK FOREIGN KEY (USER_ID)
	  REFERENCES USERS (USR_ID) ENABLE NOVALIDATE;

  ALTER TABLE USER_ROLE_ASSOC ADD CONSTRAINT USER_ROLE_ROLE_FK1 FOREIGN KEY (ROLE_ID)
	  REFERENCES ROLE (ROLE_ID) ENABLE NOVALIDATE;

  ALTER TABLE RSRC_TO_RSRC_REL ADD CONSTRAINT RESOURC_ID_FK FOREIGN KEY (RESOURC_ID)
	  REFERENCES RESOURC (RESOURC_ID) ENABLE;

  ALTER TABLE RSRC_TO_RSRC_REL ADD CONSTRAINT RSRC_REL_RES_TYPES_FK FOREIGN KEY (RSRC_TYP_CD)
	  REFERENCES REFERENCE_VALUES (VALUE_ID) ENABLE;

  ALTER TABLE RSRC_TO_RSRC_REL ADD CONSTRAINT RSRC_REL_REL_TYPE_FK FOREIGN KEY (REL_TYP_CD)
	  REFERENCES REFERENCE_VALUES (VALUE_ID) ENABLE;

  ALTER TABLE ACCESSOR ADD CONSTRAINT ACCESSOR_ROLE_ID_FK FOREIGN KEY (ROLE_ID)
	  REFERENCES ROLE (ROLE_ID) ENABLE NOVALIDATE;

  ALTER TABLE GROUP_TO_USER ADD CONSTRAINT GROUP_TO_USER_USERS_FK FOREIGN KEY (USER_ID)
	  REFERENCES USERS (USR_ID) ENABLE NOVALIDATE;

  ALTER TABLE GROUP_TO_USER ADD CONSTRAINT GROUP_TO_USER_GROUPS_FK FOREIGN KEY (GROUP_ID)
	  REFERENCES GROUPS (GROUP_ID) ENABLE NOVALIDATE;

  ALTER TABLE GROUPS ADD CONSTRAINT PARENT_GROUP_FK FOREIGN KEY (PARENT_GROUP_ID)
	  REFERENCES GROUPS (GROUP_ID) ENABLE;

  ALTER TABLE GROUP_TO_ROLE ADD CONSTRAINT FK_GROUP_TO_ROLE_GROUPID FOREIGN KEY (GROUP_ID)
	  REFERENCES GROUPS (GROUP_ID) ENABLE NOVALIDATE;

  ALTER TABLE GROUP_TO_ROLE ADD CONSTRAINT FK_GROUP_TO_ROLEID FOREIGN KEY (ROLE_ID)
	  REFERENCES ROLE (ROLE_ID) ENABLE NOVALIDATE;

  ALTER TABLE CMPNY_TO_CMPNY_REL ADD CONSTRAINT CMPNY_TO_CMPNY_REL_COMPAN_FK1 FOREIGN KEY (CMPNY_ID1)
	  REFERENCES COMPANY (CMPNY_CD) ENABLE NOVALIDATE;

  ALTER TABLE CMPNY_TO_CMPNY_REL ADD CONSTRAINT CMPNY_REL_TYPES_FK FOREIGN KEY (REL_TYP_CD)
	  REFERENCES REFERENCE_VALUES (VALUE_ID) ENABLE;

  ALTER TABLE USER_TO_USER_REL ADD CONSTRAINT USER_TO_USER_REL_USER_FK2 FOREIGN KEY (USR_ID1)
	  REFERENCES USERS (USR_ID) ENABLE NOVALIDATE;

  ALTER TABLE USER_TO_USER_REL ADD CONSTRAINT USER_REL_TYPES_FK FOREIGN KEY (REL_TYP_CD)
	  REFERENCES REFERENCE_VALUES (VALUE_ID) ENABLE;

  ALTER TABLE USERS ADD CONSTRAINT USERS_LDAP_DETAILS_FK FOREIGN KEY (DOMAIN_ID)
	  REFERENCES DOMAIN_DETAILS (DOMAIN_ID) ENABLE;

  ALTER TABLE REFERENCE_VALUES ADD CONSTRAINT REF_TYPE_REF_VALUES_FK FOREIGN KEY (TYPE_ID)
	  REFERENCES REFERENCE_TYPES (TYPE_ID) ENABLE;

  ALTER TABLE RESOURC ADD CONSTRAINT RESOURC_RES_TYPE_FK FOREIGN KEY (RSRC_TYP_CD)
	  REFERENCES REFERENCE_VALUES (VALUE_ID) ENABLE;

  ALTER TABLE RESOURC ADD CONSTRAINT RESORC_PRESEN_ID_FK FOREIGN KEY (PRSNTTN_ID)
	  REFERENCES PRESENTATION (PRSNTTN_ID) ENABLE;

  ALTER TABLE USER_PROFILE ADD CONSTRAINT USER_PROFILE_USERS_FK FOREIGN KEY (USR_ID)
	  REFERENCES USERS (USR_ID) ENABLE;

  ALTER TABLE HIST_USER ADD CONSTRAINT HIST_USER_FK FOREIGN KEY (USR_ID)
	  REFERENCES USERS (USR_ID) ENABLE;

  ALTER TABLE ACCESS_AUTH ADD CONSTRAINT ACCESS_AUTH_WRITE_FK FOREIGN KEY (WRITE)
	  REFERENCES REFERENCE_VALUES (VALUE_ID) ENABLE;

  ALTER TABLE ACCESS_AUTH ADD CONSTRAINT ACCESS_AUTH_ACCESSORID_FK FOREIGN KEY (ACCESSOR_ID)
	  REFERENCES ACCESSOR (ACCESSOR_ID) ENABLE NOVALIDATE;

  ALTER TABLE ACCESS_AUTH ADD CONSTRAINT ACCESS_AUTH_READ_FK FOREIGN KEY (READ)
	  REFERENCES REFERENCE_VALUES (VALUE_ID) ENABLE;

  ALTER TABLE TENANT_CMPNY_REL ADD CONSTRAINT FK_TNT_ID FOREIGN KEY (TNT_ID)
	  REFERENCES TENANT (TNT_ID) ENABLE;

  ALTER TABLE GROUP_PARTNER_ASSOC ADD CONSTRAINT GROUP_PARTNER_ASSOC_PARTNER_FK FOREIGN KEY (PARTNER_ID)
	  REFERENCES PARTNER (PARTNER_ID) ENABLE;

  ALTER TABLE GROUP_PARTNER_ASSOC ADD CONSTRAINT GROUP_PARTNER_ASSOC_GROUP_FK FOREIGN KEY (GROUP_ID)
	  REFERENCES GROUPS (GROUP_ID) ENABLE;

  ALTER TABLE CLIENT_SERVICE_ASSOC ADD CONSTRAINT FK_SERVIC_ID FOREIGN KEY (SERVICE_ID)
	  REFERENCES SERVICE_INFO (SERVICE_ID) ENABLE;

  ALTER TABLE CLIENT_SERVICE_ASSOC ADD CONSTRAINT FK_CLIENT_ID FOREIGN KEY (CLIENT_ID)
	  REFERENCES USERS (USR_ID) ENABLE;

  ALTER TABLE ACCESSTOKEN_INFO ADD CONSTRAINT FK_CLIENT_INFO FOREIGN KEY (CLIENT_ID)
	  REFERENCES USERS (USR_ID) ENABLE;

  ALTER TABLE ACCESSTOKEN_INFO ADD CONSTRAINT FK_SERV_ID FOREIGN KEY (SERVICE_ID)
	  REFERENCES SERVICE_INFO (SERVICE_ID) ENABLE;

  ALTER TABLE ACCESSTOKEN_INFO ADD CONSTRAINT FK_ENCRYP_ID FOREIGN KEY (ENCRYPTIONID)
	  REFERENCES REF_ENCRYPTION (ID) ENABLE;

  ALTER TABLE PARTNER_ROLE_ASSOC ADD CONSTRAINT PARTNER_ROLE_ASSOC_ROLE_FK FOREIGN KEY (ROLE_ID)
	  REFERENCES ROLE (ROLE_ID) ENABLE;

  ALTER TABLE PARTNER_ROLE_ASSOC ADD CONSTRAINT PARTNER_ROLE_ASSOC_PARTNER_FK FOREIGN KEY (PARTNER_ID)
	  REFERENCES PARTNER (PARTNER_ID) ENABLE;

  ALTER TABLE ENTITY_USER_ASSOC ADD CONSTRAINT ENTITY_USER_ASSOC_USERS_FK FOREIGN KEY (USER_ID)
	  REFERENCES USERS (USR_ID) ENABLE;

  ALTER TABLE ENTITY_USER_ASSOC ADD CONSTRAINT USER_ENTITY_FK FOREIGN KEY (ENTITY_TYPE_ID)
	  REFERENCES REFERENCE_VALUES (VALUE_ID) ENABLE;

  ALTER TABLE USER_PARTNER_ASSOC ADD CONSTRAINT USER_PARTNER_ASSOC_USER_FK FOREIGN KEY (USER_ID)
	  REFERENCES USERS (USR_ID) ENABLE;

  ALTER TABLE USER_PARTNER_ASSOC ADD CONSTRAINT USER_PARTNER_ASSOC_PARTNER_FK FOREIGN KEY (PARTNER_ID)
	  REFERENCES PARTNER (PARTNER_ID) ENABLE;
	  

--changeset Swetha.H:GALAXY_SHIELD_DDL_03_02 splitStatements:false
--preconditions onFail:HALT onError:HALT  
	  
DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONSTRAINTS 
    WHERE  
        CONSTRAINT_NAME = 'USER_LOB_FK' ;

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE USER_LOB_ASSOC ADD CONSTRAINT USER_LOB_FK FOREIGN KEY (USER_ID)
	  REFERENCES USERS (USR_ID) ENABLE';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;
