--liquibase formatted sql
--changeset Swetha.H:GALAXY_SHIELD_DDL_04
--preconditions onFail:HALT onError:HALT


  CREATE INDEX USR_PASSW_TRACK_USRID_IND ON USR_PASSW_TRACK (USERID) 
  ;

  CREATE INDEX INDX_ACCESS_AUTH_ACCID_RSRCID ON ACCESS_AUTH (ACCESSOR_ID, RSRC_ID) 
  ;

  CREATE INDEX ACCESSOR_ID_IDX ON ACCESS_AUTH (ACCESSOR_ID) 
  ;

  CREATE INDEX IDX_GROUPS_ISACTIVE ON GROUPS (ISACTIVE) 
  ;

  CREATE INDEX IDX_GRP_IS_ACTIVE ON GROUP_TO_USER (ISACTIVE) 
  ;

  CREATE INDEX INDX_REF_VAL_VALUE ON REFERENCE_VALUES (VALUE) 
  ;

  CREATE INDEX USER_ROLE_USRID_INDX ON USER_ROLE_ASSOC (USER_ID) 
  ;

  CREATE INDEX USER_ROLE_ID_USERID_INDX ON USER_ROLE_ASSOC (ROLE_ID, USER_ID) 
  ;

  CREATE INDEX ENTITY_USER_ASSOC_INDEX1 ON ENTITY_USER_ASSOC (USER_ID) 
  ;

  CREATE INDEX RESOUR_RES_GROUP_TYPE ON RESOURC (RSRC_GROUPTYPE) 
  ;


  CREATE INDEX RSRC_PRSNTTN_ID ON RESOURC (RSRC_TYP_CD, RSRC_ID, PRSNTTN_ID) 
  ;

  CREATE INDEX RESOURC_PRESENTID ON RESOURC (PRSNTTN_ID) 
  ;


  CREATE INDEX IDX_RSRC_REL_RSRC_ID1 ON RSRC_TO_RSRC_REL (RSRC_ID1) 
  ;

  CREATE INDEX IDX_RSRC_REL_RESOURC_ID ON RSRC_TO_RSRC_REL (RESOURC_ID) 
  ;

  CREATE UNIQUE INDEX RSRC_TO_RSRC_REL_PK1 ON RSRC_TO_RSRC_REL (REL_TYP_CD, RSRC_ID1, RSRC_ID2, RSRC_TYP_CD) 
  ;


  CREATE INDEX IDX_ROLE_ISACTIVE ON GROUP_TO_ROLE (ISACTIVE) 
  ;


  CREATE INDEX ROLE_NAME_IDX ON ROLE (ROLE_NAME) 
  ;

  CREATE INDEX PORTAL_IDX ON ROLE (PORTAL) 
  ;

  CREATE INDEX GALAXY_SHIELDSTATS ON GALAXY_SHIELDSTATS (STATID, TYPE, C5, C1, C2, C3, C4, VERSION) 
  ;

  CREATE INDEX USER_XRAOD_USR_LOGIN_ID_INDX ON USERS (USR_LOGIN_ID) 
  ;

  CREATE UNIQUE INDEX USERS_CUK ON USERS (DOMAIN_ID, USR_LOGIN_ID) 
  ;


  CREATE INDEX ACCESSOR_ROLE_ID_INDX ON ACCESSOR (ROLE_ID) 
  ;


  CREATE INDEX INDX_PRSNTTN_GRP_ID ON PRESENTATION (PRSNTTN_GROUP_ID) 
  ;


  CREATE INDEX IDX_PRST_GROUP_ID ON PRESENTATION (TO_NUMBER(PRSNTTN_GROUP_ID)) 
  ;

  CREATE INDEX USR_LOGIN_ID_IDX ON USERS (UPPER(USR_LOGIN_ID), USR_ID) 
  ;

  CREATE INDEX IDX_RSRC_REL_RSRC_ID ON RESOURC (UPPER(RSRC_ID)) 
  ;

  CREATE INDEX EMP_UPPER_IDX ON USERS (UPPER(TRIM(USR_LOGIN_ID))) 
  ;

  CREATE INDEX IDX_ROLE_PORTAL ON ROLE (UPPER(TRIM(PORTAL))) 
  ;