[ADD]
app.apigateway.newrepo=true
app.apigateway.newrepo1=true
app.apigateway.newrepo12=true
[UPDATE]
app.perfFlag=true
app.saveFlag=true
[REMOVE]
app.apigateway.newrepo1234=true
app.apigateway.newrepo4321=true
