--liquibase formatted sql
--changeset Vijaysree.S:CIF_DDL_02 splitStatements:true
--preconditions onFail:HALT onError:HALT


CREATE TABLE ACCESSTOKEN_INFO 
   (	TOKEN_ID NUMBER, 
	CLIENT_ID NUMBER, 
	TOKEN_TYPE VARCHAR2(100), 
	SERVICE_ID NUMBER, 
	ENCRYPTIONID NUMBER, 
	SUBJECT VARCHAR2(100), 
	EXPIRY_DATE TIMESTAMP (6), 
	ISSUED_DATE TIMESTAMP (6), 
	KEY_TYPE VARCHAR2(100), 
	KEYFILEPATH VARCHAR2(100), 
	SECRET_KEY VARCHAR2(100), 
	TOKEN VARCHAR2(500), 
	STATUS VARCHAR2(100), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

CREATE TABLE ACCOUNT_INFO 
   (	ACCOUNT_ID NUMBER, 
	ACCOUNT_NAME VARCHAR2(100), 
	USERNAME VARCHAR2(100), 
	PASSWORD VARCHAR2(100), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	CONTACT_NAME VARCHAR2(100), 
	EMAIL VARCHAR2(100), 
	PHONE_NO NUMBER, 
	AUTHENTICATION_TYPE VARCHAR2(50), 
	ENCRYPTION_TYPE VARCHAR2(50), 
	VALIDITY_PERIOD VARCHAR2(50), 
	TENANT_ID NUMBER
   ) ;

CREATE TABLE ACCOUNT_SERVICEGROUP_ASSOC 
   (	ID NUMBER, 
	ACCOUNT_ID NUMBER, 
	SERVICE_GROUP_ID NUMBER, 
	CREATED_BY VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

CREATE TABLE ACCOUNT_SERVICE_ASSOC 
   (	ID NUMBER, 
	ACCOUNT_ID NUMBER, 
	SERVICE_ID NUMBER, 
	CREATED_BY VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

CREATE TABLE ACCOUNT_USER_ASSOC 
   (	ID NUMBER, 
	ACCOUNT_ID NUMBER, 
	USER_ID NUMBER, 
	CREATED_BY VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

CREATE TABLE AUDIT_EVENT_LOG 
   (	AUDIT_EVENT_ID NUMBER, 
	ENTITY_ID NUMBER, 
	ENTITY_TYPE VARCHAR2(50), 
	SYSTEM_EVENT_DATE TIMESTAMP (6), 
	EVENT_DESC VARCHAR2(100), 
	ZONE_ID VARCHAR2(50), 
	LAST_SIGN_ON VARCHAR2(50)
   ) ;

CREATE TABLE AUDIT_RETRY_TRANSACTION 
   (	ID NUMBER DEFAULT AUDIT_RETRY_ID_SEQ.NEXTVAL, 
	TRANSACTION_ID NUMBER, 
	RELATED_TRANSACTION_ID NUMBER, 
	TRANSCTION_TYPE VARCHAR2(50), 
	SERVICE_NAME VARCHAR2(50), 
	CURRENT_REQUEST CLOB, 
	PREVIOUS_REQUEST CLOB, 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	TENANT_ID NUMBER, 
	CHANNEL VARCHAR2(50), 
	HTTP_RESPONSE VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	RESPONSE_MSG CLOB, 
	TRANSACTION_STATUS VARCHAR2(100), 
	HTTP_REQUEST VARCHAR2(50), 
	SERVICE_URL VARCHAR2(500), 
	REQ_SENT_DATE TIMESTAMP (6), 
	USER_LOGIN_ID VARCHAR2(50), 
	MODIFIED_BY VARCHAR2(100), 
	RESP_RECEIVED_DATE TIMESTAMP (6), 
	ROOT_TRANSACTION_ID NUMBER, 
	EXT_TRANSACTION_ID NUMBER, 
	BATCH_ID NUMBER
   ) ;

CREATE TABLE BASIC_AUTH_DETAILS 
   (	SERVICE_NAME VARCHAR2(100), 
	USER_NAME VARCHAR2(100), 
	PASSCODE VARCHAR2(256), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	USER_ID NUMBER, 
	TYPE VARCHAR2(20), 
	PARTNER_NAME VARCHAR2(500), 
	USER_STATUS VARCHAR2(200), 
	CLIENT_ID VARCHAR2(256), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE BATCH_DETAILS 
   (	ID NUMBER, 
	TYPE VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(50), 
	STATUS VARCHAR2(50), 
	CHANNEL VARCHAR2(50), 
	ACCOUNT_ID VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MDN_COUNT NUMBER, 
	SCHEDULED_DATE TIMESTAMP (6), 
	EXECUTION_TYPE VARCHAR2(50), 
	SYNC_BILLER VARCHAR2(5)
   ) ;

CREATE TABLE BATCH_JOB_EXECUTION 
   (	JOB_EXECUTION_ID NUMBER, 
	VERSION NUMBER, 
	JOB_INSTANCE_ID NUMBER, 
	CREATE_TIME TIMESTAMP (6), 
	START_TIME TIMESTAMP (6) DEFAULT NULL, 
	END_TIME TIMESTAMP (6) DEFAULT NULL, 
	STATUS VARCHAR2(10), 
	EXIT_CODE VARCHAR2(20), 
	EXIT_MESSAGE VARCHAR2(2500), 
	LAST_UPDATED TIMESTAMP (6), 
	JOB_CONFIGURATION_LOCATION VARCHAR2(2500)
   ) ;

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT 
   (	JOB_EXECUTION_ID NUMBER, 
	SHORT_CONTEXT VARCHAR2(2500), 
	SERIALIZED_CONTEXT CLOB
   ) ;

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS 
   (	JOB_EXECUTION_ID NUMBER, 
	TYPE_CD VARCHAR2(6), 
	KEY_NAME VARCHAR2(100), 
	STRING_VAL VARCHAR2(4000), 
	DATE_VAL TIMESTAMP (6) DEFAULT NULL, 
	LONG_VAL NUMBER, 
	DOUBLE_VAL NUMBER, 
	IDENTIFYING CHAR(1)
   ) ;

CREATE TABLE BATCH_JOB_INSTANCE 
   (	JOB_INSTANCE_ID NUMBER, 
	VERSION NUMBER, 
	JOB_NAME VARCHAR2(100), 
	JOB_KEY VARCHAR2(2500)
   ) ;

CREATE TABLE BATCH_STEP_EXECUTION 
   (	STEP_EXECUTION_ID NUMBER, 
	VERSION NUMBER, 
	STEP_NAME VARCHAR2(100), 
	JOB_EXECUTION_ID NUMBER, 
	START_TIME TIMESTAMP (6), 
	END_TIME TIMESTAMP (6) DEFAULT NULL, 
	STATUS VARCHAR2(10), 
	COMMIT_COUNT NUMBER, 
	READ_COUNT NUMBER, 
	FILTER_COUNT NUMBER, 
	WRITE_COUNT NUMBER, 
	READ_SKIP_COUNT NUMBER, 
	WRITE_SKIP_COUNT NUMBER, 
	PROCESS_SKIP_COUNT NUMBER, 
	ROLLBACK_COUNT NUMBER, 
	EXIT_CODE VARCHAR2(20), 
	EXIT_MESSAGE VARCHAR2(2500), 
	LAST_UPDATED TIMESTAMP (6)
   ) ;

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT 
   (	STEP_EXECUTION_ID NUMBER, 
	SHORT_CONTEXT VARCHAR2(2500), 
	SERIALIZED_CONTEXT CLOB
   ) ;

CREATE TABLE CONFIGURATION_MANAGEMENT 
   (	ID NUMBER(10,0), 
	ENTITY VARCHAR2(200), 
	TYPE VARCHAR2(500), 
	VALUE VARCHAR2(2000), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	DISPLAY_FLAG VARCHAR2(10) DEFAULT ('Y')
   ) ;

CREATE TABLE ERROR_DETAILS 
   (	HTTP_STATUS_CODE VARCHAR2(100), 
	MESSAGE VARCHAR2(100), 
	STATUS VARCHAR2(100), 
	ERROR_ID NUMBER DEFAULT SEQ_ERROR_ID.NEXTVAL
   ) ;

CREATE TABLE EVENT_NOTIFICATION 
   (	EVENT_ID NUMBER DEFAULT EVENT_ID_SEQ.NEXTVAL, 
	EVENT_TYPE VARCHAR2(200), 
	EVENT_NAME VARCHAR2(200), 
	EVENT_DESC VARCHAR2(200), 
	EVENT_GROUP VARCHAR2(200), 
	EVENT_STATUS VARCHAR2(200), 
	NOTIFICATION_TYPE NUMBER, 
	VALUE CLOB, 
	EVENT_SOURCE VARCHAR2(200), 
	EVENT_TIME TIMESTAMP (6), 
	EXTERNAL_ID NUMBER, 
	ACKNOWLEDGE_STATUS VARCHAR2(200), 
	ACKNOWLEDGE_ID NUMBER, 
	ACKNOWLEDGE_TIME TIMESTAMP (6), 
	ACKNOWLEDGED_BY NUMBER, 
	APPLIACTION_NAME VARCHAR2(200), 
	TRANSACTION_TYPE VARCHAR2(200), 
	EVENT_DESTINATION VARCHAR2(200), 
	SENT_DATE TIMESTAMP (6), 
	SENT_STATUS VARCHAR2(200), 
	MDN NUMBER, 
	PROMO_ID VARCHAR2(50), 
	EVENT_ORIGINATION VARCHAR2(4000)
   ) ;

CREATE TABLE EXTERNAL_SYSTEM_CODE_MAPPING 
   (	SOURCE VARCHAR2(100), 
	INTERNAL_CODE VARCHAR2(100), 
	EXTERNAL_CODE VARCHAR2(100)
   ) ;

CREATE TABLE FALLOUT_TRANSACTION_DETAILS 
   (	TRANSACTION_ID NUMBER, 
	ROOT_TRANSACTION_ID NUMBER, 
	AGENT_ID VARCHAR2(100), 
	AGENT_FIRST_NAME VARCHAR2(100), 
	AGENT_LAST_NAME VARCHAR2(100), 
	AGENT_EMAIL_ID VARCHAR2(100), 
	AGENT_ADDRESSLINE1 VARCHAR2(200), 
	AGENT_ADDRESSLINE2 VARCHAR2(200), 
	AGENT_CITY VARCHAR2(50), 
	AGENT_STATE VARCHAR2(50), 
	AGENT_ZIPCODE VARCHAR2(9), 
	CHANNEL VARCHAR2(5), 
	AGENT_PHONE_NUMBER VARCHAR2(30), 
	EXTERNAL_TRANSACTION_ID VARCHAR2(200), 
	TRANSACTION_START_DATE TIMESTAMP (6), 
	TRANSACTION_END_DATE TIMESTAMP (6), 
	TRANSATION_STATUS VARCHAR2(30), 
	SERVICE_URL VARCHAR2(500), 
	TRANS_OBJ BLOB, 
	LAST_RESUBMITTED_DATE TIMESTAMP (6), 
	RESUBMITTED_BY VARCHAR2(100), 
	RETRY_COUNT NUMBER, 
	TARGET_SYSTEM VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	QUEUE_NAME VARCHAR2(300), 
	HTTP_RESPONSE VARCHAR2(50), 
	TENANT_ID NUMBER, 
	ERROR_TRACE VARCHAR2(4000)
   ) ;

CREATE TABLE FILE_DETAILS 
   (	FILE_DETAILS_ID NUMBER DEFAULT FILE_ID.NEXTVAL, 
	FILENAME VARCHAR2(200), 
	FILE_TYPE VARCHAR2(100), 
	DOWNLOADED VARCHAR2(5), 
	PARSED VARCHAR2(5), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIIFED_BY VARCHAR2(100)
   ) ;

CREATE TABLE FTP_SERVER_INFO 
   (	FTP_HOST VARCHAR2(100), 
	FTP_PORT NUMBER, 
	USER_NAME VARCHAR2(100), 
	PASSWORD VARCHAR2(100), 
	FTP_PATH VARCHAR2(500), 
	FILE_EXTENSION VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100)
   ) ;

CREATE TABLE GROUP_INFO 
   (	SERVICE_GROUP_ID NUMBER, 
	GROUP_NAME VARCHAR2(100), 
	SERVICE_GROUP_DESCRIPTION VARCHAR2(500), 
	SERVICE_GROUP_URL VARCHAR2(500), 
	STATUS VARCHAR2(100), 
	HEALTH_STATUS VARCHAR2(100), 
	RESPONSE_TIME NUMBER(10,0), 
	LAST_RESPOND_TIME TIMESTAMP (6), 
	ISSUER_NAME VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100)
   ) ;

CREATE GLOBAL TEMPORARY TABLE HT_RH_CSR_REQUEST 
   (	TRANSACTION_ID NUMBER(10,0)
   ) ON COMMIT DELETE ROWS ;

CREATE TABLE LINE_STATUS_INFO 
   (	ID NUMBER, 
	CURRENT_STATUS VARCHAR2(50), 
	POSSIBLE_STATUS VARCHAR2(50)
   ) ;

CREATE TABLE MESSAGE_TEMPLATE 
   (	TEMPLATE_ID NUMBER DEFAULT SEQ_TEMPLATE_ID.NEXTVAL, 
	TEMPLATE_NAME VARCHAR2(100), 
	TEMPLATE_LOCATION VARCHAR2(100), 
	MESSAGE_TYPE VARCHAR2(20), 
	SUBJECT VARCHAR2(50), 
	BODY CLOB, 
	SENDER VARCHAR2(100), 
	RECEIVER VARCHAR2(100), 
	CC VARCHAR2(100), 
	BCC VARCHAR2(100), 
	MESSAGE_PRIORITY VARCHAR2(100), 
	STATUS VARCHAR2(50), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

CREATE TABLE NOTIFICATION_ALERT 
   (	ID NUMBER(10,0), 
	TYPE CHAR(1), 
	TITLE VARCHAR2(30), 
	DESCRIPTION VARCHAR2(126), 
	DETAILS VARCHAR2(2024), 
	START_DATE TIMESTAMP (6), 
	END_DATE TIMESTAMP (6), 
	USERID VARCHAR2(20), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(25), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(25)
   ) ;

CREATE TABLE NOTIFICATION_LOG 
   (	LOG_ID NUMBER DEFAULT SEQ_LOG_ID.NEXTVAL, 
	EVENT_ID NUMBER, 
	TEMPLATE_ID NUMBER, 
	NOTIFICATION_TYPE VARCHAR2(100), 
	SENDER VARCHAR2(100), 
	RECEIVER VARCHAR2(500), 
	CC VARCHAR2(100), 
	BCC VARCHAR2(100), 
	MESSAGE_PRIORITY VARCHAR2(100), 
	MESSAGE_TYPE VARCHAR2(20), 
	SUBJECT VARCHAR2(50), 
	MESSAGE_CONTENT CLOB, 
	SENT_DATE TIMESTAMP (6), 
	ACK_RECEIVED TIMESTAMP (6), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

CREATE TABLE OAUTH_ACCESS_TOKEN 
   (	TOKEN_ID VARCHAR2(256), 
	TOKEN BLOB, 
	AUTHENTICATION_ID VARCHAR2(256), 
	USER_NAME VARCHAR2(256), 
	CLIENT_ID VARCHAR2(256), 
	AUTHENTICATION BLOB, 
	REFRESH_TOKEN VARCHAR2(256)
   ) ;

CREATE TABLE OAUTH_CLIENT_DETAILS 
   (	CLIENT_ID VARCHAR2(256), 
	RESOURCE_IDS VARCHAR2(4000) DEFAULT 'century-federated-auth-server,account-service', 
	CLIENT_SECRET VARCHAR2(256), 
	SCOPE VARCHAR2(256), 
	AUTHORIZED_GRANT_TYPES VARCHAR2(256) DEFAULT 'client_credentials', 
	WEB_SERVER_REDIRECT_URI VARCHAR2(256), 
	AUTHORITIES VARCHAR2(256), 
	ACCESS_TOKEN_VALIDITY NUMBER DEFAULT 120, 
	REFRESH_TOKEN_VALIDITY NUMBER DEFAULT 180, 
	ADDITIONAL_INFORMATION VARCHAR2(4000), 
	AUTOAPPROVE VARCHAR2(256), 
	CLIENT_NAME VARCHAR2(500), 
	PARTNER_NAME VARCHAR2(500), 
	CREATED_BY VARCHAR2(200), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(200), 
	MODIFIED_DATE TIMESTAMP (6), 
	USER_STATUS VARCHAR2(200), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE OAUTH_CLIENT_TOKEN 
   (	TOKEN_ID VARCHAR2(256), 
	TOKEN BLOB, 
	AUTHENTICATION_ID VARCHAR2(256), 
	USER_NAME VARCHAR2(256), 
	CLIENT_ID VARCHAR2(256)
   ) ;

CREATE TABLE OAUTH_CODE 
   (	CODE VARCHAR2(256), 
	AUTHENTICATION BLOB
   ) ;

CREATE TABLE OAUTH_REFRESH_TOKEN 
   (	TOKEN_ID VARCHAR2(256), 
	TOKEN BLOB, 
	AUTHENTICATION BLOB
   ) ;

CREATE TABLE PROCESS_METADATA 
   (	TRANSACTION_TYPE VARCHAR2(50), 
	ROOT_TRANSACTION_ID NUMBER, 
	TRANSACTION_ID NUMBER, 
	PROCESS_DATA CLOB, 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100)
   ) ;

CREATE TABLE PROCESS_SPECIFICATION 
   (	SPECIFICATION_ID NUMBER DEFAULT SEQ_SPECIFICATION_ID.NEXTVAL, 
	SPECIFICATION_NAME VARCHAR2(300), 
	SERVICE_VERSION NUMBER, 
	SPECIFICATION_DESCRIPTION VARCHAR2(100), 
	STATUS VARCHAR2(20), 
	OFFERING_NAME VARCHAR2(200), 
	OFFERING_VERSION NUMBER, 
	PROCESS_PLAN VARCHAR2(200), 
	PROCESS_PLAN_VERSION NUMBER, 
	WORKFLOW VARCHAR2(200), 
	WORKFLOW_VERSION NUMBER, 
	INBOUND_TEMPLATE VARCHAR2(200), 
	INBOUND_TEMPLATE_VERSION NUMBER, 
	CREATED_BY VARCHAR2(20), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	MODIFIED_BY VARCHAR2(20), 
	MODIFIED_DATE TIMESTAMP (6), 
	OFFER_TYPE VARCHAR2(100)
   ) ;

CREATE TABLE PROCESS_SPECIFICATION_APALLONE 
   (	SPECIFICATION_ID NUMBER, 
	SPECIFICATION_NAME VARCHAR2(300), 
	SERVICE_VERSION NUMBER, 
	SPECIFICATION_DESCRIPTION VARCHAR2(100), 
	STATUS VARCHAR2(20), 
	OFFERING_NAME VARCHAR2(200), 
	OFFERING_VERSION NUMBER, 
	PROCESS_PLAN VARCHAR2(200), 
	PROCESS_PLAN_VERSION NUMBER, 
	WORKFLOW VARCHAR2(200), 
	WORKFLOW_VERSION NUMBER, 
	INBOUND_TEMPLATE VARCHAR2(200), 
	INBOUND_TEMPLATE_VERSION NUMBER, 
	CREATED_BY VARCHAR2(20), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(20), 
	MODIFIED_DATE TIMESTAMP (6), 
	OFFER_TYPE VARCHAR2(100)
   ) ;

CREATE TABLE PROCESS_SPECIFICATION_APP_LAT 
   (	SPECIFICATION_ID NUMBER, 
	SPECIFICATION_NAME VARCHAR2(300), 
	SERVICE_VERSION NUMBER, 
	SPECIFICATION_DESCRIPTION VARCHAR2(100), 
	STATUS VARCHAR2(20), 
	OFFERING_NAME VARCHAR2(200), 
	OFFERING_VERSION NUMBER, 
	PROCESS_PLAN VARCHAR2(200), 
	PROCESS_PLAN_VERSION NUMBER, 
	WORKFLOW VARCHAR2(200), 
	WORKFLOW_VERSION NUMBER, 
	INBOUND_TEMPLATE VARCHAR2(200), 
	INBOUND_TEMPLATE_VERSION NUMBER, 
	CREATED_BY VARCHAR2(20), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(20), 
	MODIFIED_DATE TIMESTAMP (6), 
	OFFER_TYPE VARCHAR2(100)
   ) ;

CREATE TABLE QRTZ_BLOB_TRIGGERS 
   (	SCHED_NAME VARCHAR2(120), 
	TRIGGER_NAME VARCHAR2(200), 
	TRIGGER_GROUP VARCHAR2(200), 
	BLOB_DATA BLOB
   ) ;

CREATE TABLE QRTZ_CALENDARS 
   (	SCHED_NAME VARCHAR2(120), 
	CALENDAR_NAME VARCHAR2(200), 
	CALENDAR BLOB
   ) ;

CREATE TABLE QRTZ_CRON_TRIGGERS 
   (	SCHED_NAME VARCHAR2(120), 
	TRIGGER_NAME VARCHAR2(200), 
	TRIGGER_GROUP VARCHAR2(200), 
	CRON_EXPRESSION VARCHAR2(120), 
	TIME_ZONE_ID VARCHAR2(80)
   ) ;

CREATE TABLE QRTZ_FIRED_TRIGGERS 
   (	SCHED_NAME VARCHAR2(120), 
	ENTRY_ID VARCHAR2(95), 
	TRIGGER_NAME VARCHAR2(200), 
	TRIGGER_GROUP VARCHAR2(200), 
	INSTANCE_NAME VARCHAR2(200), 
	FIRED_TIME NUMBER(13,0), 
	SCHED_TIME NUMBER(13,0), 
	PRIORITY NUMBER(13,0), 
	STATE VARCHAR2(16), 
	JOB_NAME VARCHAR2(200), 
	JOB_GROUP VARCHAR2(200), 
	IS_NONCONCURRENT VARCHAR2(1), 
	REQUESTS_RECOVERY VARCHAR2(1)
   ) ;

CREATE TABLE QRTZ_JOB_DETAILS 
   (	SCHED_NAME VARCHAR2(120), 
	JOB_NAME VARCHAR2(200), 
	JOB_GROUP VARCHAR2(200), 
	DESCRIPTION VARCHAR2(250), 
	JOB_CLASS_NAME VARCHAR2(250), 
	IS_DURABLE VARCHAR2(1), 
	IS_NONCONCURRENT VARCHAR2(1), 
	IS_UPDATE_DATA VARCHAR2(1), 
	REQUESTS_RECOVERY VARCHAR2(1), 
	JOB_DATA BLOB
   ) ;

CREATE TABLE QRTZ_LOCKS 
   (	SCHED_NAME VARCHAR2(120), 
	LOCK_NAME VARCHAR2(40)
   ) ;

CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS 
   (	SCHED_NAME VARCHAR2(120), 
	TRIGGER_GROUP VARCHAR2(200)
   ) ;

CREATE TABLE QRTZ_SCHEDULER_STATE 
   (	SCHED_NAME VARCHAR2(120), 
	INSTANCE_NAME VARCHAR2(200), 
	LAST_CHECKIN_TIME NUMBER(13,0), 
	CHECKIN_INTERVAL NUMBER(13,0)
   ) ;

CREATE TABLE QRTZ_SIMPLE_TRIGGERS 
   (	SCHED_NAME VARCHAR2(120), 
	TRIGGER_NAME VARCHAR2(200), 
	TRIGGER_GROUP VARCHAR2(200), 
	REPEAT_COUNT NUMBER(7,0), 
	REPEAT_INTERVAL NUMBER(12,0), 
	TIMES_TRIGGERED NUMBER(10,0)
   ) ;

CREATE TABLE QRTZ_SIMPROP_TRIGGERS 
   (	SCHED_NAME VARCHAR2(120), 
	TRIGGER_NAME VARCHAR2(200), 
	TRIGGER_GROUP VARCHAR2(200), 
	STR_PROP_1 VARCHAR2(512), 
	STR_PROP_2 VARCHAR2(512), 
	STR_PROP_3 VARCHAR2(512), 
	INT_PROP_1 NUMBER(10,0), 
	INT_PROP_2 NUMBER(10,0), 
	LONG_PROP_1 NUMBER(13,0), 
	LONG_PROP_2 NUMBER(13,0), 
	DEC_PROP_1 NUMBER(13,4), 
	DEC_PROP_2 NUMBER(13,4), 
	BOOL_PROP_1 VARCHAR2(1), 
	BOOL_PROP_2 VARCHAR2(1)
   ) ;

CREATE TABLE QRTZ_TRIGGERS 
   (	SCHED_NAME VARCHAR2(120), 
	TRIGGER_NAME VARCHAR2(200), 
	TRIGGER_GROUP VARCHAR2(200), 
	JOB_NAME VARCHAR2(200), 
	JOB_GROUP VARCHAR2(200), 
	DESCRIPTION VARCHAR2(250), 
	NEXT_FIRE_TIME NUMBER(13,0), 
	PREV_FIRE_TIME NUMBER(13,0), 
	PRIORITY NUMBER(13,0), 
	TRIGGER_STATE VARCHAR2(16), 
	TRIGGER_TYPE VARCHAR2(8), 
	START_TIME NUMBER(13,0), 
	END_TIME NUMBER(13,0), 
	CALENDAR_NAME VARCHAR2(200), 
	MISFIRE_INSTR NUMBER(2,0), 
	JOB_DATA BLOB
   ) ;

CREATE TABLE REF_ADDITIONAL_DATA 
   (	TRANSACTIONID NUMBER, 
	REFNAME VARCHAR2(100), 
	REFVALUE VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100)
   ) ;

CREATE TABLE REF_ENCRYPTION 
   (	SIGNATUREALGORITHM VARCHAR2(100), 
	ID NUMBER, 
	TYPE VARCHAR2(100), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

CREATE TABLE REF_ENV_CONTEXT 
   (	ENV_NAME VARCHAR2(10), 
	ENV_DESCRIPTION VARCHAR2(100), 
	FILTER_PRIORITY NUMBER, 
	STATUS VARCHAR2(10), 
	IS_CURRENT_ENV VARCHAR2(10), 
	DNS VARCHAR2(300)
   ) ;

CREATE TABLE REF_ENV_CONTEXT_CONFIG 
   (	ENV_NAME VARCHAR2(20), 
	ENV_DESCRIPTION VARCHAR2(100), 
	FILTER_PRIORITY NUMBER, 
	STATUS VARCHAR2(20), 
	IS_CURRENT_ENV VARCHAR2(5)
   ) ;

CREATE TABLE REF_ERROR_RULES 
   (	ERROR_RULE_ID NUMBER DEFAULT SEQ_ERROR_RULE_ID.NEXTVAL, 
	ERROR_CODE VARCHAR2(20), 
	ERROR_MESSAGE VARCHAR2(200), 
	HTTP_STATUS_CODE NUMBER, 
	ACTION_TO_EXECUTE VARCHAR2(20), 
	RETRY_LIMIT NUMBER, 
	RULE_DETAILS VARCHAR2(200), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	DESCRIPTION VARCHAR2(200), 
	EXT_ERROR_CODE VARCHAR2(20), 
	EXT_ERROR_MESSAGE VARCHAR2(200), 
	TARGET_SYSTEM VARCHAR2(100), 
	SERVICE_ID NUMBER, 
	RETRY_INTERVAL NUMBER, 
	RETRY_WITHNEWTXNID VARCHAR2(20), 
	RETRY_RULE VARCHAR2(500)
   ) ;

CREATE TABLE REF_EVENT 
   (	REF_TYPE_ID NUMBER, 
	REF_TYPE_VALUE VARCHAR2(200)
   ) ;

CREATE TABLE REF_FIELD_INFO 
   (	ID NUMBER, 
	TYPE VARCHAR2(50), 
	FIELD_NAME VARCHAR2(50), 
	FIELD_TYPE VARCHAR2(600), 
	VALUE VARCHAR2(2000), 
	REQUIRED VARCHAR2(50), 
	EDIT_FLAG VARCHAR2(50), 
	DEFAULT_VALUE VARCHAR2(500), 
	PARENT_ID NUMBER DEFAULT (0)
   ) ;

CREATE TABLE REF_NB_SERVICE_CONFIG 
   (	CONTEXT_ID VARCHAR2(200), 
	OAUTH_URL VARCHAR2(200), 
	LOGIN_ID VARCHAR2(200), 
	CLIENT_SECRET VARCHAR2(200), 
	STATUS VARCHAR2(200), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(200), 
	MODIFIED_BY VARCHAR2(200), 
	MODIFIED_DATE TIMESTAMP (6), 
	INTERFACE_NAME VARCHAR2(100), 
	SERVICE_NAME VARCHAR2(100)
   ) ;

CREATE TABLE REF_NB_UNSOL_CONFIG 
   (	ENV VARCHAR2(200), 
	NB_UNSOL_URL VARCHAR2(200), 
	STATUS VARCHAR2(200), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(200), 
	MODIFIED_BY VARCHAR2(200), 
	MODIFIED_DATE TIMESTAMP (6), 
	CONTEXT_ID VARCHAR2(20), 
	SERVICE_NAME VARCHAR2(50), 
	INTERFACE_NAME VARCHAR2(50)
   ) ;

CREATE TABLE REF_ONSP_CODES 
   (	ONSPCD VARCHAR2(50), 
	CARRIERCAT VARCHAR2(100), 
	CARRIERTRANSTYPE VARCHAR2(100), 
	CARRIERLONGDESC VARCHAR2(200), 
	CARRIERSHORTDESC VARCHAR2(100), 
	CREATED_DATE DATE, 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE DATE, 
	MODIFIED_BY VARCHAR2(100)
   ) ;

CREATE TABLE REF_PROXY_CONFIG 
   (	INTERFACE_NAME VARCHAR2(100), 
	FILTER_VARIABLE_NAME VARCHAR2(20), 
	FILTER_VARIABLE_JSON_PATH VARCHAR2(100), 
	EXECUTE_ACTION VARCHAR2(50), 
	EXCHANGE_PATTERN VARCHAR2(20)
   ) ;

CREATE TABLE REF_RATE_PLAN_DATA_TIER 
   (	DATA_TIER_ID NUMBER, 
	RETAIL_PLAN VARCHAR2(50), 
	DPFO_CODE VARCHAR2(50), 
	RETAIL_PLAN_DESC VARCHAR2(200), 
	DATA_LIMIT VARCHAR2(50), 
	DATA_LIMIT_TYPE VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(20), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(20)
   ) ;

CREATE TABLE REF_SERVER_METRICS 
   (	METRIC_NAME VARCHAR2(50), 
	INSTANCE_TYPE VARCHAR2(50), 
	UNIT VARCHAR2(50), 
	URL VARCHAR2(50)
   ) ;

CREATE TABLE REF_TEMPLATE 
   (	ID NUMBER, 
	NAME VARCHAR2(50), 
	TYPE VARCHAR2(50), 
	SEQUENCE NUMBER, 
	PARENT NUMBER
   ) ;

CREATE TABLE REF_TENANT 
   (	TENANT_ID NUMBER, 
	TENANT_NAME VARCHAR2(50), 
	CREATED_BY VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

CREATE TABLE REF_THROTTLE_DETAILS 
   (	RETAILPLANCODE VARCHAR2(100), 
	WHOLESALEPLANCODE VARCHAR2(100), 
	DEVICETYPE VARCHAR2(100), 
	THROTTLE_LIMIT_LTE VARCHAR2(100), 
	THROTTLE_LIMIT_MHS VARCHAR2(100), 
	WHOLESALEFEATURECODE VARCHAR2(100)
   ) ;

CREATE TABLE REPORT_TEMPLATE 
   (	REPORT_ID NUMBER, 
	REPORT_NAME VARCHAR2(200), 
	QUERY CLOB, 
	TEMPLATE_DETAILS CLOB, 
	STATUS VARCHAR2(5), 
	CREATED_DATE DATE, 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE DATE, 
	MODIFIED_BY VARCHAR2(100), 
	SERVICE_ID NUMBER, 
	REPORT_TYPE VARCHAR2(100), 
	REPORT_FILE_NAME VARCHAR2(300), 
	CSV_DELIMITER VARCHAR2(5), 
	VALIDATE_TEMPLATE VARCHAR2(100), 
	FILE_RETRIEVE_ID NUMBER
   ) ;



CREATE TABLE RH_BATCH_SCHEDULER_TRANSACTION 
   (	ID NUMBER, 
	BATCH_ID VARCHAR2(100), 
	MDN NUMBER, 
	EXC_TIMESTAMP TIMESTAMP (6), 
	SCHEDULED_STATUS VARCHAR2(100), 
	SERVICE_TYPE VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	SYNC CHAR(1), 
	BATCH_ITEM_ID NUMBER, 
	BATCH_STATUS VARCHAR2(100)
   ) ;

CREATE TABLE RH_BATCH_TRANSACTION 
   (	ID NUMBER, 
	EXT_BATCH_ID VARCHAR2(100), 
	BATCH_ID NUMBER DEFAULT BATCH_ID_SEQ.NEXTVAL, 
	MDN NUMBER, 
	TRANSACTION_ID NUMBER, 
	EXC_TIMESTAMP TIMESTAMP (6), 
	BATCH_TYPE VARCHAR2(100), 
	STATUS VARCHAR2(100), 
	REFERENCE_NUMBER VARCHAR2(100), 
	SYNC CHAR(1), 
	CHANNEL_ID VARCHAR2(100), 
	SERVICE_TYPE VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	BATCH_UPDATE_STATUS VARCHAR2(100), 
	BATCH_ITEM_ID NUMBER, 
	BATCH_STATUS VARCHAR2(100), 
	DEVICE_TYPE VARCHAR2(10), 
	DEVICE_ID NUMBER(20,0), 
	NEXT_BCD VARCHAR2(5), 
	REQUEST_MSG CLOB, 
	RESPONSE_MSG CLOB, 
	EXTERNAL_VALUE_1 VARCHAR2(500), 
	EXTERNAL_VALUE_2 VARCHAR2(500), 
	EXTERNAL_VALUE_3 VARCHAR2(500)
   ) ;

CREATE TABLE RH_PRICE_PLAN_CODES 
   (	PRICE_PLAN VARCHAR2(100), 
	FEATURE_CODE VARCHAR2(100), 
	FEATURE_ACT VARCHAR2(100), 
	SERVICE_CODE VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MOFIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100)
   ) ;

CREATE TABLE RH_REF_CBRS_DEVICES 
   (	BRAND VARCHAR2(100), 
	MODEL_NUMBER VARCHAR2(100), 
	MODEL_NAME VARCHAR2(100), 
	TAC VARCHAR2(100), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

CREATE TABLE RH_REF_TAC_DEVICE_DATA 
   (	BRAND VARCHAR2(50), 
	MODEL_NAME VARCHAR2(50), 
	MODEL_NUMBER VARCHAR2(50), 
	SERIAL_NUMBER VARCHAR2(50), 
	MEID NUMBER, 
	IMEI NUMBER, 
	EID NUMBER, 
	IMEI2 NUMBER, 
	CREATED_BY VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

CREATE TABLE RH_SCHEDULER_PROCESS 
   (	SCHEDULER_ID NUMBER, 
	SCHEDULER_PROCESS_NAME VARCHAR2(200), 
	SCHEDULER_TIME VARCHAR2(50), 
	PROCESS_TYPE VARCHAR2(100), 
	END_POINT_URL VARCHAR2(500), 
	TYPE VARCHAR2(10), 
	SYSTEM VARCHAR2(10), 
	REQUEST CLOB, 
	REQUEST_TYPE VARCHAR2(10), 
	AUTH_TYPE VARCHAR2(10), 
	IS_ACTIVE CHAR(1), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50)
   ) ;

CREATE TABLE RULE_ENTITY 
   (	RULE_ENTITY_ID NUMBER DEFAULT SEQ_RULE_ENTITY_ID.NEXTVAL, 
	RULE_ENTITY_NAME VARCHAR2(300), 
	DESCRIPTION VARCHAR2(500), 
	CREATED_BY VARCHAR2(20), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	MODIFIED_BY VARCHAR2(20), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

CREATE TABLE RULE_ENTITY_GROUP 
   (	RULE_ENTITY_GROUP_ID NUMBER DEFAULT SEQ_RULE_ENTITY_GROUP_ID.NEXTVAL, 
	SPECIFICATION_ID NUMBER, 
	START_DATE TIMESTAMP (6), 
	END_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(20), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	MODIFIED_BY VARCHAR2(20), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

CREATE TABLE RULE_ENTITY_GROUP_APALLONE 
   (	RULE_ENTITY_GROUP_ID NUMBER, 
	SPECIFICATION_ID NUMBER, 
	START_DATE TIMESTAMP (6), 
	END_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(20), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(20), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

CREATE TABLE RULE_ENTITY_GROUP_APP_LAT 
   (	RULE_ENTITY_GROUP_ID NUMBER, 
	SPECIFICATION_ID NUMBER, 
	START_DATE TIMESTAMP (6), 
	END_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(20), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(20), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

CREATE TABLE RULE_ENTITY_GROUP_ASSOC 
   (	RULE_ENTITY_GRP_ASSOC_ID NUMBER DEFAULT SEQ_RULE_ENTITY_GRP_ASSOC_ID.NEXTVAL, 
	RULE_ENTITY_GROUP_ID NUMBER, 
	RULE_ENTITY_ID NUMBER, 
	RULE_ENTITY_VALUE VARCHAR2(300), 
	CREATED_BY VARCHAR2(20), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	MODIFIED_BY VARCHAR2(20), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;



CREATE TABLE RULE_ENTITY_GRP_ASSOC_APALLONE 
   (	RULE_ENTITY_GRP_ASSOC_ID NUMBER, 
	RULE_ENTITY_GROUP_ID NUMBER, 
	RULE_ENTITY_ID NUMBER, 
	RULE_ENTITY_VALUE VARCHAR2(300), 
	CREATED_BY VARCHAR2(20), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(20), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

CREATE TABLE SERVER_NODE_INFO 
   (	NODE_ID NUMBER, 
	NODE_NAME VARCHAR2(50), 
	NODE_IP VARCHAR2(50), 
	INSTANCE_TYPE VARCHAR2(50), 
	INSTANC_ID VARCHAR2(50)
   ) ;

CREATE TABLE SERVICE_GROUP_INFO 
   (	ID NUMBER, 
	NAME VARCHAR2(200), 
	DESCRIPTION VARCHAR2(200), 
	SERVICE_GROUP_URL VARCHAR2(500), 
	STATUS VARCHAR2(100), 
	HEALTH_STATUS VARCHAR2(100), 
	RESPONSE_TIME NUMBER(10,0), 
	LAST_RESPOND_TIME TIMESTAMP (6), 
	ISSUER_NAME VARCHAR2(100), 
	CREATED_BY VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	TENANT_ID NUMBER, 
	PARENT_GROUP_ID NUMBER
   ) ;

CREATE TABLE SERVICE_INFO 
   (	SERVICE_ID NUMBER, 
	SERVICE_NAME VARCHAR2(100), 
	SERVICE_URL VARCHAR2(500), 
	STATUS VARCHAR2(100), 
	VERSION VARCHAR2(100), 
	ISSUER_NAME VARCHAR2(100), 
	SERVICE_TYPE VARCHAR2(100), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	SERVICE_PORT NUMBER(10,0), 
	SERVICE_REQUEST CLOB, 
	TYPE VARCHAR2(100), 
	ACTION VARCHAR2(20), 
	RETRYLIMIT VARCHAR2(100), 
	TIMEDELAY NUMBER, 
	SERVER VARCHAR2(100), 
	HEALTH_STATUS VARCHAR2(100), 
	RESPONSE_TIME TIMESTAMP (6), 
	LAST_RESPOND_TIME TIMESTAMP (6), 
	SERVICE_GROUP VARCHAR2(100), 
	SERVICE_DESCRIPTION VARCHAR2(100), 
	SERVICE_GROUP_ID NUMBER, 
	METHOD VARCHAR2(50), 
	TENANT_ID NUMBER, 
	GRAPH_META_JSON BLOB, 
	PROCESSPLAN VARCHAR2(100), 
	REQUEST_PARAM_TYPE VARCHAR2(100), 
	AUTH_TYPE VARCHAR2(100), 
	END_POINT_URL VARCHAR2(300), 
	END_POINT_URL2 VARCHAR2(300), 
	EXCHANGE_PATTERN VARCHAR2(50), 
	SERVICE_CATEGORY VARCHAR2(50), 
	REQUEST_CONTENT_TYPE VARCHAR2(100), 
	RESPONSE_CONTENT_TYPE VARCHAR2(100), 
	PRIORITY_GROUP VARCHAR2(100), 
	PRIORITY NUMBER, 
	USER_NAME VARCHAR2(1000), 
	PASSWORD VARCHAR2(1000), 
	ISSUER_ENVIRONMENT VARCHAR2(1000), 
	AUTH_SERVICE_ID NUMBER, 
	CONNECTION_STATUS VARCHAR2(1000), 
	APPLICATION_VER VARCHAR2(100), 
	STUB_URL VARCHAR2(500), 
	QUEUE_NAME VARCHAR2(200), 
	ERROR_DLQ_NAME VARCHAR2(200), 
	ISSUER_ENV_CONTEXT VARCHAR2(50), 
	TARGET_SYSTEM VARCHAR2(10), 
	AUTH_SERVICE_NAME VARCHAR2(200), 
	SOURCE_URL VARCHAR2(200), 
	DESTINATION_URL VARCHAR2(200)
   ) ;


CREATE TABLE SERVICE_RULE_ENITITY_ASSOC 
   (	SEV_RUL_ENT_ASSOC_ID NUMBER DEFAULT SEQ_SEV_RUL_ENT_ASSOC_ID.NEXTVAL, 
	SERVICE_ID NUMBER, 
	SERVICE_NAME VARCHAR2(300), 
	RULE_ENTITY_ID NUMBER, 
	RULE_ENTITY_JSON_PATH VARCHAR2(1000), 
	CREATED_BY VARCHAR2(20), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	MODIFIED_BY VARCHAR2(20), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

CREATE TABLE TBL_PROCESS_ENTITY 
   (	ID NUMBER, 
	NAME VARCHAR2(200), 
	TYPE_ID NUMBER, 
	PARENT_ID NUMBER, 
	SERVICENAME VARCHAR2(200), 
	URL VARCHAR2(500), 
	IMAGENAME VARCHAR2(500), 
	IMAGEPATH VARCHAR2(500), 
	CREATED_BY VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	SEQUENCE NUMBER
   ) ;

CREATE TABLE TBL_REF_PROCESS_ENTITY 
   (	ID NUMBER, 
	NAME VARCHAR2(100), 
	CREATED_BY VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

CREATE TABLE TRANSACTION_CORRECTION_ASSOC 
   (	RELATED_CORRECTION_ID NUMBER, 
	CORRECTION_STATUS VARCHAR2(100), 
	CORRECTION_TYPE VARCHAR2(100), 
	TRANSACTION_PARENT_ID NUMBER
   ) ;

CREATE TABLE TRANSACTION_DETAILS 
   (	TRANSACTION_ID NUMBER, 
	REL_TRANSACTION_ID NUMBER, 
	APPLICATION_NAME VARCHAR2(50), 
	TRANSACTION_TYPE VARCHAR2(50), 
	STATUS VARCHAR2(30), 
	REQ_SENT_DATE TIMESTAMP (6), 
	RESP_RECEIVED_DATE TIMESTAMP (6), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	EXTERNAL_ID1 VARCHAR2(100), 
	NOTIFI_ENTITY_ID NUMBER, 
	NOTIFI_REL_ENTITY_ID NUMBER, 
	NOTIFI_ENTITY_TYPE VARCHAR2(50), 
	NOTIFI_RETRY_COUNTS NUMBER, 
	NOTIFI_ENTITY_STATUS VARCHAR2(50), 
	RESPONSE_MSG CLOB, 
	REQUEST_MSG CLOB, 
	ENTITY_ID VARCHAR2(100), 
	ICC_VAL VARCHAR2(100), 
	TRANSACTION_UID VARCHAR2(300), 
	GROUP_ID VARCHAR2(255), 
	TRANS_GROUP_ID NUMBER, 
	SERVICENAME VARCHAR2(100), 
	TRANSACTION_NAME VARCHAR2(100), 
	HTTP_REQUEST VARCHAR2(50), 
	HTTP_RESPONSE VARCHAR2(50), 
	NOTES VARCHAR2(255), 
	SOURCE_SYSTEM VARCHAR2(200), 
	ORDERTIMESTAMP TIMESTAMP (6), 
	TENANT_ID NUMBER, 
	TRANSACTION_STATUS VARCHAR2(100), 
	ROOT_TRANSACTION_ID NUMBER, 
	TARGET_SYSTEM VARCHAR2(100), 
	EXT_TRANSACTION_ID VARCHAR2(255), 
	CHANNEL VARCHAR2(200), 
	AGENT_ID VARCHAR2(200), 
	USER_LOGIN_ID VARCHAR2(50), 
	USER_LOGIN_REF VARCHAR2(50), 
	WORKFLOW_NAME VARCHAR2(200), 
	BATCH_ID NUMBER, 
	OBJECT_DETAILS_URL VARCHAR2(150), 
	EXTERNAL_ID2 VARCHAR2(100), 
	APPLICATION_VER VARCHAR2(100), 
	PROCESS_INSTANCE_ID NUMBER, 
	OUTBOUND_URL VARCHAR2(500), 
	CORRECTION_TRANSACTION_ID NUMBER, 
	RETURN_URL VARCHAR2(500), 
	ASYNC_ERROR_URL VARCHAR2(500), 
	CORRECTION_STATUS VARCHAR2(100), 
	CORRECTION_TRANSACTION VARCHAR2(3)
   ) ;

CREATE TABLE TRANSACTION_FAILURE_DETAILS 
   (	TRANSACTION_ID NUMBER DEFAULT SEQ_TRANSACTION_ID.NEXTVAL, 
	REL_TRANSACTION_ID NUMBER, 
	APPLICATION_NAME VARCHAR2(50), 
	TRANSACTION_TYPE VARCHAR2(50), 
	STATUS VARCHAR2(30), 
	REQ_SENT_DATE TIMESTAMP (6), 
	RESP_RECEIVED_DATE TIMESTAMP (6), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	EXTERNAL_ID1 VARCHAR2(30), 
	NOTIFI_ENTITY_ID NUMBER, 
	NOTIFI_REL_ENTITY_ID NUMBER, 
	NOTIFI_ENTITY_TYPE VARCHAR2(50), 
	NOTIFI_RETRY_COUNTS NUMBER, 
	NOTIFI_ENTITY_STATUS VARCHAR2(30), 
	RESPONSE_MSG CLOB, 
	REQUEST_MSG CLOB, 
	ENTITY_ID VARCHAR2(100), 
	ICC_VAL VARCHAR2(100), 
	TRANSACTION_UID VARCHAR2(300), 
	GROUP_ID VARCHAR2(255), 
	TRANS_GROUP_ID NUMBER, 
	SERVICENAME VARCHAR2(100), 
	TRANSACTION_NAME VARCHAR2(100), 
	HTTP_REQUEST VARCHAR2(50), 
	HTTP_RESPONSE VARCHAR2(50), 
	NOTES VARCHAR2(255), 
	SOURCE_SYSTEM VARCHAR2(100), 
	ORDERTIMESTAMP TIMESTAMP (6), 
	TENANT_ID NUMBER, 
	TRANSACTION_STATUS VARCHAR2(100), 
	ROOT_TRANSACTION_ID NUMBER, 
	TARGET_SYSTEM VARCHAR2(100), 
	EXT_TRANSACTION_ID VARCHAR2(255), 
	CHANNEL VARCHAR2(200), 
	AGENT_ID VARCHAR2(200), 
	USER_LOGIN_ID VARCHAR2(50), 
	USER_LOGIN_REF VARCHAR2(50), 
	REASON_CODE VARCHAR2(300), 
	REASON_DESCRIPTION VARCHAR2(300)
   ) ;

CREATE TABLE TRANSACTION_FILE_LOG 
   (	TRANSACTION_ID NUMBER, 
	FILE_NAME VARCHAR2(100), 
	FILE_EXTENSION VARCHAR2(10), 
	FILE_TYPE VARCHAR2(30), 
	FILE_CONTENT BLOB, 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	ENTITY_ID NUMBER, 
	ENTITY_TYPE_ID NUMBER, 
	REASON VARCHAR2(1000), 
	STATUS VARCHAR2(50), 
	TOTAL_RECORDS NUMBER, 
	TOTAL_RECORDS_PROCESSED NUMBER, 
	TOTAL_RECORDS_FAILED NUMBER, 
	START_DATE TIMESTAMP (6), 
	END_DATE TIMESTAMP (6), 
	RESPONSE_MSG CLOB, 
	TRANSACTION_NAME VARCHAR2(500)
   ) ;

CREATE TABLE TRANSACTION_LOG 
   (	TRANSACTION_ID NUMBER, 
	FILE_NAME VARCHAR2(100), 
	FILE_GEN_DATE DATE, 
	STATUS VARCHAR2(100), 
	FILE_TYPE VARCHAR2(100), 
	FILE_PROCESS_TIME TIMESTAMP (6), 
	DATA_FILE CLOB, 
	EXTERNAL_SYSTEM VARCHAR2(30), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_DATE TIMESTAMP (6), 
	TRANSACTION_NAME VARCHAR2(500)
   ) ;

CREATE TABLE TRANSACTION_METADATA 
   (	TRANSACTION_METADATA_ID NUMBER DEFAULT SEQ_TXN_MD_ID.NEXTVAL, 
	TRANSACTION_ID NUMBER, 
	ROOT_TRANSACTION_ID NUMBER, 
	EXTERNAL_TRANSACTION_ID VARCHAR2(500), 
	SERVICE_URL VARCHAR2(500), 
	RETURN_URL VARCHAR2(500), 
	RETURN_ERROR_URL VARCHAR2(500), 
	SUBORDERID VARCHAR2(500), 
	EXTERNAL_VALUE_1 VARCHAR2(500), 
	EXTERNAL_VALUE_2 VARCHAR2(500), 
	EXTERNAL_VALUE_3 VARCHAR2(500), 
	CREATED_BY VARCHAR2(20), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	MODIFIED_BY VARCHAR2(20), 
	MODIFIED_DATE TIMESTAMP (6), 
	TRANSACTION_MILESTONE VARCHAR2(300), 
	ALT_ZIPCODE VARCHAR2(20), 
	EXTERNAL_VALUE_4 VARCHAR2(100), 
	EXTERNAL_VALUE_5 VARCHAR2(100)
   ) ;

CREATE TABLE TRANSACTION_SMB_DETAILS 
   (	TRANSACTION_ID NUMBER DEFAULT SEQ_TRANSACTION_SMB_ID.NEXTVAL, 
	ROOT_TRANSACTION_ID NUMBER, 
	EXT_TRANSACTION_ID VARCHAR2(300), 
	TRANSACTION_UID VARCHAR2(300), 
	TRANSACTION_TYPE VARCHAR2(10), 
	TRANSACTION_NAME VARCHAR2(300), 
	TRANSACTION_STATUS VARCHAR2(100), 
	SOURCE_SYSTEM VARCHAR2(100), 
	TARGET_SYSTEM VARCHAR2(100), 
	APPLICATION_NAME VARCHAR2(100), 
	SERVICENAME VARCHAR2(100), 
	SERVICEURL VARCHAR2(500), 
	RETURNURL VARCHAR2(500), 
	ASYNCERRORURL VARCHAR2(500), 
	HTTP_REQUEST VARCHAR2(500), 
	HTTP_RESPONSE VARCHAR2(500), 
	REQUEST_MSG CLOB, 
	RESPONSE_MSG CLOB, 
	REQ_SENT_DATE TIMESTAMP (6), 
	RESP_RECEIVED_DATE TIMESTAMP (6), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(20), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(20), 
	CHANNEL VARCHAR2(200), 
	AGENT_ID VARCHAR2(200), 
	USER_LOGIN_ID VARCHAR2(50), 
	USER_LOGIN_REF VARCHAR2(50), 
	NOTES VARCHAR2(500), 
	EXTERNAL_ID1 VARCHAR2(100), 
	NOTIFI_ENTITY_ID NUMBER, 
	NOTIFI_REL_ENTITY_ID NUMBER, 
	NOTIFI_ENTITY_TYPE VARCHAR2(50), 
	NOTIFI_RETRY_COUNTS NUMBER, 
	NOTIFI_ENTITY_STATUS VARCHAR2(30), 
	ENTITY_ID VARCHAR2(50), 
	GROUP_ID VARCHAR2(255), 
	TRANS_GROUP_ID NUMBER, 
	ORDERTIMESTAMP TIMESTAMP (6), 
	TENANT_ID NUMBER, 
	STATUS VARCHAR2(50), 
	ICC_VAL VARCHAR2(255), 
	REL_TRANSACTION_ID VARCHAR2(255)
   ) ;

CREATE TABLE TRANS_FAILURE_LOG 
   (	TRANSACTION_ID NUMBER, 
	ENTITY_ID NUMBER, 
	ENTITY_TYPE_ID NUMBER, 
	STATUS VARCHAR2(50), 
	ERROR_CODE VARCHAR2(100), 
	ERROR_MSG VARCHAR2(500), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	REJECT_CODE VARCHAR2(100), 
	REJECT_MESSAGE VARCHAR2(500), 
	ENTITY_VALUE VARCHAR2(250), 
	ROOT_TRANSACTION_ID NUMBER, 
	ERROR_DETAILS CLOB, 
	TARGET_SYSTEM VARCHAR2(100), 
	TRANS_FAILURE_LOG_ID VARCHAR2(100), 
	ERROR_TYPE VARCHAR2(50)
   ) ;

CREATE TABLE USER_INFO 
   (	ID NUMBER, 
	USER_NAME VARCHAR2(200), 
	FIRST_NAME VARCHAR2(200), 
	LAST_NAME VARCHAR2(200), 
	EMAIL VARCHAR2(200), 
	MOBILE NUMBER, 
	CREATED_BY VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	PASSWORD VARCHAR2(500), 
	TENANT_ID NUMBER, 
	AUTHENTICATION_TYPE VARCHAR2(200), 
	ENCRYPTION_TYPE VARCHAR2(200), 
	VALIDITY_PERIOD VARCHAR2(200), 
	ACCOUNT_ID NUMBER
   ) ;

CREATE TABLE LINE (
L_ID                             NUMBER        NOT NULL,
ACCT_ID                          NUMBER      ,
ACCOUNT_NUMBER                   VARCHAR2(50),
E_LINE_ID                        VARCHAR2(50),
MDN                              NUMBER      ,
LINE_STATUS                      VARCHAR2(50),
LTE_STATUS                       VARCHAR2(50),
LINE_NAME                        VARCHAR2(50),
ACTIVATION_DATE                  TIMESTAMP(6),
HOST_MDN                         NUMBER      ,
DEACTIVATION_DATE                TIMESTAMP(6),
MIN                              NUMBER      ,
BCD                              NUMBER      ,
HOTLINE_TYPE                     VARCHAR2(50),
ISPORTED                         VARCHAR2(50),
LINETYPE                         VARCHAR2(50),
SERVICE_TYPE                     VARCHAR2(50),
REFERENCENUMBER                  VARCHAR2(200),
INFLIGHT_TRANS_STATUS            VARCHAR2(50),
SPEED_REDUCED_FLAG               VARCHAR2(20),
IS_GF_PLAN                       VARCHAR2(5) ,
CREATED_DATE                     TIMESTAMP(6),
CREATED_BY                       VARCHAR2(20),
MODIFIED_DATE                    TIMESTAMP(6),
MODIFIED_BY                      VARCHAR2(20),
IS_MIGRATED                      VARCHAR2(5) ,
MIG_STATUS                       VARCHAR2(50),
SYNC_TRANSACTION                 VARCHAR2(5) ,
RCS_ELIGIBILE_STATUS             VARCHAR2(20),
RCS_ACCT_STATUS                  VARCHAR2(20),
ROAMING_EVENT                    VARCHAR2(50),
CBRS_FLAG                        VARCHAR2(5) ,
CBRS_LAST_UPDATED_DATE           TIMESTAMP(6),
RELATED_L_ID                     NUMBER      ,
RELATED_ELINE_ID                 VARCHAR2(50),
MHS_SPEED_REDUCED_FLAG           VARCHAR2(10),
PLAN_MIGRATION_ELIGIBLE          VARCHAR2(5) ,
WIFI_SPEED_POLICY                VARCHAR2(20),
LINESTATUSDATE                   TIMESTAMP(6),
LINECHANGEDDATE                  TIMESTAMP(6)  
);

--changeset Vijaysree.S:CIF_DDL_02_01 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TAB_COLUMNS
    WHERE  
        TABLE_NAME = 'TRANSACTION_DETAILS'
        AND COLUMN_NAME IN ( 'RECONCILIATION_STATUS','PROCESS_METADATA_ID','RECONCILIATION_COUNT');

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE transaction_details ADD (
    reconciliation_status VARCHAR2(100),
    process_metadata_id   NUMBER,
    reconciliation_count  NUMBER
)';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:CIF_DDL_02_02 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TAB_COLUMNS
    WHERE  
        TABLE_NAME = 'SERVICE_INFO'
        AND COLUMN_NAME IN ( 'TOKEN_USERNAME','TOKEN_PASSWORD');

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE SERVICE_INFO ADD (
    TOKEN_USERNAME VARCHAR2(1000),
    TOKEN_PASSWORD   VARCHAR2(1000))';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;
