--liquibase formatted sql
--changeset Vijaysree.S:CIF_DDL_03 splitStatements:true
--preconditions onFail:HALT onError:HALT


CREATE INDEX IDX_CREATED_DATE ON TRANSACTION_DETAILS (TRUNC(CREATED_DATE)) 
  ;

CREATE INDEX IDX_ASA_ACC_ID ON ACCOUNT_SERVICE_ASSOC (ACCOUNT_ID) 
  ;

CREATE INDEX IDX_QRTZ_J_REQ_RECOVERY ON QRTZ_JOB_DETAILS (SCHED_NAME, REQUESTS_RECOVERY) 
  ;

CREATE INDEX IND_ACCTKN_TOKEN ON ACCESSTOKEN_INFO (TOKEN) 
  ;

CREATE INDEX IND_REF_ADD_DATA_TXN_ID ON REF_ADDITIONAL_DATA (TRANSACTIONID) 
  ;

CREATE INDEX IDX_QRTZ_J_GRP ON QRTZ_JOB_DETAILS (SCHED_NAME, JOB_GROUP) 
  ;

CREATE INDEX IND_RH_BAT_SCH_TX_MDN ON RH_BATCH_SCHEDULER_TRANSACTION (BATCH_STATUS, MDN) 
  ;

CREATE INDEX IND_RH_BAT_BATCH_ID ON RH_BATCH_SCHEDULER_TRANSACTION (BATCH_ID) 
  ;

CREATE INDEX IDX_PROC_META_TRANS_ID ON PROCESS_METADATA (TRANSACTION_ID) 
  ;

CREATE INDEX IDX_META_ROOT_ID ON PROCESS_METADATA (ROOT_TRANSACTION_ID) 
  ;

CREATE UNIQUE INDEX TRANSACTION_FAILURE_DETAILS_PK ON TRANSACTION_FAILURE_DETAILS (TRANSACTION_ID) 
  ;

CREATE INDEX IDX_TRANS_FILE_LOG_TRANS_ID ON TRANSACTION_FILE_LOG (TRANSACTION_ID) 
  ;

CREATE INDEX INDX_TRANS_FE_LOG_RT_TXN_ID ON TRANS_FAILURE_LOG (ROOT_TRANSACTION_ID) 
  ;

CREATE INDEX IDX_TRANS_FAILURE_LOG_TRANS_ID ON TRANS_FAILURE_LOG (TRANSACTION_ID) 
  ;

CREATE INDEX IND_C_TX_RELTXID_TT_TN ON TRANSACTION_DETAILS (REL_TRANSACTION_ID, TRANSACTION_TYPE, TRANSACTION_NAME) 
  ;

CREATE INDEX IDX_REL_TRANS_ID ON TRANSACTION_DETAILS (REL_TRANSACTION_ID) 
  ;

CREATE INDEX IDX_APPLN_NAME ON TRANSACTION_DETAILS (APPLICATION_NAME) 
  ;

CREATE INDEX IND_EXT_TRANS_ID ON TRANSACTION_DETAILS (EXT_TRANSACTION_ID) 
  ;

CREATE INDEX IDX_ASGA_ACC_ID ON ACCOUNT_SERVICEGROUP_ASSOC (ACCOUNT_ID) 
  ;

CREATE INDEX IND_REF_ADD_DATA_CR_DATE ON REF_ADDITIONAL_DATA (CREATED_DATE) 
  ;

CREATE INDEX IND_MEID_REF_TAC ON RH_REF_TAC_DEVICE_DATA (MEID) 
  ;

CREATE INDEX IDX_ROOT_TRANS_ID ON TRANSACTION_DETAILS (ROOT_TRANSACTION_ID) 
  ;

CREATE INDEX IDX_REQ_SENT_DATE ON TRANSACTION_DETAILS (REQ_SENT_DATE) 
  ;

CREATE INDEX IND_TXN_DET_CR_DATE ON TRANSACTION_DETAILS (CREATED_DATE) 
  ;

CREATE INDEX ENTITY_TRANSACTION_IDX ON TRANS_FAILURE_LOG (ENTITY_ID, TRANSACTION_ID) 
  ;

CREATE INDEX IDX_EXTNL_ID1 ON TRANSACTION_DETAILS (EXTERNAL_ID1) 
  ;

CREATE INDEX IDX_TRANSACTION_UID ON TRANSACTION_DETAILS (TRANSACTION_UID) 
  ;

CREATE INDEX TRANS_FAIL_LOG_INX ON TRANS_FAILURE_LOG (TRANSACTION_ID, ENTITY_ID) 
  ;

CREATE INDEX IND_F_TXN_DET_REQ_SENT_DT ON TRANSACTION_DETAILS (TRUNC(REQ_SENT_DATE)) 
  ;

CREATE INDEX IDX_FALL_TRANS_STATUS ON FALLOUT_TRANSACTION_DETAILS (TRANSATION_STATUS) 
  ;

CREATE INDEX IDX_FALL_TRANS_START_DATE ON FALLOUT_TRANSACTION_DETAILS (TRANSACTION_START_DATE) 
  ;

CREATE INDEX IDX_FALL_EXT_TRANS_ID ON FALLOUT_TRANSACTION_DETAILS (EXTERNAL_TRANSACTION_ID) 
  ;

CREATE INDEX IDX_FALL_TRANS_END_DATE ON FALLOUT_TRANSACTION_DETAILS (TRANSACTION_END_DATE) 
  ;

CREATE INDEX IDX_SERV_GROUP_ID ON SERVICE_INFO (SERVICE_GROUP_ID) 
  ;

CREATE INDEX IND_C_SERVICE_ST_SN_M ON SERVICE_INFO (SERVICE_TYPE, SERVICE_NAME, TYPE) 
  ;

CREATE INDEX IND_REF_THROTTLE_DET ON REF_THROTTLE_DETAILS (WHOLESALEFEATURECODE) 
  ;

CREATE INDEX IDX_AUA_ACC_ID ON ACCOUNT_USER_ASSOC (ACCOUNT_ID) 
  ;

CREATE INDEX IDX_FALL_ROOT_TRANS_ID ON FALLOUT_TRANSACTION_DETAILS (ROOT_TRANSACTION_ID) 
  ;

CREATE INDEX IDX_QRTZ_T_J ON QRTZ_TRIGGERS (SCHED_NAME, JOB_NAME, JOB_GROUP) 
  ;

CREATE INDEX IDX_QRTZ_T_JG ON QRTZ_TRIGGERS (SCHED_NAME, JOB_GROUP) 
  ;

CREATE INDEX IDX_QRTZ_T_NEXT_FIRE_TIME ON QRTZ_TRIGGERS (SCHED_NAME, NEXT_FIRE_TIME) 
  ;

CREATE INDEX IDX_QRTZ_T_C ON QRTZ_TRIGGERS (SCHED_NAME, CALENDAR_NAME) 
  ;

CREATE INDEX IDX_QRTZ_T_N_G_STATE ON QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_GROUP, TRIGGER_STATE) 
  ;

CREATE INDEX IDX_QRTZ_T_NFT_MISFIRE ON QRTZ_TRIGGERS (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME) 
  ;

CREATE INDEX IDX_QRTZ_T_NFT_ST ON QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_STATE, NEXT_FIRE_TIME) 
  ;

CREATE INDEX IDX_QRTZ_T_G ON QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_GROUP) 
  ;

CREATE UNIQUE INDEX QRTZ_TRIGGERS_PK ON QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) 
  ;

CREATE INDEX IDX_QRTZ_T_STATE ON QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_STATE) 
  ;

CREATE INDEX IDX_QRTZ_T_NFT_ST_MISFIRE_GRP ON QRTZ_TRIGGERS (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_GROUP, TRIGGER_STATE) 
  ;

CREATE INDEX IDX_QRTZ_T_NFT_ST_MISFIRE ON QRTZ_TRIGGERS (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_STATE) 
  ;

CREATE INDEX IDX_QRTZ_T_N_STATE ON QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP, TRIGGER_STATE) 
  ;

CREATE INDEX IDX_TRNS_PROC_INST_ID ON TRANSACTION_DETAILS (PROCESS_INSTANCE_ID) 
  ;

CREATE INDEX IDX_QRTZ_FT_INST_JOB_REQ_RCVRY ON QRTZ_FIRED_TRIGGERS (SCHED_NAME, INSTANCE_NAME, REQUESTS_RECOVERY) 
  ;

CREATE INDEX IDX_QRTZ_FT_JG ON QRTZ_FIRED_TRIGGERS (SCHED_NAME, JOB_GROUP) 
  ;

CREATE INDEX IDX_QRTZ_FT_J_G ON QRTZ_FIRED_TRIGGERS (SCHED_NAME, JOB_NAME, JOB_GROUP) 
  ;

CREATE INDEX IDX_QRTZ_FT_TG ON QRTZ_FIRED_TRIGGERS (SCHED_NAME, TRIGGER_GROUP) 
  ;

CREATE INDEX IDX_QRTZ_FT_TRIG_INST_NAME ON QRTZ_FIRED_TRIGGERS (SCHED_NAME, INSTANCE_NAME) 
  ;

CREATE INDEX IDX_QRTZ_FT_T_G ON QRTZ_FIRED_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) 
  ;

CREATE INDEX IND_BASIC_AUTH_USRNAME ON BASIC_AUTH_DETAILS (USER_NAME, PASSCODE) 
  ;

