--liquibase formatted sql
--changeset Vijaysree.S:CIF_DDL_04 splitStatements:true
--preconditions onFail:HALT onError:HALT

ALTER TABLE ACCOUNT_SERVICE_ASSOC ADD CONSTRAINT ACCSERV_ID_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE;

ALTER TABLE USER_INFO ADD CONSTRAINT USERINFO_ID_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE;

ALTER TABLE QRTZ_SIMPLE_TRIGGERS ADD CONSTRAINT QRTZ_SIMPLE_TRIG_PK PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
  USING INDEX  ENABLE;

ALTER TABLE REPORT_TEMPLATE ADD CONSTRAINT REPORT_ID_PK PRIMARY KEY (REPORT_ID)
  USING INDEX  ENABLE;

ALTER TABLE QRTZ_JOB_DETAILS ADD CONSTRAINT QRTZ_JOB_DETAILS_PK PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
  USING INDEX  ENABLE;

ALTER TABLE TRANSACTION_LOG ADD CONSTRAINT TRANS_ID_PK PRIMARY KEY (TRANSACTION_ID)
  USING INDEX  ENABLE;

ALTER TABLE AUDIT_EVENT_LOG ADD CONSTRAINT AUDIT_EVENT_PK PRIMARY KEY (AUDIT_EVENT_ID)
  USING INDEX  ENABLE;

ALTER TABLE SERVICE_GROUP_INFO ADD CONSTRAINT SERVGROUP_ID_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE;


ALTER TABLE ACCOUNT_INFO ADD CONSTRAINT CLIENT_INFO_PK PRIMARY KEY (ACCOUNT_ID)
  USING INDEX  ENABLE;

ALTER TABLE QRTZ_CALENDARS ADD CONSTRAINT QRTZ_CALENDARS_PK PRIMARY KEY (SCHED_NAME, CALENDAR_NAME)
  USING INDEX  ENABLE;

ALTER TABLE OAUTH_ACCESS_TOKEN ADD CONSTRAINT OAUTH_ACCESS_AUTH_ID_PK PRIMARY KEY (AUTHENTICATION_ID)
  USING INDEX  ENABLE;

ALTER TABLE QRTZ_PAUSED_TRIGGER_GRPS ADD CONSTRAINT QRTZ_PAUSED_TRIG_GRPS_PK PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP)
  USING INDEX  ENABLE;

ALTER TABLE QRTZ_FIRED_TRIGGERS ADD CONSTRAINT QRTZ_FIRED_TRIGGER_PK PRIMARY KEY (SCHED_NAME, ENTRY_ID)
  USING INDEX  ENABLE;

ALTER TABLE TBL_REF_PROCESS_ENTITY ADD CONSTRAINT REF_PRCENT_ID_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE;

ALTER TABLE QRTZ_CRON_TRIGGERS ADD CONSTRAINT QRTZ_CRON_TRIG_PK PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
  USING INDEX  ENABLE;

ALTER TABLE BATCH_JOB_EXECUTION_CONTEXT ADD PRIMARY KEY (JOB_EXECUTION_ID)
  USING INDEX  ENABLE;

ALTER TABLE BATCH_JOB_INSTANCE ADD PRIMARY KEY (JOB_INSTANCE_ID)
  USING INDEX  ENABLE;

ALTER TABLE CONFIGURATION_MANAGEMENT ADD CONSTRAINT CONFIG_MGMT_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE;

ALTER TABLE REF_ENCRYPTION ADD CONSTRAINT ENCRYP_ID_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE;

ALTER TABLE RH_SCHEDULER_PROCESS ADD CONSTRAINT SCHEDULER_ID_PK PRIMARY KEY (SCHEDULER_ID)
  USING INDEX  ENABLE;

ALTER TABLE TRANSACTION_DETAILS ADD CONSTRAINT TRANSACTION_DETAILS_PK PRIMARY KEY (TRANSACTION_ID)
  USING INDEX  ENABLE;

ALTER TABLE ACCOUNT_SERVICEGROUP_ASSOC ADD CONSTRAINT ACCSERV_ASSOC_ID_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE;

ALTER TABLE QRTZ_SIMPROP_TRIGGERS ADD CONSTRAINT QRTZ_SIMPROP_TRIG_PK PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
  USING INDEX  ENABLE;

ALTER TABLE BATCH_JOB_EXECUTION ADD PRIMARY KEY (JOB_EXECUTION_ID)
  USING INDEX  ENABLE;

ALTER TABLE NOTIFICATION_ALERT ADD CONSTRAINT NOTIF_ALERT_ID_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE;

ALTER TABLE ACCOUNT_USER_ASSOC ADD CONSTRAINT ACCUSER_ASSOC_ID_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE;

ALTER TABLE FALLOUT_TRANSACTION_DETAILS ADD CONSTRAINT FALLOUT_TRANSACTION_PK PRIMARY KEY (TRANSACTION_ID)
  USING INDEX  ENABLE;

ALTER TABLE SERVICE_INFO ADD CONSTRAINT SERV_ID_PK PRIMARY KEY (SERVICE_ID)
  USING INDEX  ENABLE;

ALTER TABLE QRTZ_SCHEDULER_STATE ADD CONSTRAINT QRTZ_SCHEDULER_STATE_PK PRIMARY KEY (SCHED_NAME, INSTANCE_NAME)
  USING INDEX  ENABLE;

ALTER TABLE REF_EVENT ADD CONSTRAINT REF_TYPE_ID_PK PRIMARY KEY (REF_TYPE_ID)
  USING INDEX  ENABLE;

ALTER TABLE QRTZ_LOCKS ADD CONSTRAINT QRTZ_LOCKS_PK PRIMARY KEY (SCHED_NAME, LOCK_NAME)
  USING INDEX  ENABLE;

ALTER TABLE BATCH_STEP_EXECUTION ADD PRIMARY KEY (STEP_EXECUTION_ID)
  USING INDEX  ENABLE;

ALTER TABLE BATCH_STEP_EXECUTION_CONTEXT ADD PRIMARY KEY (STEP_EXECUTION_ID)
  USING INDEX  ENABLE;

ALTER TABLE QRTZ_TRIGGERS ADD CONSTRAINT QRTZ_TRIGGERS_PK PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
  USING INDEX IDX_QRTZ_T_N_STATE  ENABLE;

ALTER TABLE OAUTH_CLIENT_DETAILS ADD CONSTRAINT OAUTH_CLIENT_ID_PK PRIMARY KEY (CLIENT_ID)
  USING INDEX  ENABLE;

ALTER TABLE QRTZ_BLOB_TRIGGERS ADD CONSTRAINT QRTZ_BLOB_TRIG_PK PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
  USING INDEX  ENABLE;

ALTER TABLE TBL_PROCESS_ENTITY ADD CONSTRAINT PRCENT_ID_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE;

ALTER TABLE REF_ONSP_CODES ADD CONSTRAINT ONSPCD_PK PRIMARY KEY (ONSPCD)
  USING INDEX  ENABLE;

ALTER TABLE BASIC_AUTH_DETAILS ADD CONSTRAINT CLIENTID_TYPE_PK PRIMARY KEY (CLIENT_ID, TYPE)
  USING INDEX  ENABLE;

ALTER TABLE OAUTH_CLIENT_TOKEN ADD CONSTRAINT OAUTH_CLIENT_AUTH_ID_PK PRIMARY KEY (AUTHENTICATION_ID)
  USING INDEX  ENABLE;

ALTER TABLE ACCESSTOKEN_INFO ADD CONSTRAINT FK_CLIENT_INFO FOREIGN KEY (CLIENT_ID)
	  REFERENCES ACCOUNT_INFO (ACCOUNT_ID) ENABLE NOVALIDATE;

ALTER TABLE ACCESSTOKEN_INFO ADD CONSTRAINT FK_ENCRYP_ID FOREIGN KEY (ENCRYPTIONID)
	  REFERENCES REF_ENCRYPTION (ID) ENABLE NOVALIDATE;

ALTER TABLE ACCOUNT_SERVICE_ASSOC ADD CONSTRAINT FK_ACCSERV_ACCID FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES ACCOUNT_INFO (ACCOUNT_ID) ENABLE NOVALIDATE;

ALTER TABLE REPORT_TEMPLATE ADD CONSTRAINT FK_SERVICE_ID FOREIGN KEY (SERVICE_ID)
	  REFERENCES SERVICE_INFO (SERVICE_ID) ENABLE NOVALIDATE;

ALTER TABLE QRTZ_SIMPLE_TRIGGERS ADD CONSTRAINT QRTZ_SIMPLE_TRIG_TO_TRIG_FK FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
	  REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ENABLE NOVALIDATE;

ALTER TABLE BATCH_JOB_EXECUTION_CONTEXT ADD CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID)
	  REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID) ENABLE;

ALTER TABLE QRTZ_CRON_TRIGGERS ADD CONSTRAINT QRTZ_CRON_TRIG_TO_TRIG_FK FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
	  REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ENABLE NOVALIDATE;

ALTER TABLE TRANSACTION_DETAILS ADD CONSTRAINT TRANSACTION_DETAILS_FK FOREIGN KEY (REL_TRANSACTION_ID)
	  REFERENCES TRANSACTION_DETAILS (TRANSACTION_ID) ON DELETE CASCADE ENABLE NOVALIDATE;

ALTER TABLE BATCH_JOB_EXECUTION ADD CONSTRAINT JOB_INSTANCE_EXECUTION_FK FOREIGN KEY (JOB_INSTANCE_ID)
	  REFERENCES BATCH_JOB_INSTANCE (JOB_INSTANCE_ID) ENABLE;

ALTER TABLE ACCOUNT_SERVICEGROUP_ASSOC ADD CONSTRAINT FK_ACCSERV_ASSOC_SGID FOREIGN KEY (SERVICE_GROUP_ID)
	  REFERENCES SERVICE_GROUP_INFO (ID) ENABLE NOVALIDATE;

ALTER TABLE ACCOUNT_SERVICEGROUP_ASSOC ADD CONSTRAINT FK_ACCSERV_ASSOC_ACCID FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES ACCOUNT_INFO (ACCOUNT_ID) ENABLE NOVALIDATE;

ALTER TABLE SERVICE_INFO ADD CONSTRAINT FK_SERVINFO_SGID FOREIGN KEY (SERVICE_GROUP_ID)
	  REFERENCES SERVICE_GROUP_INFO (ID) ENABLE NOVALIDATE;

ALTER TABLE QRTZ_SIMPROP_TRIGGERS ADD CONSTRAINT QRTZ_SIMPROP_TRIG_TO_TRIG_FK FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
	  REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ENABLE NOVALIDATE;

ALTER TABLE ACCOUNT_USER_ASSOC ADD CONSTRAINT FK_ACCUSER_ASSOC_USERID FOREIGN KEY (USER_ID)
	  REFERENCES USER_INFO (ID) ENABLE NOVALIDATE;

ALTER TABLE ACCOUNT_USER_ASSOC ADD CONSTRAINT FK_ACCUSER_ASSOC_ACCID FOREIGN KEY (ACCOUNT_ID)
	  REFERENCES ACCOUNT_INFO (ACCOUNT_ID) ENABLE NOVALIDATE;

ALTER TABLE BATCH_STEP_EXECUTION_CONTEXT ADD CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID)
	  REFERENCES BATCH_STEP_EXECUTION (STEP_EXECUTION_ID) ENABLE;

ALTER TABLE QRTZ_TRIGGERS ADD CONSTRAINT QRTZ_TRIGGER_TO_JOBS_FK FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
	  REFERENCES QRTZ_JOB_DETAILS (SCHED_NAME, JOB_NAME, JOB_GROUP) ENABLE NOVALIDATE;

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS ADD CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID)
	  REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID) ENABLE;

ALTER TABLE BATCH_STEP_EXECUTION ADD CONSTRAINT JOB_EXECUTION_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID)
	  REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID) ENABLE;

ALTER TABLE QRTZ_BLOB_TRIGGERS ADD CONSTRAINT QRTZ_BLOB_TRIG_TO_TRIG_FK FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
	  REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ENABLE NOVALIDATE;

ALTER TABLE TBL_PROCESS_ENTITY ADD CONSTRAINT FK_TYPE_ID FOREIGN KEY (TYPE_ID)
	  REFERENCES TBL_REF_PROCESS_ENTITY (ID) ENABLE NOVALIDATE;
