--liquibase formatted sql
--changeset Swetha.H:CRDM_DDL_02 splitStatements:true
--preconditions onFail:HALT onError:HALT


  CREATE TABLE COUNTRY 
   (	NAME VARCHAR2(30), 
	ABBREVIATION VARCHAR2(50), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	COUNTRY_ID NUMBER, 
	COUNTRY_AR VARCHAR2(50)
   ) ;
   
   

  CREATE TABLE STATE 
   (	NAME VARCHAR2(100), 
	ABBREVIATIONS VARCHAR2(5), 
	COUNTRY_NAME VARCHAR2(30), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	STATE_ID NUMBER
   ) ;
   

  CREATE TABLE CITY 
   (	NAME VARCHAR2(100), 
	STATE_NAME VARCHAR2(100), 
	ABBREVIATION VARCHAR2(100), 
	STATE_ABBREVIATIONS VARCHAR2(5), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	CITY_ID NUMBER
   ) ;
   
   

  CREATE TABLE COUNTY 
   (	COUNTY_NAME VARCHAR2(50), 
	STATE_NAME VARCHAR2(100), 
	CITY_NAME VARCHAR2(100), 
	ZIP_CODE VARCHAR2(30), 
	COUNTY_ABBREVIATION VARCHAR2(50), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;
   

  CREATE TABLE ZIPCODE 
   (	ZIPCODE VARCHAR2(30), 
	CITY_NAME VARCHAR2(100), 
	STATE_NAME VARCHAR2(100), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

  CREATE TABLE ZIPCODE_SYSPRIN 
   (	LOCAL_BILLER_NAME VARCHAR2(50), 
	DIVISION VARCHAR2(50), 
	REGION VARCHAR2(50), 
	MARKET VARCHAR2(50), 
	ZIPCODE VARCHAR2(30), 
	CITY VARCHAR2(100), 
	STATE VARCHAR2(100), 
	COUNTRY VARCHAR2(30), 
	STATUS VARCHAR2(10), 
	CORP_SYSPRIN_ID VARCHAR2(30), 
	CORP_SYSPRIN_NAME VARCHAR2(50), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;
   
   

  CREATE TABLE REFERENCE_TYPES 
   (	REF_TYPE_ID NUMBER, 
	REF_TYPE_NAME VARCHAR2(200), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;
   

  CREATE TABLE REFERENCE_TYPE_VALUES 
   (	REF_VAL_ID NUMBER, 
	REF_TYPE_ID NUMBER, 
	HIERARCHY_ID NUMBER, 
	REF_VALUE VARCHAR2(500), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	STATUS VARCHAR2(20), 
	SEQUENCE NUMBER, 
	REF_VAL_DESC VARCHAR2(1000), 
	SYS_DEFN_FLAG VARCHAR2(5)
   ) ;

  CREATE TABLE REGION 
   (	NAME VARCHAR2(50), 
	DIVISION_NAME VARCHAR2(50), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	REGION_ID NUMBER
   ) ;
   

  CREATE TABLE MARKET 
   (	NAME VARCHAR2(50), 
	REGION_NAME VARCHAR2(50), 
	DIVISION_NAME VARCHAR2(50), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	MARKET_ID NUMBER
   ) ;
   
   
  CREATE TABLE DIVISION 
   (	NAME VARCHAR2(50), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	DIVISION_ID NUMBER
   ) ;