--liquibase formatted sql
--changeset Swetha.H:CRDM_DDL_03 splitStatements:true
--preconditions onFail:HALT onError:HALT


ALTER TABLE COUNTRY ADD CONSTRAINT COUNTRY_PK PRIMARY KEY (NAME);
  
ALTER TABLE STATE ADD CONSTRAINT STATE_PK PRIMARY KEY (NAME);

ALTER TABLE CITY ADD CONSTRAINT CITY_PK PRIMARY KEY (NAME, STATE_NAME);
  
ALTER TABLE ZIPCODE ADD CONSTRAINT ZIPCODE_PK PRIMARY KEY (ZIPCODE, CITY_NAME, STATE_NAME);
  
ALTER TABLE REFERENCE_TYPES ADD CONSTRAINT REF_TYPE_ID_PK PRIMARY KEY (REF_TYPE_ID);
  
ALTER TABLE REFERENCE_TYPE_VALUES ADD CONSTRAINT REF_TYPE_VALUE_ID_PK PRIMARY KEY (REF_VAL_ID);

ALTER TABLE COUNTY ADD CONSTRAINT COUNTY_PK PRIMARY KEY (COUNTY_NAME, STATE_NAME, CITY_NAME, ZIP_CODE);

ALTER TABLE REGION ADD CONSTRAINT REGION_PK PRIMARY KEY (NAME);

ALTER TABLE MARKET ADD CONSTRAINT MARKET_PK PRIMARY KEY (NAME);

ALTER TABLE DIVISION ADD CONSTRAINT DIVISION_PK PRIMARY KEY (DIVISION_ID);
 
ALTER TABLE REFERENCE_TYPE_VALUES ADD CONSTRAINT REF_HIERARCHY_TYPE_FK FOREIGN KEY (HIERARCHY_ID)
	  REFERENCES REFERENCE_TYPE_VALUES (REF_VAL_ID) ENABLE;

ALTER TABLE REFERENCE_TYPE_VALUES ADD CONSTRAINT REF_TYPE_ID_FK FOREIGN KEY (REF_TYPE_ID)
	  REFERENCES REFERENCE_TYPES (REF_TYPE_ID) ENABLE;
	  
ALTER TABLE ZIPCODE_SYSPRIN ADD CONSTRAINT ZIPCODE_SYSPRIN_ZIPCODE_FK FOREIGN KEY (ZIPCODE, CITY, STATE)
	  REFERENCES ZIPCODE (ZIPCODE, CITY_NAME, STATE_NAME) ENABLE;

ALTER TABLE ZIPCODE_SYSPRIN ADD CONSTRAINT ZIPCODE_SYSPRIN_COUNTRY_FK FOREIGN KEY (COUNTRY)
	  REFERENCES COUNTRY (NAME) ENABLE;

ALTER TABLE COUNTY ADD CONSTRAINT COUNTY_ZIPCODE_FK FOREIGN KEY (ZIP_CODE, CITY_NAME, STATE_NAME)
	  REFERENCES ZIPCODE (ZIPCODE, CITY_NAME, STATE_NAME) ENABLE;
	  
ALTER TABLE ZIPCODE ADD CONSTRAINT ZIPCODE_CITY_FK FOREIGN KEY (CITY_NAME, STATE_NAME)
	  REFERENCES CITY (NAME, STATE_NAME) ENABLE;
	  
ALTER TABLE CITY ADD CONSTRAINT CITY_STATE_FK FOREIGN KEY (STATE_NAME)
	  REFERENCES STATE (NAME) ENABLE;

ALTER TABLE STATE ADD CONSTRAINT STATE_COUNTRY_FK FOREIGN KEY (COUNTRY_NAME)
	  REFERENCES COUNTRY (NAME) ENABLE;
	  
ALTER TABLE ZIPCODE_SYSPRIN ADD CONSTRAINT ZIPCODE_SYSPRIN_REGION_FK FOREIGN KEY (REGION)
	  REFERENCES REGION (NAME) ENABLE;

ALTER TABLE ZIPCODE_SYSPRIN ADD CONSTRAINT ZIPCODE_SYSPRIN_MARKET_FK FOREIGN KEY (MARKET)
	  REFERENCES MARKET (NAME) ENABLE;
  
