--liquibase formatted sql
--changeset Swetha.H:CRF_DDL_02 
--preconditions onFail:HALT onError:HALT


  CREATE TABLE ADMIN_USER 
   (	USERID NUMBER, 
	FIRSTNAME VARCHAR2(25), 
	LASTNAME VARCHAR2(25), 
	EMAIL VARCHAR2(100)
   ) ;

  CREATE TABLE CONNECTION_DETAILS 
   (	DB_ID NUMBER, 
	USER_NAME VARCHAR2(50), 
	PASSWORD VARCHAR2(50), 
	SERVER_HOST VARCHAR2(100), 
	PORT NUMBER, 
	SERVICE_NAME VARCHAR2(50), 
	SCHEMA_KEYSPACE_NAME VARCHAR2(50), 
	USER_ID NUMBER, 
	CONNECTION_ID NUMBER
   ) ;

  CREATE TABLE CRF_QRTZ_BLOB_TRIGGERS 
   (	TRIGGER_NAME VARCHAR2(200), 
	TRIGGER_GROUP VARCHAR2(200), 
	BLOB_DATA BLOB, 
	SCHED_NAME VARCHAR2(100) 
	-- CONSTRAINT CRF_QRTZ__26_FK FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP)
	 -- REFERENCES CRF_QRTZ_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP) ENABLE
   ) ;

  CREATE TABLE CRF_QRTZ_CALENDARS 
   (	CALENDAR_NAME VARCHAR2(200), 
	CALENDAR BLOB, 
	SCHED_NAME VARCHAR2(100)
   ) ;

  CREATE TABLE CRF_QRTZ_CRON_TRIGGERS 
   (	TRIGGER_NAME VARCHAR2(200), 
	TRIGGER_GROUP VARCHAR2(200), 
	CRON_EXPRESSION VARCHAR2(120), 
	TIME_ZONE_ID VARCHAR2(80), 
	SCHED_NAME VARCHAR2(100)
	-- CONSTRAINT CRF_QRTZ__52_FK FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP)
	--  REFERENCES CRF_QRTZ_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP) ENABLE
   ) ;

  CREATE TABLE CRF_QRTZ_FIRED_TRIGGERS 
   (	ENTRY_ID VARCHAR2(95), 
	TRIGGER_NAME VARCHAR2(200), 
	TRIGGER_GROUP VARCHAR2(200), 
	IS_VOLATILE VARCHAR2(1), 
	INSTANCE_NAME VARCHAR2(200), 
	FIRED_TIME NUMBER(13,0), 
	PRIORITY NUMBER(13,0), 
	STATE VARCHAR2(16), 
	JOB_NAME VARCHAR2(200), 
	JOB_GROUP VARCHAR2(200), 
	IS_STATEFUL VARCHAR2(1), 
	REQUESTS_RECOVERY VARCHAR2(1), 
	SCHED_NAME VARCHAR2(100)
   ) ;

  CREATE TABLE CRF_QRTZ_JOB_DETAILS 
   (	JOB_NAME VARCHAR2(200), 
	JOB_GROUP VARCHAR2(200), 
	DESCRIPTION VARCHAR2(250), 
	JOB_CLASS_NAME VARCHAR2(250), 
	IS_DURABLE VARCHAR2(1), 
	IS_VOLATILE VARCHAR2(1), 
	IS_STATEFUL VARCHAR2(1), 
	REQUESTS_RECOVERY VARCHAR2(1), 
	JOB_DATA BLOB, 
	SCHED_NAME VARCHAR2(100)
   ) ;

  CREATE TABLE CRF_QRTZ_JOB_LISTENERS 
   (	JOB_NAME VARCHAR2(200), 
	JOB_GROUP VARCHAR2(200), 
	JOB_LISTENER VARCHAR2(200) 
	-- CONSTRAINT CRF_QRTZ__42_FK FOREIGN KEY (JOB_NAME, JOB_GROUP)
	--  REFERENCES CRF_QRTZ_JOB_DETAILS (JOB_NAME, JOB_GROUP) ENABLE
   ) ;

  CREATE TABLE CRF_QRTZ_LOCKS 
   (	LOCK_NAME VARCHAR2(40), 
	SCHED_NAME VARCHAR2(100)
   ) ;

  CREATE TABLE CRF_QRTZ_PAUSED_TRIGGER_GRPS 
   (	TRIGGER_GROUP VARCHAR2(200), 
	SCHED_NAME VARCHAR2(100)
   ) ;

  CREATE TABLE CRF_QRTZ_SCHEDULER_STATE 
   (	INSTANCE_NAME VARCHAR2(200), 
	LAST_CHECKIN_TIME NUMBER(13,0), 
	CHECKIN_INTERVAL NUMBER(13,0), 
	SCHED_NAME VARCHAR2(100)
   ) ;

  CREATE TABLE CRF_QRTZ_SIMPLE_TRIGGERS 
   (	TRIGGER_NAME VARCHAR2(200), 
	TRIGGER_GROUP VARCHAR2(200), 
	REPEAT_COUNT NUMBER(7,0), 
	REPEAT_INTERVAL NUMBER(12,0), 
	TIMES_TRIGGERED NUMBER(10,0), 
	SCHED_NAME VARCHAR2(100)
	-- CONSTRAINT CRF_QRTZ__2_FK FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP)
	--  REFERENCES CRF_QRTZ_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP) ENABLE
   ) ;

  CREATE TABLE CRF_QRTZ_TRIGGERS 
   (	TRIGGER_NAME VARCHAR2(200), 
	TRIGGER_GROUP VARCHAR2(200), 
	JOB_NAME VARCHAR2(200), 
	JOB_GROUP VARCHAR2(200), 
	IS_VOLATILE VARCHAR2(1), 
	DESCRIPTION VARCHAR2(250), 
	NEXT_FIRE_TIME NUMBER(13,0), 
	PREV_FIRE_TIME NUMBER(13,0), 
	PRIORITY NUMBER(13,0), 
	TRIGGER_STATE VARCHAR2(16), 
	TRIGGER_TYPE VARCHAR2(8), 
	START_TIME NUMBER(13,0), 
	END_TIME NUMBER(13,0), 
	CALENDAR_NAME VARCHAR2(200), 
	MISFIRE_INSTR NUMBER(2,0), 
	JOB_DATA BLOB, 
	SCHED_NAME VARCHAR2(100)
	-- CONSTRAINT CRF_QRTZ__1_FK FOREIGN KEY (JOB_NAME, JOB_GROUP)
	--  REFERENCES CRF_QRTZ_JOB_DETAILS (JOB_NAME, JOB_GROUP) ENABLE
   ) ;

  CREATE TABLE CRF_QRTZ_TRIGGER_LISTENERS 
   (	TRIGGER_NAME VARCHAR2(200), 
	TRIGGER_GROUP VARCHAR2(200), 
	TRIGGER_LISTENER VARCHAR2(200)
	-- CONSTRAINT CRF_QRTZ__35_FK FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP)
	--  REFERENCES CRF_QRTZ_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP) ENABLE
   ) ;

  CREATE TABLE DASHBOARDDETAILS 
   (	DASHBOARDID NUMBER, 
	DASHBOARDNAME VARCHAR2(100), 
	DOMAINID NUMBER, 
	TEMPLATEID NUMBER, 
	USERID NUMBER, 
	TYPE VARCHAR2(10), 
	DESCRIPTION VARCHAR2(2000)
   ) ;

  CREATE TABLE DASHBOARDQUERYRELATION 
   (	DASHBOARDQUERYRELATIONID NUMBER, 
	QUERYID NUMBER, 
	DASHBOARDID NUMBER
	-- CONSTRAINT DASHBOARDID_FK2 FOREIGN KEY (DASHBOARDID)
	--  REFERENCES DASHBOARDDETAILS (DASHBOARDID) ENABLE
   ) ;

  CREATE TABLE DASHBOARDUSERRELATION 
   (	DASHBOARDUSERRELATIONID NUMBER, 
	USERID NUMBER, 
	DASHBOARDID NUMBER
	-- CONSTRAINT USERID_FK2 FOREIGN KEY (USERID)
	--  REFERENCES ADMIN_USER (USERID) ENABLE, 
	-- CONSTRAINT DASHBOARID_FK1 FOREIGN KEY (DASHBOARDID)
	--  REFERENCES DASHBOARDDETAILS (DASHBOARDID) ENABLE
   ) ;

  CREATE TABLE DASHBOARD_COMP 
   (	DASHBOARD_COMP_ID NUMBER, 
	DASHBOARD_ID NUMBER, 
	SUMMARY_ID NUMBER, 
	DASHBOARD_COMP_NAME VARCHAR2(100), 
	DASHBOARD_COMP_TYPE VARCHAR2(30), 
	HEIGHT_PERCENTAGE NUMBER, 
	WIDTH_PERCENTAGE NUMBER, 
	DISP_SEQ NUMBER, 
	REL_DASHBOARD_COMP_ID NUMBER, 
	LAYOUT_ID NUMBER
	-- CONSTRAINT DASHBOARD_COMP_SMRY_DET_FK FOREIGN KEY (SUMMARY_ID)
	--  REFERENCES SUMMARY_DETAILS (SUMMARY_ID) ENABLE, 
	-- CONSTRAINT DASHBOARD_COMP_LAYOUT_FK FOREIGN KEY (LAYOUT_ID)
	--  REFERENCES LAYOUT (LAYOUT_ID) ENABLE, 
	-- CONSTRAINT DASHBOARD_LAYOUT_FK FOREIGN KEY (REL_DASHBOARD_COMP_ID)
	--  REFERENCES DASHBOARD_COMP (DASHBOARD_COMP_ID) ENABLE, 
	-- CONSTRAINT DASHBOARD_USERS_DASHBRD_FK FOREIGN KEY (DASHBOARD_ID)
	 -- REFERENCES USERS_DASHBOARD (DASHBOARD_ID) ENABLE
   ) ;

  CREATE TABLE DASHBOARD_PUBLISH_DETAIL 
   (	DASHBOARD_ID NUMBER, 
	USER_ID NUMBER, 
	GROUP_ID NUMBER, 
	DASHBOARD_PUBLISH_FLG VARCHAR2(1), 
	DFLT_FLG VARCHAR2(1), 
	PUBLISHED_BY VARCHAR2(50), 
	PUBLISHED_DATE TIMESTAMP (6), 
	FILTER_DATA CLOB, 
	DEFAULT_YN VARCHAR2(1)
   ) ;

  
  CREATE TABLE DATABASEPRIVILEGES 
   (	DBPRIVILEGESID NUMBER(30,0), 
	USERID VARCHAR2(100), 
	TABLENAME VARCHAR2(200), 
	DOMAINNAME VARCHAR2(100)
   ) ;

  CREATE TABLE DB_DETAILS 
   (	DB_ID NUMBER, 
	DB_NAME VARCHAR2(50), 
	DB_DESCRIPTION VARCHAR2(50), 
	DB_SOURCE VARCHAR2(25)
   ) ;

  CREATE TABLE DOMAIN 
   (	DOMAINID NUMBER, 
	DOMAINNAME VARCHAR2(25), 
	DOMAININITIAL VARCHAR2(20), 
	DOMAINSOURCE VARCHAR2(25), 
	DESCRIPTION VARCHAR2(100), 
	TESTING VARCHAR2(4000)
   ) ;

  CREATE TABLE EXPORT_DETAILS 
   (	EXPORT_ID NUMBER, 
	EXPORT_NAME VARCHAR2(200), 
	EXPORT_DATA CLOB, 
	CREATED_BY VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

  CREATE TABLE FIELD_DATA_OPERATOR_DETAILS 
   (	FIELD_ID NUMBER(30,0), 
	DEPENDENT_FIELD_NAME VARCHAR2(100), 
	OPERATOR VARCHAR2(50), 
	FIELD_DB_NAME VARCHAR2(500) 
	-- CONSTRAINT FIELDDATAOPERATOR_FIELDID_FK FOREIGN KEY (FIELD_ID)
	--  REFERENCES REPORT_SEARCH_FIELDS (FIELD_ID) ENABLE
   ) ;

  CREATE TABLE FOLDER_QUERY_ASSOC 
   (	FOLDER_ID NUMBER, 
	QUERY_ID NUMBER
   ) ;

  CREATE TABLE HISTORYSCHEDULEDETAILS 
   (	SCHEDULEID VARCHAR2(50), 
	SCHEDULENAME VARCHAR2(200), 
	STARTTIME VARCHAR2(100), 
	ENDTIME VARCHAR2(100), 
	STATUS VARCHAR2(50), 
	SCHEDULETYPE VARCHAR2(100), 
	PUBLISHMODE VARCHAR2(50)
   ) ;

  CREATE TABLE LAYOUT 
   (	LAYOUT_ID NUMBER, 
	LAYOUT_NAME VARCHAR2(100), 
	LAYOUT_TYPE VARCHAR2(30), 
	LAYOUT_DESC VARCHAR2(500), 
	LAYOUT_FRAMETYPE VARCHAR2(30), 
	LAYOUT_IMAGE BLOB, 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

  CREATE TABLE LAYOUT_COMPONENT 
   (	LAYOUT_COMP_ID NUMBER, 
	LAYOUT_ID NUMBER, 
	REL_LAYOUT_COMP_ID NUMBER, 
	LAYOUT_COMP_NAME VARCHAR2(100), 
	LAYOUT_COMP_DESC VARCHAR2(500), 
	HEIGHT_PERCENTAGE NUMBER, 
	WIDTH_PERCENTAGE NUMBER, 
	DISP_SEQ NUMBER, 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6) 
	-- CONSTRAINT LAYOUT_COMPONENT_FK FOREIGN KEY (REL_LAYOUT_COMP_ID)
	--  REFERENCES LAYOUT_COMPONENT (LAYOUT_COMP_ID) ENABLE, 
	-- CONSTRAINT LAYOUT_COMPONENT_LAYOUT_FK FOREIGN KEY (LAYOUT_ID)
	--  REFERENCES LAYOUT (LAYOUT_ID) ENABLE
   ) ;

  CREATE TABLE LAYOUT_USER_ASSOC 
   (	LAYOUT_ID NUMBER, 
	USERID VARCHAR2(150) 
	-- CONSTRAINT LAYOUT_USER_ASSOC_LAYOUT_FK FOREIGN KEY (LAYOUT_ID)
	--  REFERENCES LAYOUT (LAYOUT_ID) ENABLE
   ) ;

  CREATE TABLE LOGSEARCH_DETAILS 
   (	LOGSEARCH_ID NUMBER, 
	NAME VARCHAR2(100), 
	URL VARCHAR2(255), 
	DESCRIPTION VARCHAR2(4000), 
	SEARCH_CRITERIA CLOB, 
	EXTERNAL_ID1 VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100)
   ) ;

  CREATE TABLE METRICS_COMPONENT 
   (	METRICE_TEMPLATE_ID NUMBER, 
	COMPONENT_NAME VARCHAR2(100), 
	DATATYPE VARCHAR2(30), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE DATE, 
	METRICS_MEASURE VARCHAR2(100), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE DATE, 
	FIELD_ID NUMBER
	-- CONSTRAINT METRICS_COMPONENT_FK FOREIGN KEY (FIELD_ID)
	--  REFERENCES REPORT_SEARCH_FIELDS (FIELD_ID) ENABLE
   ) ;

  CREATE TABLE METRICS_TEMPLATE_DETAIL 
   (	METRICE_TEMPLATE_ID NUMBER, 
	METRICE_NAME VARCHAR2(500), 
	STATIC_QUERY CLOB, 
	METRICS_TYPE VARCHAR2(50), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE DATE, 
	METRICS_MEASURE VARCHAR2(100), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE DATE, 
	METRICS_LEVEL VARCHAR2(100), 
	METRICS_INDICATOR VARCHAR2(100), 
	DRILL_DOWN_LEVEL NUMBER, 
	DRILL_DOWN_PARENT_ID NUMBER, 
	DATASOURCE VARCHAR2(50), 
	LAST_REFRESH_DATE TIMESTAMP (6), 
	METRICS_IMAGE BLOB
   ) ;

  CREATE TABLE OBJECT_METADATA 
   (	OBJECT_ID NUMBER, 
	OBJECT_NAME VARCHAR2(30), 
	OBJECT_TYPE VARCHAR2(30), 
	DISPLAY_NAME VARCHAR2(100), 
	USER_ID VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	SOURCE VARCHAR2(20), 
	CONNECTION_ID NUMBER
   ) ;

  CREATE TABLE QRTZ_BLOB_TRIGGERS 
   (	TRIGGER_NAME VARCHAR2(200), 
	TRIGGER_GROUP VARCHAR2(200), 
	BLOB_DATA BLOB
	-- CONSTRAINT QRTZ__26_FK FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP)
	--  REFERENCES QRTZ_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP) ENABLE
   ) ;

  CREATE TABLE QRTZ_CALENDARS 
   (	CALENDAR_NAME VARCHAR2(200), 
	CALENDAR BLOB
   ) ;

  CREATE TABLE QRTZ_CRON_TRIGGERS 
   (	TRIGGER_NAME VARCHAR2(200), 
	TRIGGER_GROUP VARCHAR2(200), 
	CRON_EXPRESSION VARCHAR2(120), 
	TIME_ZONE_ID VARCHAR2(80)
	-- CONSTRAINT QRTZ__52_FK FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP)
	--  REFERENCES QRTZ_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP) ENABLE
   ) ;

  CREATE TABLE QRTZ_FIRED_TRIGGERS 
   (	ENTRY_ID VARCHAR2(95), 
	TRIGGER_NAME VARCHAR2(200), 
	TRIGGER_GROUP VARCHAR2(200), 
	IS_VOLATILE VARCHAR2(1), 
	INSTANCE_NAME VARCHAR2(200), 
	FIRED_TIME NUMBER(13,0), 
	PRIORITY NUMBER(13,0), 
	STATE VARCHAR2(16), 
	JOB_NAME VARCHAR2(200), 
	JOB_GROUP VARCHAR2(200), 
	IS_STATEFUL VARCHAR2(1), 
	REQUESTS_RECOVERY VARCHAR2(1)
   ) ;

  CREATE TABLE QRTZ_JOB_DETAILS 
   (	JOB_NAME VARCHAR2(200), 
	JOB_GROUP VARCHAR2(200), 
	DESCRIPTION VARCHAR2(250), 
	JOB_CLASS_NAME VARCHAR2(250), 
	IS_DURABLE VARCHAR2(1), 
	IS_VOLATILE VARCHAR2(1), 
	IS_STATEFUL VARCHAR2(1), 
	REQUESTS_RECOVERY VARCHAR2(1), 
	JOB_DATA BLOB
   ) ;

  CREATE TABLE QRTZ_JOB_LISTENERS 
   (	JOB_NAME VARCHAR2(200), 
	JOB_GROUP VARCHAR2(200), 
	JOB_LISTENER VARCHAR2(200)
	-- CONSTRAINT QRTZ__42_FK FOREIGN KEY (JOB_NAME, JOB_GROUP)
	--  REFERENCES QRTZ_JOB_DETAILS (JOB_NAME, JOB_GROUP) ENABLE
   ) ;

  CREATE TABLE QRTZ_LOCKS 
   (	LOCK_NAME VARCHAR2(40)
   ) ;

  CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS 
   (	TRIGGER_GROUP VARCHAR2(200)
   ) ;

  CREATE TABLE QRTZ_SCHEDULER_STATE 
   (	INSTANCE_NAME VARCHAR2(200), 
	LAST_CHECKIN_TIME NUMBER(13,0), 
	CHECKIN_INTERVAL NUMBER(13,0)
   ) ;

  CREATE TABLE QRTZ_SIMPLE_TRIGGERS 
   (	TRIGGER_NAME VARCHAR2(200), 
	TRIGGER_GROUP VARCHAR2(200), 
	REPEAT_COUNT NUMBER(7,0), 
	REPEAT_INTERVAL NUMBER(12,0), 
	TIMES_TRIGGERED NUMBER(10,0) 
	-- CONSTRAINT QRTZ__2_FK FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP)
	--  REFERENCES QRTZ_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP) ENABLE
   ) ;

  CREATE TABLE QRTZ_TRIGGERS 
   (	TRIGGER_NAME VARCHAR2(200), 
	TRIGGER_GROUP VARCHAR2(200), 
	JOB_NAME VARCHAR2(200), 
	JOB_GROUP VARCHAR2(200), 
	IS_VOLATILE VARCHAR2(1), 
	DESCRIPTION VARCHAR2(250), 
	NEXT_FIRE_TIME NUMBER(13,0), 
	PREV_FIRE_TIME NUMBER(13,0), 
	PRIORITY NUMBER(13,0), 
	TRIGGER_STATE VARCHAR2(16), 
	TRIGGER_TYPE VARCHAR2(8), 
	START_TIME NUMBER(13,0), 
	END_TIME NUMBER(13,0), 
	CALENDAR_NAME VARCHAR2(200), 
	MISFIRE_INSTR NUMBER(2,0), 
	JOB_DATA BLOB
	-- CONSTRAINT QRTZ__1_FK FOREIGN KEY (JOB_NAME, JOB_GROUP)
	--  REFERENCES QRTZ_JOB_DETAILS (JOB_NAME, JOB_GROUP) ENABLE
   ) ;

  CREATE TABLE QRTZ_TRIGGER_LISTENERS 
   (	TRIGGER_NAME VARCHAR2(200), 
	TRIGGER_GROUP VARCHAR2(200), 
	TRIGGER_LISTENER VARCHAR2(200)
	-- CONSTRAINT QRTZ__35_FK FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP)
	 -- REFERENCES QRTZ_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP) ENABLE
   ) ;

  CREATE TABLE QUERYDETAILS 
   (	QUERYID NUMBER, 
	QUERYNAME VARCHAR2(100), 
	QUERYXML CLOB, 
	USERID NUMBER DEFAULT 27, 
	CREATEDDATE DATE DEFAULT SYSDATE, 
	QUERYDESCRIPTION VARCHAR2(3000), 
	DOMAINNAME VARCHAR2(30), 
	STATUS VARCHAR2(50), 
	ALTEREDCOLUNMS VARCHAR2(4000), 
	REPORTTYPE VARCHAR2(100), 
	QRY_FORMATION_TYPE VARCHAR2(20), 
	QUERY CLOB, 
	CUSTOM_QUERY CLOB, 
	MODIFIED_DATE DATE, 
	QUERY_REL_ID VARCHAR2(3000), 
	CUST_REL_ID NUMBER, 
	QUERY_CUSTOM_FILTER VARCHAR2(100) 
	-- CONSTRAINT USERID_FK1 FOREIGN KEY (USERID)
	--  REFERENCES ADMIN_USER (USERID) ENABLE
   ) ;

  CREATE TABLE REF_DIRECTORY 
   (	RPT_DIR_ID NUMBER  NOT NULL, 
	RPT_DIR_NAME VARCHAR2(300), 
	RPT_DIR_TYPE VARCHAR2(50), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	DIR_LEVEL NUMBER, 
	DIRECTORY_TYPE VARCHAR2(20)
   ) ;

  CREATE TABLE REF_SOURCE_TYPE 
   (	REP_SOURCE_ID NUMBER(2,0), 
	REP_SOURCE_TYPE_NAME VARCHAR2(50), 
	TYPE_DESCRIPTION VARCHAR2(100)
   ) ;

  CREATE TABLE REPORT_DASHBOARD_ASSOC 
   (	REPORT_ID NUMBER(30,0), 
	DASHBOARD_ID NUMBER
	-- CONSTRAINT REP_USER_ASSOC_FK FOREIGN KEY (REPORT_ID)
	--  REFERENCES REPORT_DETAILS (REPORT_ID) ENABLE, 
	-- CONSTRAINT REP_USERS_DASHBOARD_FK FOREIGN KEY (DASHBOARD_ID)
	 -- REFERENCES USERS_DASHBOARD (DASHBOARD_ID) ENABLE
   ) ;

  CREATE TABLE REPORT_DETAILS 
   (	REPORT_ID NUMBER(30,0), 
	REPORT_SOURCE_ID NUMBER(2,0), 
	REP_OUTPUT_ID NUMBER(2,0), 
	REP_OUTPUT_TYPE_ID NUMBER(2,0), 
	REP_GENERATION_ID NUMBER(2,0), 
	REPORT_TEMPLATE_ID NUMBER(30,0), 
	DOMAIN_ID NUMBER(30,0), 
	REPORT_NAME VARCHAR2(50), 
	REPORT_DESCRIPTION VARCHAR2(100), 
	ACTIVE_STATUS CHAR(1), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	REPORT_TYPE VARCHAR2(30), 
	HEADERS CLOB, 
	REPORT_HEADER VARCHAR2(100), 
	REPORT_FOOTER VARCHAR2(100), 
	GROUP_ID NUMBER, 
	RELATED_REPORT_ID NUMBER(30,0) 
	-- CONSTRAINT REP_DOMAIN_DETAILS_FK FOREIGN KEY (DOMAIN_ID)
	--  REFERENCES REPORT_DOMAIN_DETAILS (DOMAIN_ID) ENABLE, 
	-- CONSTRAINT REP_SOURCE_TYPE_FK FOREIGN KEY (REPORT_SOURCE_ID)
	--  REFERENCES REF_SOURCE_TYPE (REP_SOURCE_ID) ENABLE, 
	-- CONSTRAINT REPORT_DETAILS_FK FOREIGN KEY (RELATED_REPORT_ID)
	--  REFERENCES REPORT_DETAILS (REPORT_ID) ENABLE, 
	 --CONSTRAINT REP_TEMPLATE_DETAILS_FK FOREIGN KEY (REPORT_TEMPLATE_ID)
	 -- REFERENCES REP_TEMPLATE_DETAILS (REPORT_TEMPLATE_ID) ENABLE
   ) ;

  CREATE TABLE REPORT_DOMAIN_DETAILS 
   (	DOMAIN_ID NUMBER(30,0), 
	DOMAIN_NAME VARCHAR2(50), 
	DOMAIN_DESCRIPTION VARCHAR2(100), 
	DATASOURCE_JNDI VARCHAR2(100)
   ) ;

  CREATE TABLE REPORT_HEADER_DETAILS 
   (	REPORT_ID NUMBER(30,0), 
	COLUMN_HEADER VARCHAR2(100), 
	REPORT_COLUMN VARCHAR2(50), 
	COLUMN_INDEX NUMBER(3,0), 
	SORTABLE CHAR(1), 
	HIDEABLE CHAR(1), 
	DRAGGABLE CHAR(1), 
	RENDERER VARCHAR2(100), 
	DATATYPE VARCHAR2(30), 
	COLUMN_ID NUMBER, 
	QUERYID NUMBER, 
	MAPPED_ENTITY_TYPE VARCHAR2(30), 
	MAPPED_ENTITY_ID NUMBER, 
	OBJECT_ID NUMBER, 
	COLUMN_QUERY CLOB, 
	METRICS_ID NUMBER, 
	FIELD_ID NUMBER, 
	DEFAULT_VALUE VARCHAR2(100) 
	-- CONSTRAINT REP_HDR_DET_QRYDET_FK FOREIGN KEY (QUERYID)
	--  REFERENCES QUERYDETAILS (QUERYID) ENABLE, 
	-- CONSTRAINT REP_HEADER_DETAILS_FK FOREIGN KEY (REPORT_ID)
	--  REFERENCES REPORT_DETAILS (REPORT_ID) ENABLE, 
	-- CONSTRAINT REPORT_HDR_OBJ_METADATA_FK FOREIGN KEY (OBJECT_ID)
	 -- REFERENCES OBJECT_METADATA (OBJECT_ID) ENABLE, 
	-- CONSTRAINT REPORT_HEADER_DETAILS_FK FOREIGN KEY (FIELD_ID)
	--  REFERENCES REPORT_SEARCH_FIELDS (FIELD_ID) ENABLE
   ) ;

  CREATE TABLE REPORT_PARAM 
   (	REP_PARAM_ID NUMBER, 
	REP_PARAM_NAME VARCHAR2(100), 
	REP_PARAM_TYPE VARCHAR2(30), 
	REP_PARAM_VALUE VARCHAR2(500), 
	REPORT_ID NUMBER(30,0), 
	REP_COMP_TYPE VARCHAR2(30), 
	REP_COMP_ID NUMBER, 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6)
	-- CONSTRAINT REP_PARAM_REP_DETAILS_FK FOREIGN KEY (REPORT_ID)
	 -- REFERENCES REPORT_DETAILS (REPORT_ID) ENABLE
   ) ;

  CREATE TABLE REPORT_SEARCH_FIELDS 
   (	FIELD_ID NUMBER(30,0), 
	REPORT_ID NUMBER(30,0), 
	FIELD_NAME VARCHAR2(100), 
	FIELD_DISPLAY_NAME VARCHAR2(100), 
	OPERATOR VARCHAR2(400), 
	CONTROL_TYPE VARCHAR2(50), 
	DEPENDENT_FIELDS VARCHAR2(200), 
	MANDATORY CHAR(1), 
	CSS_CLASS VARCHAR2(50), 
	SEQUENCE_NUMBER NUMBER(2,0), 
	LISTENERS VARCHAR2(500)
   ) ;

  CREATE TABLE REPORT_SEARCH_FIELD_VALUES 
   (	FIELD_ID NUMBER(30,0), 
	DATA_PROVIDER VARCHAR2(50), 
	DATA_PROVIDER_INPUT VARCHAR2(500) 
	-- CONSTRAINT REPSEARCHFIELD_FK FOREIGN KEY (FIELD_ID)
	 -- REFERENCES REPORT_SEARCH_FIELDS (FIELD_ID) ENABLE
   ) ;

  CREATE TABLE REPORT_STYLE 
   (	STYLE_ID NUMBER(30,0), 
	STYLE_NAME VARCHAR2(50), 
	FOREGROUND_COLOR VARCHAR2(30), 
	BACKGROUND_COLOR VARCHAR2(30), 
	FONT_NAME VARCHAR2(30), 
	FONT_SIZE VARCHAR2(30), 
	FONT_STYLE VARCHAR2(30), 
	ALIGNMENT VARCHAR2(20), 
	VERTICAL_ALIGNMENT VARCHAR2(20), 
	BOLD CHAR(1), 
	ITALIC CHAR(1), 
	UNDERLINE CHAR(1)
   ) ;

  CREATE TABLE REP_TEMPLATE_DETAILS 
   (	REPORT_TEMPLATE_ID NUMBER(30,0), 
	PAGE_HEADER NUMBER(30,0), 
	COLUMN_HEADER NUMBER(30,0), 
	DETAIL NUMBER(30,0), 
	PAGE_FOOTER NUMBER(30,0), 
	PAGE_LAYOUT NUMBER(30,0), 
	TEMPLATE_NAME VARCHAR2(50), 
	TEMPLATE_DESCRIPTION VARCHAR2(100), 
	COLUMN_FOOTER NUMBER(30,0) 
	-- CONSTRAINT REP_PG_HEADER_STYLE_FK FOREIGN KEY (PAGE_HEADER)
	--  REFERENCES REPORT_STYLE (STYLE_ID) ENABLE, 
	-- CONSTRAINT REP_PG_LAYOUT_STYLE_FK FOREIGN KEY (PAGE_LAYOUT)
	--  REFERENCES REPORT_STYLE (STYLE_ID) ENABLE, 
	-- CONSTRAINT REP_COL_FOOTER_STYLE_FK FOREIGN KEY (COLUMN_FOOTER)
	--  REFERENCES REPORT_STYLE (STYLE_ID) ENABLE, 
	-- CONSTRAINT REP_DETAIL_STYLE_FK FOREIGN KEY (DETAIL)
	--  REFERENCES REPORT_STYLE (STYLE_ID) ENABLE, 
	-- CONSTRAINT REP_PG_FOOTER_STYLE_FK FOREIGN KEY (PAGE_FOOTER)
	--  REFERENCES REPORT_STYLE (STYLE_ID) ENABLE, 
	-- CONSTRAINT REP_COL_HEADER_STYLE_FK FOREIGN KEY (COLUMN_HEADER)
	--  REFERENCES REPORT_STYLE (STYLE_ID) ENABLE
   ) ;

  CREATE TABLE REP_VIEW_DETAILS 
   (	REPORT_ID NUMBER(30,0), 
	QUERY_DETAILS CLOB
	-- CONSTRAINT REP_VIEW_DETAILS_FK FOREIGN KEY (REPORT_ID)
	 -- REFERENCES REPORT_DETAILS (REPORT_ID) ENABLE
   ) ;

  CREATE TABLE RPT_DIRECTORY_HIERARCHY 
   (	MAST_DIR_ID NUMBER, 
	DIR_ID NUMBER, 
	REL_DIR_ID NUMBER, 
	USER_ID NUMBER, 
	GROUP_ID NUMBER, 
	REPORT_ID NUMBER, 
	OBJECT_ID NUMBER, 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6) 
	-- CONSTRAINT RPT_DIR_HIER_OBJECTID_FK FOREIGN KEY (OBJECT_ID)
	 -- REFERENCES OBJECT_METADATA (OBJECT_ID) ENABLE, 
	-- CONSTRAINT RPT_DIR_HIER_REPORTID_FK FOREIGN KEY (REPORT_ID)
	--  REFERENCES REPORT_DETAILS (REPORT_ID) ENABLE
   ) ;

  CREATE TABLE SAVE_FILTER_DETAILS 
   (	SAVE_FILTER_ID NUMBER, 
	QUERYID NUMBER, 
	FILTER_JSON CLOB, 
	SAVE_FILTER_NAME VARCHAR2(100), 
	FILTER_USER_ID NUMBER
   ) ;

  CREATE TABLE SCHEDULEDETAILS 
   (	SCHEDULENAME VARCHAR2(200), 
	SCHEDULETYPE VARCHAR2(100), 
	SCHEDULEID VARCHAR2(50), 
	SCHEDULETIME VARCHAR2(100), 
	STATUS VARCHAR2(50), 
	REPORTID NUMBER, 
	USERID VARCHAR2(100), 
	SCHEDULEENDDATETIME VARCHAR2(100), 
	SCHEDULETO VARCHAR2(200), 
	PUBLISHMODE VARCHAR2(50), 
	INTERVAL VARCHAR2(100), 
	LASTRUNTIME VARCHAR2(100), 
	SERVERTIME VARCHAR2(100), 
	REPORTNAME VARCHAR2(100), 
	PUBLISHTO VARCHAR2(100), 
	REPORTTYPE VARCHAR2(100), 
	MAILSUBJECT VARCHAR2(500), 
	MAILBODY VARCHAR2(3000), 
	REPORT_DATA BLOB, 
	ENTITY_NAME VARCHAR2(20), 
	USERNAME VARCHAR2(100), 
	PASSWORD VARCHAR2(100), 
	HOST VARCHAR2(100), 
	PORT NUMBER(2,0), 
	SFTPPATH NVARCHAR2(1000), 
	CONNECTIONNAME VARCHAR2(100), 
	ZIPTYPE VARCHAR2(50)
   ) ;

  CREATE TABLE SCHEDULE_ENTITY_ASSOC 
   (	SCHEDULEID VARCHAR2(50), 
	REPORTID NUMBER, 
	USR_GROUP_ID NUMBER, 
	USERID VARCHAR2(100), 
	USR_ID NUMBER
	-- CONSTRAINT SCHD_ENT_ASSOC_SCHD_FK FOREIGN KEY (SCHEDULEID)
	--  REFERENCES SCHEDULEDETAILS (SCHEDULEID) ENABLE
   ) ;

  CREATE TABLE SFTPSERVERDETAILS 
   (	USERID NUMBER, 
	CONNECTIONNAME VARCHAR2(100), 
	USERNAME VARCHAR2(100), 
	PASSWORD VARCHAR2(100), 
	HOST VARCHAR2(100), 
	PORT NUMBER(2,0), 
	SFTPPATH NVARCHAR2(1000)
   ) ;

  CREATE TABLE SUMMARY_DETAILS 
   (	SUMMARY_ID NUMBER, 
	QUERYID NUMBER, 
	USERID VARCHAR2(100), 
	DISPLAYFORMAT VARCHAR2(100), 
	QUERY CLOB, 
	METRICS_TEMPLATE_ID NUMBER, 
	CHART_NAME VARCHAR2(100) 
	 --CONSTRAINT QUERYID_FK FOREIGN KEY (QUERYID)
	 -- REFERENCES QUERYDETAILS (QUERYID) ENABLE
   ) ;

  CREATE TABLE URL_CONFIG 
   (	URL_ID NUMBER, 
	URL_NAME VARCHAR2(100), 
	URL VARCHAR2(500), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

  CREATE TABLE USERQUERYASSOCIATION 
   (	USERQUERYASSID NUMBER, 
	USERID VARCHAR2(100), 
	QUERYID NUMBER(20,0), 
	QUERY_PRIVILEGE VARCHAR2(50), 
	USR_GROUP_ID NUMBER, 
	USR_ID NUMBER, 
	PUBLISHED_BY VARCHAR2(50), 
	PUBLISHED_DATE TIMESTAMP (6), 
	WRITE_ACCESS CHAR(1), 
	ENTITY_ID NUMBER, 
	ENTITY_TYPE VARCHAR2(50)
   ) ;

  CREATE TABLE USERS_DASHBOARD 
   (	DASHBOARD_ID NUMBER, 
	DASHBOARD_NAME VARCHAR2(100), 
	DASHBOARD_DESCRIPTION VARCHAR2(300), 
	USER_ID VARCHAR2(150), 
	CREATED_DATE TIMESTAMP (6), 
	DEFAULT_YN VARCHAR2(1), 
	NUM_OF_HFRAMES NUMBER, 
	NUM_OF_VFRAMES NUMBER, 
	DASHBOARD_TYPE VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	FAVORITE_FLAG VARCHAR2(100)
   ) ;


--changeset Swetha.H:CRF_DDL_02_02 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TABLES 
    WHERE  
        TABLE_NAME = 'DASHBOARD_PAGE_ASSOC' ;

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE DASHBOARD_PAGE_ASSOC
		(
		DASHBOARD_ID           NUMBER(38) ,   
        PAGE_ID                NUMBER        NOT NULL,
        USER_ID                NUMBER(38)    ,
        USER_NAME              VARCHAR2(100) NOT NULL,
        DEFAULT_FLAG           VARCHAR2(1)   ,
        ENTITY_ID              NUMBER        NOT NULL,
        USER_GROUP_ID          NUMBER        NOT NULL
		
		)';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;




--changeset Swetha.H:CRF_DDL_02_03 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    l_cnt NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO l_cnt
    FROM
        user_tables
    WHERE
        table_name = 'BATCH_JOB_EXECUTION';

    IF l_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE BATCH_JOB_EXECUTION 
   (	JOB_EXECUTION_ID NUMBER(20) NOT NULL, 
	VERSION NUMBER(20), 
	JOB_INSTANCE_ID NUMBER(20) NOT NULL, 
	CREATE_TIME TIMESTAMP (6) NOT NULL, 
	START_TIME TIMESTAMP (6), 
	END_TIME TIMESTAMP (6), 
	STATUS VARCHAR2(10), 
	EXIT_CODE VARCHAR2(20), 
	EXIT_MESSAGE VARCHAR2(2500), 
	LAST_UPDATED TIMESTAMP (6)
   )';
        dbms_output.put_line('Created');
    ELSE
        dbms_output.put_line('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line('Skipped');
END;



--changeset Swetha.H:CRF_DDL_02_04 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    l_cnt NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO l_cnt
    FROM
        user_tables
    WHERE
        table_name = 'BATCH_JOB_EXECUTION_CONTEXT';

    IF l_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT
   (	JOB_EXECUTION_ID    NUMBER(20)  NOT NULL,   
SHORT_CONTEXT       VARCHAR2(2500) NOT NULL,
SERIALIZED_CONTEXT          CLOB 
   )';
        dbms_output.put_line('Created');
    ELSE
        dbms_output.put_line('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line('Skipped');
END;



--changeset Swetha.H:CRF_DDL_02_05 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    l_cnt NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO l_cnt
    FROM
        user_tables
    WHERE
        table_name = 'BATCH_JOB_EXECUTION_PARAMS';

    IF l_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE BATCH_JOB_EXECUTION_PARAMS
   (	JOB_EXECUTION_ID  NUMBER(20) NOT NULL,    
PARAMETER_NAME    VARCHAR2(100)  NOT NULL,
PARAMETER_TYPE    VARCHAR2(100)  NOT NULL,
PARAMETER_VALUE           VARCHAR2(2500), 
IDENTIFYING       CHAR(1) NOT NULL
   ) ';
        dbms_output.put_line('Created');
    ELSE
        dbms_output.put_line('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line('Skipped');
END;



--changeset Swetha.H:CRF_DDL_02_06 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    l_cnt NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO l_cnt
    FROM
        user_tables
    WHERE
        table_name = 'BATCH_JOB_INSTANCE';

    IF l_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE BATCH_JOB_INSTANCE
   (	JOB_INSTANCE_ID  NUMBER(20) NOT NULL,    
VERSION                  NUMBER(20)     ,
JOB_NAME        VARCHAR2(100)  NOT NULL ,
JOB_KEY                  VARCHAR2(2500)
   ) ';
        dbms_output.put_line('Created');
    ELSE
        dbms_output.put_line('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line('Skipped');
END;



--changeset Swetha.H:CRF_DDL_02_07 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    l_cnt NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO l_cnt
    FROM
        user_tables
    WHERE
        table_name = 'BATCH_STEP_EXECUTION';

    IF l_cnt = 0 THEN
        EXECUTE IMMEDIATE ' CREATE TABLE BATCH_STEP_EXECUTION
   (	STEP_EXECUTION_ID   NUMBER(20)  NOT NULL,   
VERSION             NUMBER(20)    NOT NULL ,
STEP_NAME           VARCHAR2(100) NOT NULL ,
JOB_EXECUTION_ID    NUMBER(20)     NOT NULL,
CREATE_TIME         TIMESTAMP(6) NOT NULL  ,
START_TIME                  TIMESTAMP(6)   ,
END_TIME                    TIMESTAMP(6)   ,
STATUS                      VARCHAR2(10)   ,
COMMIT_COUNT                NUMBER(20)     ,
READ_COUNT                  NUMBER(20)     ,
FILTER_COUNT                NUMBER(20)     ,
WRITE_COUNT                 NUMBER(20)     ,
READ_SKIP_COUNT             NUMBER(20)     ,
WRITE_SKIP_COUNT            NUMBER(20)     ,
PROCESS_SKIP_COUNT          NUMBER(20)     ,
ROLLBACK_COUNT              NUMBER(20)     ,
EXIT_CODE                   VARCHAR2(20)   ,
EXIT_MESSAGE                VARCHAR2(2500) ,
LAST_UPDATED                TIMESTAMP(6) 
   ) ';
        dbms_output.put_line('Created');
    ELSE
        dbms_output.put_line('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line('Skipped');
END;



--changeset Swetha.H:CRF_DDL_02_08 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    l_cnt NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO l_cnt
    FROM
        user_tables
    WHERE
        table_name = 'BATCH_STEP_EXECUTION_CONTEXT';

    IF l_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT
   (	STEP_EXECUTION_ID   NUMBER(20)  NOT NULL,   
SHORT_CONTEXT      VARCHAR2(2500) NOT NULL, 
SERIALIZED_CONTEXT          CLOB
   ) ';
        dbms_output.put_line('Created');
    ELSE
        dbms_output.put_line('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line('Skipped');
END;



--changeset Swetha.H:CRF_DDL_02_09 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE 
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO L_CNT
    FROM
        USER_TABLES
    WHERE
        TABLE_NAME = 'CRF_NEW_QRTZ_BLOB_TRIGGERS';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'create table CRF_NEW_QRTZ_BLOB_TRIGGERS(
                                                 SCHED_NAME             VARCHAR2(120)    NOT NULL,
                                                 TRIGGER_NAME           VARCHAR2(200)    NOT NULL,
                                                 TRIGGER_GROUP          VARCHAR2(200)    NOT NULL,
                                                 BLOB_DATA              BLOB
                                                 )';
        DBMS_OUTPUT.PUT_LINE('Created ');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ALREADY EXIST');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SKIPPED');
END;



--changeset Swetha.H:CRF_DDL_02_10 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE 
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO L_CNT
    FROM
        USER_TABLES
    WHERE
        TABLE_NAME = 'CRF_NEW_QRTZ_CALENDARS';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'create table CRF_NEW_QRTZ_CALENDARS(
                                                 SCHED_NAME     VARCHAR2(120)   NOT NULL,
                                                 CALENDAR_NAME  VARCHAR2(200)   NOT NULL,
                                                 CALENDAR       BLOB NOT NULL
                                                 )';
        DBMS_OUTPUT.PUT_LINE('Created ');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ALREADY EXIST');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SKIPPED');
END;



--changeset Swetha.H:CRF_DDL_02_11 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE 
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO L_CNT
    FROM
        USER_TABLES
    WHERE
        TABLE_NAME = 'CRF_NEW_QRTZ_CRON_TRIGGERS';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'create table CRF_NEW_QRTZ_CRON_TRIGGERS(
                                                 SCHED_NAME       VARCHAR2(120)  NOT NULL,
                                                 TRIGGER_NAME     VARCHAR2(200)  NOT NULL,
                                                 TRIGGER_GROUP    VARCHAR2(200)  NOT NULL,
                                                 CRON_EXPRESSION  VARCHAR2(120)  NOT NULL,
                                                 TIME_ZONE_ID     VARCHAR2(80)
                                                 )';
        DBMS_OUTPUT.PUT_LINE('Created ');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ALREADY EXIST');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SKIPPED');
END;



--changeset Swetha.H:CRF_DDL_02_12 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE 
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO L_CNT
    FROM
        USER_TABLES
    WHERE
        TABLE_NAME = 'CRF_NEW_QRTZ_FIRED_TRIGGERS';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'create table CRF_NEW_QRTZ_FIRED_TRIGGERS(
                                                 SCHED_NAME                 VARCHAR2(120)    NOT NULL,
                                                 ENTRY_ID                   VARCHAR2(140)    NOT NULL,
                                                 TRIGGER_NAME               VARCHAR2(200)    NOT NULL,
                                                 TRIGGER_GROUP              VARCHAR2(200)    NOT NULL,
                                                 INSTANCE_NAME              VARCHAR2(200)    NOT NULL ,
                                                 FIRED_TIME                 NUMBER(19)       NOT NULL ,
                                                 SCHED_TIME                 NUMBER(19)       NOT NULL ,
                                                 PRIORITY                   NUMBER(13)       NOT NULL,
                                                 STATE                      VARCHAR2(16)     NOT NULL,
                                                 JOB_NAME                   VARCHAR2(200) ,
                                                 JOB_GROUP                  VARCHAR2(200) ,
                                                 IS_NONCONCURRENT           VARCHAR2(1)   ,
                                                 REQUESTS_RECOVERY          VARCHAR2(1)   

                                                 )';
        DBMS_OUTPUT.PUT_LINE('Created ');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ALREADY EXIST');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SKIPPED');
END;



--changeset Swetha.H:CRF_DDL_02_13 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE 
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO L_CNT
    FROM
        USER_TABLES
    WHERE
        TABLE_NAME = 'CRF_NEW_QRTZ_JOB_DETAILS';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'create table CRF_NEW_QRTZ_JOB_DETAILS(
                                                 SCHED_NAME                 VARCHAR2(120)   NOT NULL,
                                                 JOB_NAME                   VARCHAR2(200)   NOT NULL, 
                                                 JOB_GROUP                  VARCHAR2(200)   NOT NULL,
                                                 DESCRIPTION                VARCHAR2(250)   ,
                                                 JOB_CLASS_NAME             VARCHAR2(250)   NOT NULL,
                                                 IS_DURABLE                 VARCHAR2(1)     NOT NULL,
                                                 IS_NONCONCURRENT           VARCHAR2(1)     NOT NULL,
                                                 IS_UPDATE_DATA             VARCHAR2(1)     NOT NULL,  
                                                 REQUESTS_RECOVERY          VARCHAR2(1)     NOT NULL,
                                                 JOB_DATA                   BLOB         

                                                 )';
        DBMS_OUTPUT.PUT_LINE('Created ');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ALREADY EXIST');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SKIPPED');
END;



--changeset Swetha.H:CRF_DDL_02_14 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE 
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO L_CNT
    FROM
        USER_TABLES
    WHERE
        TABLE_NAME = 'CRF_NEW_QRTZ_LOCKS';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'create table CRF_NEW_QRTZ_LOCKS(
                                                 SCHED_NAME   VARCHAR2(120)    NOT NULL ,
                                                 LOCK_NAME    VARCHAR2(40)     NOT NULL
                                                 )';
        DBMS_OUTPUT.PUT_LINE('Created ');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ALREADY EXIST');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SKIPPED');
END;




--changeset Swetha.H:CRF_DDL_02_15 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE 
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO L_CNT
    FROM
        USER_TABLES
    WHERE
        TABLE_NAME = 'CRF_NEW_QRTZ_PAUSED_TRIGGER_GRPS';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'create table CRF_NEW_QRTZ_PAUSED_TRIGGER_GRPS(
                                                 SCHED_NAME     VARCHAR2(120)  NOT NULL,
                                                 TRIGGER_GROUP  VARCHAR2(200)  NOT NULL
                                                 )';
        DBMS_OUTPUT.PUT_LINE('Created ');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ALREADY EXIST');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SKIPPED');
END;



--changeset Swetha.H:CRF_DDL_02_16 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE 
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO L_CNT
    FROM
        USER_TABLES
    WHERE
        TABLE_NAME = 'CRF_NEW_QRTZ_SCHEDULER_STATE';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'create table CRF_NEW_QRTZ_SCHEDULER_STATE(
                                                 SCHED_NAME         VARCHAR2(120)  NOT NULL,
                                                 INSTANCE_NAME      VARCHAR2(200)  NOT NULL,
                                                 LAST_CHECKIN_TIME  NUMBER(19)     NOT NULL,
                                                 CHECKIN_INTERVAL   NUMBER(13)     NOT NULL
                                                 )';
        DBMS_OUTPUT.PUT_LINE('Created ');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ALREADY EXIST');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SKIPPED');
END;


--changeset Swetha.H:CRF_DDL_02_17 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE 
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO L_CNT
    FROM
        USER_TABLES
    WHERE
        TABLE_NAME = 'CRF_NEW_QRTZ_SIMPLE_TRIGGERS';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'create table CRF_NEW_QRTZ_SIMPLE_TRIGGERS(
                                                 SCHED_NAME       VARCHAR2(120)  NOT NULL,
                                                 TRIGGER_NAME     VARCHAR2(200)  NOT NULL,
                                                 TRIGGER_GROUP    VARCHAR2(200)  NOT NULL,
                                                 REPEAT_COUNT     NUMBER(7)      NOT NULL,
                                                 REPEAT_INTERVAL  NUMBER(12)     NOT NULL,
                                                 TIMES_TRIGGERED  NUMBER(10)     NOT NULL

                                                 )';
        DBMS_OUTPUT.PUT_LINE('Created ');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ALREADY EXIST');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SKIPPED');
END;



--changeset Swetha.H:CRF_DDL_02_18 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE 
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO L_CNT
    FROM
        USER_TABLES
    WHERE
        TABLE_NAME = 'CRF_NEW_QRTZ_SIMPROP_TRIGGERS';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'create table CRF_NEW_QRTZ_SIMPROP_TRIGGERS(
                                                 SCHED_NAME             VARCHAR2(120)  NOT NULL,
                                                 TRIGGER_NAME           VARCHAR2(200)  NOT NULL,
                                                 TRIGGER_GROUP          VARCHAR2(200)  NOT NULL,
                                                 STR_PROP_1             VARCHAR2(512) ,
                                                 STR_PROP_2             VARCHAR2(512) ,
                                                 STR_PROP_3             VARCHAR2(512) ,
                                                 INT_PROP_1             NUMBER(10)    ,
                                                 INT_PROP_2             NUMBER(10)    ,
                                                 LONG_PROP_1            NUMBER(19)    ,
                                                 LONG_PROP_2            NUMBER(19)    ,
                                                 DEC_PROP_1             NUMBER(13,4)  ,
                                                 DEC_PROP_2             NUMBER(13,4)  ,
                                                 BOOL_PROP_1            VARCHAR2(1)   ,
                                                 BOOL_PROP_2            VARCHAR2(1)   ,
                                                 TIME_ZONE_ID           VARCHAR2(80)  
                                                 )';
        DBMS_OUTPUT.PUT_LINE('Created ');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ALREADY EXIST');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SKIPPED');
END;



--changeset Swetha.H:CRF_DDL_02_19 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE 
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO L_CNT
    FROM
        USER_TABLES
    WHERE
        TABLE_NAME = 'CRF_NEW_QRTZ_TRIGGERS';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'create table CRF_NEW_QRTZ_TRIGGERS(
                                                 SCHED_NAME              VARCHAR2(120)   NOT NULL,
                                                 TRIGGER_NAME            VARCHAR2(200)   NOT NULL,
                                                 TRIGGER_GROUP           VARCHAR2(200)   NOT NULL,
                                                 JOB_NAME                VARCHAR2(200)   NOT NULL,
                                                 JOB_GROUP               VARCHAR2(200)   NOT NULL,
                                                 DESCRIPTION             VARCHAR2(250) ,
                                                 NEXT_FIRE_TIME          NUMBER(19)    ,
                                                 PREV_FIRE_TIME          NUMBER(19)    ,
                                                 PRIORITY                NUMBER(13)    ,
                                                 TRIGGER_STATE           VARCHAR2(16)    NOT NULL,
                                                 TRIGGER_TYPE            VARCHAR2(8)     NOT NULL,
                                                 START_TIME              NUMBER(19)      NOT NULL,
                                                 END_TIME                NUMBER(19)    ,
                                                 CALENDAR_NAME           VARCHAR2(200) ,
                                                 MISFIRE_INSTR           NUMBER(2)     ,
                                                 JOB_DATA                BLOB          
  
                                                 )';
        DBMS_OUTPUT.PUT_LINE('Created ');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ALREADY EXIST');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SKIPPED');
END;



--changeset Swetha.H:CRF_DDL_02_20 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TAB_COLUMNS
    WHERE  
        TABLE_NAME = 'USERS_DASHBOARD'
        AND COLUMN_NAME = 'AUTO_REFRESH_FLAG';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE users_dashboard ADD auto_refresh_flag VARCHAR2(100)';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;