--liquibase formatted sql
--changeset Swetha.H:CRF_DDL_03 
--preconditions onFail:HALT onError:HALT


  ALTER TABLE REPORT_PARAM ADD CONSTRAINT REPORT_PARAM_PK PRIMARY KEY (REP_PARAM_ID)
  USING INDEX   ENABLE;

  ALTER TABLE LAYOUT ADD CONSTRAINT LAYOUT_PK PRIMARY KEY (LAYOUT_ID)
  USING INDEX   ENABLE;

  ALTER TABLE METRICS_TEMPLATE_DETAIL ADD CONSTRAINT METRICE_TEMPLATE_ID_PK PRIMARY KEY (METRICE_TEMPLATE_ID)
  USING INDEX   ENABLE;

  ALTER TABLE QUERYDETAILS ADD CONSTRAINT QUERYID_PK PRIMARY KEY (QUERYID)
  USING INDEX   ENABLE;

  ALTER TABLE EXPORT_DETAILS ADD CONSTRAINT EXPORT_ID_PK PRIMARY KEY (EXPORT_ID)
  USING INDEX   ENABLE;

  ALTER TABLE SCHEDULEDETAILS ADD CONSTRAINT SCHEDULEDETAILS_PK PRIMARY KEY (SCHEDULEID)
  USING INDEX   ENABLE;

  ALTER TABLE CRF_QRTZ_TRIGGER_LISTENERS ADD CONSTRAINT CRF_QRTZ__61_PK PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP, TRIGGER_LISTENER)
  USING INDEX   ENABLE;

  ALTER TABLE DASHBOARDDETAILS ADD CONSTRAINT DASHBOARDID_PK PRIMARY KEY (DASHBOARDID)
  USING INDEX   ENABLE;

  ALTER TABLE OBJECT_METADATA ADD CONSTRAINT OBJECT_METADATA_PK PRIMARY KEY (OBJECT_ID)
  USING INDEX   ENABLE;

  ALTER TABLE CRF_QRTZ_JOB_LISTENERS ADD CONSTRAINT CRF_QRTZ__54_PK PRIMARY KEY (JOB_NAME, JOB_GROUP, JOB_LISTENER)
  USING INDEX   ENABLE;

  ALTER TABLE QRTZ_PAUSED_TRIGGER_GRPS ADD CONSTRAINT QRTZ__59_PK PRIMARY KEY (TRIGGER_GROUP)
  USING INDEX   ENABLE;

  ALTER TABLE USERS_DASHBOARD ADD CONSTRAINT USERS_DASHBOARD_PK PRIMARY KEY (DASHBOARD_ID)
  USING INDEX   ENABLE;

  ALTER TABLE CRF_QRTZ_FIRED_TRIGGERS ADD CONSTRAINT CRF_QRTZ__8_PK PRIMARY KEY (ENTRY_ID)
  USING INDEX   ENABLE;

  ALTER TABLE REF_DIRECTORY ADD CONSTRAINT REF_DIR_ID_PK PRIMARY KEY (RPT_DIR_ID)
  USING INDEX   ENABLE;

  ALTER TABLE QRTZ_FIRED_TRIGGERS ADD CONSTRAINT QRTZ__8_PK PRIMARY KEY (ENTRY_ID)
  USING INDEX   ENABLE;


  ALTER TABLE QRTZ_SCHEDULER_STATE ADD CONSTRAINT QRTZ__36_PK PRIMARY KEY (INSTANCE_NAME)
  USING INDEX   ENABLE;

  ALTER TABLE DOMAIN ADD CONSTRAINT DOMAINID_PK PRIMARY KEY (DOMAINID)
  USING INDEX   ENABLE;

  ALTER TABLE QRTZ_TRIGGER_LISTENERS ADD CONSTRAINT QRTZ__61_PK PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP, TRIGGER_LISTENER)
  USING INDEX   ENABLE;

  ALTER TABLE REPORT_SEARCH_FIELDS ADD CONSTRAINT REPORT_FIELDID_PK PRIMARY KEY (FIELD_ID)
  USING INDEX   ENABLE;

  ALTER TABLE CRF_QRTZ_SIMPLE_TRIGGERS ADD CONSTRAINT CRF_QRTZ__9_PK PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP)
  USING INDEX   ENABLE;

  ALTER TABLE CRF_QRTZ_LOCKS ADD CONSTRAINT CRF_QRTZ__43_PK PRIMARY KEY (LOCK_NAME)
  USING INDEX   ENABLE;

  ALTER TABLE CRF_QRTZ_PAUSED_TRIGGER_GRPS ADD CONSTRAINT CRF_QRTZ__59_PK PRIMARY KEY (TRIGGER_GROUP)
  USING INDEX   ENABLE;

  ALTER TABLE URL_CONFIG ADD CONSTRAINT URL_CONFIG_PK PRIMARY KEY (URL_ID)
  USING INDEX   ENABLE;

  ALTER TABLE CRF_QRTZ_CRON_TRIGGERS ADD CONSTRAINT CRF_QRTZ__37_PK PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP)
  USING INDEX   ENABLE;

  ALTER TABLE REF_SOURCE_TYPE ADD CONSTRAINT REF_SOURCE_TYPE_PK PRIMARY KEY (REP_SOURCE_ID)
  USING INDEX   ENABLE;

  ALTER TABLE DASHBOARD_COMP ADD CONSTRAINT DASHBOARD_COMP_PK PRIMARY KEY (DASHBOARD_COMP_ID)
  USING INDEX   ENABLE;

  ALTER TABLE REPORT_DOMAIN_DETAILS ADD CONSTRAINT REPORT_DOMAIN_DETAILS_PK PRIMARY KEY (DOMAIN_ID)
  USING INDEX   ENABLE;

  ALTER TABLE LAYOUT_COMPONENT ADD CONSTRAINT LAYOUT_COMPONENT_PK PRIMARY KEY (LAYOUT_COMP_ID)
  USING INDEX   ENABLE;

  ALTER TABLE QRTZ_CRON_TRIGGERS ADD CONSTRAINT QRTZ__37_PK PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP)
  USING INDEX   ENABLE;

  ALTER TABLE SFTPSERVERDETAILS ADD CONSTRAINT PK_CONS_USR_ID_CON_NAME PRIMARY KEY (USERID, CONNECTIONNAME)
  USING INDEX  ENABLE;

  ALTER TABLE QRTZ_SIMPLE_TRIGGERS ADD CONSTRAINT QRTZ__9_PK PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP)
  USING INDEX   ENABLE;

  ALTER TABLE REPORT_STYLE ADD CONSTRAINT REPORT_STYLE_PK PRIMARY KEY (STYLE_ID)
  USING INDEX   ENABLE;

  ALTER TABLE QRTZ_LOCKS ADD CONSTRAINT QRTZ__43_PK PRIMARY KEY (LOCK_NAME)
  USING INDEX   ENABLE;

  ALTER TABLE REP_TEMPLATE_DETAILS ADD CONSTRAINT REP_TEMPLATE_DETAILS_PK PRIMARY KEY (REPORT_TEMPLATE_ID)
  USING INDEX   ENABLE;

  ALTER TABLE CRF_QRTZ_SCHEDULER_STATE ADD CONSTRAINT CRF_QRTZ__36_PK PRIMARY KEY (INSTANCE_NAME)
  USING INDEX   ENABLE;

  ALTER TABLE QRTZ_CALENDARS ADD CONSTRAINT QRTZ__60_PK PRIMARY KEY (CALENDAR_NAME)
  USING INDEX   ENABLE;

  ALTER TABLE ADMIN_USER ADD CONSTRAINT USERID_PK PRIMARY KEY (USERID)
  USING INDEX   ENABLE;

  ALTER TABLE DASHBOARDQUERYRELATION ADD CONSTRAINT DASHBOARDQUERYRELATIONID_PK PRIMARY KEY (DASHBOARDQUERYRELATIONID)
  USING INDEX   ENABLE;

  ALTER TABLE QRTZ_TRIGGERS ADD CONSTRAINT QRTZ__53_PK PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP)
  USING INDEX   ENABLE;

  ALTER TABLE CRF_QRTZ_BLOB_TRIGGERS ADD CONSTRAINT CRF_QRTZ__16_PK PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP)
  USING INDEX   ENABLE;

  ALTER TABLE QRTZ_JOB_LISTENERS ADD CONSTRAINT QRTZ__54_PK PRIMARY KEY (JOB_NAME, JOB_GROUP, JOB_LISTENER)
  USING INDEX   ENABLE;

  ALTER TABLE SUMMARY_DETAILS ADD CONSTRAINT SUMMARY_DETAILS_PK PRIMARY KEY (SUMMARY_ID)
  USING INDEX   ENABLE;

  ALTER TABLE REPORT_HEADER_DETAILS ADD CONSTRAINT REPORT_HEADER_DETAILS_PK PRIMARY KEY (COLUMN_ID)
  USING INDEX   ENABLE;

  ALTER TABLE REPORT_DETAILS ADD CONSTRAINT REPORT_DETAILS_PK PRIMARY KEY (REPORT_ID)
  USING INDEX   ENABLE;

  ALTER TABLE QRTZ_BLOB_TRIGGERS ADD CONSTRAINT QRTZ__16_PK PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP)
  USING INDEX   ENABLE;

  ALTER TABLE QRTZ_JOB_DETAILS ADD CONSTRAINT QRTZ__38_PK PRIMARY KEY (JOB_NAME, JOB_GROUP)
  USING INDEX   ENABLE;

  ALTER TABLE CRF_QRTZ_CALENDARS ADD CONSTRAINT CRF_QRTZ__60_PK PRIMARY KEY (CALENDAR_NAME)
  USING INDEX   ENABLE;

  ALTER TABLE CRF_QRTZ_TRIGGERS ADD CONSTRAINT CRF_QRTZ__53_PK PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP)
  USING INDEX   ENABLE;

  ALTER TABLE CRF_QRTZ_JOB_DETAILS ADD CONSTRAINT CRF_QRTZ__38_PK PRIMARY KEY (JOB_NAME, JOB_GROUP)
  USING INDEX   ENABLE;

  ALTER TABLE SAVE_FILTER_DETAILS ADD PRIMARY KEY (SAVE_FILTER_ID)
  USING INDEX  ENABLE;
  
  
  ALTER TABLE QUERYDETAILS ADD CONSTRAINT USERID_FK1 FOREIGN KEY (USERID)
	  REFERENCES ADMIN_USER (USERID) ENABLE;

  ALTER TABLE REP_VIEW_DETAILS ADD CONSTRAINT REP_VIEW_DETAILS_FK FOREIGN KEY (REPORT_ID)
	  REFERENCES REPORT_DETAILS (REPORT_ID) ENABLE;

  ALTER TABLE CRF_QRTZ_TRIGGER_LISTENERS ADD CONSTRAINT CRF_QRTZ__35_FK FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP)
	  REFERENCES CRF_QRTZ_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP) ENABLE;

  ALTER TABLE CRF_QRTZ_JOB_LISTENERS ADD CONSTRAINT CRF_QRTZ__42_FK FOREIGN KEY (JOB_NAME, JOB_GROUP)
	  REFERENCES CRF_QRTZ_JOB_DETAILS (JOB_NAME, JOB_GROUP) ENABLE;

  ALTER TABLE QRTZ_TRIGGER_LISTENERS ADD CONSTRAINT QRTZ__35_FK FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP)
	  REFERENCES QRTZ_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP) ENABLE;

  ALTER TABLE CRF_QRTZ_SIMPLE_TRIGGERS ADD CONSTRAINT CRF_QRTZ__2_FK FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP)
	  REFERENCES CRF_QRTZ_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP) ENABLE;

  ALTER TABLE DASHBOARD_COMP ADD CONSTRAINT DASHBOARD_COMP_SMRY_DET_FK FOREIGN KEY (SUMMARY_ID)
	  REFERENCES SUMMARY_DETAILS (SUMMARY_ID) ENABLE;

  ALTER TABLE DASHBOARD_COMP ADD CONSTRAINT DASHBOARD_COMP_LAYOUT_FK FOREIGN KEY (LAYOUT_ID)
	  REFERENCES LAYOUT (LAYOUT_ID) ENABLE;

  ALTER TABLE DASHBOARD_COMP ADD CONSTRAINT DASHBOARD_LAYOUT_FK FOREIGN KEY (REL_DASHBOARD_COMP_ID)
	  REFERENCES DASHBOARD_COMP (DASHBOARD_COMP_ID) ENABLE;

  ALTER TABLE DASHBOARD_COMP ADD CONSTRAINT DASHBOARD_USERS_DASHBRD_FK FOREIGN KEY (DASHBOARD_ID)
	  REFERENCES USERS_DASHBOARD (DASHBOARD_ID) ENABLE;

  ALTER TABLE LAYOUT_COMPONENT ADD CONSTRAINT LAYOUT_COMPONENT_FK FOREIGN KEY (REL_LAYOUT_COMP_ID)
	  REFERENCES LAYOUT_COMPONENT (LAYOUT_COMP_ID) ENABLE;

  ALTER TABLE LAYOUT_COMPONENT ADD CONSTRAINT LAYOUT_COMPONENT_LAYOUT_FK FOREIGN KEY (LAYOUT_ID)
	  REFERENCES LAYOUT (LAYOUT_ID) ENABLE;

  ALTER TABLE CRF_QRTZ_CRON_TRIGGERS ADD CONSTRAINT CRF_QRTZ__52_FK FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP)
	  REFERENCES CRF_QRTZ_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP) ENABLE;

  ALTER TABLE QRTZ_SIMPLE_TRIGGERS ADD CONSTRAINT QRTZ__2_FK FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP)
	  REFERENCES QRTZ_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP) ENABLE;

  ALTER TABLE QRTZ_CRON_TRIGGERS ADD CONSTRAINT QRTZ__52_FK FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP)
	  REFERENCES QRTZ_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP) ENABLE;

  ALTER TABLE REP_TEMPLATE_DETAILS ADD CONSTRAINT REP_PG_HEADER_STYLE_FK FOREIGN KEY (PAGE_HEADER)
	  REFERENCES REPORT_STYLE (STYLE_ID) ENABLE;

  ALTER TABLE REP_TEMPLATE_DETAILS ADD CONSTRAINT REP_PG_LAYOUT_STYLE_FK FOREIGN KEY (PAGE_LAYOUT)
	  REFERENCES REPORT_STYLE (STYLE_ID) ENABLE;

  ALTER TABLE REP_TEMPLATE_DETAILS ADD CONSTRAINT REP_COL_FOOTER_STYLE_FK FOREIGN KEY (COLUMN_FOOTER)
	  REFERENCES REPORT_STYLE (STYLE_ID) ENABLE;

  ALTER TABLE REP_TEMPLATE_DETAILS ADD CONSTRAINT REP_DETAIL_STYLE_FK FOREIGN KEY (DETAIL)
	  REFERENCES REPORT_STYLE (STYLE_ID) ENABLE;

  ALTER TABLE REP_TEMPLATE_DETAILS ADD CONSTRAINT REP_PG_FOOTER_STYLE_FK FOREIGN KEY (PAGE_FOOTER)
	  REFERENCES REPORT_STYLE (STYLE_ID) ENABLE;

  ALTER TABLE REP_TEMPLATE_DETAILS ADD CONSTRAINT REP_COL_HEADER_STYLE_FK FOREIGN KEY (COLUMN_HEADER)
	  REFERENCES REPORT_STYLE (STYLE_ID) ENABLE;

  ALTER TABLE DASHBOARDQUERYRELATION ADD CONSTRAINT DASHBOARDID_FK2 FOREIGN KEY (DASHBOARDID)
	  REFERENCES DASHBOARDDETAILS (DASHBOARDID) ENABLE;

  ALTER TABLE REPORT_HEADER_DETAILS ADD CONSTRAINT REP_HDR_DET_QRYDET_FK FOREIGN KEY (QUERYID)
	  REFERENCES QUERYDETAILS (QUERYID) ENABLE;

  ALTER TABLE REPORT_HEADER_DETAILS ADD CONSTRAINT REP_HEADER_DETAILS_FK FOREIGN KEY (REPORT_ID)
	  REFERENCES REPORT_DETAILS (REPORT_ID) ENABLE;

  ALTER TABLE REPORT_HEADER_DETAILS ADD CONSTRAINT REPORT_HDR_OBJ_METADATA_FK FOREIGN KEY (OBJECT_ID)
	  REFERENCES OBJECT_METADATA (OBJECT_ID) ENABLE;

  ALTER TABLE REPORT_HEADER_DETAILS ADD CONSTRAINT REPORT_HEADER_DETAILS_FK FOREIGN KEY (FIELD_ID)
	  REFERENCES REPORT_SEARCH_FIELDS (FIELD_ID) ENABLE;

  ALTER TABLE QRTZ_BLOB_TRIGGERS ADD CONSTRAINT QRTZ__26_FK FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP)
	  REFERENCES QRTZ_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP) ENABLE;

  ALTER TABLE QRTZ_JOB_LISTENERS ADD CONSTRAINT QRTZ__42_FK FOREIGN KEY (JOB_NAME, JOB_GROUP)
	  REFERENCES QRTZ_JOB_DETAILS (JOB_NAME, JOB_GROUP) ENABLE;

  ALTER TABLE SUMMARY_DETAILS ADD CONSTRAINT QUERYID_FK FOREIGN KEY (QUERYID)
	  REFERENCES QUERYDETAILS (QUERYID) ENABLE;

  ALTER TABLE CRF_QRTZ_BLOB_TRIGGERS ADD CONSTRAINT CRF_QRTZ__26_FK FOREIGN KEY (TRIGGER_NAME, TRIGGER_GROUP)
	  REFERENCES CRF_QRTZ_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP) ENABLE;

  ALTER TABLE QRTZ_TRIGGERS ADD CONSTRAINT QRTZ__1_FK FOREIGN KEY (JOB_NAME, JOB_GROUP)
	  REFERENCES QRTZ_JOB_DETAILS (JOB_NAME, JOB_GROUP) ENABLE;

  ALTER TABLE REPORT_DETAILS ADD CONSTRAINT REP_DOMAIN_DETAILS_FK FOREIGN KEY (DOMAIN_ID)
	  REFERENCES REPORT_DOMAIN_DETAILS (DOMAIN_ID) ENABLE;

  ALTER TABLE REPORT_DETAILS ADD CONSTRAINT REP_SOURCE_TYPE_FK FOREIGN KEY (REPORT_SOURCE_ID)
	  REFERENCES REF_SOURCE_TYPE (REP_SOURCE_ID) ENABLE;

  ALTER TABLE REPORT_SEARCH_FIELD_VALUES ADD CONSTRAINT REPSEARCHFIELD_FK FOREIGN KEY (FIELD_ID)
	  REFERENCES REPORT_SEARCH_FIELDS (FIELD_ID) ENABLE;

  ALTER TABLE RPT_DIRECTORY_HIERARCHY ADD CONSTRAINT RPT_DIR_HIER_OBJECTID_FK FOREIGN KEY (OBJECT_ID)
	  REFERENCES OBJECT_METADATA (OBJECT_ID) ENABLE;

  ALTER TABLE RPT_DIRECTORY_HIERARCHY ADD CONSTRAINT RPT_DIR_HIER_REPORTID_FK FOREIGN KEY (REPORT_ID)
	  REFERENCES REPORT_DETAILS (REPORT_ID) ENABLE;

  ALTER TABLE REPORT_DASHBOARD_ASSOC ADD CONSTRAINT REP_USER_ASSOC_FK FOREIGN KEY (REPORT_ID)
	  REFERENCES REPORT_DETAILS (REPORT_ID) ENABLE;

  ALTER TABLE REPORT_DASHBOARD_ASSOC ADD CONSTRAINT REP_USERS_DASHBOARD_FK FOREIGN KEY (DASHBOARD_ID)
	  REFERENCES USERS_DASHBOARD (DASHBOARD_ID) ENABLE;

  ALTER TABLE LAYOUT_USER_ASSOC ADD CONSTRAINT LAYOUT_USER_ASSOC_LAYOUT_FK FOREIGN KEY (LAYOUT_ID)
	  REFERENCES LAYOUT (LAYOUT_ID) ENABLE;

  ALTER TABLE REPORT_PARAM ADD CONSTRAINT REP_PARAM_REP_DETAILS_FK FOREIGN KEY (REPORT_ID)
	  REFERENCES REPORT_DETAILS (REPORT_ID) ENABLE;

  ALTER TABLE METRICS_COMPONENT ADD CONSTRAINT METRICS_COMPONENT_FK FOREIGN KEY (FIELD_ID)
	  REFERENCES REPORT_SEARCH_FIELDS (FIELD_ID) ENABLE;

  ALTER TABLE SCHEDULE_ENTITY_ASSOC ADD CONSTRAINT SCHD_ENT_ASSOC_SCHD_FK FOREIGN KEY (SCHEDULEID)
	  REFERENCES SCHEDULEDETAILS (SCHEDULEID) ENABLE;

  ALTER TABLE REPORT_DETAILS ADD CONSTRAINT REPORT_DETAILS_FK FOREIGN KEY (RELATED_REPORT_ID)
	  REFERENCES REPORT_DETAILS (REPORT_ID) ENABLE;

  ALTER TABLE REPORT_DETAILS ADD CONSTRAINT REP_TEMPLATE_DETAILS_FK FOREIGN KEY (REPORT_TEMPLATE_ID)
	  REFERENCES REP_TEMPLATE_DETAILS (REPORT_TEMPLATE_ID) ENABLE;

  ALTER TABLE CRF_QRTZ_TRIGGERS ADD CONSTRAINT CRF_QRTZ__1_FK FOREIGN KEY (JOB_NAME, JOB_GROUP)
	  REFERENCES CRF_QRTZ_JOB_DETAILS (JOB_NAME, JOB_GROUP) ENABLE;

  ALTER TABLE DASHBOARDUSERRELATION ADD CONSTRAINT USERID_FK2 FOREIGN KEY (USERID)
	  REFERENCES ADMIN_USER (USERID) ENABLE;

  ALTER TABLE DASHBOARDUSERRELATION ADD CONSTRAINT DASHBOARID_FK1 FOREIGN KEY (DASHBOARDID)
	  REFERENCES DASHBOARDDETAILS (DASHBOARDID) ENABLE;

  ALTER TABLE FIELD_DATA_OPERATOR_DETAILS ADD CONSTRAINT FIELDDATAOPERATOR_FIELDID_FK FOREIGN KEY (FIELD_ID)
	  REFERENCES REPORT_SEARCH_FIELDS (FIELD_ID) ENABLE;

--changeset Swetha.H:CRF_DDL_03_02 splitStatements:false
--preconditions onFail:HALT onError:HALT
	  
	  
DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        user_constraints 
    WHERE  
        CONSTRAINT_NAME = 'PAGE_USER_ENTITY_GROUP_PK' ;

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE DASHBOARD_PAGE_ASSOC ADD CONSTRAINT PAGE_USER_ENTITY_GROUP_PK PRIMARY KEY (PAGE_ID,USER_NAME,ENTITY_ID,USER_GROUP_ID)';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Swetha.H:CRF_DDL_03_03 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    l_cnt NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO l_cnt
    FROM
        user_constraints
    WHERE
        constraint_name = 'JOB_EXECUTION_ID_PK';

    IF l_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BATCH_JOB_EXECUTION ADD CONSTRAINT JOB_EXECUTION_ID_PK PRIMARY KEY (JOB_EXECUTION_ID)';
        dbms_output.put_line('Altered');
    ELSE
        dbms_output.put_line('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line('Skipped');
END;


--changeset Swetha.H:CRF_DDL_03_04 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    l_cnt NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO l_cnt
    FROM
        user_constraints
    WHERE
        constraint_name = 'BATCH_JOB_EXECUTION_CONTEXT_PK';

    IF l_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BATCH_JOB_EXECUTION_CONTEXT ADD CONSTRAINT BATCH_JOB_EXECUTION_CONTEXT_PK PRIMARY KEY (JOB_EXECUTION_ID)';
        dbms_output.put_line('Altered');
    ELSE
        dbms_output.put_line('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line('Skipped');
END;


--changeset Swetha.H:CRF_DDL_03_05 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    l_cnt NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO l_cnt
    FROM
        user_constraints
    WHERE
        constraint_name = 'JOB_EXEC_CTX_FK';

    IF l_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BATCH_JOB_EXECUTION_CONTEXT ADD CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID)
	  REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID) ENABLE';
        dbms_output.put_line('Altered');
    ELSE
        dbms_output.put_line('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line('Skipped');
END;


--changeset Swetha.H:CRF_DDL_03_06 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    l_cnt NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO l_cnt
    FROM
        user_constraints
    WHERE
        constraint_name = 'JOB_EXEC_PARAMS_FK';

    IF l_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BATCH_JOB_EXECUTION_PARAMS ADD CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID)
	  REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID) ENABLE';
        dbms_output.put_line('Altered');
    ELSE
        dbms_output.put_line('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line('Skipped');
END;


--changeset Swetha.H:CRF_DDL_03_07 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    l_cnt NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO l_cnt
    FROM
        user_constraints
    WHERE
        constraint_name = 'BATCH_JOB_INSTANCE_PK';

    IF l_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BATCH_JOB_INSTANCE ADD CONSTRAINT BATCH_JOB_INSTANCE_PK PRIMARY KEY (JOB_INSTANCE_ID)';
        dbms_output.put_line('Altered');
    ELSE
        dbms_output.put_line('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line('Skipped');
END;


--changeset Swetha.H:CRF_DDL_03_08 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    l_cnt NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO l_cnt
    FROM
        user_constraints
    WHERE
        constraint_name = 'BATCH_STEP_EXECUTION_PK';

    IF l_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BATCH_STEP_EXECUTION ADD CONSTRAINT BATCH_STEP_EXECUTION_PK PRIMARY KEY (STEP_EXECUTION_ID)';
        dbms_output.put_line('Altered');
    ELSE
        dbms_output.put_line('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line('Skipped');
END;


--changeset Swetha.H:CRF_DDL_03_09 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    l_cnt NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO l_cnt
    FROM
        user_constraints
    WHERE
        constraint_name = 'JOB_EXECUTION_STEP_FK';

    IF l_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BATCH_STEP_EXECUTION ADD CONSTRAINT JOB_EXECUTION_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID)
	  REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID) ENABLE';
        dbms_output.put_line('Altered');
    ELSE
        dbms_output.put_line('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line('Skipped');
END;


--changeset Swetha.H:CRF_DDL_03_10 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    l_cnt NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO l_cnt
    FROM
        user_constraints
    WHERE
        constraint_name = 'BATCH_STEP_EXECUTION_CONTEXT_PK';

    IF l_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BATCH_STEP_EXECUTION_CONTEXT ADD CONSTRAINT BATCH_STEP_EXECUTION_CONTEXT_PK PRIMARY KEY (STEP_EXECUTION_ID)';
        dbms_output.put_line('Altered');
    ELSE
        dbms_output.put_line('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line('Skipped');
END;


--changeset Swetha.H:CRF_DDL_03_11 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    l_cnt NUMBER;
BEGIN
    SELECT
        COUNT(1)
    INTO l_cnt
    FROM
        user_constraints
    WHERE
        constraint_name = 'STEP_EXEC_CTX_FK';

    IF l_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BATCH_STEP_EXECUTION_CONTEXT ADD CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID)
	  REFERENCES BATCH_STEP_EXECUTION (STEP_EXECUTION_ID) ENABLE';
        dbms_output.put_line('Altered');
    ELSE
        dbms_output.put_line('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line('Skipped');
END;