--liquibase formatted sql
--changeset Swetha.H:CRF_DDL_04 
--preconditions onFail:HALT onError:HALT
  

  CREATE INDEX IND_QRTZ24 ON QRTZ_TRIGGERS (NEXT_FIRE_TIME, TRIGGER_STATE) 
  ;



  CREATE INDEX IND_QRTZ6 ON QRTZ_TRIGGERS (IS_VOLATILE) 
  ;

  CREATE INDEX IND_QRTZ14 ON QRTZ_TRIGGERS (TRIGGER_STATE) 
  ;

  CREATE INDEX IND_QRTZ19 ON QRTZ_TRIGGERS (NEXT_FIRE_TIME) 
  ;


  CREATE INDEX IND_CRF_QRTZ12 ON CRF_QRTZ_FIRED_TRIGGERS (JOB_NAME) 
  ;

  CREATE INDEX IND_CRF_QRTZ25 ON CRF_QRTZ_FIRED_TRIGGERS (IS_VOLATILE) 
  ;

  CREATE INDEX IND_CRF_QRTZ16 ON CRF_QRTZ_FIRED_TRIGGERS (IS_STATEFUL) 
  ;

  CREATE INDEX IND_CRF_QRTZ10 ON CRF_QRTZ_FIRED_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP) 
  ;

  CREATE INDEX IND_CRF_QRTZ22 ON CRF_QRTZ_FIRED_TRIGGERS (INSTANCE_NAME) 
  ;



  CREATE INDEX IND_CRF_QRTZ9 ON CRF_QRTZ_FIRED_TRIGGERS (TRIGGER_NAME) 
  ;

  CREATE INDEX IND_CRF_QRTZ15 ON CRF_QRTZ_FIRED_TRIGGERS (TRIGGER_GROUP) 
  ;

  CREATE INDEX IND_CRF_QRTZ13 ON CRF_QRTZ_FIRED_TRIGGERS (REQUESTS_RECOVERY) 
  ;

  CREATE INDEX IND_CRF_QRTZ11 ON CRF_QRTZ_FIRED_TRIGGERS (JOB_GROUP) 
  ;


  CREATE INDEX INX_RSF_REPORT_ID ON REPORT_SEARCH_FIELDS (REPORT_ID) 
  ;

 

  CREATE INDEX IND_QRTZ12 ON QRTZ_FIRED_TRIGGERS (JOB_NAME) 
  ;

  CREATE INDEX IND_QRTZ22 ON QRTZ_FIRED_TRIGGERS (INSTANCE_NAME) 
  ;

  CREATE INDEX IND_QRTZ10 ON QRTZ_FIRED_TRIGGERS (TRIGGER_NAME, TRIGGER_GROUP) 
  ;



  CREATE INDEX IND_QRTZ16 ON QRTZ_FIRED_TRIGGERS (IS_STATEFUL) 
  ;

  CREATE INDEX IND_QRTZ13 ON QRTZ_FIRED_TRIGGERS (REQUESTS_RECOVERY) 
  ;

  CREATE INDEX IND_QRTZ25 ON QRTZ_FIRED_TRIGGERS (IS_VOLATILE) 
  ;

  CREATE INDEX IND_QRTZ11 ON QRTZ_FIRED_TRIGGERS (JOB_GROUP) 
  ;

  CREATE INDEX IND_QRTZ15 ON QRTZ_FIRED_TRIGGERS (TRIGGER_GROUP) 
  ;

  CREATE INDEX IND_QRTZ9 ON QRTZ_FIRED_TRIGGERS (TRIGGER_NAME) 
  ;







  CREATE INDEX IDX_REP_VIEW_REPORT_ID ON REP_VIEW_DETAILS (REPORT_ID) 
  ;


 
  CREATE INDEX IND_CRF_QRTZ17 ON CRF_QRTZ_JOB_DETAILS (REQUESTS_RECOVERY) 
  ;




  CREATE INDEX IND_CRF_QRTZ19 ON CRF_QRTZ_TRIGGERS (NEXT_FIRE_TIME) 
  ;

  CREATE INDEX IND_CRF_QRTZ6 ON CRF_QRTZ_TRIGGERS (IS_VOLATILE) 
  ;

  CREATE INDEX IND_CRF_QRTZ14 ON CRF_QRTZ_TRIGGERS (TRIGGER_STATE) 
  ;

  CREATE INDEX IND_CRF_QRTZ24 ON CRF_QRTZ_TRIGGERS (NEXT_FIRE_TIME, TRIGGER_STATE) 
  ;



  CREATE INDEX IND_QRTZ17 ON QRTZ_JOB_DETAILS (REQUESTS_RECOVERY) 
  ;

 


  CREATE INDEX RPT_DIR_NAME_IX1 ON REF_DIRECTORY (UPPER(RPT_DIR_NAME)) 
  ;
