--liquibase formatted sql
--changeset Swetha.H:GS_AUDITLOG_REPORT_DDL_02_1 
--preconditions onFail:HALT onError:HALT

CREATE TABLE GS_AUDITLOG_REPORTSTATS 
   (	STATID VARCHAR2(30), 
	TYPE CHAR(1), 
	VERSION NUMBER, 
	FLAGS NUMBER, 
	C1 VARCHAR2(30), 
	C2 VARCHAR2(30), 
	C3 VARCHAR2(30), 
	C4 VARCHAR2(30), 
	C5 VARCHAR2(30), 
	N1 NUMBER, 
	N2 NUMBER, 
	N3 NUMBER, 
	N4 NUMBER, 
	N5 NUMBER, 
	N6 NUMBER, 
	N7 NUMBER, 
	N8 NUMBER, 
	N9 NUMBER, 
	N10 NUMBER, 
	N11 NUMBER, 
	N12 NUMBER, 
	D1 DATE, 
	R1 RAW(32), 
	R2 RAW(32), 
	CH1 VARCHAR2(1000), 
	CL1 CLOB
   ) ;

CREATE TABLE DATA_LOG 
   (	LOG_ID NUMBER, 
	LOG_TIME TIMESTAMP (6), 
	LOG_DESCRIPTION VARCHAR2(3000), 
	USER_ID VARCHAR2(100), 
	SYSTEM_IP VARCHAR2(100), 
	ENTITY_TYPE VARCHAR2(200), 
	ENTITY_ID VARCHAR2(50), 
	ENTITY_OLD_VAL VARCHAR2(300), 
	ENTITY_NEW_VAL VARCHAR2(300), 
	VENDOR_ID NUMBER, 
	VENDOR_NAME VARCHAR2(100), 
	OPERATIONS VARCHAR2(50), 
	OPSTATUS VARCHAR2(50)
   ) ;

CREATE TABLE DATA_LOG_ARCHIVAL 
   (	LOG_ID NUMBER, 
	LOG_TIME TIMESTAMP (6), 
	LOG_DESCRIPTION VARCHAR2(3000), 
	USER_ID VARCHAR2(100), 
	SYSTEM_IP VARCHAR2(100), 
	ENTITY_TYPE VARCHAR2(200), 
	ENTITY_ID VARCHAR2(50), 
	ENTITY_OLD_VAL VARCHAR2(300), 
	ENTITY_NEW_VAL VARCHAR2(300), 
	OPERATIONS VARCHAR2(50), 
	OPSTATUS VARCHAR2(50)
   ) ;

CREATE TABLE EVENT_LOG 
   (	LOG_ID NUMBER, 
	LOG_TIME TIMESTAMP (6), 
	LOG_DESCRIPTION VARCHAR2(1000), 
	USER_ID VARCHAR2(200), 
	SYSTEM_IP VARCHAR2(100), 
	EVENT_TYPE VARCHAR2(100), 
	VENDOR_ID NUMBER, 
	VENDOR_NAME VARCHAR2(100), 
	ENTITY_ID NUMBER, 
	OPERATIONS VARCHAR2(50), 
	OPSTATUS VARCHAR2(50)
   ) ;

CREATE TABLE EVENT_LOG_ARCHIVAL 
   (	LOG_ID NUMBER, 
	LOG_TIME TIMESTAMP (6), 
	LOG_DESCRIPTION VARCHAR2(1000), 
	USER_ID VARCHAR2(200), 
	SYSTEM_IP VARCHAR2(100), 
	EVENT_TYPE VARCHAR2(100), 
	OPERATIONS VARCHAR2(50), 
	OPSTATUS VARCHAR2(50)
   ) ;

CREATE TABLE DATA_LOG_REPORTS(
LOG_ID                NUMBER ,        
LOG_TIME              TIMESTAMP(6),   
LOG_DESCRIPTION       VARCHAR2(3000), 
USER_ID               VARCHAR2(100)  ,
SYSTEM_IP             VARCHAR2(100)  ,
ENTITY_TYPE           VARCHAR2(200)  ,
ENTITY_ID             VARCHAR2(50)   ,
ENTITY_OLD_VAL        VARCHAR2(300)  ,
ENTITY_NEW_VAL        VARCHAR2(300)  ,
VENDOR_ID             NUMBER         ,
VENDOR_NAME           VARCHAR2(100)  ,
SOURCE                VARCHAR2(100)  ,
APPLICATION_ID        NUMBER         ,
CREATED_DATE          TIMESTAMP(6)   ,
CREATED_BY            VARCHAR2(255)  ,
MODIFIED_BY           VARCHAR2(255)  ,
MODIFIED_DATE         TIMESTAMP(6) );


CREATE TABLE EVENT_LOG_REPORTS (
LOG_ID                NUMBER,         
LOG_TIME              TIMESTAMP(6) ,  
LOG_DESCRIPTION       VARCHAR2(1000), 
USER_ID               VARCHAR2(200)  ,
SYSTEM_IP             VARCHAR2(100)  ,
EVENT_TYPE            VARCHAR2(100)  ,
VENDOR_ID             NUMBER         ,
VENDOR_NAME           VARCHAR2(100)  ,
ENTITY_ID             NUMBER         ,
SOURCE                VARCHAR2(100)  ,
APPLICATION_ID        NUMBER         ,
CREATED_DATE          TIMESTAMP(6)   ,
CREATED_BY            VARCHAR2(255)  ,
MODIFIED_BY           VARCHAR2(255)  ,
MODIFIED_DATE         TIMESTAMP(6) );  
