--liquibase formatted sql
--changeset Swetha.H:CA_DDL_02 
--preconditions onFail:HALT onError:HALT

  CREATE TABLE AUTHORITY_AUTH 
   (	ID NUMBER, 
	NAME VARCHAR2(2000)
   ) ;

  CREATE TABLE C63 
   (	USERID VARCHAR2(256), 
	CLIENTID VARCHAR2(256), 
	SCOPE VARCHAR2(256), 
	STATUS VARCHAR2(10), 
	EXPIRESAT TIMESTAMP (6), 
	LASTMODIFIEDAT TIMESTAMP (6)
   ) ;

  
  CREATE TABLE OAUTH_ACCESS_TOKEN 
   (	TOKEN_ID VARCHAR2(256), 
	TOKEN BLOB, 
	AUTHENTICATION_ID VARCHAR2(256), 
	USER_NAME VARCHAR2(256), 
	CLIENT_ID VARCHAR2(256), 
	AUTHENTICATION BLOB, 
	REFRESH_TOKEN VARCHAR2(256)
   ) ;


  CREATE TABLE OAUTH_CLIENT_TOKEN 
   (	TOKEN_ID VARCHAR2(256), 
	TOKEN BLOB, 
	AUTHENTICATION_ID VARCHAR2(256), 
	USER_NAME VARCHAR2(256), 
	CLIENT_ID VARCHAR2(256)
   ) ;

  CREATE TABLE OAUTH_CODE 
   (	CODE VARCHAR2(256), 
	AUTHENTICATION BLOB
   ) ;

  CREATE TABLE OAUTH_REFRESH_TOKEN 
   (	TOKEN_ID VARCHAR2(256), 
	TOKEN BLOB, 
	AUTHENTICATION BLOB
   ) ;

  CREATE TABLE USERS_AUTH 
   (	ID NUMBER, 
	USER_NAME VARCHAR2(2000), 
	FIRST_NAME VARCHAR2(2000), 
	LAST_NAME VARCHAR2(2000), 
	EMAIL VARCHAR2(2000), 
	PASSWORD VARCHAR2(2000)
   ) ;
   

--changeset Swetha.H:CA_DDL_02_02 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TABLES
    WHERE  
        TABLE_NAME = 'OAUTH_CLIENT_DETAILS';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE q'<CREATE TABLE OAUTH_CLIENT_DETAILS 
   (	CLIENT_ID VARCHAR2(2000), 
	RESOURCE_IDS VARCHAR2(2000) DEFAULT 'framework-aurthorization', 
	CLIENT_SECRET VARCHAR2(2000), 
	SCOPE VARCHAR2(2000), 
	AUTHORIZED_GRANT_TYPES VARCHAR2(2000) DEFAULT 'client_credentials', 
	WEB_SERVER_REDIRECT_URI VARCHAR2(2000), 
	AUTHORITIES VARCHAR2(2000), 
	ACCESS_TOKEN_VALIDITY NUMBER DEFAULT 120, 
	REFRESH_TOKEN_VALIDITY NUMBER DEFAULT 180, 
	ADDITIONAL_INFORMATION VARCHAR2(2000), 
	AUTOAPPROVE VARCHAR2(2000), 
	CLIENT_NAME VARCHAR2(500), 
	PARTNER_NAME VARCHAR2(500), 
	CREATED_BY VARCHAR2(200), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(200), 
	MODIFIED_DATE TIMESTAMP (6), 
	USER_STATUS VARCHAR2(200)
   )>';
		DBMS_OUTPUT.PUT_LINE('Created');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;