--liquibase formatted sql
--changeset Swetha.H:CA_DDL_01 
--preconditions onFail:HALT onError:HALT

  ALTER TABLE OAUTH_ACCESS_TOKEN ADD CONSTRAINT AUTHENTICATIONID_PK PRIMARY KEY (AUTHENTICATION_ID)
  USING INDEX  ENABLE;

  ALTER TABLE OAUTH_CLIENT_TOKEN ADD CONSTRAINT AUTHENTICATION_PK PRIMARY KEY (AUTHENTICATION_ID)
  USING INDEX  ENABLE;

  