--liquibase formatted sql
--changeset Swetha.H:NOTES_DDL_02
--preconditions onFail:HALT onError:HALT


  CREATE TABLE ALERT_TYPE 
   (	ALERT_TYPE_ID NUMBER, 
	NAME VARCHAR2(30), 
	DESCRIPTION VARCHAR2(100)
   ) ;

  CREATE TABLE CM_NOTESSTATS 
   (	STATID VARCHAR2(30), 
	TYPE CHAR(1), 
	VERSION NUMBER, 
	FLAGS NUMBER, 
	C1 VARCHAR2(30), 
	C2 VARCHAR2(30), 
	C3 VARCHAR2(30), 
	C4 VARCHAR2(30), 
	C5 VARCHAR2(30), 
	N1 NUMBER, 
	N2 NUMBER, 
	N3 NUMBER, 
	N4 NUMBER, 
	N5 NUMBER, 
	N6 NUMBER, 
	N7 NUMBER, 
	N8 NUMBER, 
	N9 NUMBER, 
	N10 NUMBER, 
	N11 NUMBER, 
	N12 NUMBER, 
	D1 DATE, 
	R1 RAW(32), 
	R2 RAW(32), 
	CH1 VARCHAR2(1000), 
	CL1 CLOB
   ) ;

  
  CREATE TABLE DR$NOTE_CONTENT_IDX$I 
   (	TOKEN_TEXT VARCHAR2(64), 
	TOKEN_TYPE NUMBER(10,0), 
	TOKEN_FIRST NUMBER(10,0), 
	TOKEN_LAST NUMBER(10,0), 
	TOKEN_COUNT NUMBER(10,0), 
	TOKEN_INFO BLOB
   ) ;

  CREATE TABLE DR$NOTE_CONTENT_IDX$K 
   (	DOCID NUMBER(38,0), 
	TEXTKEY ROWID
   ) ;

  CREATE TABLE DR$NOTE_CONTENT_IDX$N 
   (	NLT_DOCID NUMBER(38,0), 
	NLT_MARK CHAR(1)
   ) ;

  CREATE TABLE DR$NOTE_CONTENT_IDX$R 
   (	ROW_NO NUMBER(3,0), 
	DATA BLOB
   ) ;

  CREATE TABLE FOLLOWUP_STATUS 
   (	FOLLOWUP_STATUS_ID NUMBER, 
	NAME VARCHAR2(30), 
	DESCRIPTION VARCHAR2(100)
   ) ;

  CREATE TABLE FOLLOWUP_TYPE 
   (	FOLLOWUP_TYPE_ID NUMBER, 
	NAME VARCHAR2(30), 
	DESCRIPTION VARCHAR2(100)
   ) ;

  CREATE TABLE NOTE 
   (	ID NUMBER, 
	VERSIONID NUMBER DEFAULT null, 
	ENTITY_TYPE_ID NUMBER, 
	ENTITY_ID NUMBER, 
	ENTITY_NAME VARCHAR2(250), 
	NOTE_DESCRIPTION VARCHAR2(4000), 
	APPLICATION_ID NUMBER(30,0), 
	CREATED_BY VARCHAR2(30), 
	CREATED_DATE TIMESTAMP (0) WITH TIME ZONE, 
	MODIFIED_BY VARCHAR2(30), 
	MODIFIED_DATE TIMESTAMP (0) WITH TIME ZONE, 
	START_DATE TIMESTAMP (6) WITH TIME ZONE, 
	END_DATE TIMESTAMP (6) WITH TIME ZONE, 
	IS_SYSTEM_DEFINED CHAR(1), 
	NOTE_LEVEL VARCHAR2(200), 
	EXTERNAL_ID1 VARCHAR2(100), 
	EXTERNAL_ID2 VARCHAR2(100), 
	EXTERNAL_ID3 VARCHAR2(100), 
	NOTE_TYPE VARCHAR2(100), 
	CUSTOMERID NUMBER, 
	NOTE_CONTENT CLOB, 
	NOTE_TEMPLATE_ID NUMBER, 
	ENTITY_VER NUMBER, 
	TAG VARCHAR2(250), 
	PARENT_ID NUMBER, 
	TITLE VARCHAR2(250), 
	NOTE_TEMPLATE VARCHAR2(250), 
	NOTE_ENTERED_BY VARCHAR2(250), 
	NOTE_IN_AT_SOURCE VARCHAR2(250), 
	ATTACHMENT_MODE VARCHAR2(250), 
	EMAIL VARCHAR2(250), 
	ATTACHMENT_FILE VARCHAR2(4000), 
	SEARCH VARCHAR2(250), 
	SETUP_FOLLOW_UP VARCHAR2(250), 
	DROP_DOCUMENT_HERE VARCHAR2(250), 
	ATTACH_DOCUMENT_TO_NOTE VARCHAR2(250), 
	ENTER_OR_UPDATE_A_NOTE VARCHAR2(250), 
	ATTACHMENT_TYPE VARCHAR2(250), 
	ATTACH_SIZE VARCHAR2(250), 
	ATTACH_TEXT_OR_EMAIL_NOTE VARCHAR2(250), 
	NOTE_BROWSE VARCHAR2(50), 
	NOTE_ADD VARCHAR2(50), 
	NOTE_DELETE VARCHAR2(50)
	-- CONSTRAINT NOTE_NOTE_ENTITY_TYPE_FK FOREIGN KEY (ENTITY_TYPE_ID)
	 -- REFERENCES NOTE_ENTITY_TYPE (ENTITY_TYPE_ID) ENABLE, 
	-- CONSTRAINT NOTE_TEMPLATE_FK FOREIGN KEY (NOTE_TEMPLATE_ID)
	--  REFERENCES TEMPLATE (TEMPLATE_ID) ENABLE
   ) ;


  CREATE TABLE NOTE_ENTITY_TYPE 
   (	ENTITY_TYPE_ID NUMBER, 
	ENTITY_TYPE VARCHAR2(25), 
	ENTITY_DESC VARCHAR2(50)
   ) ;

  CREATE TABLE NOTE_FOLLOWUP 
   (	NOTE_FOLLOWUP_ID NUMBER, 
	DATETIME TIMESTAMP (6), 
	ALERT_TYPE_ID NUMBER, 
	VERSIONID NUMBER, 
	FOLLOWUP_STATUS_ID NUMBER, 
	DESCRIPTION VARCHAR2(100), 
	FOLLOW_UP_NAME VARCHAR2(4000), 
	FU_OWNER VARCHAR2(100), 
	FOLLOW_UP_PRIORITY VARCHAR2(100), 
	FOLLOW_UP_ACTION VARCHAR2(500), 
	ENTITY_TYPE_ID NUMBER, 
	ENTITY_ID NUMBER, 
	ENTITY_VER NUMBER, 
	FOLLOW_UP_DATE DATE, 
	CREATED_BY VARCHAR2(30), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(30), 
	MODIFIED_DATE TIMESTAMP (6), 
	TAG VARCHAR2(250), 
	ENTITY_NAME VARCHAR2(100), 
	FOLLOW_UP_ID NUMBER, 
	FOLLOW_UP_TEMPLATE VARCHAR2(100), 
	NOTE_IN_AT_SOURCE VARCHAR2(100), 
	SEQUENCE NUMBER, 
	FOLLOW_UP_BY VARCHAR2(100), 
	FOLLOW_UP_DISTRIBUTION_LIST VARCHAR2(100), 
	NOTE_ENTERED_BY VARCHAR2(100), 
	FOLLOW_UP_EMAIL_DIST_LIST VARCHAR2(100), 
	TITLE VARCHAR2(50), 
	ENTER_OR_UPDATE_FOLLOW_UP VARCHAR2(100), 
	SEARCH VARCHAR2(100), 
	DROP_DOCUMENT_HERE VARCHAR2(100), 
	ATTACHMENT_MODE VARCHAR2(1001), 
	ATTACH_SIZE VARCHAR2(100), 
	ATTACH_TYPE VARCHAR2(100), 
	ATTACH_DOCUMENT_FOLLOW_UP VARCHAR2(100), 
	MANAGE_FOLLOW_UP VARCHAR2(100), 
	FOLLOWUP_TYPE VARCHAR2(250), 
	ATTACH_TEXT_OR_EMAIL_FOLLOWUP VARCHAR2(250), 
	NOTE_BROWSE VARCHAR2(50), 
	NOTE_ADD VARCHAR2(50), 
	NOTE_DELETE VARCHAR2(50), 
	ATTACHMENT_FILE VARCHAR2(4000) 
	-- CONSTRAINT NOTEFP_FPSTATUS_FK4 FOREIGN KEY (FOLLOWUP_STATUS_ID)
	 -- REFERENCES FOLLOWUP_STATUS (FOLLOWUP_STATUS_ID) DISABLE
   ) ;

  CREATE TABLE NOTE_FOLLOWUP_USERS 
   (	NOTE_FOLLOWUP_ID NUMBER, 
	VERSIONID NUMBER, 
	USER_ID NUMBER(38,0), 
	NOTE_FOLLOWUP_USER_STATUSID NUMBER, 
	USER_GROUP_ID NUMBER, 
	CREATED_DATE DATE, 
	CREATED_BY VARCHAR2(50), 
	MODIFIED_DATE DATE, 
	MODIFIED_BY VARCHAR2(50)
   ) ;

  CREATE TABLE NOTE_FOLLOWUP_USER_STATUS 
   (	NOTE_FOLLOWUP_USER_STATUSID NUMBER, 
	NAME VARCHAR2(300), 
	DESCRIPTION VARCHAR2(500), 
	CREATED_DATE DATE, 
	CREATED_BY VARCHAR2(50), 
	MODIFIED_DATE DATE, 
	MODIFIED_BY VARCHAR2(50)
   ) ;

  CREATE TABLE NOTE_TEMP 
   (	NOTE_ID NUMBER, 
	VERSIONID NUMBER, 
	ENTITY_TYPE_ID NUMBER, 
	ENTITY_ID NUMBER, 
	NOTE_NAME VARCHAR2(250), 
	NOTE_DESCRIPTION VARCHAR2(4000), 
	APPLICATION_ID NUMBER(30,0), 
	CREATED_BY VARCHAR2(30), 
	CREATED_DATE TIMESTAMP (0) WITH TIME ZONE, 
	MODIFIED_BY VARCHAR2(30), 
	MODIFIED_DATE TIMESTAMP (0) WITH TIME ZONE, 
	START_DATE TIMESTAMP (6) WITH TIME ZONE, 
	END_DATE TIMESTAMP (6) WITH TIME ZONE, 
	IS_SYSTEM_DEFINED CHAR(1), 
	NOTE_LEVEL VARCHAR2(200), 
	EXTERNAL_ID1 VARCHAR2(100), 
	EXTERNAL_ID2 VARCHAR2(100), 
	EXTERNAL_ID3 VARCHAR2(100), 
	NOTE_TYPE VARCHAR2(100), 
	CUSTOMERID NUMBER, 
	NOTE_CONTENT CLOB, 
	NOTE_TEMPLATE_ID NUMBER, 
	ENTITY_VER NUMBER, 
	TAG VARCHAR2(250)
   ) ;

  CREATE TABLE SITE_NOTE_ASSOC 
   (	SITE_ORDER_ID NUMBER, 
	NOTE_ID NUMBER, 
	UPDATE_FLAG VARCHAR2(5), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(255), 
	MODIFIED_BY VARCHAR2(255), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

  CREATE TABLE TEMPLATE 
   (	TEMPLATE_ID NUMBER, 
	TEMPLATE_NAME VARCHAR2(100), 
	TEMPLATE_TYPE VARCHAR2(30), 
	TEMPLATE_LOCATION VARCHAR2(200), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(255), 
	MODIFIED_BY VARCHAR2(255), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;
  
  

--changeset Vijaysree.S:NOTES_DDL_02_02 splitStatements:false
--preconditions onFail:HALT onError:HALT
  
DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TAB_COLUMNS 
    WHERE  
        TABLE_NAME = 'NOTE_FOLLOWUP' 
	AND
	    COLUMN_NAME in ('FOLLOW_UP_EVENT','FOLLOW_UP_START_TIME','FOLLOW_UP_END_TIME','FOLLOW_UP_FREQUENCY','FOLLOW_UP_EVENT_DATE',
                        'EVERY','EVERY_WEEKDAY','DAYS','REMAINDER_TIME','PROJECT_START_DATE','PROJECT_END_DATE','FREQUENCY',
                        'YEARLY_AND_OF_EVERY','YEARLY_AND_MONTHS','MONTHLY_DAY','MONTHLY_OF_EVERY','MONTHLY_MONTHS','MONTHLY_THE',
                        'MONTHLY_WEEK','MONTHLY_DAYS','MONTHLY_AND_OF_EVERY','MONTHLY_AND_MONTHS','WEEKLY_RECURE_EVERY','WEEKLY_WEEKS_ON',
                        'WEEKLY_DAYS','YEARLY_RECURE_EVERY','YEARLY_YEARS','YEARLY_ON','YEARLY_MONTHS','YEARLY_DAYS','YEARLY_ON_THE','YEARLY_WEEK',
                        'YEARLY_AND_DAYS','ATTACHMENT_TYPE','FOLLOW_UP_START_DATE','FOLLOW_UP_END_DATE','STATUS','ASSIGNED_TO');

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE NOTE_FOLLOWUP ADD ( 
FOLLOW_UP_EVENT                     VARCHAR2(50)  , 
FOLLOW_UP_START_TIME                TIMESTAMP(6)  , 
FOLLOW_UP_END_TIME                  TIMESTAMP(6)  , 
FOLLOW_UP_FREQUENCY                 VARCHAR2(50)  , 
FOLLOW_UP_EVENT_DATE                TIMESTAMP(6)  , 
EVERY                               VARCHAR2(100) , 
EVERY_WEEKDAY                       VARCHAR2(100) , 
DAYS                                VARCHAR2(100) , 
REMAINDER_TIME                      VARCHAR2(100) , 
PROJECT_START_DATE                  TIMESTAMP(6)  , 
PROJECT_END_DATE                    TIMESTAMP(6)  , 
FREQUENCY                           VARCHAR2(100) , 
YEARLY_AND_OF_EVERY                 VARCHAR2(100) , 
YEARLY_AND_MONTHS                   VARCHAR2(100) , 
MONTHLY_DAY                         VARCHAR2(100) , 
MONTHLY_OF_EVERY                    VARCHAR2(100) , 
MONTHLY_MONTHS                      VARCHAR2(100) , 
MONTHLY_THE                         VARCHAR2(100) , 
MONTHLY_WEEK                        VARCHAR2(100) , 
MONTHLY_DAYS                        VARCHAR2(100) , 
MONTHLY_AND_OF_EVERY                VARCHAR2(100) , 
MONTHLY_AND_MONTHS                  VARCHAR2(100) , 
WEEKLY_RECURE_EVERY                 VARCHAR2(100) , 
WEEKLY_WEEKS_ON                     VARCHAR2(100) , 
WEEKLY_DAYS                         VARCHAR2(100) , 
YEARLY_RECURE_EVERY                 VARCHAR2(100) , 
YEARLY_YEARS                        VARCHAR2(100) , 
YEARLY_ON                           VARCHAR2(100) , 
YEARLY_MONTHS                       VARCHAR2(100) , 
YEARLY_DAYS                         VARCHAR2(100) , 
YEARLY_ON_THE                       VARCHAR2(100) , 
YEARLY_WEEK                         VARCHAR2(100) , 
YEARLY_AND_DAYS                     VARCHAR2(100) , 
ATTACHMENT_TYPE                     VARCHAR2(100) , 
FOLLOW_UP_START_DATE                DATE          , 
FOLLOW_UP_END_DATE                  DATE          , 
STATUS                              VARCHAR2(100) , 
ASSIGNED_TO                         VARCHAR2(100) )' ;

        DBMS_OUTPUT.PUT_LINE('ALTERED');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ALREADY EXIST');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SKIPPED');
END;


--changeset Vijaysree.S:NOTES_DDL_02_03 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TAB_COLUMNS
    WHERE  
        TABLE_NAME = 'NOTE'
        AND COLUMN_NAME IN ( 'TASK_NAME','TASK_ID');

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE NOTE ADD (
    TASK_NAME VARCHAR2(100),
    TASK_ID   NUMBER)';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:NOTES_DDL_02_04 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TAB_COLUMNS
    WHERE  
        TABLE_NAME = 'NOTE'
        AND COLUMN_NAME IN ( 'STATUS');

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE NOTE ADD STATUS VARCHAR2(100)';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;