--liquibase formatted sql
--changeset Swetha.H:NOTES_DDL_03
--preconditions onFail:HALT onError:HALT


  ALTER TABLE DR$NOTE_CONTENT_IDX$K ADD PRIMARY KEY (TEXTKEY)
  USING INDEX  ENABLE;

  ALTER TABLE NOTE ADD CONSTRAINT NOTE_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE;

  ALTER TABLE NOTE_FOLLOWUP_USER_STATUS ADD CONSTRAINT NOTE_FOLLOWUP_USER_ST_PK PRIMARY KEY (NOTE_FOLLOWUP_USER_STATUSID)
  USING INDEX  ENABLE;

  ALTER TABLE TEMPLATE ADD CONSTRAINT EMAIL_TEMPLATES_PK PRIMARY KEY (TEMPLATE_ID)
  USING INDEX  ENABLE;

  ALTER TABLE FOLLOWUP_STATUS ADD CONSTRAINT PK_FOLLOWUP_STATUS_ID PRIMARY KEY (FOLLOWUP_STATUS_ID)
  USING INDEX   ENABLE;

  ALTER TABLE NOTE_ENTITY_TYPE ADD CONSTRAINT ENTITY_TYPE_PK PRIMARY KEY (ENTITY_TYPE_ID)
  USING INDEX  ENABLE;

  ALTER TABLE DR$NOTE_CONTENT_IDX$N ADD PRIMARY KEY (NLT_DOCID)
  USING INDEX  ENABLE;

  ALTER TABLE FOLLOWUP_TYPE ADD CONSTRAINT PK_FOLLOWUPTYPE_ID PRIMARY KEY (FOLLOWUP_TYPE_ID)
  USING INDEX   ENABLE;


  ALTER TABLE NOTE_FOLLOWUP ADD CONSTRAINT NOTE_FOLLOWUP_CPK PRIMARY KEY (NOTE_FOLLOWUP_ID) DISABLE;
  
  
  ALTER TABLE NOTE ADD CONSTRAINT NOTE_NOTE_ENTITY_TYPE_FK FOREIGN KEY (ENTITY_TYPE_ID)
	  REFERENCES NOTE_ENTITY_TYPE (ENTITY_TYPE_ID) ENABLE;

  ALTER TABLE NOTE ADD CONSTRAINT NOTE_TEMPLATE_FK FOREIGN KEY (NOTE_TEMPLATE_ID)
	  REFERENCES TEMPLATE (TEMPLATE_ID) ENABLE;

  ALTER TABLE NOTE_FOLLOWUP ADD CONSTRAINT NOTEFP_FPSTATUS_FK4 FOREIGN KEY (FOLLOWUP_STATUS_ID)
	  REFERENCES FOLLOWUP_STATUS (FOLLOWUP_STATUS_ID) DISABLE;
	  