--liquibase formatted sql
--changeset Swetha.H:NOTES_DDL_04
--preconditions onFail:HALT onError:HALT


  CREATE INDEX DR$NOTE_CONTENT_IDX$X ON DR$NOTE_CONTENT_IDX$I (TOKEN_TEXT, TOKEN_TYPE, TOKEN_FIRST, TOKEN_LAST, TOKEN_COUNT) 
  ;


  CREATE INDEX NOTE_ENTITY_ID ON NOTE (ENTITY_ID) 
  ;

  CREATE INDEX NOTE_DESCRIPTION_IDX ON NOTE (NOTE_DESCRIPTION) 
  ;

  CREATE INDEX NOTE_ENTITY_TYPE_ID ON NOTE (ENTITY_TYPE_ID) 
  ;

  CREATE INDEX NOTE_ENTITY_TYP_ID_IDX ON NOTE (ENTITY_TYPE_ID, ENTITY_ID) 
  ;

  CREATE INDEX NOTE_TAG ON NOTE (TAG) 
  ;


  CREATE INDEX CM_NOTESSTATS ON CM_NOTESSTATS (STATID, TYPE, C5, C1, C2, C3, C4, VERSION) 
  ;

  CREATE UNIQUE INDEX IDX_ALERT_TYPE_ID ON ALERT_TYPE (ALERT_TYPE_ID) 
  ;

  CREATE INDEX IDX_NOTE_CREATEBY ON NOTE (UPPER(CREATED_BY)) 
  ;

  CREATE INDEX IDX_NOTE_STARTDATE ON NOTE (TRUNC(START_DATE)) 
  ;

  CREATE INDEX NOTE_TAG_FUNC_IDX ON NOTE (UPPER(TAG)) 
  ;

  CREATE INDEX NOTE_DESCRIPTION_FUNC_IDX ON NOTE (UPPER(NOTE_DESCRIPTION)) 
  ;

  CREATE INDEX IDX_FOLLOWUP_STATUS_NAME ON FOLLOWUP_STATUS (UPPER(NAME)) 
  ;

  CREATE INDEX IDX_NOTE_FOLLOWUP_DATETIME ON NOTE_FOLLOWUP (TRUNC(DATETIME)) 
  ;

  CREATE INDEX IDX_NOTE_MODIFIEDBY ON NOTE (UPPER(MODIFIED_BY)) 
  ;

  CREATE INDEX IDX_NOTE_ENDDATE ON NOTE (TRUNC(END_DATE)) 
  ;