--liquibase formatted sql
--changeset Vijaysree.S:APPCATALOG_DDL_02 splitStatements:true
--preconditions onFail:HALT onError:HALT

CREATE TABLE ACTION_INPUT_PARAMETER 
   (	ACTION_SPEC_ID NUMBER, 
	ENTITY_ID NUMBER, 
	GRANDFATHERED VARCHAR2(50), 
	ENTITY_TYPE VARCHAR2(250), 
	ACTION_INPUT_PARAM_ID NUMBER DEFAULT ACTION_INPUT_PARAM_ID_SEQ.NEXTVAL, 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE ARCHIVAL_PKG_CONFIG 
   (	INSTANCE_CONFIG_NAME VARCHAR2(200), 
	INSTANCE_CONFIG_VALUE VARCHAR2(4000), 
	INSTANCE_CONFIG_VARIABLE VARCHAR2(250), 
	INSTANCE_CONFIG_TYPE VARCHAR2(250), 
	INSTANCE_ARGUMENT_TYPE VARCHAR2(100), 
	PKG_PROC_NAME VARCHAR2(100), 
	CONFIGURATION_TYPE VARCHAR2(100), 
	SCHEMA_NAME VARCHAR2(100)
   ) ;

CREATE TABLE ARCHIVAL_TABLE_CONFIG 
   (	INSTANCE_TABLE_ID NUMBER, 
	INSTANCE_TABLE_NAME VARCHAR2(200), 
	INSTANCE_TABLE_ALIAS_NAME VARCHAR2(100), 
	INSTANCE_TABLE_SEQ NUMBER, 
	INSTANCE_TABLE_DELETE_SEQ NUMBER, 
	INSTANCE_FETCH_QUERY CLOB, 
	IS_ACTIVE VARCHAR2(1), 
	INSTANCE_QUERY_TYPE VARCHAR2(4000), 
	CONDITION_COLUMN VARCHAR2(4000), 
	SCHEMA_NAME VARCHAR2(20), 
	ARCHIVE_TABLE_NAME VARCHAR2(50), 
	IS_PURGE VARCHAR2(1)
   ) ;

CREATE TABLE BUSINESS_ENTITY 
   (	BID NUMBER, 
	BUSINESS_ENTITY_NAME VARCHAR2(100), 
	VERSION NUMBER, 
	LIFECYCLE_ID NUMBER, 
	DISPLAY_NAME VARCHAR2(100), 
	START_DATE TIMESTAMP (6), 
	END_DATE TIMESTAMP (6), 
	ENTITY_TYPE VARCHAR2(100), 
	ICON VARCHAR2(200), 
	ENTITY_GROUP VARCHAR2(100), 
	LOCATION_SELECTION VARCHAR2(100), 
	ACCESS_SELECTION VARCHAR2(100), 
	DATA_SOURCE_TYPE VARCHAR2(100), 
	DATA_SOURCE_NAME VARCHAR2(100), 
	OBJECT_URL VARCHAR2(1000), 
	DOMAIN_TYPE VARCHAR2(50), 
	GLOBALLY_AVAILABLE VARCHAR2(100), 
	PRODUCT_TYPE VARCHAR2(25), 
	GRANDFATHERED VARCHAR2(50), 
	DESCRIPTION VARCHAR2(250), 
	IMAGE_URL VARCHAR2(250), 
	EFFECTIVE_START_DATE TIMESTAMP (6), 
	EFFECTIVE_END_DATE TIMESTAMP (6), 
	MIN_VALUE NUMBER, 
	MAX_VALUE NUMBER, 
	SEQUENCE NUMBER, 
	GROUP_TYPE VARCHAR2(200), 
	IS_FORM_REQ VARCHAR2(10), 
	PARTY_NAME VARCHAR2(500), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	EXPORT_IDENTIFIER VARCHAR2(200), 
	REPORTING_TABLE VARCHAR2(100), 
	CATALOG_ENTITY_GROUP NUMBER, 
	CONTRACT_ID NUMBER,
	SAVE_ENTITY_TYPE VARCHAR2(100),
	SAVE_ENTITY_NAME VARCHAR2(100)
   )  ENABLE ROW MOVEMENT ;

CREATE TABLE BUSINESS_ENTITY_DETERMINANTS 
   (	BUSINESS_ENTITY_DET_ID NUMBER, 
	BID NUMBER, 
	ENTITY_NAME VARCHAR2(500), 
	DETERMINANT_TYPE VARCHAR2(100), 
	DETERMINANT_VALUE VARCHAR2(100), 
	LEAD_TIME TIMESTAMP (6)
   ) ;

CREATE TABLE BUSINESS_ENTITY_PARAMETER 
   (	RECORD_KEY_PARAM NUMBER, 
	ENTITY VARCHAR2(200), 
	VERSION_NO NUMBER, 
	PARENT_ID NUMBER, 
	NAME VARCHAR2(100), 
	PARAMETER_SPEC_ID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	GRANDFATHERED VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE BUSINESS_ENTITY_RELATION 
   (	PARENT_ID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	VERSION NUMBER, 
	CHILD_ID NUMBER, 
	RULE_FLAG VARCHAR2(25), 
	GRANDFATHERED VARCHAR2(50), 
	BUSINESS_RELATION_ID NUMBER, 
	BUSINESS_ENTITY_REL_ID NUMBER DEFAULT BUSINESS_ENTITY_REL_ID_SEQ.NEXTVAL, 
	ROOT_ID NUMBER, 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	CHILD_SPEC_SUB_TYPE VARCHAR2(30), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE BUSINESS_ENTITY_SPECIFICATION 
   (	BUSINESS_ENTITY_SPEC_ID NUMBER DEFAULT BUSINESS_ENTITY_SPEC_ID_SEQ.NEXTVAL, 
	ENTITY_ID NUMBER, 
	PARENT_ENTITY_ID NUMBER, 
	ROOT_ID NUMBER, 
	RELATED_ENTITY_ID NUMBER, 
	ENTITY_RELATIONSHIP VARCHAR2(100), 
	ENTITY_MAPPING_ID NUMBER, 
	EXPORT_IDENTIFIER VARCHAR2(200), 
	ENTITY_ASSOCIATION_TYPE VARCHAR2(100), 
	MIN_VALUE VARCHAR2(100), 
	MAX_VALUE VARCHAR2(100), 
	ENTITY_REQUIREMENT_TYPE VARCHAR2(100), 
	ENTITY_DATA_TYPE VARCHAR2(100), 
	ENTITY_DATA_SOURCE_TYPE VARCHAR2(100), 
	ENTITY_DATA_SOURCE_NAME VARCHAR2(100), 
	ENTITY_DATA_SOURCE_MAPPING VARCHAR2(100), 
	REPORTING_TABLE VARCHAR2(100), 
	DATA_SOURCE_TYPE VARCHAR2(100), 
	DATA_SOURCE_NAME VARCHAR2(100), 
	RELATIONSHIP VARCHAR2(100), 
	REQUIREMENT_TYPE VARCHAR2(100), 
	RELATIONSHIP_TYPE VARCHAR2(100), 
	INTERCONNECT_SPECIFICATION VARCHAR2(250)
   ) ;

CREATE TABLE BUSINESS_PARAMETERS 
   (	BID NUMBER, 
	PARAMETER_ID NUMBER, 
	VERSION NUMBER, 
	GRANDFATHERED VARCHAR2(50), 
	LIFECYCLE_ID NUMBER, 
	TYPE VARCHAR2(100), 
	CORE_PARAM_SPEC_ID NUMBER, 
	BUSINESS_PARAM_ID NUMBER DEFAULT BUSINESS_PARAM_ID_SEQ.NEXTVAL, 
	ROOT_ID NUMBER, 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	PARENT_BID NUMBER, 
	EXPORT_IDENTIFIER VARCHAR2(200)
   )  ENABLE ROW MOVEMENT ;




CREATE TABLE BUSINESS_PROCESS_MAPPING 
   (	RECORD_KEY NUMBER, 
	ENTITY_TYPE VARCHAR2(50), 
	VERSION_NO NUMBER, 
	ENTITYID NUMBER, 
	PARENT_ID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	GRANDFATHERED VARCHAR2(50), 
	BUSINESS_RELATION_ID NUMBER, 
	ROOT_ID NUMBER, 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE CHARGE_PARAMETER_SPECIFICATION 
   (	CHARGE_INSTANCE_ID NUMBER, 
	CHARGE_ITEM_CONSTRAIN VARCHAR2(100), 
	CONSTRAIN_VALUE_STARTING VARCHAR2(100), 
	CONSTRAIN_VALUE_ENDING VARCHAR2(100), 
	CEILING_VALUE_MIN NUMBER, 
	BOOLEAN_SET NUMBER, 
	DECISION_TREE VARCHAR2(100), 
	RULE_CHECK VARCHAR2(100), 
	CUSTOM_RULE_CHECK VARCHAR2(100), 
	ON_DYNAMIC_RULE_CHECK VARCHAR2(100), 
	DATA_STORE_NAME VARCHAR2(100), 
	ENTRY_TYPE VARCHAR2(100), 
	INPUT_DATA_STORE_NAME VARCHAR2(100), 
	OUTPUT_DATA_STORE_NAME VARCHAR2(100), 
	REFERENCE_STORE_ID NUMBER, 
	REFERENCE_TYPE VARCHAR2(100), 
	MIN_SELECTION VARCHAR2(100), 
	MAX_SELECTION VARCHAR2(100), 
	SEARCHABLE VARCHAR2(100), 
	FILLETER_TYPE VARCHAR2(100), 
	DYNAMIC_REFERENCE_ID NUMBER, 
	RULE_ID NUMBER, 
	ENTITY_ID NUMBER, 
	TYPE VARCHAR2(20), 
	LIFECYCLE_ID NUMBER, 
	VERSION NUMBER, 
	CHARGE_ITEM_ID NUMBER, 
	RULE_FUNCTION VARCHAR2(50), 
	CRITERIA_EXPRESSION VARCHAR2(50), 
	SERVICE_ENTITY_ID NUMBER, 
	GRANDFATHERED VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE CHARGING_ALGORITHM 
   (	CHARGING_ALGORITHM_ID NUMBER, 
	CHARGING_ALGORITHM_TYPE_CODE VARCHAR2(20), 
	CHARGING_ATTRIBUTE NUMBER, 
	GRANDFATHERED VARCHAR2(50)
   ) ;

CREATE TABLE CHARGING_ATTRIBUTE 
   (	ID NUMBER, 
	TYPE VARCHAR2(100), 
	VALUE VARCHAR2(20), 
	GRANDFATHERED VARCHAR2(50)
   ) ;

CREATE TABLE COMPARISON_DATA 
   (	TABLE_NAME VARCHAR2(100), 
	COLUMN_NAME VARCHAR2(100), 
	SCHEMA_1 VARCHAR2(100), 
	SCHEMA_2 VARCHAR2(100), 
	DDL_TYPE VARCHAR2(10)
   ) ;

CREATE TABLE CUSTOM_API_SPECIFICATION 
   (	CUSTOM_API_SPEC_ID NUMBER, 
	API_URL VARCHAR2(4000), 
	REQUEST_TEMPLATE_ID NUMBER, 
	RESPONSE_TEMPLATE_ID NUMBER, 
	MAPPING_TEMPLATE_ID NUMBER, 
	RULE_ID NUMBER, 
	METHOD_TYPE VARCHAR2(100)
   ) ;

CREATE TABLE CUSTOM_TEMPLATE_MAPPING 
   (	CUSTOM_TEMPL_MAP_ID NUMBER, 
	ENTITY_ID NUMBER, 
	ENTITY_TYPE_ID NUMBER, 
	TEMPLATE_ID NUMBER, 
	TEMPLATE_TYPE VARCHAR2(200), 
	ENTITY_RELATION_TYPE VARCHAR2(100), 
	ENTITY_RELATION_SUB_TYPE VARCHAR2(100), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE CYCLE_PREP_SUMMARY 
   (	ACCOUNT_ID NUMBER, 
	SERVICE_ID NUMBER, 
	CYCLE_PREP_ID NUMBER, 
	ADJUSTMENT_ID NUMBER, 
	ACCOUNT_NAME VARCHAR2(1000), 
	BILL_RUN_EXC_ID NUMBER, 
	SERVICE_NAME VARCHAR2(1000)
   ) ;


CREATE TABLE DECISION_TREE 
   (	DECISION_TREE_NODE_ID NUMBER, 
	DECISION_TREE_PARENT_ID NUMBER, 
	ENTITY_ID NUMBER, 
	ENTITY_TYPE VARCHAR2(50), 
	LEAF_NODE VARCHAR2(10), 
	DECISION_TREE_ROOT_ID NUMBER, 
	GRANDFATHERED VARCHAR2(50)
   ) ;

CREATE TABLE DETERMINANTS 
   (	DETERMINANT_ID NUMBER, 
	DETERMINANT_NAME VARCHAR2(250), 
	DETERMINANT_VALUE VARCHAR2(250), 
	CREATED_ON TIMESTAMP (6), 
	DETERMINANT_ENTITY_TYPE VARCHAR2(100), 
	GRANDFATHERED VARCHAR2(50)
   ) ;

CREATE TABLE EMAIL_TEMPLATE 
   (	TEMPLATE_ID NUMBER, 
	TEMPLATE_FROM VARCHAR2(50), 
	TEMPLATE_TO VARCHAR2(500), 
	TEMPLATE_CC VARCHAR2(500), 
	TEMPLATE_BCC VARCHAR2(500), 
	REPLY_TO VARCHAR2(500), 
	SUBJECT VARCHAR2(100), 
	EMAIL_CONTENT CLOB, 
	CREATED_BY VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	TEMPLATE_VER NUMBER, 
	TOEMAILTYPES VARCHAR2(100), 
	CCEMAILTYPES VARCHAR2(100), 
	BCCEMAILTYPES VARCHAR2(100), 
	REPLYTOEMAILTYPES VARCHAR2(100), 
	EMAIL_TEMP_ID NUMBER DEFAULT EMAIL_TEMP_ID_SEQ.NEXTVAL, 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE ENTITY_BOUNDARY_CONDITION 
   (	EBC_ID NUMBER, 
	ENTITY_ID NUMBER, 
	ENTITY_TYPE VARCHAR2(100), 
	RESPONSE_TYPE VARCHAR2(100), 
	CONDITION_TYPE VARCHAR2(200), 
	CONDITION_SUBTYPE VARCHAR2(200), 
	ACTION VARCHAR2(100), 
	MIN_VAL NUMBER, 
	MAX_VAL NUMBER, 
	HTTP_CODE VARCHAR2(4000), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE ENTITY_GROUP_FUNCTION 
   (	PID NUMBER, 
	ENTITY_TYPE VARCHAR2(100), 
	VERSION NUMBER, 
	BID NUMBER, 
	GROUP_ID VARCHAR2(50), 
	JOIN_PID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	HIERARCHY VARCHAR2(50), 
	PARENT_PID NUMBER, 
	PROCESS_ENTITY_TYPE VARCHAR2(100), 
	PROCESS_BID NUMBER, 
	ENTITY_FUNCTION_ID NUMBER, 
	GROUP_NAME VARCHAR2(250), 
	RELATED_FUNCTION_ID NUMBER, 
	START_DATE TIMESTAMP (6), 
	END_DATE TIMESTAMP (6), 
	STATUS VARCHAR2(50), 
	DESCRIPTION VARCHAR2(250), 
	NAME VARCHAR2(250), 
	GRANDFATHERED VARCHAR2(50), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	MAPPING_TYPE_SOURCE VARCHAR2(100), 
	MAPPING_TYPE_TARGET VARCHAR2(100), 
	EFFECTIVE_END_DATE TIMESTAMP (6), 
	CATEGORY_TYPE VARCHAR2(100), 
	MAPPING_TYPE VARCHAR2(250), 
	ENTITY_GROUP_FUNC_ID NUMBER DEFAULT ENTITY_GROUP_FUNC_ID_SEQ.NEXTVAL, 
	EXPORT_IDENTIFIER VARCHAR2(200), 
	TARGET_ENTITY_TYPE VARCHAR2(100)
   ) ;





CREATE TABLE ENTITY_JOIN_PARAMETER 
   (	PARAMKEY1 NUMBER, 
	PARAMKEY2 NUMBER, 
	BUSINESS_ENTITY VARCHAR2(50), 
	VERSION_NO NUMBER, 
	GROUP_ID VARCHAR2(50), 
	LIFECYCLE_ID NUMBER, 
	ENTITY_FUNCTION_ID NUMBER, 
	GRANDFATHERED VARCHAR2(50), 
	JOIN_METHOD VARCHAR2(100), 
	MAPPING_ENTITY_ID NUMBER, 
	MAPPING_ENTITY_TYPE VARCHAR2(100), 
	TRANSFORMATION_TYPE VARCHAR2(100), 
	SOURCE_VALUE VARCHAR2(100), 
	TARGET_VALUE VARCHAR2(100), 
	JOIN_SEQ NUMBER, 
	ENTITY_JOIN_PARAM_ID NUMBER DEFAULT ENTITY_JOIN_PARAM_ID_SEQ.NEXTVAL, 
	TRANSFORMATION_REQ VARCHAR2(20), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	ALLOW_OTHER_OBJECTS VARCHAR2(1), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE ENTITY_JSON_MAPPING 
   (	ENTITY_JSON_MAP_ID NUMBER, 
	PID NUMBER, 
	ENTITY_TYPE_ID NUMBER, 
	JSON_DATA CLOB, 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(400), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(400), 
	ENTITY_LIFECYCLE_ID NUMBER, 
	ENTITY_NAME VARCHAR2(200)
   ) ;

CREATE TABLE ENTITY_PRODUCT_CODE_MAPPING 
   (	ENTITY_PRD_CD_ID NUMBER DEFAULT ENTITY_PRD_CD_ID_SEQ.NEXTVAL, 
	BUSINESS_ENTITY_ID NUMBER, 
	ENTITY_TYPE VARCHAR2(100), 
	PRODUCT_CODE_ID NUMBER, 
	ROOT_ID NUMBER
   ) ;

CREATE TABLE ENTITY_RELEASE_HISTORY 
   (	ERH_ID NUMBER, 
	ENTITY_ID NUMBER, 
	ENTITY_TYPE VARCHAR2(100), 
	ENTITY_VERSION NUMBER, 
	GROUP_RELEASE_ID NUMBER, 
	ENV_RELEASE_NUMBER NUMBER, 
	SOURCE_ENVIRONMENT VARCHAR2(1000), 
	RELEASE_ENVIRONMENT VARCHAR2(1000), 
	RELEASE_STATUS VARCHAR2(1000), 
	CREATED_BY VARCHAR2(1000), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(1000), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

CREATE TABLE ERROR_INFO 
   (	ERROR_ID NUMBER, 
	ERROR_CODE VARCHAR2(100), 
	ERROR_DESCRIPTION VARCHAR2(255), 
	ERROR_TYPE VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	LANGUAGE VARCHAR2(100), 
	ERROR_MSG VARCHAR2(3000), 
	TRANSFORMATION_CODE VARCHAR2(1000), 
	TRANSFORMATION_MESSAGE VARCHAR2(1000), 
	SYSTEM_NAME VARCHAR2(1000), 
	IS_RETRY VARCHAR2(10), 
	RETRY_COUNT NUMBER, 
	RETRY_INTERVAL NUMBER, 
	ERROR_SUB_TYPE VARCHAR2(1000), 
	HTTP_CODE NUMBER, 
	HTTP_MESSAGE VARCHAR2(1000), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE ERROR_LOG 
   (	SR_ID NUMBER, 
	ERROR_TIME TIMESTAMP (6), 
	ERRBKTRACE CLOB, 
	ERRSTCK CLOB, 
	CHANNNEL VARCHAR2(150)
   ) ;

CREATE TABLE HIERARCHY_METADATA 
   (	HIERARCHY_ENTITY_ID NUMBER, 
	HIERARCHY_ENTITY_TYPE VARCHAR2(100), 
	HIERARCHY_NAME VARCHAR2(100), 
	HIERARCHY_LEVEL NUMBER, 
	DYNAMIC_LOAD_PROCESS_ID NUMBER, 
	DYNAMIC_PARENT_ID NUMBER, 
	HIERARCHY_ACTION VARCHAR2(50), 
	PARENT_ENTITY_ID NUMBER, 
	BUSINESS_ENTITY_TYPE VARCHAR2(150), 
	HIERARCHY_ID NUMBER, 
	NAVIGATION_PROCESS_ID NUMBER, 
	GROUP_BY VARCHAR2(100), 
	SOFT_NODE VARCHAR2(100), 
	SOFT_NODE_NAME VARCHAR2(100), 
	HIERARCHY_DESCRIPTION VARCHAR2(150), 
	VERSION NUMBER, 
	SEQUENCE NUMBER, 
	GRANDFATHERED VARCHAR2(50), 
	HIERARCHY_METADATA_ID NUMBER DEFAULT HIERARCHY_METADATA_ID_SEQ.NEXTVAL, 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE HISTORY_ENTITY_GROUP_FUNCTION 
   (	PID NUMBER, 
	ENTITY_TYPE VARCHAR2(100), 
	VERSION NUMBER, 
	BID NUMBER, 
	GROUP_ID VARCHAR2(50), 
	JOIN_PID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	HIERARCHY VARCHAR2(50), 
	PARENT_PID NUMBER, 
	PROCESS_ENTITY_TYPE VARCHAR2(100), 
	PROCESS_BID NUMBER
   ) ;

CREATE TABLE HISTORY_PROCESS_ENTITY 
   (	PID NUMBER, 
	PROCESS_ENTITY_NAME VARCHAR2(200), 
	VERSION NUMBER, 
	TYPE VARCHAR2(100), 
	PARENT_ID NUMBER, 
	PROCESS_SEQUENCE VARCHAR2(50), 
	LIFECYCLE_ID NUMBER, 
	ACTION_TYPE VARCHAR2(100), 
	DISPLAY_NAME VARCHAR2(100), 
	PROCESS_FLAG VARCHAR2(20), 
	CHART_ID NUMBER, 
	ROOT_ID NUMBER, 
	HIERARCHY_TYPE VARCHAR2(50)
   ) ;

CREATE TABLE HISTORY_PROCESS_ENTITY_SPEC 
   (	PROCESS_SPEC_ID NUMBER, 
	PID NUMBER, 
	NAME VARCHAR2(100), 
	DESCRIPTION VARCHAR2(255), 
	VERSION NUMBER, 
	START_DATE TIMESTAMP (6), 
	END_DATE TIMESTAMP (6), 
	SEQUENCE NUMBER, 
	TYPE VARCHAR2(100), 
	DISPLAY_NAME VARCHAR2(255), 
	ICON VARCHAR2(255), 
	LIFECYCLE_ID NUMBER, 
	LAUNCH_TYPE VARCHAR2(30), 
	TASK_ID NUMBER, 
	STANDARD_TASK_AGE NUMBER, 
	GRACE_TASK_AGE NUMBER, 
	CRITICAL_TASK_AGE NUMBER, 
	TASK_DESCRIPTION VARCHAR2(500), 
	TASK_TYPE VARCHAR2(500), 
	TASK_GROUP_ID NUMBER, 
	TASK_GROUP_NAME VARCHAR2(500), 
	CATEGORIES VARCHAR2(500), 
	TASK_DURATION NUMBER, 
	EXECUTION_URL VARCHAR2(255), 
	DEPENDENT_TASK VARCHAR2(255), 
	PAYLOAD_TYPE VARCHAR2(255), 
	ARCHIVAL_STATUS VARCHAR2(100)
   ) ;

CREATE TABLE HISTORY_RULE 
   (	RULE_ID NUMBER, 
	RULE_NAME VARCHAR2(100), 
	RULE_DESC VARCHAR2(500), 
	EXPRESSION VARCHAR2(4000), 
	RULE_TYPE VARCHAR2(50), 
	ENTITY_ID NUMBER, 
	ENTITY_TYPE_ID NUMBER, 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	RULE_MESSAGE VARCHAR2(4000), 
	EVENT_TYPE VARCHAR2(50), 
	TYPE VARCHAR2(50), 
	TEMPLATE_ID NUMBER, 
	ERROR_CODE VARCHAR2(100), 
	SUCCESS_CODE VARCHAR2(100), 
	CUSTOM_FUNCTION VARCHAR2(100), 
	QUERY VARCHAR2(100), 
	MODEL VARCHAR2(255), 
	RULE_SEQUENCE NUMBER, 
	TEMPLATE VARCHAR2(250), 
	LIFECYCLE_ID NUMBER, 
	VERSION NUMBER, 
	PARENT_RULE_ID NUMBER, 
	ENTITY_EVENT_TYPE VARCHAR2(255)
   ) ;

CREATE TABLE HIS_BUSINESS_ENTITY 
   (	BID NUMBER, 
	BUSINESS_ENTITY_NAME VARCHAR2(100), 
	VERSION NUMBER, 
	LIFECYCLE_ID NUMBER, 
	DISPLAY_NAME VARCHAR2(100), 
	START_DATE TIMESTAMP (6), 
	END_DATE TIMESTAMP (6), 
	ENTITY_TYPE VARCHAR2(100), 
	GRANDFATHERE VARCHAR2(100), 
	ICON VARCHAR2(200), 
	ENTITY_GROUP VARCHAR2(100), 
	LOCATION_SELECTION VARCHAR2(100), 
	ACCESS_SELECTION VARCHAR2(100), 
	SAVE_ENTITY_TYPE VARCHAR2(100), 
	SAVE_ENTITY_NAME VARCHAR2(100), 
	OBJECT_URL VARCHAR2(1000), 
	GRANDFATHERED VARCHAR2(50)
   ) ;

CREATE TABLE HIS_BUSINESS_ENTITY_PARAMETER 
   (	RECORD_KEY_PARAM NUMBER, 
	ENTITY VARCHAR2(200), 
	VERSION_NO NUMBER, 
	PARENT_ID NUMBER, 
	NAME VARCHAR2(100), 
	PARAMETER_SPEC_ID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	ARCHIVAL_STATUS VARCHAR2(100), 
	GRANDFATHERED VARCHAR2(50)
   ) ;

CREATE TABLE HIS_BUSINESS_ENTITY_RELATION 
   (	PARENT_ID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	VERSION NUMBER, 
	CHILD_ID NUMBER, 
	GRANDFATHERED VARCHAR2(50)
   ) ;

CREATE TABLE HIS_BUSINESS_PARAMETERS 
   (	BID NUMBER, 
	PARAMETER_ID NUMBER, 
	VERSION NUMBER, 
	GRANDFATHERED VARCHAR2(50)
   ) ;

CREATE TABLE HIS_BUSINESS_PROCESS_MAPPING 
   (	RECORD_KEY NUMBER, 
	ENTITY_TYPE VARCHAR2(50), 
	VERSION_NO NUMBER, 
	ENTITYID NUMBER, 
	PARENT_ID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	ARCHIVAL_STATUS VARCHAR2(100)
   ) ;

CREATE TABLE HIS_ENTITY_GROUP_FUNCTION 
   (	PID NUMBER, 
	ENTITY_TYPE VARCHAR2(100), 
	VERSION NUMBER, 
	BID NUMBER, 
	GROUP_ID VARCHAR2(50), 
	JOIN_PID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	HIERARCHY VARCHAR2(50), 
	PARENT_PID NUMBER, 
	PROCESS_ENTITY_TYPE VARCHAR2(100), 
	PROCESS_BID NUMBER, 
	ENTITY_FUNCTION_ID NUMBER, 
	GROUP_NAME VARCHAR2(250), 
	RELATED_FUNCTION_ID NUMBER, 
	START_DATE TIMESTAMP (6), 
	END_DATE TIMESTAMP (6), 
	STATUS VARCHAR2(50), 
	DESCRIPTION VARCHAR2(250), 
	NAME VARCHAR2(250), 
	GRANDFATHERED VARCHAR2(50), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	CATEGORY_TYPE VARCHAR2(100), 
	MAPPING_TYPE_SOURCE VARCHAR2(100), 
	MAPPING_TYPE_TARGET VARCHAR2(100), 
	EFFECTIVE_END_DATE TIMESTAMP (6), 
	MAPPING_TYPE VARCHAR2(250)
   ) ;

CREATE TABLE HIS_ENTITY_JOIN_PARAMETER 
   (	PARAMKEY1 NUMBER, 
	PARAMKEY2 NUMBER, 
	BUSINESS_ENTITY VARCHAR2(50), 
	VERSION_NO NUMBER, 
	GROUP_ID VARCHAR2(50), 
	LIFECYCLE_ID NUMBER, 
	ARCHIVAL_STATUS VARCHAR2(100), 
	GRANDFATHERED VARCHAR2(50), 
	ENTITY_FUNCTION_ID NUMBER
   ) ;

CREATE TABLE HIS_PARAMETER_DATA_SPEC 
   (	PARAM_DATA_SPEC_ID NUMBER, 
	DATA_STORE_NAME VARCHAR2(200), 
	ENTRY_TYPE VARCHAR2(100), 
	INPUT_DATA_NAME VARCHAR2(100), 
	OUTPUT_DATA_NAME VARCHAR2(100), 
	REFERENCE_STORE_ID NUMBER, 
	REFERENCE_TYPE VARCHAR2(100), 
	MIN_SELECTION NUMBER, 
	MAX_SELECTION NUMBER, 
	SEARCHABLE VARCHAR2(100), 
	FILTER_TYPE VARCHAR2(100), 
	DYNAMIC_REF_ID NUMBER, 
	PARENT_ID NUMBER, 
	PARAM_SEQUENCE VARCHAR2(50), 
	LIFECYCLE_ID NUMBER, 
	VERSION NUMBER, 
	REFERENCE_DATA_URL VARCHAR2(100), 
	FILTER_OPERATOR VARCHAR2(25), 
	FILTER_VALUES VARCHAR2(100), 
	INPUT_SEARCH_VALUES VARCHAR2(3000), 
	ARCHIVAL_STATUS VARCHAR2(100), 
	GRANDFATHERED VARCHAR2(50)
   ) ;

CREATE TABLE HIS_PARAM_RULE_SPECIFICATION 
   (	PARAM_RULE_SPEC_ID NUMBER, 
	CONSTRAIN VARCHAR2(100), 
	CONS_VAL_START VARCHAR2(100), 
	CONS_VAL_END VARCHAR2(100), 
	CEILING_VALUE_MIN NUMBER, 
	BOOLEAN_SET VARCHAR2(100), 
	DECISION_TREE VARCHAR2(100), 
	RULE_CHECK VARCHAR2(100), 
	CUSTOM_RULE_CHECK VARCHAR2(100), 
	DYNMAIC_RULE_CHECK VARCHAR2(200), 
	PARENT_ID NUMBER, 
	PARAM_SEQUENCE VARCHAR2(50), 
	RULE_ID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	VERSION NUMBER, 
	DATA_STORE_NAME VARCHAR2(100), 
	ENTRY_TYPE VARCHAR2(100), 
	INPUT_DATA_STORE_NAME VARCHAR2(100), 
	OUTPUT_DATA_STORE_NAME VARCHAR2(100), 
	REFERENCE_STORE_ID NUMBER, 
	REFERENCE_TYPE VARCHAR2(100), 
	MIN_SELECTION VARCHAR2(100), 
	MAX_SELECTION VARCHAR2(100), 
	SEARCHABLE VARCHAR2(100), 
	FILLETER_TYPE VARCHAR2(100), 
	DYNAMIC_REFERENCE_ID NUMBER, 
	REFERENCE_VALUE VARCHAR2(50), 
	REFERENCE_VISIBILITY VARCHAR2(10), 
	VALUE_SET VARCHAR2(100), 
	BOOLEAN_VALUE_SET VARCHAR2(100), 
	BOOLEAN_VALUE VARCHAR2(100), 
	VALIDATION_TYPE VARCHAR2(255), 
	CEILING_VALUE_MAX NUMBER, 
	REGEX_VALUE VARCHAR2(255), 
	ERROR_ID NUMBER, 
	FUNCTION VARCHAR2(100), 
	VALUE VARCHAR2(100), 
	SEQUENCE_NO NUMBER, 
	BOOLEAN_FUNCTION VARCHAR2(5), 
	EDITABLE_REFERENCE VARCHAR2(50), 
	RULE_SCRIPT_ID NUMBER, 
	ASSOCIATED_PROCESS_ID NUMBER, 
	EXPRESSION_TYPE VARCHAR2(50), 
	CONDITIONAL_FUNCTION VARCHAR2(50), 
	COMPLEX_FUNCTION VARCHAR2(50), 
	GRANDFATHERED VARCHAR2(50)
   ) ;

CREATE TABLE HIS_PRICE_PLAN 
   (	PRICE_PLAN_ID NUMBER, 
	PRICE_PLAN_NAME VARCHAR2(300), 
	PRICE_PLAN_DESC VARCHAR2(1500), 
	VERSION NUMBER, 
	PRICE_PLAN_START_DATE DATE, 
	CREATED_BY VARCHAR2(4000), 
	CREATED_DATE DATE, 
	MODIFIED_BY VARCHAR2(4000), 
	MODIFIED_DATE DATE, 
	PRICE_PLAN_END_DATE DATE, 
	PRICE_PLAN_DISP_NAME VARCHAR2(300), 
	PRICE_PLAN_IMAGE_URL VARCHAR2(1000), 
	PRICE_PLAN_GRANDFATHERED VARCHAR2(3), 
	CURRENCY_ID VARCHAR2(50), 
	STARTDATE TIMESTAMP (6), 
	ENDDATE TIMESTAMP (6), 
	GRANDFATHER VARCHAR2(100), 
	QUANTIFIABLE VARCHAR2(100), 
	CATEGORY VARCHAR2(100), 
	EXTERNAL_REFERENCE_ID VARCHAR2(100), 
	LIFECYCLE_ID NUMBER, 
	DEFAULT_VALUE VARCHAR2(255), 
	GRANDFATHERED VARCHAR2(50)
   ) ;

CREATE TABLE HIS_PRICE_PLAN_ENTITY 
   (	ENTITY_ID NUMBER, 
	ENTITY_TYPE VARCHAR2(50), 
	PLAN_ID NUMBER, 
	VALID_FROM DATE, 
	VERSION NUMBER, 
	GRANDFATHERED VARCHAR2(50)
   ) ;

CREATE TABLE HIS_PRICE_PLAN_SPECIFICATION 
   (	PP_INSTANCE_ID NUMBER, 
	PP_ITEM_NAME VARCHAR2(100), 
	VERSION NUMBER, 
	PARENT_ID NUMBER, 
	PRIORITY NUMBER, 
	SEQUENCE NUMBER, 
	CHARGE_ITEM_TYPE VARCHAR2(100), 
	UNIT_OF_MEASURE_BASELINED VARCHAR2(100), 
	CHARGE_UNIT_CUSTOM NUMBER, 
	STARTDATE TIMESTAMP (6), 
	ENDDATE TIMESTAMP (6), 
	PRICE_PLAN_ID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	DEFAULT_VALUE VARCHAR2(255), 
	SERVICE_ENTITY_ID NUMBER, 
	CHARGE_UNIT_BASELINED VARCHAR2(50), 
	GRANDFATHERED VARCHAR2(50)
   ) ;

CREATE TABLE HIS_PROCESS_ACTION_SPEC 
   (	ACTION_ID NUMBER, 
	ACTION_NAME VARCHAR2(100), 
	DESCRIPTION VARCHAR2(255), 
	ACTION_BOTTON_TYPE VARCHAR2(100), 
	PROCESS_TYPE VARCHAR2(100), 
	DISPLAY_NAME VARCHAR2(100), 
	FLYOVER_TEXT VARCHAR2(100), 
	SEQUENCE NUMBER, 
	ACTION_LENGTH VARCHAR2(50), 
	ACTION_VISIBLE VARCHAR2(50), 
	FORMATTING VARCHAR2(100), 
	QUANTIFIABLE VARCHAR2(100), 
	PARENT_ID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	VERSION NUMBER, 
	ACTION VARCHAR2(50), 
	ACTION_URL VARCHAR2(4000), 
	FUNCTION_TYPE VARCHAR2(50), 
	ACTION_TYPE VARCHAR2(50), 
	WIDTH NUMBER, 
	TOP_MARGIN NUMBER, 
	LEFT_MARGIN NUMBER, 
	HEIGHT NUMBER, 
	POSITION VARCHAR2(50), 
	RESPONSE_HANDLER VARCHAR2(50), 
	ACTION_PROCESS_ID NUMBER, 
	BUTTON_ICON VARCHAR2(50), 
	ACTION_LOAD_PROCESS_ID NUMBER, 
	ARCHIVAL_STATUS VARCHAR2(100), 
	GRANDFATHERED VARCHAR2(50)
   ) ;

CREATE TABLE HIS_PROCESS_ENTITY 
   (	PID NUMBER, 
	PROCESS_ENTITY_NAME VARCHAR2(200), 
	VERSION NUMBER, 
	TYPE VARCHAR2(100), 
	PARENT_ID NUMBER, 
	PROCESS_SEQUENCE VARCHAR2(200), 
	LIFECYCLE_ID NUMBER, 
	ACTION_TYPE VARCHAR2(100), 
	DISPLAY_NAME VARCHAR2(100), 
	PROCESS_FLAG VARCHAR2(20), 
	CHART_ID NUMBER, 
	ROOT_ID NUMBER, 
	HIERARCHY_TYPE VARCHAR2(50), 
	GRANDFATHERED VARCHAR2(50), 
	REVERSE_PROCESS_FLAG VARCHAR2(100), 
	REVERSE_PROCESS_ID NUMBER, 
	ARCHIVAL_STATUS VARCHAR2(100)
   ) ;

CREATE TABLE HIS_PROCESS_ENTITY_SPEC 
   (	PROCESS_SPEC_ID NUMBER, 
	PID NUMBER, 
	NAME VARCHAR2(100), 
	DESCRIPTION VARCHAR2(255), 
	VERSION NUMBER, 
	START_DATE TIMESTAMP (6), 
	END_DATE TIMESTAMP (6), 
	SEQUENCE NUMBER, 
	TYPE VARCHAR2(100), 
	DISPLAY_NAME VARCHAR2(255), 
	ICON VARCHAR2(255), 
	LIFECYCLE_ID NUMBER, 
	LAUNCH_TYPE VARCHAR2(30), 
	TASK_ID NUMBER, 
	STANDARD_TASK_AGE NUMBER, 
	GRACE_TASK_AGE NUMBER, 
	CRITICAL_TASK_AGE NUMBER, 
	TASK_DESCRIPTION VARCHAR2(500), 
	TASK_TYPE VARCHAR2(500), 
	TASK_GROUP_ID NUMBER, 
	TASK_GROUP_NAME VARCHAR2(500), 
	CATEGORIES VARCHAR2(500), 
	TASK_DURATION NUMBER, 
	EXECUTION_URL VARCHAR2(255), 
	DEPENDENT_TASK VARCHAR2(255), 
	PAYLOAD_TYPE VARCHAR2(255), 
	ARCHIVAL_STATUS VARCHAR2(100), 
	GRANDFATHERED VARCHAR2(50)
   ) ;

CREATE TABLE HIS_PROCESS_LAYOUT_SPEC 
   (	LAYOUT_ID NUMBER, 
	NAME VARCHAR2(100), 
	DESCRIPTION_TYPE VARCHAR2(100), 
	DESCRIPTION VARCHAR2(255), 
	DISPLAY_NAME VARCHAR2(100), 
	FLYOVER_TEXT VARCHAR2(100), 
	SEQUENCE NUMBER, 
	PARENT_ID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	VERSION NUMBER, 
	HEIGHT NUMBER, 
	WIDTH NUMBER, 
	TOP_MARGIN NUMBER, 
	LEF_MARGIN NUMBER, 
	COLLAPSIBLE VARCHAR2(10), 
	VISIBILITY VARCHAR2(5), 
	ISPANEL VARCHAR2(50), 
	LAYOUT_ACTION_TYPE VARCHAR2(100), 
	MINVAL NUMBER, 
	MAXVAL NUMBER, 
	FONT_COLOR VARCHAR2(50), 
	IMG_WEIGHT VARCHAR2(50), 
	FONT_SIZE VARCHAR2(150), 
	HORIZONTAL_ALIGNMENT VARCHAR2(50), 
	CHART_ID NUMBER, 
	DYNAMIC_PARAMETER_CHECK VARCHAR2(20), 
	ARCHIVAL_STATUS VARCHAR2(100), 
	GRANDFATHERED VARCHAR2(50)
   ) ;

CREATE TABLE HIS_SCRIPT_INFO 
   (	SCRIPT_ID NUMBER, 
	SCRIPT_NAME VARCHAR2(50), 
	SCRIPT_GROUP_ID NUMBER, 
	SCRIPT_TYPE VARCHAR2(50), 
	SCRIPT_FILE_URL VARCHAR2(100), 
	SCRIPT_DESCRIPTION VARCHAR2(100), 
	SEQUENCE NUMBER, 
	CODE VARCHAR2(3000), 
	SCHEMA_NAME VARCHAR2(100), 
	SCRIPT_FILE_TYPE VARCHAR2(50)
   ) ;

CREATE TABLE HIS_TABLE_PARAMETER_MAPPING 
   (	PARAMETER_SPEC_ID NUMBER, 
	ROW_SPEC_ID NUMBER, 
	ARCHIVAL_STATUS VARCHAR2(100), 
	GRANDFATHERED VARCHAR2(50)
   ) ;

CREATE TABLE HIS_TABLE_ROW_SPECIFICATION 
   (	ID NUMBER, 
	NAME VARCHAR2(100), 
	CATEGORY VARCHAR2(100), 
	TYPE VARCHAR2(100), 
	DESCRIPTION VARCHAR2(255), 
	DISPLAY_NAME VARCHAR2(100), 
	WIDTH NUMBER, 
	HEIGHT NUMBER, 
	MIN_ROW NUMBER, 
	MAX_ROW NUMBER, 
	ENTITY_ID NUMBER, 
	PARENT_ID NUMBER, 
	STATUS VARCHAR2(50), 
	STATUS_DATE TIMESTAMP (6), 
	VERSION NUMBER, 
	VERSION_DATE TIMESTAMP (6), 
	LIFECYCLE_STATUS VARCHAR2(50), 
	POSITION NUMBER, 
	VISIBILITY VARCHAR2(20), 
	SEQUENCE NUMBER, 
	ROW_INDENT NUMBER, 
	ARCHIVAL_STATUS VARCHAR2(100), 
	GRANDFATHERED VARCHAR2(50)
   ) ;

CREATE TABLE HIS_TABLE_SPECIFICATION 
   (	ID NUMBER, 
	NAME VARCHAR2(100), 
	CATEGORY VARCHAR2(100), 
	TYPE VARCHAR2(100), 
	DESCRIPTION VARCHAR2(255), 
	DISPLAY_NAME VARCHAR2(100), 
	WIDTH NUMBER, 
	HEIGHT NUMBER, 
	MIN_ROW NUMBER, 
	MAX_ROW NUMBER, 
	ENTITY_ID NUMBER, 
	PARENT_ID NUMBER, 
	STATUS VARCHAR2(50), 
	STATUS_DATE TIMESTAMP (6), 
	VERSION NUMBER, 
	VERSION_DATE TIMESTAMP (6), 
	LIFECYCLE_STATUS VARCHAR2(50), 
	POSITION NUMBER, 
	CRITERIA_TYPE VARCHAR2(100), 
	ARCHIVAL_STATUS VARCHAR2(100), 
	GRANDFATHERED VARCHAR2(50)
   ) ;

CREATE TABLE INVOICE_INFO 
   (	INVOICE_ID NUMBER, 
	ACCOUNT_ID NUMBER, 
	ACCOUNT_NAME VARCHAR2(1000), 
	BILLING_PERIOD VARCHAR2(100), 
	INVOICE_GENERATED_DATE DATE, 
	TAX NUMBER, 
	TOTAL_AMOUNT NUMBER, 
	INVOICE_STATUS VARCHAR2(100), 
	INVOICE_DUE_DATE DATE, 
	PAYMENT_RECEIVED NUMBER, 
	PREVIOUS_BALANCE NUMBER, 
	ADJUSTMENT_ID NUMBER, 
	CURRENT_BILL_AMOUNT NUMBER, 
	BILL_RUN_ID NUMBER, 
	CYCLE_PREP_ID NUMBER, 
	CREATION_DATE DATE, 
	PAST_DUE_AMOUNT NUMBER
   ) ;

CREATE TABLE LIFE_CYCLE_ACTIVITY_METADATA 
   (	LCA_ID NUMBER, 
	LCA_TYPE VARCHAR2(50), 
	LCA_DESCRIPTION VARCHAR2(100), 
	LCA_VERSION NUMBER, 
	LCA_STATUS VARCHAR2(50), 
	LCA_STATUS_DTM TIMESTAMP (6), 
	LCA_LEVEL VARCHAR2(20), 
	LCA_PRIORITY VARCHAR2(20), 
	LCA_DEPENDENCY_DATE DATE, 
	LCA_CREATION_DTM TIMESTAMP (6), 
	LCA_CREATED_BY VARCHAR2(50), 
	LCA_SCHEDULE VARCHAR2(50), 
	LCA_DISPLAY_ON_TIMELINE VARCHAR2(50), 
	LCA_PLAN_START_DTM VARCHAR2(100), 
	LCA_PLAN_END_DTM VARCHAR2(100), 
	LCA_ACTUAL_START_DTM VARCHAR2(100), 
	LCA_ACTUAL_END_DTM VARCHAR2(100), 
	LCA_POTENTIAL_START_DTM VARCHAR2(100), 
	LCA_POTENTIAL_END_DTM VARCHAR2(100), 
	LCA_DURATION_PLAN NUMBER, 
	LCA_DURATION_ACTUAL NUMBER, 
	LCA_THRESHOLD NUMBER, 
	LCA_THRESHOLD_REASON_CODE VARCHAR2(10), 
	LCA_THRESHOLD_DATE DATE, 
	LCA_MILESTONE VARCHAR2(20), 
	LCA_REASON_CODE VARCHAR2(10), 
	LCA_COLOR_CODE VARCHAR2(10), 
	LCA_LABEL_COUNT NUMBER, 
	LCA_BEHAVIOUR_CODE VARCHAR2(10), 
	CPC_LCA_ID NUMBER, 
	CPC_LCA_VERSION NUMBER, 
	LCA_PARENT_ID NUMBER, 
	LCA_CHILD_ID NUMBER, 
	LCA_ROOT_ID NUMBER, 
	LCA_EXTERNAL_SOURCE_ID NUMBER, 
	LCA_NAME VARCHAR2(100), 
	LCA_COMPLETION_PERCENTAGE NUMBER, 
	LCA_MILESTONE_DTM TIMESTAMP (6), 
	LCA_MODIFIED_BY VARCHAR2(50), 
	LCA_MODIFIED_ON TIMESTAMP (6), 
	LCA_OWNER VARCHAR2(150), 
	ENTITY_SEQ NUMBER, 
	ENTITY_ID NUMBER, 
	ENTITY_NAME VARCHAR2(100), 
	LCA_DATA_LOG CLOB, 
	LCA_ACTIVITY_REASON VARCHAR2(100), 
	LCA_ACTIVITY VARCHAR2(50), 
	VERSION NUMBER, 
	LIFE_CYCLE_ID NUMBER, 
	LCA_USERID NUMBER, 
	GRANDFATHERED VARCHAR2(50), 
	SCHEDULE_DATETIME TIMESTAMP (6), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE LIFE_CYCLE_ACTIVITY_METADATA_12032024 
   (	LCA_ID NUMBER, 
	LCA_TYPE VARCHAR2(50), 
	LCA_DESCRIPTION VARCHAR2(100), 
	LCA_VERSION NUMBER, 
	LCA_STATUS VARCHAR2(50), 
	LCA_STATUS_DTM TIMESTAMP (6), 
	LCA_LEVEL VARCHAR2(20), 
	LCA_PRIORITY VARCHAR2(20), 
	LCA_DEPENDENCY_DATE DATE, 
	LCA_CREATION_DTM TIMESTAMP (6), 
	LCA_CREATED_BY VARCHAR2(50), 
	LCA_SCHEDULE VARCHAR2(50), 
	LCA_DISPLAY_ON_TIMELINE VARCHAR2(50), 
	LCA_PLAN_START_DTM VARCHAR2(100), 
	LCA_PLAN_END_DTM VARCHAR2(100), 
	LCA_ACTUAL_START_DTM VARCHAR2(100), 
	LCA_ACTUAL_END_DTM VARCHAR2(100), 
	LCA_POTENTIAL_START_DTM VARCHAR2(100), 
	LCA_POTENTIAL_END_DTM VARCHAR2(100), 
	LCA_DURATION_PLAN NUMBER, 
	LCA_DURATION_ACTUAL NUMBER, 
	LCA_THRESHOLD NUMBER, 
	LCA_THRESHOLD_REASON_CODE VARCHAR2(10), 
	LCA_THRESHOLD_DATE DATE, 
	LCA_MILESTONE VARCHAR2(20), 
	LCA_REASON_CODE VARCHAR2(10), 
	LCA_COLOR_CODE VARCHAR2(10), 
	LCA_LABEL_COUNT NUMBER, 
	LCA_BEHAVIOUR_CODE VARCHAR2(10), 
	CPC_LCA_ID NUMBER, 
	CPC_LCA_VERSION NUMBER, 
	LCA_PARENT_ID NUMBER, 
	LCA_CHILD_ID NUMBER, 
	LCA_ROOT_ID NUMBER, 
	LCA_EXTERNAL_SOURCE_ID NUMBER, 
	LCA_NAME VARCHAR2(100), 
	LCA_COMPLETION_PERCENTAGE NUMBER, 
	LCA_MILESTONE_DTM TIMESTAMP (6), 
	LCA_MODIFIED_BY VARCHAR2(50), 
	LCA_MODIFIED_ON TIMESTAMP (6), 
	LCA_OWNER VARCHAR2(150), 
	ENTITY_SEQ NUMBER, 
	ENTITY_ID NUMBER, 
	ENTITY_NAME VARCHAR2(100), 
	LCA_DATA_LOG CLOB, 
	LCA_ACTIVITY_REASON VARCHAR2(100), 
	LCA_ACTIVITY VARCHAR2(50), 
	VERSION NUMBER, 
	LIFE_CYCLE_ID NUMBER, 
	LCA_USERID NUMBER, 
	GRANDFATHERED VARCHAR2(50), 
	SCHEDULE_DATETIME TIMESTAMP (6)
   ) ;




CREATE TABLE METADATA_DELETE_TRACE 
   (	METADATA_DELETE_EXECUTION_ID NUMBER, 
	METADATA_DELETE_PROC_NAME VARCHAR2(500), 
	METADATA_DELETE_LOGS VARCHAR2(4000), 
	METADATA_DELETE_DYNAMIC_SCRIPT CLOB, 
	METADATA_DELETE_IDS CLOB, 
	METADATA_DELETE_EXECUTION_TIME TIMESTAMP (6), 
	METADATA_DELETE_IP_PID NUMBER, 
	METADATA_DELETE_NOTIN_PARENTID CLOB
   ) ;

CREATE TABLE METADATA_EXPORT_ERROR 
   (	METADATA_EXPORT_EXECUTION_ID NUMBER, 
	METADATA_EXPORT_PROC_NAME VARCHAR2(500), 
	METADATA_EXPORT_LOGS VARCHAR2(4000), 
	METADATA_EXPORT_ERROR_CODE VARCHAR2(4000), 
	METADATA_EXPORT_ERROR_MSG VARCHAR2(4000), 
	METADATA_EXPORT_EXECUTION_TIME TIMESTAMP (6)
   ) ;

CREATE TABLE METADATA_EXPORT_FILE_CONFIG 
   (	METADATA_CONFIG_NAME VARCHAR2(200), 
	METADATA_CONFIG_VALUE VARCHAR2(4000), 
	METADATA_CONFIG_VARIABLE VARCHAR2(250), 
	IS_ACTIVE VARCHAR2(1), 
	EXECUTION_ORDER NUMBER
   ) ;



CREATE TABLE METADATA_EXPORT_TABLE_CONFIG 
   (	METADATA_TABLE_ID NUMBER, 
	METADATA_TABLE_NAME VARCHAR2(200), 
	METADATA_TABLE_ALIAS_NAME VARCHAR2(100), 
	METADATA_TABLE_SEQ NUMBER, 
	METADATA_TABLE_DELETE_SEQ NUMBER, 
	METADATA_FETCH_QUERY CLOB, 
	IS_ACTIVE VARCHAR2(1), 
	METADATA_NOTEXIST_COND_COL VARCHAR2(4000), 
	METADATA_IS_UPDATE VARCHAR2(1),
	METADATA_ENTITY_TYPE             VARCHAR2(100)
   ) ;


CREATE TABLE METADATA_EXPORT_TRACE 
   (	METADATA_EXPORT_EXECUTION_ID NUMBER, 
	METADATA_EXPORT_PROC_NAME VARCHAR2(500), 
	METADATA_EXPORT_LOGS VARCHAR2(4000), 
	METADATA_EXPORT_DYNAMIC_SCRIPT CLOB, 
	METADATA_EXPORT_EXECUTION_TIME TIMESTAMP (6), 
	METADATA_EXECUTION_PID NUMBER
   ) ;

CREATE TABLE METADATA_SCRIPT_EXPORT 
   (	IP_PID NUMBER, 
	OP_SCRIPTS CLOB, 
	CREATED_DATE TIMESTAMP (6), 
	OP_SCRIPTS_DEL CLOB, 
	SCRIPT_TYPE VARCHAR2(100), 
	IP_RELATED_PID NUMBER, 
	EXPORTED_BY VARCHAR2(100), 
	EXPORT_IDENTIFIER VARCHAR2(200),
	EXPORT_DURATION         VARCHAR2(100) 
   ) ;

CREATE TABLE OBJECT_CHANGE_DETAILS 
   (	SCRIPT_ID NUMBER, 
	BASELINE VARCHAR2(30), 
	RELEASE_NO VARCHAR2(100), 
	TAG_ID VARCHAR2(50), 
	SCRIPT_PATH VARCHAR2(200), 
	SCRIPT_DIRECTORY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	FILE_NAME VARCHAR2(250), 
	STATUS VARCHAR2(10), 
	VERSION NUMBER, 
	DESCRIPTION VARCHAR2(100), 
	REFERENCE_ID VARCHAR2(100), 
	ENTITY_ID NUMBER, 
	ENTITY_TYPE VARCHAR2(100), 
	CREATED_BY VARCHAR2(100), 
	ENTITY_STATUS VARCHAR2(100), 
	ENVIRONMENT_URL VARCHAR2(250), 
	APPLICATION_NAME VARCHAR2(100), 
	ENTITY_NAME VARCHAR2(250), 
	SCAN_STATUS VARCHAR2(50), 
	SMOKE_STATUS VARCHAR2(50), 
	TIME_TAKEN VARCHAR2(50), 
	PIPELINE_NAME VARCHAR2(500), 
	INJECT_PROPERTY VARCHAR2(500), 
	CONNECTION_STATUS VARCHAR2(100), 
	SOURCE_URL VARCHAR2(250), 
	SOURCE_ENVIRONMENT_URL VARCHAR2(250), 
	PARENT_SCRIPT_ID NUMBER, 
	RELEASE_TYPE VARCHAR2(1000), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE PARAMETER 
   (	PARAMETER_ID NUMBER, 
	PARAMETER_NAME VARCHAR2(100), 
	VERSION NUMBER, 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	LIFECYCLE_ID NUMBER, 
	PARAMETER_CONTROL_TYPE VARCHAR2(100), 
	PARAMETER_FORMAT_TYPE VARCHAR2(100), 
	SEARCHABLE VARCHAR2(50), 
	DESCRIPTION VARCHAR2(100), 
	PARAMETER_LENGTH NUMBER, 
	QUANTIFIABLE VARCHAR2(50), 
	DISPLAY_NAME VARCHAR2(100), 
	PARENT_ID NUMBER, 
	GRANDFATHERED VARCHAR2(50), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE PARAMETER_ADDON_SPECIFICATION 
   (	PARAM_ADDON_SPEC_ID NUMBER, 
	DISPLAY_TYPE VARCHAR2(50), 
	REQUIREMENT_TYPE VARCHAR2(50), 
	INITIAL_VALUE VARCHAR2(50), 
	LABEL VARCHAR2(50), 
	ICON VARCHAR2(50), 
	POSITION VARCHAR2(50), 
	IMG_EFFECT_COLOR VARCHAR2(50), 
	PARENT_ID NUMBER, 
	PARAM_SEQUENCE VARCHAR2(50), 
	FLYOVER VARCHAR2(50), 
	DISPLAY_NAME VARCHAR2(100), 
	NAME VARCHAR2(100), 
	STATUS VARCHAR2(50), 
	DESCRIPTION VARCHAR2(255), 
	STARTDATE TIMESTAMP (6), 
	ENDDATE TIMESTAMP (6), 
	GRANDFATHERED VARCHAR2(100), 
	QUANTIFIABLE VARCHAR2(100), 
	CATEGORY VARCHAR2(100), 
	EXTERNAL_REFERENCE_ID VARCHAR2(100), 
	CRITERIA_TYPE VARCHAR2(50), 
	FORMATION VARCHAR2(50), 
	DISPLAY_INFORMATION VARCHAR2(255), 
	LIFECYCLE_ID NUMBER, 
	ACTION VARCHAR2(100), 
	VALUETYPE VARCHAR2(100), 
	SUBTYPE VARCHAR2(100), 
	PARAMETERTYPE VARCHAR2(100), 
	MINLENGTH NUMBER, 
	MAXLENGTH NUMBER, 
	DATEFORMAT VARCHAR2(100), 
	TIMEFORMAT VARCHAR2(100), 
	DEFAULT_VALUE VARCHAR2(4000), 
	CATALOG_ID NUMBER, 
	IMAGE_URL VARCHAR2(255), 
	CHANNEL_TYPE VARCHAR2(100), 
	VISIBILITY VARCHAR2(100), 
	CONDITIONAL VARCHAR2(100), 
	DISPLAY_ONLY VARCHAR2(255), 
	OPTIONAL VARCHAR2(255), 
	MANDATORY VARCHAR2(50), 
	FORMAT_TYPE_VALUE VARCHAR2(50), 
	PRECISION NUMBER, 
	NUMBER_SEPERATOR NUMBER, 
	NEGATIVE_NUMBER VARCHAR2(50), 
	SYMBOL VARCHAR2(50), 
	VERTICAL_ALIGNMENT VARCHAR2(50), 
	HORIZONTAL_ALIGNMENT VARCHAR2(50), 
	SPECIAL_FORMATING VARCHAR2(50), 
	SPECIAL_FORMATING_EXPRESSION VARCHAR2(50), 
	LOCALIZATION VARCHAR2(100), 
	CUSTOM_MASK VARCHAR2(100), 
	MASK_TYPE VARCHAR2(100), 
	LIST_SEARCH_TYPE VARCHAR2(100), 
	LIST_FILTER_TYPE VARCHAR2(100), 
	LIST_REFERENCE_ID NUMBER, 
	LIST_DYNAMIC_REFERENCE_ID NUMBER, 
	VERSION NUMBER, 
	HEIGHT NUMBER, 
	WIDTH NUMBER, 
	END_VALUE NUMBER, 
	START_VALUE NUMBER, 
	MASK_POSITION NUMBER, 
	MASK_PADDING NUMBER, 
	MAX_LINE NUMBER, 
	FORMATING VARCHAR2(50), 
	FORMATING_TYPE VARCHAR2(50), 
	ROW_SPEC_ID NUMBER, 
	ALLOWPAST VARCHAR2(50), 
	FONT_WEIGHT VARCHAR2(50), 
	FONT_COLOR VARCHAR2(50), 
	IMG_SIZE NUMBER, 
	IMG_EFFECT_THICKNESS NUMBER, 
	FONT_SIZE VARCHAR2(150), 
	EFFECT_SIZE VARCHAR2(150), 
	EFFECT_HOVER_COLOR VARCHAR2(150), 
	EFFECT_ACTIVE_COLOR VARCHAR2(150), 
	LANGUAGE VARCHAR2(150), 
	CALENDER_TYPE VARCHAR2(150), 
	SPECIAL_FORMAT_TYPE VARCHAR2(50), 
	DYNAMIC_IMAGE VARCHAR2(5), 
	PARAMETER_USE_OPTION VARCHAR2(100), 
	SORTING_ORDER VARCHAR2(20), 
	DEPENDENCY VARCHAR2(10), 
	LINE_HEIGHT VARCHAR2(50), 
	TEXT_DECORATION VARCHAR2(50), 
	TEXT_ALIGN VARCHAR2(50), 
	TEXT_TRANSFORM VARCHAR2(50), 
	OPACITY VARCHAR2(50), 
	Z_INDEX VARCHAR2(50), 
	BACKGROUND_IMAGE VARCHAR2(50), 
	BACKGROUND_SIZE VARCHAR2(50), 
	BACKGROUND_POSITION VARCHAR2(50), 
	BACKGROUND_REPEAT VARCHAR2(50), 
	MARGIN VARCHAR2(50), 
	MARGIN_RIGHT VARCHAR2(50), 
	MARGIN_BOTTOM VARCHAR2(50), 
	PADDING VARCHAR2(50), 
	PADDING_RIGHT VARCHAR2(50), 
	PADDING_BOTTOM VARCHAR2(50), 
	BORDER VARCHAR2(50), 
	BORDER_LEFT VARCHAR2(50), 
	BORDER_RIGHT VARCHAR2(50), 
	BORDER_TOP VARCHAR2(50), 
	BORDER_BOTTOM VARCHAR2(50), 
	BORDER_COLOR VARCHAR2(50), 
	BORDER_RADIUS VARCHAR2(50), 
	BOX_SHADOW VARCHAR2(50), 
	MAX_WIDTH VARCHAR2(50), 
	MAX_HEIGHT VARCHAR2(50), 
	TOP VARCHAR2(50), 
	BOTTOM VARCHAR2(50), 
	CONTENT VARCHAR2(50), 
	CURSOR VARCHAR2(50), 
	DISPLAY VARCHAR2(50), 
	FLEX VARCHAR2(50), 
	FLEX_BASIS VARCHAR2(50), 
	FLEX_DIRECTION VARCHAR2(50), 
	FLEX_FLOW VARCHAR2(50), 
	FLEX_GROW VARCHAR2(50), 
	FLEX_SHRINK VARCHAR2(50), 
	FLEX_WRAP VARCHAR2(50), 
	ALIGN_ITEMS VARCHAR2(50), 
	JUSTIFY_CONTENT VARCHAR2(50), 
	OVERFLOW VARCHAR2(50), 
	OVERFLOW_X VARCHAR2(50), 
	OVERFLOW_Y VARCHAR2(50), 
	WHITE_SPACE VARCHAR2(50), 
	TEXT_OVERFLOW VARCHAR2(50), 
	TRANSFORM VARCHAR2(50), 
	LETTER_SPACING VARCHAR2(50), 
	BACKGROUND_COLOUR VARCHAR2(50), 
	PADDING_LEFT VARCHAR2(50), 
	PADDING_TOP VARCHAR2(50), 
	LEFT VARCHAR2(50), 
	RIGHT VARCHAR2(50), 
	MARGIN_LEFT VARCHAR2(50), 
	MARGIN_TOP VARCHAR2(50), 
	CLASS_NAME VARCHAR2(100), 
	EXT_REFERENCE_NAME VARCHAR2(100), 
	TRANSFORMATION_PARAMETER VARCHAR2(100), 
	DEFAULT_TIME TIMESTAMP (6), 
	SYSTEM_TIME VARCHAR2(10), 
	FORMAT_TYPE VARCHAR2(1000), 
	TIME_FORMAT VARCHAR2(1000), 
	DISPLAY_REQUIRED VARCHAR2(10), 
	ORIENTATION VARCHAR2(50), 
	IS_RANGE VARCHAR2(10), 
	RANGE_START NUMBER, 
	RANGE_END NUMBER, 
	IS_UPDATED VARCHAR2(10), 
	ALLOWFUTURE VARCHAR2(10), 
	SPACEREQUIRED VARCHAR2(10), 
	SUFFIXREQUIRED VARCHAR2(10), 
	SUFFIXDESCRIPTION VARCHAR2(100), 
	UPPERCASEREQUIRED VARCHAR2(10), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	PREFERENCE NUMBER, 
	PLACEHOLDER VARCHAR2(100), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   )  ENABLE ROW MOVEMENT ;


CREATE TABLE PARAMETER_DATA_SPECIFICATION 
   (	PARAM_DATA_SPEC_ID NUMBER, 
	DATA_STORE_NAME VARCHAR2(200), 
	ENTRY_TYPE VARCHAR2(100), 
	INPUT_DATA_NAME VARCHAR2(100), 
	OUTPUT_DATA_NAME VARCHAR2(100), 
	REFERENCE_STORE_ID NUMBER, 
	REFERENCE_TYPE VARCHAR2(100), 
	MIN_SELECTION NUMBER, 
	MAX_SELECTION NUMBER, 
	SEARCHABLE VARCHAR2(100), 
	FILTER_TYPE VARCHAR2(2000), 
	DYNAMIC_REF_ID NUMBER, 
	PARENT_ID NUMBER, 
	PARAM_SEQUENCE VARCHAR2(50), 
	LIFECYCLE_ID NUMBER, 
	VERSION NUMBER, 
	REFERENCE_DATA_URL VARCHAR2(100), 
	FILTER_OPERATOR VARCHAR2(2000), 
	FILTER_VALUES VARCHAR2(2000), 
	INPUT_SEARCH_VALUES VARCHAR2(3000), 
	GRANDFATHERED VARCHAR2(50), 
	FUNCTION_TYPE VARCHAR2(25), 
	DATA_FUNCTIONS VARCHAR2(25), 
	PARTITION VARCHAR2(100), 
	ORDER_BY VARCHAR2(100), 
	REL_DATA_STORE_NAME VARCHAR2(100), 
	DEFAULT_VALUE VARCHAR2(100), 
	ALIAS_NAME VARCHAR2(100), 
	DATA_SOURCE VARCHAR2(100), 
	FIELD_TYPE VARCHAR2(100), 
	REQUIREMENT_TYPE VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	IS_UPDATED VARCHAR2(10), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE PARAMETER_FORMAT_ADDON_SPEC 
   (	PARAM_FORMAT_ADDON_SPEC_ID NUMBER, 
	PARAM_SPEC_ID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	VERSION NUMBER, 
	PARAM_FORMAT_SUB_TYPE VARCHAR2(1000), 
	PARAM_FORMAT_ADDON_VALUES VARCHAR2(1000), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(200), 
	IS_UPDATED VARCHAR2(10), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE PARAMETER_FUNC_SPECIFICATION 
   (	PARAM_FUNC_SPEC_ID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	VERSION NUMBER, 
	PARAM_SPEC_ID NUMBER, 
	PARAM_FUNC_TYPE VARCHAR2(1000), 
	PARAM_FUNC_KEY VARCHAR2(1000), 
	PARAM_FUNC_VALUE VARCHAR2(4000), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(200), 
	IS_UPDATED VARCHAR2(10), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE PARAMETER_LOCALE_SPECIFICATION 
   (	LOCALIZATION_ID NUMBER, 
	LOCALIZATION_COUNTRY VARCHAR2(100), 
	SPECIAL_FORMATING_EXPRESSION VARCHAR2(100), 
	SPECIAL_FORMATING VARCHAR2(100), 
	LOCALE VARCHAR2(100), 
	CALENDER_TYPE VARCHAR2(100), 
	SYMBOL VARCHAR2(100), 
	DATE_FORMAT_VALUE VARCHAR2(100), 
	PRECISION NUMBER, 
	NUMBER_SEPERATOR NUMBER, 
	TIME_FORMAT_VALUE VARCHAR2(100), 
	LIFECYCLE_ID NUMBER, 
	NUMBER_FORMAT_VALUE VARCHAR2(100), 
	ALIGNMENT VARCHAR2(50), 
	UNIT_OF_METRICS VARCHAR2(50), 
	NUMBER_SEPARATOR_VALUE VARCHAR2(10), 
	GRANDFATHERED VARCHAR2(50)
   ) ;

CREATE TABLE PARAMETER_REFERENCE_VALUE 
   (	PARAM_SPEC_ID NUMBER, 
	REF_DEFAULT_ID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	VERSION NUMBER, 
	REF_VAL_ID NUMBER, 
	GRANDFATHERED VARCHAR2(50), 
	ENTITY_SPECIFICATION_TYPE VARCHAR2(100), 
	CATEGORY_TYPE VARCHAR2(100), 
	PARAM_REF_VAL_ID NUMBER DEFAULT PARAM_REF_VAL_ID_SEQ.NEXTVAL, 
	DETERMINANT_ID NUMBER, 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   )  ENABLE ROW MOVEMENT ;



CREATE TABLE PARAMETER_RULE_SPECIFICATION 
   (	PARAM_RULE_SPEC_ID NUMBER, 
	CONSTRAIN VARCHAR2(100), 
	CONS_VAL_START VARCHAR2(100), 
	CONS_VAL_END VARCHAR2(100), 
	CEILING_VALUE_MIN NUMBER, 
	BOOLEAN_SET VARCHAR2(100), 
	DECISION_TREE VARCHAR2(100), 
	RULE_CHECK VARCHAR2(100), 
	CUSTOM_RULE_CHECK VARCHAR2(100), 
	DYNMAIC_RULE_CHECK VARCHAR2(200), 
	PARENT_ID NUMBER, 
	PARAM_SEQUENCE VARCHAR2(50), 
	RULE_ID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	VERSION NUMBER, 
	DATA_STORE_NAME VARCHAR2(100), 
	ENTRY_TYPE VARCHAR2(100), 
	INPUT_DATA_STORE_NAME VARCHAR2(100), 
	OUTPUT_DATA_STORE_NAME VARCHAR2(100), 
	REFERENCE_STORE_ID NUMBER, 
	REFERENCE_TYPE VARCHAR2(100), 
	MIN_SELECTION VARCHAR2(100), 
	MAX_SELECTION VARCHAR2(100), 
	SEARCHABLE VARCHAR2(100), 
	FILLETER_TYPE VARCHAR2(100), 
	DYNAMIC_REFERENCE_ID NUMBER, 
	REFERENCE_VALUE VARCHAR2(50), 
	REFERENCE_VISIBILITY VARCHAR2(10), 
	VALUE_SET VARCHAR2(100), 
	BOOLEAN_VALUE_SET VARCHAR2(100), 
	BOOLEAN_VALUE VARCHAR2(100), 
	VALIDATION_TYPE VARCHAR2(255), 
	CEILING_VALUE_MAX NUMBER, 
	REGEX_VALUE VARCHAR2(255), 
	ERROR_ID NUMBER, 
	FUNCTION VARCHAR2(100), 
	VALUE VARCHAR2(500), 
	SEQUENCE_NO NUMBER, 
	BOOLEAN_FUNCTION VARCHAR2(5), 
	EDITABLE_REFERENCE VARCHAR2(50), 
	RULE_SCRIPT_ID NUMBER, 
	ASSOCIATED_PROCESS_ID NUMBER, 
	EXPRESSION_TYPE VARCHAR2(50), 
	CONDITIONAL_FUNCTION VARCHAR2(50), 
	COMPLEX_FUNCTION VARCHAR2(50), 
	GRANDFATHERED VARCHAR2(50), 
	VALUE_URL VARCHAR2(250), 
	GROUPING_EXPRESSION VARCHAR2(50), 
	EP_NAME VARCHAR2(100), 
	EP_CODE VARCHAR2(10), 
	EP_IAC VARCHAR2(50), 
	EP_ENDPOINT_TYPE_ID VARCHAR2(100), 
	ENTITY_TYPE_ID NUMBER, 
	ENTITY_ID NUMBER, 
	PARENT_BID NUMBER, 
	APPEND_TYPE VARCHAR2(100), 
	LABEL_NAME VARCHAR2(200), 
	SELECTED_VALUES VARCHAR2(2000), 
	TRANSFORMATION_VALUE VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE PARAMETER_SPECIFICATION 
   (	PARAM_BASIC_SPEC_ID NUMBER, 
	PARAM_CONTROL_TYPE VARCHAR2(100), 
	PARAM_FORMAT_TYPE VARCHAR2(100), 
	VERSION NUMBER, 
	PARENT_ID NUMBER, 
	SEARCHABLE VARCHAR2(50), 
	PARAM_NAME VARCHAR2(100), 
	DESCRIPTION VARCHAR2(100), 
	PARAM_SEQUENCE NUMBER, 
	PARAM_LENGTH NUMBER, 
	QUANTIFIABLE VARCHAR2(50), 
	LIFECYCLE_ID NUMBER, 
	CHANNEL_TYPE VARCHAR2(100), 
	GRANDFATHERED VARCHAR2(50), 
	PARAM_LISTING_FLAG VARCHAR2(10), 
	CORE_SPEC VARCHAR2(25), 
	SOURCE VARCHAR2(100), 
	EXTERNAL_CATALOG_ID VARCHAR2(100), 
	RULE_BASED_ON VARCHAR2(100), 
	IS_UPDATED VARCHAR2(10), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	IS_REVISABLE VARCHAR2(3), 
	PARAMETER_TYPE VARCHAR2(100), 
	EXPORT_IDENTIFIER VARCHAR2(200), 
	REPORTING_COLUMN VARCHAR2(100), 
	DATA_SOURCE_COLUMN VARCHAR2(100)
   ) ;


CREATE TABLE PRICE_PLAN 
   (	PRICE_PLAN_ID NUMBER, 
	PRICE_PLAN_NAME VARCHAR2(300), 
	PRICE_PLAN_DESC VARCHAR2(1500), 
	VERSION NUMBER, 
	PRICE_PLAN_START_DATE DATE, 
	CREATED_BY VARCHAR2(4000), 
	CREATED_DATE DATE, 
	MODIFIED_BY VARCHAR2(4000), 
	MODIFIED_DATE DATE, 
	PRICE_PLAN_END_DATE DATE, 
	PRICE_PLAN_DISP_NAME VARCHAR2(300), 
	PRICE_PLAN_IMAGE_URL VARCHAR2(1000), 
	PRICE_PLAN_GRANDFATHERED VARCHAR2(3), 
	CURRENCY_ID VARCHAR2(50), 
	STARTDATE TIMESTAMP (6), 
	ENDDATE TIMESTAMP (6), 
	GRANDFATHERED VARCHAR2(100), 
	QUANTIFIABLE VARCHAR2(100), 
	CATEGORY VARCHAR2(100), 
	EXTERNAL_REFERENCE_ID VARCHAR2(100), 
	LIFECYCLE_ID NUMBER, 
	DEFAULT_VALUE VARCHAR2(255), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE PRICE_PLAN_COUNTER 
   (	PRICE_PLAN_PRICING_ID NUMBER, 
	PRICE_PLAN_ITEM_ID NUMBER, 
	VERSION NUMBER, 
	COUNTER_ID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	GRANDFATHERED VARCHAR2(50)
   ) ;

CREATE TABLE PRICE_PLAN_ENTITY 
   (	ENTITY_ID NUMBER, 
	ENTITY_TYPE VARCHAR2(50), 
	PLAN_ID NUMBER, 
	VALID_FROM DATE, 
	VERSION NUMBER, 
	GRANDFATHERED VARCHAR2(50), 
	PRICE_PLAN_ENTITY_ID NUMBER DEFAULT PRICE_PLAN_ENTITY_ID_SEQ.NEXTVAL, 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE PRICE_PLAN_SPECIFICATION 
   (	PP_INSTANCE_ID NUMBER, 
	PP_ITEM_NAME VARCHAR2(100), 
	VERSION NUMBER, 
	PARENT_ID NUMBER, 
	PRIORITY NUMBER, 
	SEQUENCE NUMBER, 
	CHARGE_ITEM_TYPE VARCHAR2(100), 
	UNIT_OF_MEASURE_BASELINED VARCHAR2(100), 
	CHARGE_UNIT_CUSTOM NUMBER, 
	STARTDATE TIMESTAMP (6), 
	ENDDATE TIMESTAMP (6), 
	PRICE_PLAN_ID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	DEFAULT_VALUE VARCHAR2(255), 
	SERVICE_ENTITY_ID NUMBER, 
	CHARGE_UNIT_BASELINED VARCHAR2(50), 
	PRODUCT_CODE_ID NUMBER, 
	DECISION_TREE_NODE_ID NUMBER, 
	DETERMINANT_RULE_ID NUMBER, 
	CHARGING_ALGORITHM_ID NUMBER, 
	GRANDFATHERED VARCHAR2(50), 
	PROMO_CODE VARCHAR2(100), 
	DESCRIPTION VARCHAR2(250), 
	PROMOTION_TYPE VARCHAR2(100), 
	VALIDITY VARCHAR2(100), 
	VALIDATION_TYPE VARCHAR2(100), 
	DURATION VARCHAR2(100), 
	USAGE_LIMIT VARCHAR2(100), 
	NO_OF_LIMITS VARCHAR2(100), 
	EXPIRY VARCHAR2(250), 
	EXPIRY_TYPE VARCHAR2(200), 
	ENTITY_RELATION_ID NUMBER, 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE PROCESS_ACTION_SPECIFICATION 
   (	ACTION_ID NUMBER, 
	ACTION_NAME VARCHAR2(100), 
	DESCRIPTION VARCHAR2(255), 
	ACTION_BOTTON_TYPE VARCHAR2(100), 
	PROCESS_TYPE VARCHAR2(100), 
	DISPLAY_NAME VARCHAR2(100), 
	FLYOVER_TEXT VARCHAR2(100), 
	SEQUENCE NUMBER, 
	ACTION_LENGTH VARCHAR2(50), 
	ACTION_VISIBLE VARCHAR2(50), 
	FORMATTING VARCHAR2(100), 
	QUANTIFIABLE VARCHAR2(100), 
	PARENT_ID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	VERSION NUMBER, 
	ACTION VARCHAR2(50), 
	ACTION_URL VARCHAR2(4000), 
	FUNCTION_TYPE VARCHAR2(50), 
	ACTION_TYPE VARCHAR2(50), 
	WIDTH NUMBER, 
	TOP_MARGIN NUMBER, 
	LEFT_MARGIN NUMBER, 
	HEIGHT NUMBER, 
	POSITION VARCHAR2(50), 
	RESPONSE_HANDLER VARCHAR2(50), 
	ACTION_PROCESS_ID NUMBER, 
	BUTTON_ICON VARCHAR2(50), 
	ACTION_LOAD_PROCESS_ID NUMBER, 
	BUTTON_COLOUR VARCHAR2(10), 
	ACTION_ENTITY_TYPE VARCHAR2(100), 
	GRANDFATHERED VARCHAR2(50), 
	ACTION_QUEUE_ID NUMBER, 
	ACTION_VALUE VARCHAR2(500), 
	ACTION_MAPPING_PROCESS_ID NUMBER, 
	ACTION_MAPPING_NAME VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE PROCESS_ENTITY 
   (	PID NUMBER, 
	PROCESS_ENTITY_NAME VARCHAR2(200), 
	VERSION NUMBER, 
	TYPE VARCHAR2(100), 
	PARENT_ID NUMBER, 
	PROCESS_SEQUENCE VARCHAR2(200), 
	LIFECYCLE_ID NUMBER, 
	ACTION_TYPE VARCHAR2(100), 
	DISPLAY_NAME VARCHAR2(100), 
	PROCESS_FLAG VARCHAR2(20), 
	CHART_ID NUMBER, 
	ROOT_ID NUMBER, 
	HIERARCHY_TYPE VARCHAR2(50), 
	REVERSE_PROCESS_FLAG VARCHAR2(50), 
	REVERSE_PROCESS_ID NUMBER, 
	GRANDFATHERED VARCHAR2(50), 
	IS_REQUIRED VARCHAR2(30), 
	OUTPUT_PORT_NUMBER NUMBER, 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	ENTITY_COLOR_CODE VARCHAR2(15), 
	IS_UPDATED VARCHAR2(10), 
	IS_MODIFICATION_INITIATED VARCHAR2(1) DEFAULT 'N', 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE PROCESS_ENTITY_ERROR_MAPPING 
   (	PROCESS_ENTITY_ID NUMBER, 
	PROCESS_ENTITY_TYPE VARCHAR2(100), 
	ERROR_ID NUMBER
   ) ;

CREATE TABLE PROCESS_ENTITY_SPECIFICATION 
   (	PROCESS_SPEC_ID NUMBER, 
	PID NUMBER, 
	NAME VARCHAR2(100), 
	DESCRIPTION VARCHAR2(4000), 
	VERSION NUMBER, 
	START_DATE TIMESTAMP (6), 
	END_DATE TIMESTAMP (6), 
	SEQUENCE NUMBER, 
	TYPE VARCHAR2(100), 
	DISPLAY_NAME VARCHAR2(255), 
	ICON VARCHAR2(255), 
	LIFECYCLE_ID NUMBER, 
	LAUNCH_TYPE VARCHAR2(30), 
	TASK_ID NUMBER, 
	TASK_DESCRIPTION VARCHAR2(500), 
	TASK_TYPE VARCHAR2(500), 
	TASK_GROUP_ID NUMBER, 
	TASK_GROUP_NAME VARCHAR2(500), 
	CATEGORIES VARCHAR2(500), 
	TASK_DURATION NUMBER, 
	EXECUTION_URL VARCHAR2(255), 
	DEPENDENT_TASK VARCHAR2(255), 
	PAYLOAD_TYPE VARCHAR2(255), 
	CONDITIONAL VARCHAR2(10), 
	HIERARCHY_ID NUMBER, 
	STANDARD_TASK_AGE NUMBER, 
	GRACE_TASK_AGE NUMBER, 
	CRITICAL_TASK_AGE NUMBER, 
	DATA_LOAD_TYPE VARCHAR2(40) DEFAULT 'Normal', 
	DEFAULT_INITIALIZATION VARCHAR2(10) DEFAULT 'FALSE', 
	REUSABLE_PROCESS VARCHAR2(10) DEFAULT 'FALSE', 
	PROCESS_GROUP VARCHAR2(250), 
	CHANNEL_TYPE VARCHAR2(100), 
	QUANTIFIABLE VARCHAR2(50) DEFAULT 'No', 
	DEPENDENCY_ID NUMBER, 
	EVENT_DURATION_TYPE VARCHAR2(150), 
	EVENT_DURATION_VALUE VARCHAR2(150), 
	EVENT_TIMER_CYCLE VARCHAR2(150), 
	EVENT_RECURRENCE_TYPE VARCHAR2(150), 
	EVENT_DATE_TIME TIMESTAMP (6), 
	EVENT_CHECKBOX VARCHAR2(150), 
	EVENT_START_TIME VARCHAR2(150), 
	EVENT_REF_DAY_ID NUMBER, 
	EVENT_RECURR_PATTERN VARCHAR2(150), 
	WEEK VARCHAR2(150), 
	MONTH VARCHAR2(150), 
	YEAR VARCHAR2(150), 
	DEFAULT_INSTANCE VARCHAR2(10) DEFAULT 'False', 
	TASK_API_TYPE VARCHAR2(100), 
	METHOD_API_TYPE VARCHAR2(100), 
	CALLING_URL VARCHAR2(250), 
	GRANDFATHERED VARCHAR2(50), 
	PROCESS_METHOD_TYPE VARCHAR2(50), 
	AUTHENTICATION_REQUIRED VARCHAR2(10), 
	AUTHENTICATION_TYPE VARCHAR2(50), 
	EXTERNAL_API_USERNAME VARCHAR2(100), 
	EXTERNAL_API_PASSWORD VARCHAR2(100), 
	EXTERNAL_API_ENDPOINT VARCHAR2(250), 
	OUTBOUND_SERVICE_NAME VARCHAR2(100), 
	RETIRED_FROM TIMESTAMP (6), 
	REQUEST_FUNCTION_ID NUMBER, 
	OBJECT_TYPE VARCHAR2(500), 
	TASK_SUBTYPE VARCHAR2(150), 
	RESPONSE_FUNCTION_ID NUMBER, 
	CALCULATE_FROM VARCHAR2(150), 
	CALCULATE_BASED_ON VARCHAR2(150), 
	CUSTOM_RULE VARCHAR2(150), 
	ASSIGN_WHEN VARCHAR2(100), 
	AUTO_ASSIGN VARCHAR2(100), 
	ASSIGN_RULE VARCHAR2(100), 
	ENTITY_FUNCTION_ID NUMBER, 
	RELATIVE_PARENT VARCHAR2(100) DEFAULT 'false', 
	LOOP_COUNT NUMBER, 
	MANDATORY_VALIDATION_REQUIRED VARCHAR2(10), 
	ISACTIVE VARCHAR2(100), 
	REPORT_ID NUMBER, 
	INTERNAL_FLAG VARCHAR2(10), 
	DEPENDENT_ASYNC_TASK_ID NUMBER, 
	OUTBOUND_FAILURE_SERVICE_NAME VARCHAR2(100), 
	INBOUND_API_PROFILE VARCHAR2(100), 
	INBOUND_API_PROFILE_VALUE VARCHAR2(100), 
	ERROR_FUNCTION_ID NUMBER, 
	IS_TRANSACTION_PERSIST CHAR(1), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	ASYNC_SLA_REQUIRED VARCHAR2(10) DEFAULT 'False', 
	ASYNC_SLA_DURATION NUMBER, 
	ALLOW_MULTIPLE_RESPONSE CHAR(1), 
	IS_UPDATED VARCHAR2(10), 
	EXPORT_IDENTIFIER VARCHAR2(200), 
	CHATBOT_AGENT_ID NUMBER
   ) ;

CREATE TABLE PROCESS_FUNCTION_MAPPING 
   (	FUNCTION_SPEC_ID NUMBER, 
	FUNCTION_NAME VARCHAR2(100), 
	FUNCTION_TYPE VARCHAR2(25), 
	ENTITY_TYPE VARCHAR2(50), 
	ENTRY_TYPE VARCHAR2(30), 
	ENTITY_ID NUMBER, 
	PARENT_ID NUMBER, 
	ERROR_CODE NUMBER, 
	MESSAGE_CODE NUMBER, 
	ENTITY_VALUE VARCHAR2(4000), 
	VERSION NUMBER, 
	LIFECYCLE_ID NUMBER
   ) ;

CREATE TABLE PROCESS_LAYOUT_SPECIFICATION 
   (	LAYOUT_ID NUMBER, 
	NAME VARCHAR2(100), 
	DESCRIPTION_TYPE VARCHAR2(100), 
	DESCRIPTION VARCHAR2(255), 
	DISPLAY_NAME VARCHAR2(100), 
	FLYOVER_TEXT VARCHAR2(100), 
	SEQUENCE NUMBER, 
	PARENT_ID NUMBER, 
	LIFECYCLE_ID NUMBER, 
	VERSION NUMBER, 
	HEIGHT NUMBER, 
	WIDTH NUMBER, 
	TOP_MARGIN NUMBER, 
	LEF_MARGIN NUMBER, 
	COLLAPSIBLE VARCHAR2(10), 
	VISIBILITY VARCHAR2(5), 
	ISPANEL VARCHAR2(50), 
	LAYOUT_ACTION_TYPE VARCHAR2(100), 
	MINVAL NUMBER, 
	MAXVAL NUMBER, 
	FONT_COLOR VARCHAR2(50), 
	IMG_WEIGHT VARCHAR2(50), 
	FONT_SIZE VARCHAR2(150), 
	HORIZONTAL_ALIGNMENT VARCHAR2(50), 
	CHART_ID NUMBER, 
	DYNAMIC_PARAMETER_CHECK VARCHAR2(20), 
	LINE_HEIGHT VARCHAR2(50), 
	TEXT_DECORATION VARCHAR2(50), 
	TEXT_ALIGN VARCHAR2(50), 
	TEXT_TRANSFORM VARCHAR2(50), 
	OPACITY VARCHAR2(50), 
	Z_INDEX VARCHAR2(50), 
	BACKGROUND_IMAGE VARCHAR2(50), 
	BACKGROUND_SIZE VARCHAR2(50), 
	BACKGROUND_POSITION VARCHAR2(50), 
	BACKGROUND_REPEAT VARCHAR2(50), 
	MARGIN VARCHAR2(50), 
	MARGIN_RIGHT VARCHAR2(50), 
	MARGIN_BOTTOM VARCHAR2(50), 
	PADDING VARCHAR2(50), 
	PADDING_RIGHT VARCHAR2(50), 
	PADDING_BOTTOM VARCHAR2(50), 
	BORDER VARCHAR2(50), 
	BORDER_LEFT VARCHAR2(50), 
	BORDER_RIGHT VARCHAR2(50), 
	BORDER_TOP VARCHAR2(50), 
	BORDER_BOTTOM VARCHAR2(50), 
	BORDER_COLOR VARCHAR2(50), 
	BORDER_RADIUS VARCHAR2(50), 
	BOX_SHADOW VARCHAR2(50), 
	MAX_WIDTH VARCHAR2(50), 
	MAX_HEIGHT VARCHAR2(50), 
	POSITION VARCHAR2(50), 
	TOP VARCHAR2(50), 
	BOTTOM VARCHAR2(50), 
	CONTENT VARCHAR2(50), 
	CURSOR VARCHAR2(50), 
	DISPLAY VARCHAR2(50), 
	FLEX VARCHAR2(50), 
	FLEX_BASIS VARCHAR2(50), 
	FLEX_DIRECTION VARCHAR2(50), 
	FLEX_FLOW VARCHAR2(50), 
	FLEX_GROW VARCHAR2(50), 
	FLEX_SHRINK VARCHAR2(50), 
	FLEX_WRAP VARCHAR2(50), 
	ALIGN_ITEMS VARCHAR2(50), 
	JUSTIFY_CONTENT VARCHAR2(50), 
	OVERFLOW VARCHAR2(50), 
	OVERFLOW_X VARCHAR2(50), 
	OVERFLOW_Y VARCHAR2(50), 
	WHITE_SPACE VARCHAR2(50), 
	TEXT_OVERFLOW VARCHAR2(50), 
	TRANSFORM VARCHAR2(50), 
	LAYOUT_HEIGHT VARCHAR2(50), 
	LAYOUT_TOP_MARGIN VARCHAR2(50), 
	LAYOUT_LEFT_MARGIN VARCHAR2(50), 
	LAYOUT_WIDTH VARCHAR2(50), 
	LETTER_SPACING VARCHAR2(50), 
	BACKGROUND_COLOUR VARCHAR2(50), 
	PADDING_LEFT VARCHAR2(50), 
	PADDING_TOP VARCHAR2(50), 
	LEFT VARCHAR2(50), 
	RIGHT VARCHAR2(50), 
	FONT_WEIGHT VARCHAR2(50), 
	CLASS_NAME VARCHAR2(100), 
	LAZY_LOAD VARCHAR2(50), 
	GRANDFATHERED VARCHAR2(50), 
	LAYOUT_SUBTYPE VARCHAR2(100) DEFAULT 'false', 
	CHART_NAME VARCHAR2(200), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	IS_UPDATED VARCHAR2(10), 
	EXPORT_IDENTIFIER VARCHAR2(200), 
	CHART_PAGE_SELECTION NUMBER
   ) ;

CREATE TABLE PRODUCT_CODE_DETAILS 
   (	PRODUCT_CODE_ID NUMBER, 
	PRODUCT_CODE_NAME VARCHAR2(250), 
	PRODUCT_CODE_START_DATE DATE, 
	PRODUCT_CODE_END_DATE DATE, 
	PRODUCT_CODE_DESCRIPTION VARCHAR2(2500), 
	PRODUCT_TYPE_ID NUMBER, 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	EXTERNALCATALOG VARCHAR2(1000), 
	DIVISION VARCHAR2(1000), 
	EXTERNAL_ID VARCHAR2(100)
   ) ;

CREATE TABLE PRODUCT_MAPPING 
   (	FAMILY VARCHAR2(100), 
	MARKET_OFFERING VARCHAR2(100), 
	SERVICE VARCHAR2(100), 
	ELEMENT VARCHAR2(100), 
	ATTRIBUTE_NAME_1 VARCHAR2(100), 
	ATTRIBUTE_VALUE_1 VARCHAR2(100), 
	ATTRIBUTE_NAME_2 VARCHAR2(100), 
	ATTRIBUTE_VALUE_2 VARCHAR2(100), 
	ATTRIBUTE_NAME_3 VARCHAR2(100), 
	ATTRIBUTE_VALUE_3 VARCHAR2(100), 
	ATTRIBUTE_NAME_4 VARCHAR2(100), 
	ATTRIBUTE_VALUE_4 VARCHAR2(100), 
	ATTRIBUTE_NAME_5 VARCHAR2(100), 
	ATTRIBUTE_VALUE_5 VARCHAR2(100), 
	SERVICE_CODE VARCHAR2(50), 
	EXTERNAL_PRODUCT_ID NUMBER, 
	OFFERING_PROCESS_ID NUMBER, 
	SERVICE_PROCESS_ID NUMBER, 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE REFERENCE_HIERARCHY 
   (	REF_VAL_ID NUMBER, 
	HIERARCHY_ID NUMBER
   ) ;

CREATE TABLE REFERENCE_TYPES 
   (	REF_TYPE_ID NUMBER, 
	REF_TYPE_NAME VARCHAR2(200), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	ENTITY_TYPE VARCHAR2(100), 
	GRANDFATHERED VARCHAR2(50), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE REFERENCE_TYPE_VALUES 
   (	REF_VAL_ID NUMBER, 
	REF_TYPE_ID NUMBER, 
	HIERARCHY_ID NUMBER, 
	REF_VALUE VARCHAR2(500), 
	CREATED_BY VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	STATUS VARCHAR2(20), 
	SEQUENCE NUMBER, 
	REF_VAL_DESC VARCHAR2(1000), 
	SYS_DEFN_FLAG VARCHAR2(5), 
	ICON VARCHAR2(100), 
	REF_NAME VARCHAR2(500), 
	GRANDFATHERED VARCHAR2(50), 
	ROOT_FLAG VARCHAR2(5), 
	STARTDATE TIMESTAMP (6), 
	ENDDATE TIMESTAMP (6), 
	CATEGORY_TYPE VARCHAR2(100), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;


CREATE TABLE REF_CONTENT_MANAGEMENT 
   (	CONTENT_ID NUMBER, 
	CONTENT_NAME VARCHAR2(50), 
	CONTENT_TYPE VARCHAR2(50), 
	CONTENT_URL VARCHAR2(50), 
	CONTENT_DESCRIPTION VARCHAR2(50)
   ) ;

CREATE TABLE REF_ENTITY_TYPE 
   (	ENTITY_ID NUMBER, 
	ENTITY_TYPE VARCHAR2(500)
   ) ;

CREATE TABLE RULE 
   (	RULE_ID NUMBER, 
	RULE_NAME VARCHAR2(100), 
	RULE_DESC VARCHAR2(500), 
	EXPRESSION VARCHAR2(4000), 
	RULE_TYPE VARCHAR2(50), 
	ENTITY_ID NUMBER, 
	ENTITY_TYPE_ID NUMBER, 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	RULE_MESSAGE VARCHAR2(4000), 
	EVENT_TYPE VARCHAR2(50), 
	TYPE VARCHAR2(50), 
	TEMPLATE_ID NUMBER, 
	ERROR_CODE VARCHAR2(100), 
	SUCCESS_CODE VARCHAR2(100), 
	CUSTOM_FUNCTION VARCHAR2(100), 
	QUERY VARCHAR2(100), 
	MODEL VARCHAR2(255), 
	RULE_SEQUENCE NUMBER, 
	TEMPLATE VARCHAR2(250), 
	LIFECYCLE_ID NUMBER, 
	VERSION NUMBER, 
	PARENT_RULE_ID NUMBER, 
	ENTITY_EVENT_TYPE VARCHAR2(255), 
	GRANDFATHERED VARCHAR2(50), 
	CATEGORIES VARCHAR2(100), 
	RESPONSE_TYPE VARCHAR2(100), 
	CODE VARCHAR2(250), 
	EXTERNAL_SYSTEM_NAME VARCHAR2(100), 
	RULE_ACTION VARCHAR2(100), 
	RETRY_LIMIT VARCHAR2(100), 
	RETRY_TYPE VARCHAR2(100), 
	RETRY_CUSTOM_LOGIC VARCHAR2(250), 
	TRANSFORMATION_REQUIRED VARCHAR2(100), 
	TRANSFORMATION_CODE VARCHAR2(100), 
	TRANSFORMATION_MESSAGE VARCHAR2(100), 
	RULE_BASED_ON VARCHAR2(100), 
	RULE_EXECUTION VARCHAR2(100), 
	ERROR_SUBTYPE VARCHAR2(1000), 
	API_URL VARCHAR2(1000), 
	RETRY_INTERVAL NUMBER, 
	PROCESS_OFFERING_RULE VARCHAR2(100), 
	PRODUCT_CODE_ID NUMBER, 
	EXTERNALID VARCHAR2(500), 
	ROOT_ID NUMBER, 
	ERROR_GROUP VARCHAR2(50), 
	ROW_SPEC_ID NUMBER, 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE RULE_EXPRESSION 
   (	RULE_ID NUMBER, 
	ENTITY_TYPE_ID NUMBER, 
	ENTITY_ID NUMBER, 
	CRITERIA VARCHAR2(30), 
	FUNCTION VARCHAR2(30), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	VALUE VARCHAR2(100), 
	GROUP_IDENTIFIER VARCHAR2(100), 
	GROUP_CONDITION VARCHAR2(100), 
	TYPE VARCHAR2(250), 
	RULE_EXPRESSION_ID NUMBER, 
	CRITERIA_VALUE NUMBER, 
	RESULT_VALUE_TYPE VARCHAR2(100), 
	RESULT_VALUE NUMBER, 
	LIFECYCLE_ID NUMBER, 
	VERSION NUMBER, 
	RULE_EXPRESSION VARCHAR2(200), 
	PARENT_ID NUMBER
   ) ;

CREATE TABLE SCRIPT_INFO 
   (	SCRIPT_ID NUMBER, 
	SCRIPT_NAME VARCHAR2(1000), 
	SCRIPT_GROUP_ID NUMBER, 
	SCRIPT_TYPE VARCHAR2(50), 
	SCRIPT_FILE_URL VARCHAR2(100), 
	SCRIPT_DESCRIPTION VARCHAR2(100), 
	SEQUENCE NUMBER, 
	CODE VARCHAR2(3000), 
	SCHEMA_NAME VARCHAR2(100), 
	SCRIPT_FILE_TYPE VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;

CREATE TABLE SCRIPT_TASK 
   (	SCRIPT_TASK_ID NUMBER DEFAULT SCRIPT_TASK_ID_SEQ.NEXTVAL, 
	PID NUMBER, 
	SCRIPT_DATA CLOB, 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(400), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(400), 
	SCRIPT_FILE_NAME VARCHAR2(100), 
	SCRIPT_FILE_TYPE VARCHAR2(100), 
	SCRIPT_TYPE VARCHAR2(100), 
	SCHEMA_NAME VARCHAR2(100), 
	OPERATOR_TYPE VARCHAR2(100), 
	EXPORT_IDENTIFIER VARCHAR2(200), 
	PROCESS_TYPE VARCHAR2(200)
   ) ;

CREATE TABLE SCRIPT_TASK_EXPORT 
   (	EXPORT_ID NUMBER DEFAULT EXPORT_ID_SEQ.NEXTVAL, 
	PID NUMBER, 
	TASK_ID NUMBER, 
	SCRIPTS CLOB, 
	CREATED_DATE TIMESTAMP (6)
   ) ;

CREATE TABLE SERVICE_COLUMN_METADATA 
   (	PARAMETER_NAME VARCHAR2(100), 
	COLUMN_NAME VARCHAR2(100), 
	TABLE_NAME VARCHAR2(50), 
	GROUP_ID NUMBER, 
	ENTITY_ID NUMBER, 
	GRANDFATHERED VARCHAR2(50), 
	SERV_COL_META_ID NUMBER DEFAULT SERV_COL_META_ID_SEQ.NEXTVAL, 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	ROOT_ID NUMBER, 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;


CREATE GLOBAL TEMPORARY TABLE SYS_TEMP_FBT 
   (	SCHEMA VARCHAR2(130), 
	OBJECT_NAME VARCHAR2(130), 
	OBJECT# NUMBER, 
	RID UROWID (4000), 
	ACTION CHAR(1)
   ) ON COMMIT PRESERVE ROWS ;

CREATE TABLE TABLE_ORDER_SEQUENCE 
   (	TABLE_NAME VARCHAR2(1000), 
	SEQUENCE_ID NUMBER, 
	DELETE_SEQ NUMBER
   ) ;

CREATE TABLE TABLE_PARAMETER_MAPPING 
   (	PARAMETER_SPEC_ID NUMBER, 
	ROW_SPEC_ID NUMBER, 
	GRANDFATHERED VARCHAR2(50), 
	TABL_PARAM_MAPPING_ID NUMBER DEFAULT TABL_PARAM_MAPPING_ID_SEQ.NEXTVAL, 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   )  ENABLE ROW MOVEMENT ;

CREATE TABLE TABLE_ROW_SPECIFICATION 
   (	ID NUMBER, 
	NAME VARCHAR2(100), 
	CATEGORY VARCHAR2(100), 
	TYPE VARCHAR2(100), 
	DESCRIPTION VARCHAR2(255), 
	DISPLAY_NAME VARCHAR2(100), 
	WIDTH NUMBER, 
	HEIGHT NUMBER, 
	MIN_ROW NUMBER, 
	MAX_ROW NUMBER, 
	ENTITY_ID NUMBER, 
	PARENT_ID NUMBER, 
	STATUS VARCHAR2(50), 
	STATUS_DATE TIMESTAMP (6), 
	VERSION NUMBER, 
	VERSION_DATE TIMESTAMP (6), 
	LIFECYCLE_STATUS VARCHAR2(50), 
	POSITION NUMBER, 
	VISIBILITY VARCHAR2(20), 
	SEQUENCE NUMBER, 
	ROW_INDENT NUMBER, 
	AUTO_ALIGN VARCHAR2(25) DEFAULT 'True', 
	GRANDFATHERED VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   )  ENABLE ROW MOVEMENT ;

CREATE TABLE TABLE_SPECIFICATION 
   (	ID NUMBER, 
	NAME VARCHAR2(100), 
	CATEGORY VARCHAR2(100), 
	TYPE VARCHAR2(100), 
	DESCRIPTION VARCHAR2(255), 
	DISPLAY_NAME VARCHAR2(100), 
	WIDTH NUMBER, 
	HEIGHT NUMBER, 
	MIN_ROW NUMBER, 
	MAX_ROW NUMBER, 
	ENTITY_ID NUMBER, 
	PARENT_ID NUMBER, 
	STATUS VARCHAR2(50), 
	STATUS_DATE TIMESTAMP (6), 
	VERSION NUMBER, 
	VERSION_DATE TIMESTAMP (6), 
	LIFECYCLE_STATUS VARCHAR2(50), 
	POSITION NUMBER, 
	CRITERIA_TYPE VARCHAR2(100), 
	GRANDFATHERED VARCHAR2(50), 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   )  ENABLE ROW MOVEMENT ;

CREATE TABLE TEMP_BUSINESS_PROCESS_MAPPING 
   (	RECORD_KEY NUMBER, 
	NEW_RECORD_KEY NUMBER
   ) ;

CREATE TABLE TEMP_CHARGE_PARAM_SPEC 
   (	CHARGE_INSTANCE_ID NUMBER, 
	NEW_CHARGE_INSTANCE_ID NUMBER
   ) ;

CREATE TABLE TEMP_LCA_INFO 
   (	LIFECYCLE_ID NUMBER, 
	NEW_LIFECYCLE_ID NUMBER
   ) ;

CREATE TABLE TEMP_PARAMETER 
   (	PARAMETER_ID NUMBER, 
	NEW_PARAMETER_ID NUMBER
   ) ;

CREATE TABLE TEMP_PARAMETER_SPECIFICATION 
   (	PARAM_SPEC_ID NUMBER, 
	NEW_PARAM_SPEC_ID NUMBER
   ) ;

CREATE TABLE TEMP_PARAM_ADDON_SPEC 
   (	PARAM_ADDON_SPEC_ID NUMBER, 
	NEW_PARAM_ADDON_SPEC_ID NUMBER
   ) ;

CREATE TABLE TEMP_PARAM_DATA_SPECIFIC 
   (	PARAM_DATA_SPEC_ID NUMBER, 
	NEW_PARAM_DATA_SPEC_ID NUMBER
   ) ;

CREATE TABLE TEMP_PARAM_RULE_SPEC 
   (	PARAM_RULE_SPEC_ID NUMBER, 
	NEW_PARAM_RULE_SPEC_ID NUMBER
   ) ;

CREATE TABLE TEMP_PRICE_PLAN 
   (	PRICE_PLAN_ID NUMBER, 
	NEW_PRICE_PLAN_ID NUMBER
   ) ;

CREATE TABLE TEMP_PRICE_PLAN_SPECIFICATION 
   (	PP_ID NUMBER, 
	NEW_PP_ID NUMBER
   ) ;

CREATE TABLE TEMP_PROCESS_ENTITY 
   (	PID NUMBER, 
	NEW_PID NUMBER, 
	PARENT_ID NUMBER
   ) ;

CREATE TABLE TEMP_PROC_ENT 
   (	PID NUMBER, 
	NEW_PID NUMBER, 
	PARENT_ID NUMBER
   ) ;

CREATE TABLE TEMP_RULE 
   (	RULE_ID NUMBER, 
	NEW_RULE_ID NUMBER
   ) ;

CREATE TABLE TEMP_TABLE_ROW_SPECIFICATION 
   (	ROW_ID NUMBER, 
	NEW_ROW_ID NUMBER
   ) ;

CREATE TABLE TEMP_TABLE_SPECIFICATION 
   (	TBL_SPEC_ID NUMBER, 
	NEW_TBL_SPEC_ID NUMBER
   ) ;

CREATE TABLE USER_AUTH_PROCESS_MAPPING 
   (	USER_ID VARCHAR2(1000), 
	AUTH_PROCESS_ID NUMBER, 
	USR_AUTH_PROC_MAPPING_ID NUMBER DEFAULT USR_AUTH_PROC_MAPPING_ID_SEQ.NEXTVAL, 
	CREATED_DATE TIMESTAMP (6) DEFAULT systimestamp, 
	CREATED_BY VARCHAR2(200), 
	AUTH_TYPE VARCHAR2(20), 
	EXPORT_IDENTIFIER VARCHAR2(200)
   ) ;


--changeset Vijaysree.S:APPCATALOG_DDL_02_02 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TAB_COLUMNS 
    WHERE  
        TABLE_NAME = 'PROCESS_ENTITY_SPECIFICATION' 
	AND
	    COLUMN_NAME in ('IS_INSTANCE_PERSIST');

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PROCESS_ENTITY_SPECIFICATION ADD IS_INSTANCE_PERSIST CHAR(1)';
        DBMS_OUTPUT.PUT_LINE('ALTERED');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ALREADY EXIST');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SKIPPED');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_02_03 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TAB_COLUMNS 
    WHERE  
        TABLE_NAME = 'BUSINESS_ENTITY'
		AND COLUMN_NAME = 'IS_STANDARD_ENTITY';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE business_entity ADD IS_STANDARD_ENTITY VARCHAR2(200)';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_02_04 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TAB_COLUMNS 
    WHERE  
        TABLE_NAME = 'PROCESS_ENTITY_SPECIFICATION' 
	AND
	    COLUMN_NAME in ('ASYNC_SLA_ACTION');

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE process_entity_specification ADD ASYNC_SLA_ACTION  VARCHAR2(100)';
        DBMS_OUTPUT.PUT_LINE('ALTERED');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ALREADY EXIST');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SKIPPED');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_02_05 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TAB_COLUMNS 
    WHERE  
        TABLE_NAME = 'PROCESS_LAYOUT_SPECIFICATION' 
	AND
	    COLUMN_NAME in ('LAYOUT_CONTENT_ID');

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE process_layout_specification ADD LAYOUT_CONTENT_ID NUMBER';
        DBMS_OUTPUT.PUT_LINE('ALTERED');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ALREADY EXIST');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SKIPPED');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_02_06 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TAB_COLUMNS 
    WHERE  
        TABLE_NAME = 'PARAMETER_RULE_SPECIFICATION' 
	AND
	    COLUMN_NAME in ('ACTION_URL');

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PARAMETER_RULE_SPECIFICATION ADD ACTION_URL VARCHAR2(250)';
        DBMS_OUTPUT.PUT_LINE('ALTERED');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ALREADY EXIST');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SKIPPED');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_02_07 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TABLES 
    WHERE  
        TABLE_NAME = 'BUSINESS_ENTITY' ;

    IF L_CNT = 1 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE business_entity ADD DATA_SOURCE_COLUMN VARCHAR2(200)';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;



--changeset Vijaysree.S:APPCATALOG_DDL_02_08 splitStatements:false
--preconditions onFail:HALT onError:HALT


DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TABLES 
    WHERE  
        TABLE_NAME = 'RELEASE_DETAILS';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE RELEASE_DETAILS 
   (	
    RELEASE_ID NUMBER, 
	RELEASE_TAG VARCHAR2(100), 
	RELEASE_START_DATE TIMESTAMP (6), 
	RELEASE_END_DATE TIMESTAMP (6), 
	RELEASE_STATUS VARCHAR2(100), 
	CREATED_BY VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6)
   )  ';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;



--changeset Vijaysree.S:APPCATALOG_DDL_02_09 splitStatements:false
--preconditions onFail:HALT onError:HALT


DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TABLES 
    WHERE  
        TABLE_NAME = 'RELEASE_USER_STORY_MAPPING';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE RELEASE_USER_STORY_MAPPING 
   (	
    REL_USR_STRY_ID NUMBER, 
	RELEASE_ID NUMBER, 
	REL_USER_STORY VARCHAR2(500), 
	REL_USER_STORY_STATUS VARCHAR2(100), 
	CREATED_BY VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	RELEASE_TAG VARCHAR2(100)
   )  ';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;



--changeset Vijaysree.S:APPCATALOG_DDL_02_10 splitStatements:false
--preconditions onFail:HALT onError:HALT


DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TABLES 
    WHERE  
        TABLE_NAME = 'WORKSPACE_DETAILS';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE WORKSPACE_DETAILS
   (	WORKSPACE_ID NUMBER, 
	USER_ID NUMBER, 
	WORKSPACE_NAME VARCHAR2(100), 
	WORKSPACE_DESCRIPTION VARCHAR2(100), 
	WORKSPACE_START_DATE TIMESTAMP (6), 
	WORKSPACE_END_DATE TIMESTAMP (6), 
	WORKSPACE_STATUS VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	REL_USR_STRY_ID NUMBER
   )';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;



--changeset Vijaysree.S:APPCATALOG_DDL_02_11 splitStatements:false
--preconditions onFail:HALT onError:HALT


DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TABLES 
    WHERE  
        TABLE_NAME = 'WORKSPACE_ENTITY_DETAILS';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE WORKSPACE_ENTITY_DETAILS 
   (	
    WORKSPACE_ENTITY_ID NUMBER, 
	WORKSPACE_REL_ID NUMBER, 
	ENTITY_ID NUMBER, 
	ENTITY_VERSION NUMBER, 
	ENTITY_STATUS VARCHAR2(100), 
	MODULE_TYPE VARCHAR2(100), 
	IS_ENTITY_LOCKED VARCHAR2(10), 
	RELEASE_TAG VARCHAR2(100), 
	LINE_ITEM VARCHAR2(100), 
	CHANGE_TYPE VARCHAR2(200), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100), 
	ENTITY_NAME VARCHAR2(100), 
	ENTITY_USABILITY VARCHAR2(100), 
	ENTITY_DESC VARCHAR2(500), 
	ENTITY_CHNG_LOG VARCHAR2(4000)
   ) ';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;



--changeset Vijaysree.S:APPCATALOG_DDL_02_12 splitStatements:false
--preconditions onFail:HALT onError:HALT


DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TABLES 
    WHERE  
        TABLE_NAME = 'WORKSPACE_RELEASE_DETAILS';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE WORKSPACE_RELEASE_DETAILS 
   (	
    WORKSPACE_REL_ID NUMBER, 
	WORKSPACE_ID NUMBER, 
	RELEASE_TAG VARCHAR2(100), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(100), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(100)
   )  ';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_02_13 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TABLES 
    WHERE  
        TABLE_NAME = 'PARAMETER_ADDON_SPECIFICATION' ;

    IF L_CNT = 1 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE parameter_addon_specification ADD ALLOWED_SPECIAL_CHARACTERS VARCHAR2(50)';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_02_14 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TAB_COLUMNS
    WHERE  
        TABLE_NAME = 'RULE'
        AND COLUMN_NAME = 'OVERRIDE_HTTP_CODE';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE RULE ADD OVERRIDE_HTTP_CODE VARCHAR2(5)';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_02_15 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TABLES
    WHERE  
        TABLE_NAME = 'ENTITY_LOB_DETAILS';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE ENTITY_LOB_DETAILS
   (	ENTITY_ID NUMBER, 
	ENTITY_TYPE VARCHAR2(100), 
	LOB_ID NUMBER
   )';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_02_16 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TABLES
    WHERE  
        TABLE_NAME = 'REF_LINEOFBUSINESS';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE REF_LINEOFBUSINESS
   (	LOB_ID NUMBER, 
	LINEOFBUSINESS VARCHAR2(150)
   )';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_02_17 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TAB_COLUMNS
    WHERE  
        TABLE_NAME = 'PRICE_PLAN_SPECIFICATION'
        AND COLUMN_NAME = 'EXTERNAL_ID';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PRICE_PLAN_SPECIFICATION ADD EXTERNAL_ID VARCHAR2(100)';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_02_18 splitStatements:false
--preconditions onFail:HALT onError:HALT

declare
v_count NUMBER;

begin
for i in (select distinct me.METADATA_TABLE_NAME  
from metadata_export_table_config me ,user_tables utt  where
utt.table_name=me.METADATA_TABLE_NAME and
not exists (select 1 from user_tab_columns ut where ut.TABLE_NAME=me.METADATA_TABLE_NAME
and ut.column_name='CREATED_DATE') and me.METADATA_TABLE_NAME <>'LIFE_CYCLE_ACTIVITY_METADATA'
)
loop
dbms_output.put_line ('
Alter table ' || i.METADATA_TABLE_NAME ||' ADD (Created_date timestamp default systimestamp );');
EXECUTE IMMEDIATE 'Alter table '||i.METADATA_TABLE_NAME||' ADD (Created_date  timestamp default systimestamp  )';
end loop;
end;


--changeset Vijaysree.S:APPCATALOG_DDL_02_19 splitStatements:false
--preconditions onFail:HALT onError:HALT

declare
v_count NUMBER;

begin
for i in (select distinct me.METADATA_TABLE_NAME  
from metadata_export_table_config me ,user_tables utt  where
utt.table_name=me.METADATA_TABLE_NAME and
not exists (select 1 from user_tab_columns ut where ut.TABLE_NAME=me.METADATA_TABLE_NAME
and ut.column_name='CREATED_BY') and me.METADATA_TABLE_NAME <>'LIFE_CYCLE_ACTIVITY_METADATA'
)
loop
dbms_output.put_line ('
Alter table ' || i.METADATA_TABLE_NAME ||' ADD (Created_by varchar2(200) );');
EXECUTE IMMEDIATE 'Alter table '||i.METADATA_TABLE_NAME||' ADD (Created_by varchar2(200)  )';
end loop;
end;




--changeset Vijaysree.S:APPCATALOG_DDL_02_20 splitStatements:false
--preconditions onFail:HALT onError:HALT

declare
v_count NUMBER;

begin
for i in (select distinct me.METADATA_TABLE_NAME  
from metadata_export_table_config me ,user_tables utt  where
utt.table_name=me.METADATA_TABLE_NAME and
not exists (select 1 from user_tab_columns ut where ut.TABLE_NAME=me.METADATA_TABLE_NAME
and ut.column_name='MODIFIED_DATE') and me.METADATA_TABLE_NAME <>'LIFE_CYCLE_ACTIVITY_METADATA'
)
loop
dbms_output.put_line ('
Alter table ' || i.METADATA_TABLE_NAME ||' ADD (Modified_date timestamp default systimestamp );');
EXECUTE IMMEDIATE 'Alter table '||i.METADATA_TABLE_NAME||' ADD (Modified_date  timestamp default systimestamp  )';
end loop;
end;


--changeset Vijaysree.S:APPCATALOG_DDL_02_21 splitStatements:false
--preconditions onFail:HALT onError:HALT

declare
v_count NUMBER;

begin
for i in (select distinct me.METADATA_TABLE_NAME  
from metadata_export_table_config me ,user_tables utt  where
utt.table_name=me.METADATA_TABLE_NAME and
not exists (select 1 from user_tab_columns ut where ut.TABLE_NAME=me.METADATA_TABLE_NAME
and ut.column_name='MODIFIED_BY') and me.METADATA_TABLE_NAME <>'LIFE_CYCLE_ACTIVITY_METADATA'
)
loop
dbms_output.put_line ('
Alter table ' || i.METADATA_TABLE_NAME ||' ADD (Modified_by varchar2(200) );');
EXECUTE IMMEDIATE 'Alter table '||i.METADATA_TABLE_NAME||' ADD (Modified_by varchar2(200)  )';
end loop;
end;


--changeset Vijaysree.S:APPCATALOG_DDL_02_22 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TAB_COLUMNS
    WHERE  
        TABLE_NAME = 'PROCESS_ACTION_SPECIFICATION'
        AND COLUMN_NAME = 'ACTION_STATUS_ID';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PROCESS_ACTION_SPECIFICATION ADD ACTION_STATUS_ID NUMBER';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_02_23 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TAB_COLUMNS
    WHERE  
        TABLE_NAME = 'DETERMINANTS'
        AND COLUMN_NAME IN ( 'CREATED_DATE','CREATED_BY','MODIFIED_DATE','MODIFIED_BY');

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE determinants ADD (
    created_date  TIMESTAMP(6),
    created_by    VARCHAR2(200),
    modified_date TIMESTAMP(6),
    modified_by   VARCHAR2(200)
)';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_02_24 splitStatements:false
--preconditions onFail:HALT onError:HALT


DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TAB_COLUMNS
    WHERE  
        TABLE_NAME = 'PROCESS_ENTITY_SPECIFICATION'
        AND COLUMN_NAME IN ( 'DEPENDENT_GATEWAY_ID','IS_OVERRIDE_HTTP','STATIC_HTTP_CODE','IS_OVERRIDE_INBOUND_RESPONSE');

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PROCESS_ENTITY_SPECIFICATION ADD (DEPENDENT_GATEWAY_ID NUMBER,IS_OVERRIDE_HTTP VARCHAR2(10), STATIC_HTTP_CODE VARCHAR2(50),IS_OVERRIDE_INBOUND_RESPONSE VARCHAR2(10))';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_02_25 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TAB_COLUMNS
    WHERE  
        TABLE_NAME = 'ENTITY_BOUNDARY_CONDITION'
        AND COLUMN_NAME IN ( 'EXCEPTION_TYPE','ACTION_SUB_TYPE');

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ENTITY_BOUNDARY_CONDITION ADD (EXCEPTION_TYPE VARCHAR2(100),ACTION_SUB_TYPE VARCHAR2(100))';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_02_26 splitStatements:false
--preconditions onFail:HALT onError:HALT


DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TAB_COLUMNS
    WHERE  
        TABLE_NAME = 'PRODUCT_MAPPING'
        AND COLUMN_NAME IN ( 'ELEMENT_PROCESS_ID');

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PRODUCT_MAPPING ADD ELEMENT_PROCESS_ID NUMBER';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;



--changeset Vijaysree.S:APPCATALOG_DDL_02_27 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TABLES
    WHERE  
        TABLE_NAME = 'ENTITY_LOB_DETAILS';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE ENTITY_LOB_DETAILS
   (	ENTITY_ID NUMBER, 
	ENTITY_TYPE VARCHAR2(100), 
	LOB_ID NUMBER
   )';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;

--changeset Vijaysree.S:APPCATALOG_DDL_02_28 splitStatements:false
--preconditions onFail:HALT onError:HALT
  
DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TABLES
    WHERE  
        TABLE_NAME = 'REF_LINEOFBUSINESS';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE REF_LINEOFBUSINESS
   (	LOB_ID NUMBER, 
	LINEOFBUSINESS VARCHAR2(150)
   )';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_02_29 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TABLES 
    WHERE  
        TABLE_NAME = 'USER_LOB_ASSOC' ;

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE USER_LOB_ASSOC 
   (	USER_ID NUMBER, 
	LINEOFBUSINESS VARCHAR2(100)
   )';
		DBMS_OUTPUT.PUT_LINE('Created');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_02_30 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TAB_COLUMNS
    WHERE  
        TABLE_NAME = 'PARAMETER_ADDON_SPECIFICATION'
        AND COLUMN_NAME IN ( 'LABEL');

    IF L_CNT = 1 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PARAMETER_ADDON_SPECIFICATION MODIFY LABEL VARCHAR2(200)';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;

--changeset Vijaysree.S:APPCATALOG_DDL_02_31 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TAB_COLUMNS
    WHERE  
        TABLE_NAME = 'PARAMETER_ADDON_SPECIFICATION'
        AND COLUMN_NAME IN ( 'ALLOWNEGATIVE');

    IF L_CNT = 1 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PARAMETER_ADDON_SPECIFICATION ADD ALLOWNEGATIVE VARCHAR2(10)';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;

--changeset Vijaysree.S:APPCATALOG_DDL_02_32 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TAB_COLUMNS
    WHERE  
        TABLE_NAME = 'PARAMETER_SPECIFICATION'
        AND COLUMN_NAME IN ( 'DOWNLOADABLE_ENTITY');

    IF L_CNT = 1 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PARAMETER_SPECIFICATION ADD DOWNLOADABLE_ENTITY VARCHAR2(10)';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;

--changeset Vijaysree.S:APPCATALOG_DDL_02_33 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TAB_COLUMNS
    WHERE  
        TABLE_NAME = 'PROCESS_LAYOUT_SPECIFICATION'
        AND COLUMN_NAME IN ( 'DOWNLOADABLE_ENTITY');

    IF L_CNT = 1 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PROCESS_LAYOUT_SPECIFICATION ADD DOWNLOADABLE_ENTITY VARCHAR2(10)';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;