--liquibase formatted sql
--changeset Vijaysree.S:APPCATALOG_DDL_03 splitStatements:true
--preconditions onFail:HALT onError:HALT

CREATE INDEX IDX_EGF_BID ON ENTITY_GROUP_FUNCTION (BID) 
  ;

CREATE INDEX IDX_EGF_PARENT_PID ON ENTITY_GROUP_FUNCTION (PARENT_PID) 
  ;

CREATE INDEX IDX_EGF_PID ON ENTITY_GROUP_FUNCTION (PID) 
  ;

CREATE INDEX IDX_ENT_FUNC_ID ON ENTITY_GROUP_FUNCTION (ENTITY_FUNCTION_ID) 
  ;

CREATE INDEX IDX_JOIN_PID ON ENTITY_GROUP_FUNCTION (JOIN_PID) 
  ;

CREATE INDEX IDX_TABLE_ROW_PARAM_MAPPING ON TABLE_PARAMETER_MAPPING (ROW_SPEC_ID) 
  ;

CREATE INDEX IDX_BP_BID ON BUSINESS_PARAMETERS (BID) 
  ;

CREATE INDEX IDX_HIERARCHY_ENTITY_ID ON HIERARCHY_METADATA (HIERARCHY_ENTITY_ID) 
  ;

CREATE INDEX IDX_PARENT_ENTITY_ID ON HIERARCHY_METADATA (PARENT_ENTITY_ID) 
  ;

CREATE INDEX INDEX_EJP_ENT_FUNC_ID ON ENTITY_JOIN_PARAMETER (ENTITY_FUNCTION_ID) 
  ;

CREATE INDEX INDEX_EJP_GROUP_ID ON ENTITY_JOIN_PARAMETER (GROUP_ID) 
  ;

CREATE INDEX INDEX_EJP_PARAMKEY ON ENTITY_JOIN_PARAMETER (PARAMKEY1, PARAMKEY2) 
  ;

CREATE INDEX INDEX_EJP_PARAMKEY2 ON ENTITY_JOIN_PARAMETER (PARAMKEY2) 
  ;

CREATE INDEX IDX_CATEGORY_TYPE ON PARAMETER_REFERENCE_VALUE (CATEGORY_TYPE) 
  ;

CREATE INDEX IDX_PARAM_SPEC_ID ON PARAMETER_REFERENCE_VALUE (PARAM_SPEC_ID) 
  ;

CREATE INDEX IDX_LOWER_NAME ON PROCESS_ENTITY_SPECIFICATION (LOWER(NAME)) 
  ;

CREATE INDEX IDX_PARAM_ENTITY_SPEC_PID ON PROCESS_ENTITY_SPECIFICATION (PID) 
  ;

CREATE INDEX IDX_PES_LIFECYCLE ON PROCESS_ENTITY_SPECIFICATION (LIFECYCLE_ID) 
  ;

CREATE INDEX IDX_PROCESS_ENT_NAME ON PROCESS_ENTITY_SPECIFICATION (NAME) 
  ;

CREATE INDEX IDX_PROCESS_ENT_TYPE ON PROCESS_ENTITY_SPECIFICATION (TYPE) 
  ;

CREATE INDEX IDX_PROCESS_GROUP ON PROCESS_ENTITY_SPECIFICATION (PROCESS_GROUP) 
  ;

CREATE INDEX IDX_RE_ENTITYID ON RULE_EXPRESSION (ENTITY_ID) 
  ;

CREATE INDEX IDX_RULE_EXP ON RULE_EXPRESSION (RULE_ID) 
  ;

CREATE INDEX IDX_PARAM_FUNC_KEY ON PARAMETER_FUNC_SPECIFICATION (PARAM_FUNC_KEY) 
  ;

CREATE INDEX IDX_PARAM_FUNC_VALUE ON PARAMETER_FUNC_SPECIFICATION (PARAM_FUNC_VALUE) 
  ;

CREATE INDEX IDX_PARAM_DATA_SPEC_PARENTID ON PARAMETER_DATA_SPECIFICATION (PARENT_ID) 
  ;

CREATE INDEX IDX_TABLE_ROW_SPEC_PARENTID ON TABLE_ROW_SPECIFICATION (PARENT_ID) 
  ;

CREATE INDEX IDX_PAS_PARENT_ID ON PROCESS_ACTION_SPECIFICATION (PARENT_ID) 
  ;

CREATE INDEX IDX_CHARGE_ITEM_ID ON CHARGE_PARAMETER_SPECIFICATION (CHARGE_ITEM_ID) 
  ;

CREATE INDEX IDX_REF_VAL_ID ON REFERENCE_HIERARCHY (REF_VAL_ID) 
  ;

CREATE INDEX IDX_DEFAULT_VALUE ON PARAMETER_ADDON_SPECIFICATION (DEFAULT_VALUE) 
  ;

CREATE INDEX IDX_DISPLAY_NAME ON PARAMETER_ADDON_SPECIFICATION (DISPLAY_NAME) 
  ;

CREATE INDEX IDX_PAS_PARENTID ON PARAMETER_ADDON_SPECIFICATION (PARENT_ID) 
  ;

CREATE INDEX IDX_DOMAIN_TYPE ON BUSINESS_ENTITY (DOMAIN_TYPE) 
  ;

CREATE INDEX IDX_TABLE_SPEC_PARENTID ON TABLE_SPECIFICATION (PARENT_ID) 
  ;

CREATE INDEX IDX_BEP_PARAMETER_SPEC_ID ON BUSINESS_ENTITY_PARAMETER (PARAMETER_SPEC_ID) 
  ;

CREATE INDEX IDX_BEP_PARENT_ID ON BUSINESS_ENTITY_PARAMETER (PARENT_ID) 
  ;

CREATE INDEX IDX_NAME ON BUSINESS_ENTITY_PARAMETER (NAME) 
  ;

CREATE INDEX IDX_PARENT_ID ON PARAMETER_RULE_SPECIFICATION (PARENT_ID) 
  ;

CREATE INDEX IDX_REFERENCE_STORE_ID ON PARAMETER_RULE_SPECIFICATION (REFERENCE_STORE_ID) 
  ;

CREATE INDEX IDX_RULE_ID ON PARAMETER_RULE_SPECIFICATION (RULE_ID) 
  ;

CREATE INDEX REFERENCE_TYPE_VALUES_IDX ON REFERENCE_TYPE_VALUES (REF_VALUE, REF_TYPE_ID) 
  ;

CREATE INDEX IDX_PARAM_PARENTID ON PARAMETER_SPECIFICATION (PARENT_ID) 
  ;

CREATE INDEX IDX_PE_LIFECYCLEID ON PROCESS_ENTITY (LIFECYCLE_ID) 
  ;

CREATE INDEX IDX_PE_SEQ ON PROCESS_ENTITY (PROCESS_SEQUENCE) 
  ;

CREATE INDEX IDX_PE_TYPE ON PROCESS_ENTITY (TYPE) 
  ;

CREATE INDEX IDX_PROCESS_ACTION_TYPE ON PROCESS_ENTITY (ACTION_TYPE) 
  ;

CREATE INDEX IDX_PROCESS_ENT_PARENT_ID ON PROCESS_ENTITY (PARENT_ID) 
  ;

CREATE INDEX IDX_ROOT_ID ON PROCESS_ENTITY (ROOT_ID) 
  ;

CREATE INDEX IDX_PARENTID_PLS ON PROCESS_LAYOUT_SPECIFICATION (PARENT_ID) 
  ;

CREATE INDEX IDX_BPM_ENTITYID ON BUSINESS_PROCESS_MAPPING (ENTITYID) 
  ;

CREATE INDEX IDX_PARENTID ON BUSINESS_PROCESS_MAPPING (PARENT_ID) 
  ;

CREATE INDEX IDX_ENTITY_ID ON RULE (ENTITY_ID, ENTITY_TYPE_ID) 
  ;

CREATE INDEX IDX_BILL_RUN_EXC_ID ON CYCLE_PREP_SUMMARY (BILL_RUN_EXC_ID) 
  ;

CREATE INDEX IDX_CYCLE_PREP_ID ON CYCLE_PREP_SUMMARY (CYCLE_PREP_ID) 
  ;

CREATE INDEX IDX_ENTITYLCA_META ON LIFE_CYCLE_ACTIVITY_METADATA (ENTITY_ID) 
  ;

CREATE INDEX IDX_LCA_CYCLE_VERSION_METADATA ON LIFE_CYCLE_ACTIVITY_METADATA (LIFE_CYCLE_ID, LCA_VERSION) 
  ;

CREATE INDEX IDX_LCA_LIFECYCLE_ID_META ON LIFE_CYCLE_ACTIVITY_METADATA (LIFE_CYCLE_ID) 
  ;

CREATE INDEX IDX_LCA_STATUS_META ON LIFE_CYCLE_ACTIVITY_METADATA (LCA_STATUS) 
  ;

CREATE INDEX IDX_LCA_TYPE_META ON LIFE_CYCLE_ACTIVITY_METADATA (LCA_TYPE) 
  ;

CREATE INDEX IDX_LCA_VERSION_META ON LIFE_CYCLE_ACTIVITY_METADATA (LCA_VERSION) 
  ;

CREATE INDEX IND_DYNAMIC_REFERENCE_ID ON PARAMETER_RULE_SPECIFICATION (DYNAMIC_REFERENCE_ID) 
  ;

CREATE INDEX METADATA_CRT_DT_IND ON METADATA_SCRIPT_EXPORT (TRUNC(CREATED_DATE)) 
  ;

CREATE INDEX METADATA_DLT_TRC_IND ON METADATA_DELETE_TRACE (TRUNC(METADATA_DELETE_EXECUTION_TIME)) 
  ;

CREATE INDEX METADATA_EXP_TRC_IND ON METADATA_EXPORT_TRACE (TRUNC(METADATA_EXPORT_EXECUTION_TIME)) 
  ;


--changeset Swetha.H:APPCATALOG_DDL_03_02 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_IND_COLUMNS 
    WHERE  
        INDEX_NAME = 'IDX_WRK_SPC_ENT_ID'
		AND COLUMN_NAME = 'ENTITY_ID';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_WRK_SPC_ENT_ID ON WORKSPACE_ENTITY_DETAILS (ENTITY_ID)';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Swetha.H:APPCATALOG_DDL_03_03 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_IND_COLUMNS 
    WHERE  
        INDEX_NAME = 'IDX_WRK_SPC_REL_ID'
		AND COLUMN_NAME = 'WORKSPACE_REL_ID';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_WRK_SPC_REL_ID ON WORKSPACE_ENTITY_DETAILS (WORKSPACE_REL_ID)';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Swetha.H:APPCATALOG_DDL_03_04 splitStatements:false
--preconditions onFail:HALT onError:HALT


DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_IND_COLUMNS 
    WHERE  
        INDEX_NAME = 'IDX_WRK_SPC_ENT_VER'
		AND COLUMN_NAME = 'ENTITY_VERSION';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_WRK_SPC_ENT_VER ON WORKSPACE_ENTITY_DETAILS (ENTITY_VERSION)';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;
