--liquibase formatted sql
--changeset Vijaysree.S:APPCATALOG_DDL_04 splitStatements:true
--preconditions onFail:HALT onError:HALT

ALTER TABLE ENTITY_JSON_MAPPING ADD CONSTRAINT ENTITY_JSON_MAP_ID_PK PRIMARY KEY (ENTITY_JSON_MAP_ID)
  USING INDEX  ENABLE;

ALTER TABLE REF_ENTITY_TYPE ADD CONSTRAINT ENTITY_ID_PK PRIMARY KEY (ENTITY_ID)
  USING INDEX  ENABLE;

ALTER TABLE INVOICE_INFO ADD CONSTRAINT PK_INVOICE_ID PRIMARY KEY (INVOICE_ID)
  USING INDEX  ENABLE;

ALTER TABLE REFERENCE_TYPES ADD CONSTRAINT REF_TYPE_ID_PK PRIMARY KEY (REF_TYPE_ID)
  USING INDEX  ENABLE;

ALTER TABLE PROCESS_ACTION_SPECIFICATION ADD CONSTRAINT PK_ACTION_ID PRIMARY KEY (ACTION_ID)
  USING INDEX  ENABLE;

ALTER TABLE CHARGE_PARAMETER_SPECIFICATION ADD CONSTRAINT PK_CHARGE_INSTANCE_ID PRIMARY KEY (CHARGE_INSTANCE_ID)
  USING INDEX  ENABLE;

ALTER TABLE DECISION_TREE ADD CONSTRAINT PK_DECTNODE_ID PRIMARY KEY (DECISION_TREE_NODE_ID)
  USING INDEX  ENABLE;

ALTER TABLE PARAMETER ADD CONSTRAINT PK_PARAMETER_ID PRIMARY KEY (PARAMETER_ID)
  USING INDEX  ENABLE;

ALTER TABLE PRICE_PLAN_COUNTER ADD CONSTRAINT PK_PRICE_PLNA PRIMARY KEY (PRICE_PLAN_PRICING_ID)
  USING INDEX  ENABLE;

ALTER TABLE REFERENCE_TYPE_VALUES ADD CONSTRAINT REF_TYPE_VALUE_ID_PK PRIMARY KEY (REF_VAL_ID)
  USING INDEX  ENABLE;

ALTER TABLE LIFE_CYCLE_ACTIVITY_METADATA ADD CONSTRAINT LCA_ID_META_PK PRIMARY KEY (LCA_ID)
  USING INDEX  ENABLE;

ALTER TABLE PROCESS_ENTITY ADD CONSTRAINT PK_PID_PARENT_ID_VER_RT PRIMARY KEY (PID, VERSION, PARENT_ID, ROOT_ID)
  USING INDEX  ENABLE;

ALTER TABLE BUSINESS_PROCESS_MAPPING ADD CONSTRAINT BUSINESS_PROCESS_ENTITY_PK PRIMARY KEY (RECORD_KEY)
  USING INDEX  ENABLE;

ALTER TABLE CUSTOM_API_SPECIFICATION ADD CONSTRAINT PK_CUST_SPEC_ID PRIMARY KEY (CUSTOM_API_SPEC_ID)
  USING INDEX  ENABLE;

ALTER TABLE RULE ADD CONSTRAINT RULE_PK PRIMARY KEY (RULE_ID)
  USING INDEX  ENABLE;

ALTER TABLE PARAMETER_FUNC_SPECIFICATION ADD CONSTRAINT PARAM_FUNC_SPEC_PK PRIMARY KEY (PARAM_FUNC_SPEC_ID)
  USING INDEX  ENABLE;

ALTER TABLE TABLE_SPECIFICATION ADD CONSTRAINT PK_TS_ID PRIMARY KEY (ID)
  USING INDEX  ENABLE;

ALTER TABLE ENTITY_BOUNDARY_CONDITION ADD CONSTRAINT EBC_ID_PK PRIMARY KEY (EBC_ID)
  USING INDEX  ENABLE;

ALTER TABLE TABLE_ROW_SPECIFICATION ADD CONSTRAINT PK_TRS_ID PRIMARY KEY (ID)
  USING INDEX  ENABLE;

ALTER TABLE PARAMETER_DATA_SPECIFICATION ADD CONSTRAINT PK_PARAM_DATA_SPEC_ID PRIMARY KEY (PARAM_DATA_SPEC_ID)
  USING INDEX  ENABLE;

ALTER TABLE PARAMETER_ADDON_SPECIFICATION ADD CONSTRAINT PK_PARAM_ADDON_SPEC_ID PRIMARY KEY (PARAM_ADDON_SPEC_ID)
  USING INDEX  ENABLE;

ALTER TABLE SCRIPT_INFO ADD CONSTRAINT SCRIPT_ID_PK PRIMARY KEY (SCRIPT_ID)
  USING INDEX  ENABLE;

ALTER TABLE PRODUCT_CODE_DETAILS ADD CONSTRAINT PRDT_CODE_ID_PK PRIMARY KEY (PRODUCT_CODE_ID)
  USING INDEX  ENABLE;

ALTER TABLE ERROR_INFO ADD CONSTRAINT ERROR_ID_PK PRIMARY KEY (ERROR_ID)
  USING INDEX  ENABLE;

ALTER TABLE PRICE_PLAN ADD CONSTRAINT PK_PRICE_PLAN_ID PRIMARY KEY (PRICE_PLAN_ID)
  USING INDEX  ENABLE;

ALTER TABLE CHARGING_ATTRIBUTE ADD CONSTRAINT CHARGING_ATTRBIUTE_PK PRIMARY KEY (ID)
  USING INDEX  ENABLE;

ALTER TABLE PROCESS_LAYOUT_SPECIFICATION ADD CONSTRAINT PK_LAYOUT_ID PRIMARY KEY (LAYOUT_ID)
  USING INDEX  ENABLE;

ALTER TABLE PRICE_PLAN_SPECIFICATION ADD CONSTRAINT PK_PP_PP_INSTANCE_ID PRIMARY KEY (PP_INSTANCE_ID)
  USING INDEX  ENABLE;

ALTER TABLE BUSINESS_ENTITY_PARAMETER ADD CONSTRAINT BUSINESS_ENTITY_PARAMETER_PK PRIMARY KEY (RECORD_KEY_PARAM)
  USING INDEX  ENABLE;

ALTER TABLE PARAMETER_RULE_SPECIFICATION ADD CONSTRAINT PK_PARAM_RULE_SPEC_ID PRIMARY KEY (PARAM_RULE_SPEC_ID)
  USING INDEX  ENABLE;

ALTER TABLE PARAMETER_SPECIFICATION ADD CONSTRAINT PK_PARAM_BASIC_SPEC_ID PRIMARY KEY (PARAM_BASIC_SPEC_ID)
  USING INDEX  ENABLE;

ALTER TABLE CHARGING_ALGORITHM ADD CONSTRAINT CHARGING_ALGORITHM_PK PRIMARY KEY (CHARGING_ALGORITHM_ID)
  USING INDEX  ENABLE;

ALTER TABLE PROCESS_ENTITY_SPECIFICATION ADD CONSTRAINT PK_PROCESS_SPEC_ID PRIMARY KEY (PROCESS_SPEC_ID)
  USING INDEX  ENABLE;

ALTER TABLE RULE_EXPRESSION ADD CONSTRAINT RULE_EXPRESSION_PK PRIMARY KEY (RULE_EXPRESSION_ID)
  USING INDEX  ENABLE;

ALTER TABLE OBJECT_CHANGE_DETAILS ADD CONSTRAINT OBJ_DET_SCRIPT_ID_PK PRIMARY KEY (SCRIPT_ID)
  USING INDEX  ENABLE;


ALTER TABLE BUSINESS_ENTITY ADD CONSTRAINT BID_PK PRIMARY KEY (BID)
  USING INDEX  ENABLE;

ALTER TABLE CUSTOM_TEMPLATE_MAPPING ADD CONSTRAINT CUSTOM_TEMPL_MAP_ID_PK PRIMARY KEY (CUSTOM_TEMPL_MAP_ID)
  USING INDEX  ENABLE;

ALTER TABLE PARAMETER_FORMAT_ADDON_SPEC ADD CONSTRAINT PARAM_FORMAT_ADDON_SPEC_ID_PK PRIMARY KEY (PARAM_FORMAT_ADDON_SPEC_ID)
  USING INDEX  ENABLE;

ALTER TABLE BUSINESS_PARAMETERS ADD CONSTRAINT BUSINESS_PARAM_ID_PK PRIMARY KEY (BUSINESS_PARAM_ID)
  USING INDEX  ENABLE;

ALTER TABLE ENTITY_PRODUCT_CODE_MAPPING ADD CONSTRAINT ENTITY_PRD_CD_PK PRIMARY KEY (ENTITY_PRD_CD_ID)
  USING INDEX  ENABLE;

ALTER TABLE BUSINESS_ENTITY_SPECIFICATION ADD CONSTRAINT PK_BUSINESS_ENTITY_SPEC_ID PRIMARY KEY (BUSINESS_ENTITY_SPEC_ID)
  USING INDEX  ENABLE;

ALTER TABLE ACTION_INPUT_PARAMETER ADD CONSTRAINT ACTION_INPUT_PARAM_ID_PK PRIMARY KEY (ACTION_INPUT_PARAM_ID)
  USING INDEX  ENABLE;

ALTER TABLE USER_AUTH_PROCESS_MAPPING ADD CONSTRAINT USR_AUTH_PROC_MAPPING_ID_PK PRIMARY KEY (USR_AUTH_PROC_MAPPING_ID)
  USING INDEX  ENABLE;

ALTER TABLE SERVICE_COLUMN_METADATA ADD CONSTRAINT SER_COL_META_ID_PK PRIMARY KEY (SERV_COL_META_ID)
  USING INDEX  ENABLE;

ALTER TABLE BUSINESS_ENTITY_RELATION ADD CONSTRAINT BUSINESS_ENTITY_REL_ID_PK PRIMARY KEY (BUSINESS_ENTITY_REL_ID)
  USING INDEX  ENABLE;

ALTER TABLE PARAMETER_REFERENCE_VALUE ADD CONSTRAINT PARAM_REF_VAL_ID_PK PRIMARY KEY (PARAM_REF_VAL_ID)
  USING INDEX  ENABLE;

ALTER TABLE HIERARCHY_METADATA ADD CONSTRAINT HIERARCHY_META_ID_PK PRIMARY KEY (HIERARCHY_METADATA_ID)
  USING INDEX  ENABLE;

ALTER TABLE ENTITY_JOIN_PARAMETER ADD CONSTRAINT ENTITY_JOIN_PARAM_ID_PK PRIMARY KEY (ENTITY_JOIN_PARAM_ID)
  USING INDEX  ENABLE;

ALTER TABLE ENTITY_GROUP_FUNCTION ADD CONSTRAINT ENTITY_GROUP_FUNCT_ID_PK PRIMARY KEY (ENTITY_GROUP_FUNC_ID)
  USING INDEX  ENABLE;

ALTER TABLE PRICE_PLAN_ENTITY ADD CONSTRAINT PRICE_PLAN_ENTITY_ID_PK PRIMARY KEY (PRICE_PLAN_ENTITY_ID)
  USING INDEX  ENABLE;

ALTER TABLE EMAIL_TEMPLATE ADD CONSTRAINT EMAIL_TEMP_ID_PK PRIMARY KEY (EMAIL_TEMP_ID)
  USING INDEX  ENABLE;

ALTER TABLE TABLE_PARAMETER_MAPPING ADD CONSTRAINT TAB_PARAM_MAPPING_ID_PK PRIMARY KEY (TABL_PARAM_MAPPING_ID)
  USING INDEX  ENABLE;

ALTER TABLE ENTITY_RELEASE_HISTORY ADD CONSTRAINT ERH_ID_PK PRIMARY KEY (ERH_ID)
  USING INDEX  ENABLE;

ALTER TABLE ENTITY_JSON_MAPPING ADD CONSTRAINT JSON_MAP_ENTITY_ID_FK FOREIGN KEY (ENTITY_TYPE_ID)
	  REFERENCES REF_ENTITY_TYPE (ENTITY_ID) ENABLE;

ALTER TABLE PRICE_PLAN_SPECIFICATION ADD CONSTRAINT DECISION_TREE_NODE_ID_FK FOREIGN KEY (DECISION_TREE_NODE_ID)
	  REFERENCES DECISION_TREE (DECISION_TREE_NODE_ID) ENABLE NOVALIDATE;

ALTER TABLE PRICE_PLAN_SPECIFICATION ADD CONSTRAINT PRICE_PLAN_SPECIFICATION_FK1 FOREIGN KEY (PRICE_PLAN_ID)
	  REFERENCES PRICE_PLAN (PRICE_PLAN_ID) ENABLE NOVALIDATE;

ALTER TABLE BUSINESS_ENTITY_PARAMETER ADD CONSTRAINT ENTITY_GROUP_JOIN_FUNCTIO_FK1 FOREIGN KEY (PARENT_ID)
	  REFERENCES BUSINESS_PROCESS_MAPPING (RECORD_KEY) ENABLE;

ALTER TABLE PARAMETER_RULE_SPECIFICATION ADD CONSTRAINT PARAMETER_RULE_SPECIFICAT_FK1 FOREIGN KEY (RULE_ID)
	  REFERENCES RULE (RULE_ID) ENABLE NOVALIDATE;

ALTER TABLE CHARGING_ALGORITHM ADD CONSTRAINT CHARGING_ALG_CHARGI_FK FOREIGN KEY (CHARGING_ATTRIBUTE)
	  REFERENCES CHARGING_ATTRIBUTE (ID) ENABLE;

ALTER TABLE CHARGE_PARAMETER_SPECIFICATION ADD CONSTRAINT CHARGE_PARAMETER_SPECIFIC_FK1 FOREIGN KEY (RULE_ID)
	  REFERENCES RULE (RULE_ID) ENABLE NOVALIDATE;

ALTER TABLE REFERENCE_TYPE_VALUES ADD CONSTRAINT REF_TYPE_ID_FK FOREIGN KEY (REF_TYPE_ID)
	  REFERENCES REFERENCE_TYPES (REF_TYPE_ID) ENABLE;

ALTER TABLE BUSINESS_PROCESS_MAPPING ADD CONSTRAINT FK_ENTITYID FOREIGN KEY (ENTITYID)
	  REFERENCES BUSINESS_ENTITY (BID) ENABLE NOVALIDATE;

ALTER TABLE ENTITY_PRODUCT_CODE_MAPPING ADD CONSTRAINT ENTITY_PRD_MAP_FK FOREIGN KEY (PRODUCT_CODE_ID)
	  REFERENCES PRODUCT_CODE_DETAILS (PRODUCT_CODE_ID) ENABLE;

ALTER TABLE BUSINESS_ENTITY_RELATION ADD CONSTRAINT FK_BER_BID FOREIGN KEY (PARENT_ID)
	  REFERENCES BUSINESS_ENTITY (BID) ENABLE NOVALIDATE;

ALTER TABLE PRICE_PLAN_ENTITY ADD CONSTRAINT FK_PLAN_ID FOREIGN KEY (PLAN_ID)
	  REFERENCES PRICE_PLAN (PRICE_PLAN_ID) ENABLE;

ALTER TABLE PRICE_PLAN_ENTITY ADD CONSTRAINT FK_BID FOREIGN KEY (ENTITY_ID)
	  REFERENCES BUSINESS_ENTITY (BID) ENABLE;

ALTER TABLE REFERENCE_TYPE_VALUES ADD CONSTRAINT REF_HIERARCHY_TYPE_FK FOREIGN KEY (HIERARCHY_ID)
	  REFERENCES REFERENCE_TYPE_VALUES (REF_VAL_ID) ENABLE;


--changeset Vijaysree.S:APPCATALOG_DDL_04_02 splitStatements:false
--preconditions onFail:HALT onError:HALT


DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONS_COLUMNS 
    WHERE  
        CONSTRAINT_NAME = 'RELEASE_ID_PK'
		AND COLUMN_NAME = 'RELEASE_ID';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE RELEASE_DETAILS ADD CONSTRAINT RELEASE_ID_PK PRIMARY KEY (RELEASE_ID)';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_04_03 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONS_COLUMNS 
    WHERE  
        CONSTRAINT_NAME = 'REL_USR_STRY_ID_PK'
		AND COLUMN_NAME = 'REL_USR_STRY_ID';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE RELEASE_USER_STORY_MAPPING ADD CONSTRAINT REL_USR_STRY_ID_PK PRIMARY KEY (REL_USR_STRY_ID)';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_04_04 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONS_COLUMNS 
    WHERE  
        CONSTRAINT_NAME = 'USR_STRY_RELID_FK'
		AND COLUMN_NAME = 'RELEASE_ID';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE RELEASE_USER_STORY_MAPPING ADD CONSTRAINT USR_STRY_RELID_FK FOREIGN KEY (RELEASE_ID)
	  REFERENCES RELEASE_DETAILS (RELEASE_ID) ENABLE';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_04_05 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONS_COLUMNS 
    WHERE  
        CONSTRAINT_NAME = 'WORKSPACE_ID_PK'
		AND COLUMN_NAME = 'WORKSPACE_ID';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE WORKSPACE_DETAILS ADD CONSTRAINT WORKSPACE_ID_PK PRIMARY KEY (WORKSPACE_ID)';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_04_06 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONS_COLUMNS 
    WHERE  
        CONSTRAINT_NAME = 'WS_DET_REL_STRY_ID_FK'
		AND COLUMN_NAME = 'REL_USR_STRY_ID';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE WORKSPACE_DETAILS ADD CONSTRAINT WS_DET_REL_STRY_ID_FK FOREIGN KEY (REL_USR_STRY_ID)
	  REFERENCES RELEASE_USER_STORY_MAPPING (REL_USR_STRY_ID) ENABLE';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_04_07 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONS_COLUMNS 
    WHERE  
        CONSTRAINT_NAME = 'WORKSPACE_REL_ID_PK'
		AND COLUMN_NAME = 'WORKSPACE_REL_ID';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE WORKSPACE_RELEASE_DETAILS ADD CONSTRAINT WORKSPACE_REL_ID_PK PRIMARY KEY (WORKSPACE_REL_ID)';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_04_08 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONS_COLUMNS 
    WHERE  
        CONSTRAINT_NAME = 'WORKSPACE_ID_FK'
		AND COLUMN_NAME = 'WORKSPACE_ID';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE WORKSPACE_RELEASE_DETAILS ADD CONSTRAINT WORKSPACE_ID_FK FOREIGN KEY (WORKSPACE_ID)
	  REFERENCES WORKSPACE_DETAILS (WORKSPACE_ID) ENABLE';
        DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_04_09 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONSTRAINTS
    WHERE  
        TABLE_NAME = 'REF_LINEOFBUSINESS' AND CONSTRAINT_NAME = 'LOB_ID_PK';

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE REF_LINEOFBUSINESS ADD CONSTRAINT LOB_ID_PK PRIMARY KEY (LOB_ID)';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;


--changeset Vijaysree.S:APPCATALOG_DDL_04_10 splitStatements:false
--preconditions onFail:HALT onError:HALT

DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_CONSTRAINTS 
    WHERE  
        CONSTRAINT_NAME = 'USER_LOB_FK' ;

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE USER_LOB_ASSOC ADD CONSTRAINT USER_LOB_FK FOREIGN KEY (USER_ID)
	  REFERENCES USERS (USR_ID) ENABLE';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;
