--liquibase formatted sql
--changeset Swetha.H:CDM_DDL_02
--preconditions onFail:HALT onError:HALT

  CREATE TABLE CDMSTATS 
   (	STATID VARCHAR2(30), 
	TYPE CHAR(1), 
	VERSION NUMBER, 
	FLAGS NUMBER, 
	C1 VARCHAR2(30), 
	C2 VARCHAR2(30), 
	C3 VARCHAR2(30), 
	C4 VARCHAR2(30), 
	C5 VARCHAR2(30), 
	N1 NUMBER, 
	N2 NUMBER, 
	N3 NUMBER, 
	N4 NUMBER, 
	N5 NUMBER, 
	N6 NUMBER, 
	N7 NUMBER, 
	N8 NUMBER, 
	N9 NUMBER, 
	N10 NUMBER, 
	N11 NUMBER, 
	N12 NUMBER, 
	D1 DATE, 
	R1 RAW(32), 
	R2 RAW(32), 
	CH1 VARCHAR2(1000), 
	CL1 CLOB
   ) ;


  CREATE TABLE DOCUMENT_ENTITY_ASSOC 
   (	DOCUMENT_ID NUMBER, 
	SOURCE_ID NUMBER, 
	ENTITY_TYPE_ID NUMBER, 
	DOCUMENT_LEVEL VARCHAR2(200), 
	CUSTOMERID NUMBER, 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(255), 
	MODIFIED_BY VARCHAR2(255), 
	MODIFIED_DATE TIMESTAMP (6)
   ) ;

 

  CREATE TABLE DOCUMENT_INFO 
   (	DOCUMENT_ID NUMBER, 
	DOCUMENT_NAME VARCHAR2(255), 
	VERSION NUMBER, 
	STATUS_ID NUMBER, 
	REASON_ID NUMBER, 
	ISSUING_DATE TIMESTAMP (6), 
	EXPIRE_DATE TIMESTAMP (6), 
	CREATED_DATE TIMESTAMP (6), 
	CREATED_BY VARCHAR2(50), 
	MODIFIED_DATE TIMESTAMP (6), 
	MODIFIED_BY VARCHAR2(50), 
	EXTERNAL_ID1 VARCHAR2(50), 
	EXTERNAL_ID2 VARCHAR2(50), 
	EXTERNAL_ID3 VARCHAR2(50), 
	DOCUMENT_DESC VARCHAR2(500), 
	APPLICATION_ID NUMBER, 
	FAILURE_REASON VARCHAR2(400), 
	DOCUMENT_TYPE VARCHAR2(100), 
	ENTITY_ID NUMBER, 
	PARENT_ID NUMBER, 
	ENTITY_NAME VARCHAR2(100), 
	ATTACHMENT_ID NUMBER, 
	ATTACHMENT_NAME VARCHAR2(100), 
	ATTACHMENT_TYPE VARCHAR2(100), 
	NOTE_ENTERED_BY VARCHAR2(100), 
	NOTE_IN_AT_SOURCE VARCHAR2(100), 
	ENTER_OR_UPDATE_AN_ATTACHMENT VARCHAR2(100), 
	TITLES VARCHAR2(100), 
	ATTACHMENT_DESCRIPTIONS VARCHAR2(4000), 
	ADD_YOUR_ATTACHMENTS VARCHAR2(100), 
	ATTACH_SIZES VARCHAR2(100), 
	ATTACH_TYPES VARCHAR2(100), 
	SEARCH_KEY VARCHAR2(100), 
	DOCUMENT_ATTACHMENT VARCHAR2(100), 
	NOTE_BROWSE VARCHAR2(50), 
	NOTE_ADD VARCHAR2(50), 
	NOTE_DELETE VARCHAR2(50), 
	ATTACHMENT_FILE VARCHAR2(4000) 
	-- CONSTRAINT DOCUMENT_INFO_STATUS_FK FOREIGN KEY (STATUS_ID)
	--  REFERENCES DOCUMENT_STATUS (STATUS_ID) ENABLE, 
	-- CONSTRAINT DOCUMENT_STATUS_REASON_FK FOREIGN KEY (REASON_ID)
	--  REFERENCES DOCUMENT_STATUS_REASON (REASON_ID) ENABLE
   ) ;

 

  CREATE TABLE DOCUMENT_STATUS 
   (	STATUS_ID NUMBER, 
	DOCUMENT_STATUS VARCHAR2(30), 
	DOCUMENT_STATUS_DESC VARCHAR2(100)
   ) ;

  CREATE TABLE DOCUMENT_STATUS_REASON 
   (	REASON_ID NUMBER, 
	REASON VARCHAR2(150)
   ) ;
   
--changeset Swetha.H:CDM_DDL_02_02 splitStatements:false
--preconditions onFail:HALT onError:HALT


DECLARE
    L_CNT NUMBER;
BEGIN
    SELECT
        COUNT(*)
    INTO L_CNT
    FROM 
        USER_TAB_COLUMNS
    WHERE  
        TABLE_NAME = 'DOCUMENT_INFO'
        AND COLUMN_NAME IN ( 'STATUS');

    IF L_CNT = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE DOCUMENT_INFO ADD STATUS VARCHAR2(100)';
		DBMS_OUTPUT.PUT_LINE('Altered');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Already exist');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Skipped');
END;