--liquibase formatted sql
--changeset Swetha.H:CDM_DDL_03 
--preconditions onFail:HALT onError:HALT


  ALTER TABLE DOCUMENT_STATUS_REASON ADD CONSTRAINT DOCUMENT_STAT_REASON_PK PRIMARY KEY (REASON_ID)
  USING INDEX  ENABLE;

  ALTER TABLE DOCUMENT_STATUS ADD CONSTRAINT DOCUMENT_STATUS_PK PRIMARY KEY (STATUS_ID)
  USING INDEX  ENABLE;

  
  
  ALTER TABLE DOCUMENT_INFO ADD CONSTRAINT DOCUMENT_INFO_STATUS_FK FOREIGN KEY (STATUS_ID)
	  REFERENCES DOCUMENT_STATUS (STATUS_ID) ENABLE;

  ALTER TABLE DOCUMENT_INFO ADD CONSTRAINT DOCUMENT_STATUS_REASON_FK FOREIGN KEY (REASON_ID)
	  REFERENCES DOCUMENT_STATUS_REASON (REASON_ID) ENABLE;