--liquibase formatted sql
--changeset Swetha.H:CDM_DDL_04 
--preconditions onFail:HALT onError:HALT

  CREATE INDEX DOC_ENTITY_ASSOC_SOUR_IDX1 ON DOCUMENT_ENTITY_ASSOC (SOURCE_ID) 
  ;

  CREATE INDEX DOC_ENTITY_ASSOC_IDX ON DOCUMENT_ENTITY_ASSOC (ENTITY_TYPE_ID) 
  ;

  CREATE UNIQUE INDEX INX_DOCUMENT_ENTITY ON DOCUMENT_ENTITY_ASSOC (DOCUMENT_ID, SOURCE_ID, ENTITY_TYPE_ID, CUSTOMERID) 
  ;

  CREATE INDEX DM_DOCUMENT_INFO_INX ON DOCUMENT_INFO (EXTERNAL_ID1) 
  ;

  CREATE INDEX CDMSTATS ON CDMSTATS (STATID, TYPE, C5, C1, C2, C3, C4, VERSION) 
  ;
  